#pragma once
//XmlDb 全局定义文件
#include "..\BaseClass\BaseObject.h"
#include "XmlDbKeys.h"

#define CLASSID_TXMLDATABASE	(CLASSID_LISTCLASS + 1)
#define CLASSID_TXMLDBTABLE		(CLASSID_LISTCLASS + 2)
#define CLASSID_TXMLDBTAGS		(CLASSID_LISTCLASS + 3)
#define CLASSID_TXMLDBTAG		(CLASSID_LISTCLASS + 4)

#define CLASSID_XMLDATABASE		(CLASSID_LISTCLASS + 11)
#define CLASSID_XMLDBDATA		(CLASSID_LISTCLASS + 12)
#define CLASSID_XMLDBTAGS		(CLASSID_LISTCLASS + 13)
#define CLASSID_XMLDBTAG		(CLASSID_LISTCLASS + 14)