
SOURCES +=  \
$$PWD/Config/Frame/SttFrame_Button.cpp \
$$PWD/Config/Frame/SttFrame_Data.cpp \
$$PWD/Config/Frame/SttFrame_Font.cpp \
$$PWD/Config/Frame/SttFrame_GbTree.cpp \
$$PWD/Config/Frame/SttFrame_GlobalData.cpp \
$$PWD/Config/Frame/SttFrame_GlobalDatas.cpp \
$$PWD/Config/Frame/SttFrame_Item.cpp \
$$PWD/Config/Frame/SttFrame_MacroParaView.cpp \
$$PWD/Config/Frame/SttFrame_Menu.cpp \
$$PWD/Config/Frame/SttFrame_Menus.cpp \
$$PWD/Config/Frame/SttFrame_Panal.cpp \
$$PWD/Config/Frame/SttFrame_ReportView.cpp \
$$PWD/Config/Frame/SttFrame_RightPanes.cpp \
$$PWD/Config/Frame/SttFrame_Size.cpp \
$$PWD/Config/Frame/SttFrame_XBar.cpp \
$$PWD/Config/Frame/SttFrameConfig.cpp \
$$PWD/Config/Frame/SttTestCtrlFrameCfgMngrGlobal.cpp \
$$PWD/Config/MacroTestUI/SttMacroTestUI_Group.cpp \
$$PWD/Config/MacroTestUI/SttMacroTestUI_TestMacroUI.cpp \
$$PWD/Config/MacroTestUI/SttMacroTestUI_TestMacroUIDB.cpp \
$$PWD/Config/MacroTestUI/SttMacroTestUI_TestMacroUIMngr.cpp \
$$PWD/Config/MacroTestUI/SttMacroTestUI_TestMacroUIRef.cpp \
$$PWD/Config/MacroTestUI/SttMacroTestUI_TestMacroUIs.cpp \
$$PWD/Config/MacroTestUI/SttTestCtrrlMacroTestUIMngrGlobal.cpp \
$$PWD/Config/TestMacroToolUI/ClassDefMngrGlobal.cpp \
$$PWD/Config/TestMacroToolUI/CommcmdRef.cpp \
$$PWD/Config/TestMacroToolUI/TestMacroGroup.cpp \
$$PWD/Config/TestMacroToolUI/TestMacroRef.cpp \
$$PWD/Config/TestMacroToolUI/TestMacroToolBar.cpp \
$$PWD/Controls/ExportWordRpt/SttExportWordReport.cpp \
$$PWD/Controls/ExportWordRpt/SttGbTreeCtrl_ExportRpt.cpp \
$$PWD/Controls/ExportWordRpt/SttGrid_ExportRpt.cpp \
$$PWD/Controls/ExportWordRpt/SttGrid_ExportRpt_Tec.cpp \
$$PWD/Controls/FileMngr/SttFileMngrChildren.cpp \
$$PWD/Controls/FileMngr/SttFileMngrDlg.cpp \
$$PWD/Controls/FileMngr/SttFileMoveDlg.cpp \
$$PWD/Controls/FileMngr/SttFileTypeMngrGrid.cpp \
$$PWD/Controls/FileMngr/SttFileViewGrid.cpp \
$$PWD/Controls/FileMngr/SttXFolderButton.cpp \
$$PWD/Controls/SafetyMsgCfg/SttSafetyMsg.cpp \
$$PWD/Controls/SafetyMsgCfg/SttSafetyMsgCfg.cpp \
$$PWD/Controls/SafetyMsgCfg/SttSafetyMsgCfgGlobal.cpp \
$$PWD/Controls/SafetyMsgCfg/SttSafetyMsgCfgs.cpp \
$$PWD/Controls/SttAction.cpp \
$$PWD/Controls/SttAddMacroWidget.cpp \
$$PWD/Controls/SttCheckBox.cpp \
$$PWD/Controls/SttCreateNewTestWidget.cpp \
$$PWD/Controls/SttCustomSetDlg.cpp \
$$PWD/Controls/SttCustomSetTree.cpp \
$$PWD/Controls/SttDataButtons.cpp \
$$PWD/Controls/SttDvmEdit.cpp \
$$PWD/Controls/SttFileSaveAsDlg.cpp \
$$PWD/Controls/SttGbItemsEdit.cpp \
$$PWD/Controls/SttGbItemsNameSelDlg.cpp \
$$PWD/Controls/SttGbSafetyEdit.cpp \
$$PWD/Controls/SttGroupBox.cpp \
$$PWD/Controls/SttGuideBookTreeCtrl.cpp \
$$PWD/Controls/SttGuideBookTreeWidget.cpp \
$$PWD/Controls/SttGuideBookTreeWidget_Win.cpp \
$$PWD/Controls/SttItemButton.cpp \
$$PWD/Controls/SttLanguageCfgDialog.cpp \
$$PWD/Controls/SttLineEdit.cpp \
$$PWD/Controls/SttMenuBar.cpp \
$$PWD/Controls/SttMenuWidget.cpp \
$$PWD/Controls/SttOutPutWidget.cpp \
$$PWD/Controls/SttPanelBase.cpp \
$$PWD/Controls/SttReportHeadSetDlg.cpp \
$$PWD/Controls/SttTabWidget.cpp \
$$PWD/Controls/SttTestViewsTabWidget.cpp \
$$PWD/Controls/SttToolBar.cpp \
$$PWD/Controls/SttToolButton.cpp \
$$PWD/Controls/SttToolButtonBase.cpp \
$$PWD/Controls/TestMacroTool/TestMacroToolDlg.cpp \
$$PWD/Controls/ViewRpts/SttGbRptGrid_Dataset.cpp \
$$PWD/Controls/ViewRpts/SttGbRptGrid_Values.cpp \
$$PWD/Controls/ViewRpts/SttGbViewRpts.cpp \
$$PWD/Interface/SttHtmlReportViewInterface.cpp \
$$PWD/Interface/SttHtmlViewApi.cpp \
$$PWD/Interface/SttMacroParaEditInterface.cpp \
$$PWD/Interface/SttMacroParaEditViewMngr.cpp \
$$PWD/Interface/SttMacroParaEditViewOriginal.cpp \
$$PWD/Module/AinDataMap/QAinDataMapDatesetGrid.cpp \
$$PWD/Module/AinDataMap/QAinDataMapDlg.cpp \
$$PWD/Module/AinDataMap/QAinDataMapGrid.cpp \
$$PWD/Module/ChannelParaSet/channelharmtable.cpp \
$$PWD/Module/ChannelParaSet/channelpowertable.cpp \
$$PWD/Module/ChannelParaSet/channeltable.cpp \
$$PWD/Module/ChannelParaSet/QBasicTestParaSet.cpp \
$$PWD/Module/ChannelParaSet/QBasicTestParaSetImp.cpp \
$$PWD/Module/ChannelParaSet/QParaSetBase.cpp \
$$PWD/Module/ChRsMap/ChMapsGrid.cpp \
$$PWD/Module/ChRsMap/QChMapsDlg.cpp \
$$PWD/Module/ChRsMap/QChMapsWidget.cpp \
$$PWD/Module/CommConfigurationDlg/CommCfg/QSttCommCfgMainDlg.cpp \
$$PWD/Module/CommConfigurationDlg/CommCfg/SttCommCfgDeviceAttrsGrid.cpp \
$$PWD/Module/CommConfigurationDlg/DevComm/QSttCommCfgDeviceDlg.cpp \
$$PWD/Module/CommConfigurationDlg/DevComm/QSttCommCfgDeviceWidget.cpp \
$$PWD/Module/CommConfigurationDlg/DevComm/SttDevCommTeleMeasureGrid.cpp \
$$PWD/Module/CommConfigurationDlg/DevComm/SttDevCommTeleParaCommGrid.cpp \
$$PWD/Module/CommConfigurationDlg/PkgMonitor/QSttCommCfgPkgMonitorDlg.cpp \
$$PWD/Module/CommConfigurationDlg/PkgMonitor/QSttCommCfgPkgMonitorWidget.cpp \
$$PWD/Module/CommConfigurationDlg/PkgMonitor/SttCommCfgPkgMonitorLeftGrid.cpp \
$$PWD/Module/CommConfigurationDlg/PkgMonitor/SttCommCfgPkgMonitorRightGrid.cpp \
$$PWD/Module/CommConfigurationDlg/PointTblFile/QSttCommCfgPointTblFileEditorDlg.cpp \
$$PWD/Module/CommConfigurationDlg/PointTblFile/QSttCommCfgPointTblFileImportDlg.cpp \
$$PWD/Module/CommConfigurationDlg/PointTblFile/SttCommCfgPointTblFileImportGrid.cpp \
$$PWD/Module/CommConfigurationDlg/PointTblFile/SttCommCfgPointTblFileImportTreeCtrl.cpp \
$$PWD/Module/CommConfigurationDlg/PointTblFile/SttPointTblEdtTabIntervalSetGrid.cpp \
$$PWD/Module/CommConfigurationDlg/PointTblFile/SttPointTblEdtTabTeleMeasureGrid.cpp \
$$PWD/Module/CommConfigurationDlg/PointTblFile/SttPointTblEdtTabTeleParaCommGrid.cpp \
$$PWD/Module/CommConfigurationDlg/ProtocolTempl/QSttCommCfgProtocolTemplateDlg.cpp \
$$PWD/Module/CommConfigurationDlg/ProtocolTempl/SttCommCfgProtocolTemplateGrid.cpp \
$$PWD/Module/CommonCtrl_QT/Draw/QSttCustomArrowLine.cpp \
$$PWD/Module/CommonCtrl_QT/Draw/QSttCustomRect.cpp \
$$PWD/Module/CommonCtrl_QT/QCovDoubleValidator.cpp \
$$PWD/Module/CommonCtrl_QT/QDataTypeComboBox.cpp \
$$PWD/Module/CommonCtrl_QT/QFloatLineEdit.cpp \
$$PWD/Module/CommonCtrl_QT/QIecLineEdit.cpp \
$$PWD/Module/CommonCtrl_QT/QIecWidgetDelegate.cpp \
$$PWD/Module/CommonCtrl_QT/QLongLineEdit.cpp \
$$PWD/Module/CommonCtrl_QT/QNumberCheckBox.cpp \
$$PWD/Module/CommonCtrl_QT/QSttProgDlg.cpp \
$$PWD/Module/CommonCtrl_QT/SttDiffCurrCalDlg.cpp \
$$PWD/Module/CommonMethod/commonMethod.cpp \
$$PWD/Module/CommonMethod/FaultCalculat.cpp \
$$PWD/Module/DCOutput/QAuxDCOutputDlg.cpp \
$$PWD/Module/DeviceInforDlg/DeviceAttrsGrid.cpp \
$$PWD/Module/DeviceInforDlg/QDeviceInforDlg.cpp \
$$PWD/Module/DeviceInforDlg/SttModuleAttrsGrid.cpp \
$$PWD/Module/DeviceInforDlg/SttModulesGrid.cpp \
$$PWD/Module/ExSwitchSet/exswitchset.cpp \
$$PWD/Module/FT3Widget/FT3OutParaWidget.cpp \
$$PWD/Module/FT3Widget/FT3OutSetDialog.cpp \
$$PWD/Module/FT3Widget/FT3OutWidget.cpp \
$$PWD/Module/FT3Widget/IecCfgFT3OutGrid.cpp \
$$PWD/Module/GooseParaWidget/goosepubwidget.cpp \
$$PWD/Module/GooseParaWidget/IecCfgGoutChsGrid.cpp \
$$PWD/Module/GooseParaWidget/LineEdit.cpp \
$$PWD/Module/GooseParaWidget/qgooseparawidget.cpp \
$$PWD/Module/GooseParaWidget/SttIntelBoutToGinGrid.cpp \
$$PWD/Module/GooseParaWidget/SttIntelBoutToGinParaWidget.cpp \
$$PWD/Module/GooseParaWidget/SttIntelBoutToGinPubWidget.cpp \
$$PWD/Module/GooseParaWidget/SttIntelGoutToBinGrid.cpp \
$$PWD/Module/GooseParaWidget/SttIntelGoutToBinParaWidget.cpp \
$$PWD/Module/GooseParaWidget/SttIntelGoutToBinPubWidget.cpp \
$$PWD/Module/GooseParaWidget/WidgetDelegate.cpp \
$$PWD/Module/HardwareSetDlg/QHardwareSetDlg.cpp \
$$PWD/Module/infoWidget/infowidget.cpp \
$$PWD/Module/LuminousPower/LuminousPowerDlg.cpp \
$$PWD/Module/LuminousPower/LuminousPowerGrid.cpp \
$$PWD/Module/ModuleSetDlg/QModuleSetDlg.cpp \
$$PWD/Module/ModuleSetDlg/QModuleSetWidget.cpp \
$$PWD/Module/OutPutDebugDlg/QOutPutDebugDlg.cpp \
$$PWD/Module/PopupDialog/SttFileDlgBase.cpp \
$$PWD/Module/PopupDialog/SttFileMngrTool.cpp \
$$PWD/Module/PopupDialog/SttFileMngrTree.cpp \
$$PWD/Module/PopupDialog/SttFileSelectGrid.cpp \
$$PWD/Module/PopupDialog/SttPopupOpenDialog.cpp \
$$PWD/Module/PopupDialog/SttPopupSaveAsDialog.cpp \
$$PWD/Module/PowerWidget/powerdiagramwidget.cpp \
$$PWD/Module/PowerWidget/QPowerDiagramWidgetImp.cpp \
$$PWD/Module/QExBaseListGridBase/QExBaseListComBoxDelegBase.cpp \
$$PWD/Module/QExBaseListGridBase/QExBaseListFloatEditDelegBase.cpp \
$$PWD/Module/QExBaseListGridBase/QExBaseListGridBase.cpp \
$$PWD/Module/QExBaseListGridBase/QGridDefine.cpp \
$$PWD/Module/ScrollCtrl/ScrollComboBox.cpp \
$$PWD/Module/ScrollCtrl/ScrollCtrlInterface.cpp \
$$PWD/Module/ScrollCtrl/ScrollListView.cpp \
$$PWD/Module/ScrollCtrl/ScrollListWidget.cpp \
$$PWD/Module/ScrollCtrl/ScrollSlider.cpp \
$$PWD/Module/ScrollCtrl/ScrollTableWidget.cpp \
$$PWD/Module/ScrollCtrl/ScrollTextEdit.cpp \
$$PWD/Module/ScrollCtrl/ScrollTreeWidget.cpp \
$$PWD/Module/ScrollCtrl/ScrollWebView.cpp \
$$PWD/Module/StateMonitor/QStateMonitorWidgetImp.cpp \
$$PWD/Module/StateMonitor/StateMonitorBinBout.cpp \
$$PWD/Module/StateMonitor/StateMonitorPlot.cpp \
$$PWD/Module/StateMonitor/StateMonitorTab.cpp \
$$PWD/Module/StateMonitor/StateMonitorVoltCur.cpp \
$$PWD/Module/StateMonitor/StateMonitorWidget.cpp \
$$PWD/Module/SttUIDefine.cpp \
$$PWD/Module/SysParas/QSysParasDlg.cpp \
$$PWD/Module/SysParas/QSysParasWidget.cpp \
$$PWD/Module/SysParas/QWeakSetWidget.cpp \
$$PWD/Module/SysParas/WeakSetGrid.cpp \
$$PWD/Module/VectorWidget/DiagramWidget.cpp \
$$PWD/Module/VectorWidget/vectorwidget.cpp \
$$PWD/Module/ZKCharaCurve/QCharElementDlg.cpp \
$$PWD/Module/ZKCharaCurve/QCIFeatureAddDig.cpp \
$$PWD/Module/ZKCharaCurve/QZKFeatureAddDig.cpp \
$$PWD/ResultExpr/ResultExprCanvas.cpp \
$$PWD/ResultExpr/ResultExprDlg_Data.cpp \
$$PWD/ResultExpr/ResultExprDlg_Reports.cpp \
$$PWD/ResultExpr/ResultExprWidget.cpp \
$$PWD/ResultExpr/ResultExprWidget_Cmp.cpp \
$$PWD/ResultExpr/ResultExprWidget_Error.cpp \
$$PWD/ResultExpr/ResultExprWidget_Node.cpp \
$$PWD/ResultExpr/ResultExprWidget_Range.cpp \
$$PWD/ResultExpr/ResultExprWidget_ValueCal.cpp \
$$PWD/ResultExpr/ResultExprWidgetItem.cpp \
$$PWD/QSttInfWidgetBase.cpp \
$$PWD/SttTestCntrCmdDefine.cpp \
$$PWD/SttTestCntrFrameBase.cpp \
$$PWD/Webkit/SttMacroParaEditViewHtml.cpp \
$$PWD/Webkit/SttReportViewHtml.cpp \
$$PWD/Webkit/SttWebViewBase.cpp \ 
    $$PWD/SttTestCntrFrameApi.cpp \
    $$PWD/Interface/SttMacroParaEditFactory.cpp \
    $$PWD/Controls/settingselectdlg.cpp \ 
    $$PWD/Controls/QSettingGridBase.cpp \
    $$PWD/Controls/QSettingItem.cpp \
    $$PWD/Controls/QSettingLineEdit.cpp \
    $$PWD/Controls/SettingInterface.cpp\
    $$PWD/Module/CharLibWidget/InternationalModeUI/CharactEditWidget_Eng.cpp

HEADERS += \
$$PWD/Config/Frame/SttFrame_Button.h \
$$PWD/Config/Frame/SttFrame_Data.h \
$$PWD/Config/Frame/SttFrame_Font.h \
$$PWD/Config/Frame/SttFrame_GbTree.h \
$$PWD/Config/Frame/SttFrame_GlobalData.h \
$$PWD/Config/Frame/SttFrame_GlobalDatas.h \
$$PWD/Config/Frame/SttFrame_Item.h \
$$PWD/Config/Frame/SttFrame_MacroParaView.h \
$$PWD/Config/Frame/SttFrame_Menu.h \
$$PWD/Config/Frame/SttFrame_Menus.h \
$$PWD/Config/Frame/SttFrame_Panal.h \
$$PWD/Config/Frame/SttFrame_ReportView.h \
$$PWD/Config/Frame/SttFrame_RightPanes.h \
$$PWD/Config/Frame/SttFrame_Size.h \
$$PWD/Config/Frame/SttFrame_XBar.h \
$$PWD/Config/Frame/SttFrameConfig.h \
$$PWD/Config/Frame/SttTestCtrlFrameCfgMngrGlobal.h \
$$PWD/Config/MacroTestUI/SttMacroTestUI_Group.h \
$$PWD/Config/MacroTestUI/SttMacroTestUI_TestMacroUI.h \
$$PWD/Config/MacroTestUI/SttMacroTestUI_TestMacroUIDB.h \
$$PWD/Config/MacroTestUI/SttMacroTestUI_TestMacroUIMngr.h \
$$PWD/Config/MacroTestUI/SttMacroTestUI_TestMacroUIRef.h \
$$PWD/Config/MacroTestUI/SttMacroTestUI_TestMacroUIs.h \
$$PWD/Config/MacroTestUI/SttTestCtrrlMacroTestUIMngrGlobal.h \
$$PWD/Config/TestMacroToolUI/ClassDefMngrGlobal.h \
$$PWD/Config/TestMacroToolUI/CommcmdRef.h \
$$PWD/Config/TestMacroToolUI/TestMacroGroup.h \
$$PWD/Config/TestMacroToolUI/TestMacroRef.h \
$$PWD/Config/TestMacroToolUI/TestMacroToolBar.h \
$$PWD/Controls/ExportWordRpt/SttExportWordReport.h \
$$PWD/Controls/ExportWordRpt/SttGbTreeCtrl_ExportRpt.h \
$$PWD/Controls/ExportWordRpt/SttGrid_ExportRpt.h \
$$PWD/Controls/ExportWordRpt/SttGrid_ExportRpt_Tec.h \
$$PWD/Controls/FileMngr/SttFileMngrChildren.h \
$$PWD/Controls/FileMngr/SttFileMngrDlg.h \
$$PWD/Controls/FileMngr/SttFileMoveDlg.h \
$$PWD/Controls/FileMngr/SttFileTypeMngrGrid.h \
$$PWD/Controls/FileMngr/SttFileViewGrid.h \
$$PWD/Controls/FileMngr/SttXFolderButton.h \
$$PWD/Controls/SafetyMsgCfg/SttSafetyMsg.h \
$$PWD/Controls/SafetyMsgCfg/SttSafetyMsgCfg.h \
$$PWD/Controls/SafetyMsgCfg/SttSafetyMsgCfgGlobal.h \
$$PWD/Controls/SafetyMsgCfg/SttSafetyMsgCfgs.h \
$$PWD/Controls/SttAction.h \
$$PWD/Controls/SttAddMacroWidget.h \
$$PWD/Controls/SttCheckBox.h \
$$PWD/Controls/SttCreateNewTestWidget.h \
$$PWD/Controls/SttCustomSetDlg.h \
$$PWD/Controls/SttCustomSetTree.h \
$$PWD/Controls/SttDataButtons.h \
$$PWD/Controls/SttDvmEdit.h \
$$PWD/Controls/SttFileSaveAsDlg.h \
$$PWD/Controls/SttGbItemsEdit.h \
$$PWD/Controls/SttGbItemsNameSelDlg.h \
$$PWD/Controls/SttGbSafetyEdit.h \
$$PWD/Controls/SttGroupBox.h \
$$PWD/Controls/SttGuideBookTreeCtrl.h \
$$PWD/Controls/SttGuideBookTreeWidget.h \
$$PWD/Controls/SttGuideBookTreeWidget_Win.h \
$$PWD/Controls/SttItemButton.h \
$$PWD/Controls/SttLanguageCfgDialog.h \
$$PWD/Controls/SttLineEdit.h \
$$PWD/Controls/SttMenuBar.h \
$$PWD/Controls/SttMenuWidget.h \
$$PWD/Controls/SttOutPutWidget.h \
$$PWD/Controls/SttPanelBase.h \
$$PWD/Controls/SttReportHeadSetDlg.h \
$$PWD/Controls/SttTabWidget.h \
$$PWD/Controls/SttTestViewsTabWidget.h \
$$PWD/Controls/SttToolBar.h \
$$PWD/Controls/SttToolButton.h \
$$PWD/Controls/SttToolButtonBase.h \
$$PWD/Controls/TestMacroTool/TestMacroToolDlg.h \
$$PWD/Controls/ViewRpts/SttGbRptGrid_Dataset.h \
$$PWD/Controls/ViewRpts/SttGbRptGrid_Values.h \
$$PWD/Controls/ViewRpts/SttGbViewRpts.h \
$$PWD/Interface/SttHtmlReportViewInterface.h \
$$PWD/Interface/SttHtmlViewApi.h \
$$PWD/Interface/SttMacroParaEditInterface.h \
$$PWD/Interface/SttMacroParaEditViewMngr.h \
$$PWD/Interface/SttMacroParaEditViewOriginal.h \
$$PWD/Module/AinDataMap/QAinDataMapDatesetGrid.h \
$$PWD/Module/AinDataMap/QAinDataMapDlg.h \
$$PWD/Module/AinDataMap/QAinDataMapGrid.h \
$$PWD/Module/ChannelParaSet/channelharmtable.h \
$$PWD/Module/ChannelParaSet/channelpowertable.h \
$$PWD/Module/ChannelParaSet/channeltable.h \
$$PWD/Module/ChannelParaSet/QBasicTestParaSet.h \
$$PWD/Module/ChannelParaSet/QBasicTestParaSetImp.h \
$$PWD/Module/ChannelParaSet/QParaSetBase.h \
$$PWD/Module/ChRsMap/ChMapsGrid.h \
$$PWD/Module/ChRsMap/QChMapsDlg.h \
$$PWD/Module/ChRsMap/QChMapsWidget.h \
$$PWD/Module/CommConfigurationDlg/CommCfg/QSttCommCfgMainDlg.h \
$$PWD/Module/CommConfigurationDlg/CommCfg/SttCommCfgDeviceAttrsGrid.h \
$$PWD/Module/CommConfigurationDlg/DevComm/QSttCommCfgDeviceDlg.h \
$$PWD/Module/CommConfigurationDlg/DevComm/QSttCommCfgDeviceWidget.h \
$$PWD/Module/CommConfigurationDlg/DevComm/SttDevCommTeleMeasureGrid.h \
$$PWD/Module/CommConfigurationDlg/DevComm/SttDevCommTeleParaCommGrid.h \
$$PWD/Module/CommConfigurationDlg/PkgMonitor/QSttCommCfgPkgMonitorDlg.h \
$$PWD/Module/CommConfigurationDlg/PkgMonitor/QSttCommCfgPkgMonitorWidget.h \
$$PWD/Module/CommConfigurationDlg/PkgMonitor/SttCommCfgPkgMonitorLeftGrid.h \
$$PWD/Module/CommConfigurationDlg/PkgMonitor/SttCommCfgPkgMonitorRightGrid.h \
$$PWD/Module/CommConfigurationDlg/PointTblFile/QSttCommCfgPointTblFileEditorDlg.h \
$$PWD/Module/CommConfigurationDlg/PointTblFile/QSttCommCfgPointTblFileImportDlg.h \
$$PWD/Module/CommConfigurationDlg/PointTblFile/SttCommCfgPointTblFileImportGrid.h \
$$PWD/Module/CommConfigurationDlg/PointTblFile/SttCommCfgPointTblFileImportTreeCtrl.h \
$$PWD/Module/CommConfigurationDlg/PointTblFile/SttPointTblEdtTabIntervalSetGrid.h \
$$PWD/Module/CommConfigurationDlg/PointTblFile/SttPointTblEdtTabTeleMeasureGrid.h \
$$PWD/Module/CommConfigurationDlg/PointTblFile/SttPointTblEdtTabTeleParaCommGrid.h \
$$PWD/Module/CommConfigurationDlg/ProtocolTempl/QSttCommCfgProtocolTemplateDlg.h \
$$PWD/Module/CommConfigurationDlg/ProtocolTempl/SttCommCfgProtocolTemplateGrid.h \
$$PWD/Module/CommonCtrl_QT/Draw/QSttCustomArrowLine.h \
$$PWD/Module/CommonCtrl_QT/Draw/QSttCustomRect.h \
$$PWD/Module/CommonCtrl_QT/QCovDoubleValidator.h \
$$PWD/Module/CommonCtrl_QT/QDataTypeComboBox.h \
$$PWD/Module/CommonCtrl_QT/QFloatLineEdit.h \
$$PWD/Module/CommonCtrl_QT/QIecLineEdit.h \
$$PWD/Module/CommonCtrl_QT/QIecWidgetDelegate.h \
$$PWD/Module/CommonCtrl_QT/QLongLineEdit.h \
$$PWD/Module/CommonCtrl_QT/QNumberCheckBox.h \
$$PWD/Module/CommonCtrl_QT/QSttProgDlg.h \
$$PWD/Module/CommonCtrl_QT/SttDiffCurrCalDlg.h \
$$PWD/Module/CommonMethod/commonMethod.h \
$$PWD/Module/CommonMethod/FaultCalculat.h \
$$PWD/Module/DCOutput/QAuxDCOutputDlg.h \
$$PWD/Module/DeviceInforDlg/DeviceAttrsGrid.h \
$$PWD/Module/DeviceInforDlg/QDeviceInforDlg.h \
$$PWD/Module/DeviceInforDlg/SttModuleAttrsGrid.h \
$$PWD/Module/DeviceInforDlg/SttModulesGrid.h \
$$PWD/Module/ExSwitchSet/exswitchset.h \
$$PWD/Module/FT3Widget/FT3OutParaWidget.h \
$$PWD/Module/FT3Widget/FT3OutSetDialog.h \
$$PWD/Module/FT3Widget/FT3OutWidget.h \
$$PWD/Module/FT3Widget/IecCfgFT3OutGrid.h \
$$PWD/Module/GooseParaWidget/goosepubwidget.h \
$$PWD/Module/GooseParaWidget/IecCfgGoutChsGrid.h \
$$PWD/Module/GooseParaWidget/LineEdit.h \
$$PWD/Module/GooseParaWidget/qgooseparawidget.h \
$$PWD/Module/GooseParaWidget/SttIntelBoutToGinGrid.h \
$$PWD/Module/GooseParaWidget/SttIntelBoutToGinParaWidget.h \
$$PWD/Module/GooseParaWidget/SttIntelBoutToGinPubWidget.h \
$$PWD/Module/GooseParaWidget/SttIntelGoutToBinGrid.h \
$$PWD/Module/GooseParaWidget/SttIntelGoutToBinParaWidget.h \
$$PWD/Module/GooseParaWidget/SttIntelGoutToBinPubWidget.h \
$$PWD/Module/GooseParaWidget/WidgetDelegate.h \
$$PWD/Module/HardwareSetDlg/QHardwareSetDlg.h \
$$PWD/Module/infoWidget/infowidget.h \
$$PWD/Module/LuminousPower/LuminousPowerDlg.h \
$$PWD/Module/LuminousPower/LuminousPowerGrid.h \
$$PWD/Module/ModuleSetDlg/QModuleSetDlg.h \
$$PWD/Module/ModuleSetDlg/QModuleSetWidget.h \
$$PWD/Module/OutPutDebugDlg/QOutPutDebugDlg.h \
$$PWD/Module/PopupDialog/SttFileDlgBase.h \
$$PWD/Module/PopupDialog/SttFileMngrTool.h \
$$PWD/Module/PopupDialog/SttFileMngrTree.h \
$$PWD/Module/PopupDialog/SttFileSelectGrid.h \
$$PWD/Module/PopupDialog/SttPopupOpenDialog.h \
$$PWD/Module/PopupDialog/SttPopupSaveAsDialog.h \
$$PWD/Module/PowerWidget/powerdiagramwidget.h \
$$PWD/Module/PowerWidget/QPowerDiagramWidgetImp.h \
$$PWD/Module/QExBaseListGridBase/QExBaseListComBoxDelegBase.h \
$$PWD/Module/QExBaseListGridBase/QExBaseListFloatEditDelegBase.h \
$$PWD/Module/QExBaseListGridBase/QExBaseListGridBase.h \
$$PWD/Module/QExBaseListGridBase/QGridDefine.h \
$$PWD/Module/ScrollCtrl/ScrollComboBox.h \
$$PWD/Module/ScrollCtrl/ScrollCtrlInterface.h \
$$PWD/Module/ScrollCtrl/ScrollDef.h \
$$PWD/Module/ScrollCtrl/ScrollListView.h \
$$PWD/Module/ScrollCtrl/ScrollListWidget.h \
$$PWD/Module/ScrollCtrl/ScrollSlider.h \
$$PWD/Module/ScrollCtrl/ScrollTableWidget.h \
$$PWD/Module/ScrollCtrl/ScrollTextEdit.h \
$$PWD/Module/ScrollCtrl/ScrollTreeWidget.h \
$$PWD/Module/ScrollCtrl/ScrollWebView.h \
$$PWD/Module/StateMonitor/QStateMonitorWidgetImp.h \
$$PWD/Module/StateMonitor/StateMonitorBinBout.h \
$$PWD/Module/StateMonitor/StateMonitorPlot.h \
$$PWD/Module/StateMonitor/StateMonitorTab.h \
$$PWD/Module/StateMonitor/StateMonitorVoltCur.h \
$$PWD/Module/StateMonitor/StateMonitorWidget.h \
$$PWD/Module/SttUIDefine.h \
$$PWD/Module/SysParas/QSysParasDlg.h \
$$PWD/Module/SysParas/QSysParasWidget.h \
$$PWD/Module/SysParas/QWeakSetWidget.h \
$$PWD/Module/SysParas/WeakSetGrid.h \
$$PWD/Module/VectorWidget/DiagramWidget.h \
$$PWD/Module/VectorWidget/vectorwidget.h \
$$PWD/Module/ZKCharaCurve/QCharElementDlg.h \
$$PWD/Module/ZKCharaCurve/QCIFeatureAddDig.h \
$$PWD/Module/ZKCharaCurve/QZKFeatureAddDig.h \
$$PWD/ResultExpr/ResultExprCanvas.h \
$$PWD/ResultExpr/ResultExprDlg_Data.h \
$$PWD/ResultExpr/ResultExprDlg_Reports.h \
$$PWD/ResultExpr/ResultExprWidget.h \
$$PWD/ResultExpr/ResultExprWidget_Cmp.h \
$$PWD/ResultExpr/ResultExprWidget_Error.h \
$$PWD/ResultExpr/ResultExprWidget_Node.h \
$$PWD/ResultExpr/ResultExprWidget_Range.h \
$$PWD/ResultExpr/ResultExprWidget_ValueCal.h \
$$PWD/ResultExpr/ResultExprWidgetItem.h \
$$PWD/QSttInfWidgetBase.h \
$$PWD/SttTestCntrCmdDefine.h \
$$PWD/SttTestCntrFrameBase.h \
$$PWD/Webkit/SttMacroParaEditViewHtml.h \
$$PWD/Webkit/SttReportViewHtml.h \
$$PWD/Webkit/SttWebViewBase.h \ 
    $$PWD/SttTestCntrFrameApi.h \
    $$PWD/Interface/SttMacroParaEditFactory.h \
    $$PWD/Controls/settingselectdlg.h \
    $$PWD/Controls/QSettingGridBase.h \
    $$PWD/Controls/QSettingItem.h \
    $$PWD/Controls/QSettingLineEdit.h \
    $$PWD/Controls/SettingInterface.h\
    $$PWD/Module/CharLibWidget/InternationalModeUI/CharactEditWidget_Eng.h

FORMS    += \
$$PWD/Controls/ExportWordRpt/SttExportWordReport.ui \
$$PWD/Controls/SttAddMacroWidget.ui \
$$PWD/Controls/SttCreateNewTestWidget.ui \
$$PWD/Controls/SttCustomSetDlg.ui \
$$PWD/Controls/SttFileSaveAsDlg.ui \
$$PWD/Controls/SttGbItemsEdit.ui \
$$PWD/Controls/SttGbItemsNameSelDlg.ui \
$$PWD/Controls/SttGbSafetyEdit.ui \
$$PWD/Controls/SttOutPutWidget.ui \
$$PWD/Controls/SttReportHeadSetDlg.ui \
$$PWD/Controls/TestMacroTool/TestMacroToolDlg.ui \
$$PWD/Controls/ViewRpts/SttGbViewRpts.ui \
$$PWD/Module/AinDataMap/QAinDataMapDlg.ui \
$$PWD/Module/ZKCharaCurve/QCIFeatureAddDig.ui \
$$PWD/Module/ZKCharaCurve/QZKFeatureAddDig.ui \
$$PWD/ResultExpr/ResultExprDlg_Data.ui \
$$PWD/ResultExpr/ResultExprDlg_Reports.ui \
$$PWD/ResultExpr/ResultExprWidget.ui \
$$PWD/ResultExpr/ResultExprWidget_Cmp.ui \
$$PWD/ResultExpr/ResultExprWidget_Error.ui \
$$PWD/ResultExpr/ResultExprWidget_Node.ui \
$$PWD/ResultExpr/ResultExprWidget_Range.ui \
$$PWD/ResultExpr/ResultExprWidget_ValueCal.ui  \
    $$PWD/Controls/settingselectdlg.ui

