#ifndef STTMULTIMACRODISTANCEPARASDEFINE_H
#define STTMULTIMACRODISTANCEPARASDEFINE_H

#define STT_MULTI_MACRO_DISTANCE_PARAS_GRID_ID_ZPhi	        "DistanceZ-Phi"
#define STT_MULTI_MACRO_DISTANCE_PARAS_GRID_ID_RX	        "DistanceR-X"

//QDistanceResultEstimateDlg	功能参数页面
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPE			"FaultType"			//故障类型
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETTING			"ZSetting"			//阻抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZANG				"ZAng"				//阻抗角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RATE				"Rate"				//倍数
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_K0MODE			"K0Mode"			//零序补偿系数
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_KLKR				"KlKr"				//零序补偿系数RE/RL
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ANGKX				"AngKx"				//零序补偿系数XE/XL
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_IMPREFTYPE		"ImpRefType"		//阻抗参考方式
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTCURRENT		"FaultCurrent"		//短路电流
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTDIRECTION	"FaultDirection"	//故障方向
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPE1		"FaultType1"		//故障性质
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TSETTING			"TSetting"			//时间定值
//绝对误差
//相对误差

//QDistanceCommonParasDlg	通用参数页面
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_PREFAULTTIME			"PreFaultTime"		//故障前时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTIME				"FaultTime"			//故障时间裕度
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TIMEAFTERTRIGGER		"TimeAfterTrigger"	//保护动作后持续时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTRIGMODE			"FaultTrigMode"		//故障触发方式
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_PTPOS					"PTPos"				//PT安装位置
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_CTPOS					"CTPos"				//CT正极性
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ILOAD					"ILoad"				//负荷电流
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ILOADPH				"ILoadPh"			//负荷功角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_SIMULATEBREAKERDELAY	"SimulateBreakerDelay"//是否模拟断路器延时
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_BRKBREAKTIME			"BrkBreakTime"			//分闸时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_BRKCLOSETIME			"BrkCloseTime"			//断路器合闸延时
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_VZDEFINE				"VzDefine"				//抽取电压输出定义
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_VZPHDEFINE			"VzPhDefine"			//抽取电压参考项定义
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_VZPH					"VzPh"					//抽取电压相角

//QDistanceBinarysDlg		开入、开出页面
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_BINSELECT				"BinSelect"	//开入量选择
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_A						"A"			//开入A
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_B						"B"			//开入B
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_C						"C"			//开入C
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_D						"D"			//开入D
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_E						"E"			//开入E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_F						"F"			//开入F
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_G						"G"			//开入G
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_H						"H"			//开入H
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B01					"_B01"		//常态开出1状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B02					"_B02"		//常态开出2状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B03					"_B03"		//常态开出3状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B04					"_B04"		//常态开出4状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B05					"_B05"		//常态开出5状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B06					"_B06"		//常态开出6状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B07					"_B07"		//常态开出7状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B08					"_B08"		//常态开出8状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__OUTPUTSWITCHMODE		"_OutputSwitchMode"		//开出翻转启动方式
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__OUTPUTKEEPTIME		"_OutputKeepTime"		//开出保持时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__OUTPUTDELAYTIME		"_OutputDelayTime"		//开出翻转时刻

typedef enum{
	IMPREFTYPE_Z_PHI = 0,//Z-Phi
	IMPREFTYPE_R_X   = 1,//R-X
}STT_MULTI_MACRO_DISTANCE_IMPREFTYPE;

#endif // STTMULTIMACRODISTANCEPARASDEFINE_H