/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_AbortRequestPDU_H_
#define	_AbortRequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AbortRequestPDU__reason {
	AbortRequestPDU__reason_other	= 0,
	AbortRequestPDU__reason_unrecognized_service	= 1,
	AbortRequestPDU__reason_invalid_reqID	= 2,
	AbortRequestPDU__reason_invalid_argument	= 3,
	AbortRequestPDU__reason_invalid_result	= 4,
	AbortRequestPDU__reason_max_serv_outstanding_exceeded	= 5
} e_AbortRequestPDU__reason;

/* AbortRequestPDU */
typedef struct AbortRequestPDU {
	OCTET_STRING_t	 associationId;
	long	 reason;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AbortRequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AbortRequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _AbortRequestPDU_H_ */
#include <asn_internal.h>
