/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_ACSIClass_H_
#define	_ACSIClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GSP_ACSIClass {
    GSP_ACSIClass_reserved	= 0,
    GSP_ACSIClass_data_object	= 1,
    GSP_ACSIClass_data_set	= 2,
    GSP_ACSIClass_brcb	= 3,
    GSP_ACSIClass_urcb	= 4,
    GSP_ACSIClass_lcb	= 5,
    GSP_ACSIClass_log	= 6,
    GSP_ACSIClass_sgcb	= 7,
    GSP_ACSIClass_gocb	= 8,
    GSP_ACSIClass_msvcb	= 10
} e_GSP_ACSIClass;

/* ACSIClass */
typedef long	 ACSIClass_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ACSIClass_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ACSIClass;
asn_struct_free_f ACSIClass_free;
asn_struct_print_f ACSIClass_print;
asn_constr_check_f ACSIClass_constraint;
xer_type_decoder_f ACSIClass_decode_xer;
xer_type_encoder_f ACSIClass_encode_xer;
per_type_decoder_f ACSIClass_decode_aper;
per_type_encoder_f ACSIClass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ACSIClass_H_ */
#include <asn_internal.h>
