/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_AssociateNegotiateRequestPDU_H_
#define	_AssociateNegotiateRequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "INT16U.h"
#include "INT32U.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AssociateNegotiateRequestPDU */
typedef struct AssociateNegotiateRequestPDU {
	INT16U_t	 apduSize;
	INT32U_t	 asduSize;
	INT32U_t	 protocolVersion;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AssociateNegotiateRequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AssociateNegotiateRequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _AssociateNegotiateRequestPDU_H_ */
#include <asn_internal.h>
