/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_AssociateRequestPDU_H_
#define	_AssociateRequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "VisibleString129.h"
#include <OCTET_STRING.h>
#include "UtcTime.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AssociateRequestPDU */
typedef struct AssociateRequestPDU {
	VisibleString129_t	*serverAccessPointReference;	/* OPTIONAL */
	struct AssociateRequestPDU__authenticationParameter {
		OCTET_STRING_t	 signatureCertificate;
		UtcTime_t	 signedTime;
		OCTET_STRING_t	 signedValue;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *authenticationParameter;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AssociateRequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AssociateRequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _AssociateRequestPDU_H_ */
#include <asn_internal.h>
