/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_ConfirmEditSGValuesResponsePDU_H_
#define	_ConfirmEditSGValuesResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ConfirmEditSGValuesResponsePDU */
typedef NULL_t	 ConfirmEditSGValuesResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConfirmEditSGValuesResponsePDU;
asn_struct_free_f ConfirmEditSGValuesResponsePDU_free;
asn_struct_print_f ConfirmEditSGValuesResponsePDU_print;
asn_constr_check_f ConfirmEditSGValuesResponsePDU_constraint;
xer_type_decoder_f ConfirmEditSGValuesResponsePDU_decode_xer;
xer_type_encoder_f ConfirmEditSGValuesResponsePDU_encode_xer;
per_type_decoder_f ConfirmEditSGValuesResponsePDU_decode_aper;
per_type_encoder_f ConfirmEditSGValuesResponsePDU_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ConfirmEditSGValuesResponsePDU_H_ */
#include <asn_internal.h>
