/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_CreateDataSetRequestPDU_H_
#define	_CreateDataSetRequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectReference.h"
#include <asn_SEQUENCE_OF.h>
#include "FunctionalConstraint.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct CreateDataSetRequestPDU__memberData__Member {
	ObjectReference_t	 reference;
	FunctionalConstraint_t	 fc;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CreateDataSetRequestPDU__memberData__Member;

/* CreateDataSetRequestPDU */
typedef struct CreateDataSetRequestPDU {
	ObjectReference_t	 datasetReference;
	ObjectReference_t	*referenceAfter;	/* OPTIONAL */
	struct CreateDataSetRequestPDU__memberData {
		A_SEQUENCE_OF(CreateDataSetRequestPDU__memberData__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} memberData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CreateDataSetRequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CreateDataSetRequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _CreateDataSetRequestPDU_H_ */
#include <asn_internal.h>
