/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetAllDataDefinitionRequestPDU_H_
#define	_GetAllDataDefinitionRequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FunctionalConstraint.h"
#include "ObjectReference.h"
#include "ObjectName.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetAllDataDefinitionRequestPDU__reference_PR {
	GetAllDataDefinitionRequestPDU__reference_PR_NOTHING,	/* No components present */
	GetAllDataDefinitionRequestPDU__reference_PR_ldName,
	GetAllDataDefinitionRequestPDU__reference_PR_lnReference
} GetAllDataDefinitionRequestPDU__reference_PR;

/* GetAllDataDefinitionRequestPDU */
typedef struct GetAllDataDefinitionRequestPDU {
	struct GetAllDataDefinitionRequestPDU__reference {
		GetAllDataDefinitionRequestPDU__reference_PR present;
		union GetAllDataDefinitionRequestPDU__reference_u {
			ObjectName_t	 ldName;
			ObjectReference_t	 lnReference;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} reference;
	FunctionalConstraint_t	*fc;	/* OPTIONAL */
	ObjectReference_t	*referenceAfter;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetAllDataDefinitionRequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetAllDataDefinitionRequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetAllDataDefinitionRequestPDU_H_ */
#include <asn_internal.h>
