/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetAllDataDefinitionResponsePDU_H_
#define	_GetAllDataDefinitionResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include "SubReference.h"
#include <VisibleString.h>
#include "DataDefinition.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct GetAllDataDefinitionResponsePDU__data__Member {
	SubReference_t	 reference;
	VisibleString_t	*cdcType;	/* OPTIONAL */
	DataDefinition_t	 definition;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetAllDataDefinitionResponsePDU__data__Member;

/* GetAllDataDefinitionResponsePDU */
typedef struct GetAllDataDefinitionResponsePDU {
	struct GetAllDataDefinitionResponsePDU__data {
		A_SEQUENCE_OF(GetAllDataDefinitionResponsePDU__data__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} data;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetAllDataDefinitionResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetAllDataDefinitionResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetAllDataDefinitionResponsePDU_H_ */
#include <asn_internal.h>
