/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetBRCBValuesResponsePDU_H_
#define	_GetBRCBValuesResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include "ServiceError.h"
#include "BRCB.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetBRCBValuesResponsePDU__brcb__Member_PR {
	GetBRCBValuesResponsePDU__brcb__Member_PR_NOTHING,	/* No components present */
	GetBRCBValuesResponsePDU__brcb__Member_PR_error,
	GetBRCBValuesResponsePDU__brcb__Member_PR_value
} GetBRCBValuesResponsePDU__brcb__Member_PR;

/* Forward definitions */
typedef struct GetBRCBValuesResponsePDU__brcb__Member {
	GetBRCBValuesResponsePDU__brcb__Member_PR present;
	union GetBRCBValuesResponsePDU__brcb__Member_u {
		ServiceError_t	 error;
		BRCB_t	 value;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetBRCBValuesResponsePDU__brcb__Member;

/* GetBRCBValuesResponsePDU */
typedef struct GetBRCBValuesResponsePDU {
	struct GetBRCBValuesResponsePDU__brcb {
		A_SEQUENCE_OF(GetBRCBValuesResponsePDU__brcb__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} brcb;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetBRCBValuesResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetBRCBValuesResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetBRCBValuesResponsePDU_H_ */
#include <asn_internal.h>
