/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#include "GetFileRequestPDU.h"

static asn_TYPE_member_t asn_MBR_GetFileRequestPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetFileRequestPDU, filename),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString255,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"filename"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetFileRequestPDU, startPostion),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_INT32U,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"startPostion"
		},
};
static const ber_tlv_tag_t asn_DEF_GetFileRequestPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetFileRequestPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* filename */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* startPostion */
};
static asn_SEQUENCE_specifics_t asn_SPC_GetFileRequestPDU_specs_1 = {
	sizeof(struct GetFileRequestPDU),
	offsetof(struct GetFileRequestPDU, _asn_ctx),
	asn_MAP_GetFileRequestPDU_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GetFileRequestPDU = {
	"GetFileRequestPDU",
	"GetFileRequestPDU",
	&asn_OP_SEQUENCE,
	asn_DEF_GetFileRequestPDU_tags_1,
	sizeof(asn_DEF_GetFileRequestPDU_tags_1)
		/sizeof(asn_DEF_GetFileRequestPDU_tags_1[0]), /* 1 */
	asn_DEF_GetFileRequestPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetFileRequestPDU_tags_1)
		/sizeof(asn_DEF_GetFileRequestPDU_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_GetFileRequestPDU_1,
	2,	/* Elements count */
	&asn_SPC_GetFileRequestPDU_specs_1	/* Additional specs */
};

