/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetFileDirectoryResponsePDU_H_
#define	_GetFileDirectoryResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FileEntry;

/* GetFileDirectoryResponsePDU */
typedef struct GetFileDirectoryResponsePDU {
	struct GetFileDirectoryResponsePDU__fileEntry {
		A_SEQUENCE_OF(struct FileEntry) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} fileEntry;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetFileDirectoryResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetFileDirectoryResponsePDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FileEntry.h"

#endif	/* _GetFileDirectoryResponsePDU_H_ */
#include <asn_internal.h>
