/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetFileAttributeValuesResponsePDU_H_
#define	_GetFileAttributeValuesResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FileEntry.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GetFileAttributeValuesResponsePDU */
typedef FileEntry_t	 GetFileAttributeValuesResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetFileAttributeValuesResponsePDU;
asn_struct_free_f GetFileAttributeValuesResponsePDU_free;
asn_struct_print_f GetFileAttributeValuesResponsePDU_print;
asn_constr_check_f GetFileAttributeValuesResponsePDU_constraint;
xer_type_decoder_f GetFileAttributeValuesResponsePDU_decode_xer;
xer_type_encoder_f GetFileAttributeValuesResponsePDU_encode_xer;
per_type_decoder_f GetFileAttributeValuesResponsePDU_decode_aper;
per_type_encoder_f GetFileAttributeValuesResponsePDU_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _GetFileAttributeValuesResponsePDU_H_ */
#include <asn_internal.h>
