/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#include "GetGoReferenceRequestPDU.h"

static asn_TYPE_member_t asn_MBR_memberOffset_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INT16U,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_memberOffset_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_memberOffset_specs_3 = {
	sizeof(struct GetGoReferenceRequestPDU__memberOffset),
	offsetof(struct GetGoReferenceRequestPDU__memberOffset, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_memberOffset_3 = {
	"memberOffset",
	"memberOffset",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_memberOffset_tags_3,
	sizeof(asn_DEF_memberOffset_tags_3)
		/sizeof(asn_DEF_memberOffset_tags_3[0]) - 1, /* 1 */
	asn_DEF_memberOffset_tags_3,	/* Same as above */
	sizeof(asn_DEF_memberOffset_tags_3)
		/sizeof(asn_DEF_memberOffset_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_memberOffset_3,
	1,	/* Single element */
	&asn_SPC_memberOffset_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_GetGoReferenceRequestPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetGoReferenceRequestPDU, gocbReference),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObjectReference,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"gocbReference"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GetGoReferenceRequestPDU, memberOffset),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_memberOffset_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"memberOffset"
		},
};
static const ber_tlv_tag_t asn_DEF_GetGoReferenceRequestPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetGoReferenceRequestPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gocbReference */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* memberOffset */
};
static asn_SEQUENCE_specifics_t asn_SPC_GetGoReferenceRequestPDU_specs_1 = {
	sizeof(struct GetGoReferenceRequestPDU),
	offsetof(struct GetGoReferenceRequestPDU, _asn_ctx),
	asn_MAP_GetGoReferenceRequestPDU_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GetGoReferenceRequestPDU = {
	"GetGoReferenceRequestPDU",
	"GetGoReferenceRequestPDU",
	&asn_OP_SEQUENCE,
	asn_DEF_GetGoReferenceRequestPDU_tags_1,
	sizeof(asn_DEF_GetGoReferenceRequestPDU_tags_1)
		/sizeof(asn_DEF_GetGoReferenceRequestPDU_tags_1[0]), /* 1 */
	asn_DEF_GetGoReferenceRequestPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetGoReferenceRequestPDU_tags_1)
		/sizeof(asn_DEF_GetGoReferenceRequestPDU_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_GetGoReferenceRequestPDU_1,
	2,	/* Elements count */
	&asn_SPC_GetGoReferenceRequestPDU_specs_1	/* Additional specs */
};

