/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetLogStatusValuesErrorPDU_H_
#define	_GetLogStatusValuesErrorPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServiceError.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GetLogStatusValuesErrorPDU */
typedef ServiceError_t	 GetLogStatusValuesErrorPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetLogStatusValuesErrorPDU;
asn_struct_free_f GetLogStatusValuesErrorPDU_free;
asn_struct_print_f GetLogStatusValuesErrorPDU_print;
asn_constr_check_f GetLogStatusValuesErrorPDU_constraint;
xer_type_decoder_f GetLogStatusValuesErrorPDU_decode_xer;
xer_type_encoder_f GetLogStatusValuesErrorPDU_encode_xer;
per_type_decoder_f GetLogStatusValuesErrorPDU_decode_aper;
per_type_encoder_f GetLogStatusValuesErrorPDU_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _GetLogStatusValuesErrorPDU_H_ */
#include <asn_internal.h>
