/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetRpcMethodDirectoryRequestPDU_H_
#define	_GetRpcMethodDirectoryRequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetRpcMethodDirectoryRequestPDU */
typedef struct GetRpcMethodDirectoryRequestPDU {
#ifdef NOT_USE_IN_C11
	VisibleString_t	 *interfaceAPI;
#else
	VisibleString_t	 *interface;
#endif
	VisibleString_t	*referenceAfter;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetRpcMethodDirectoryRequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetRpcMethodDirectoryRequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetRpcMethodDirectoryRequestPDU_H_ */
#include <asn_internal.h>
