/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#include "GetServerDirectoryRequestPDU.h"

static int
memb_objectClass_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0L && value <= 2L)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_objectClass_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_GetServerDirectoryRequestPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetServerDirectoryRequestPDU, objectClass),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_objectClass_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_objectClass_constraint_1
		},
		0, 0, /* No default value */
		"objectClass"
		},
	{ ATF_POINTER, 1, offsetof(struct GetServerDirectoryRequestPDU, referenceAfter),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObjectReference,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"referenceAfter"
		},
};
static const int asn_MAP_GetServerDirectoryRequestPDU_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_GetServerDirectoryRequestPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetServerDirectoryRequestPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* objectClass */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* referenceAfter */
};
static asn_SEQUENCE_specifics_t asn_SPC_GetServerDirectoryRequestPDU_specs_1 = {
	sizeof(struct GetServerDirectoryRequestPDU),
	offsetof(struct GetServerDirectoryRequestPDU, _asn_ctx),
	asn_MAP_GetServerDirectoryRequestPDU_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_GetServerDirectoryRequestPDU_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GetServerDirectoryRequestPDU = {
	"GetServerDirectoryRequestPDU",
	"GetServerDirectoryRequestPDU",
	&asn_OP_SEQUENCE,
	asn_DEF_GetServerDirectoryRequestPDU_tags_1,
	sizeof(asn_DEF_GetServerDirectoryRequestPDU_tags_1)
		/sizeof(asn_DEF_GetServerDirectoryRequestPDU_tags_1[0]), /* 1 */
	asn_DEF_GetServerDirectoryRequestPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetServerDirectoryRequestPDU_tags_1)
		/sizeof(asn_DEF_GetServerDirectoryRequestPDU_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_GetServerDirectoryRequestPDU_1,
	2,	/* Elements count */
	&asn_SPC_GetServerDirectoryRequestPDU_specs_1	/* Additional specs */
};

