/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_LCB_H_
#define	_LCB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "ObjectReference.h"
#include "TriggerConditions.h"
#include "INT32U.h"
#include "LCBOptFlds.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LCB */
typedef struct LCB {
	BOOLEAN_t	 logEna;
	ObjectReference_t	 datSet;
	TriggerConditions_t	 trgOps;
	INT32U_t	 intgPd;
	ObjectReference_t	 logRef;
	LCBOptFlds_t	*optFlds;	/* OPTIONAL */
	INT32U_t	*bufTm;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCB;
extern asn_SEQUENCE_specifics_t asn_SPC_LCB_specs_1;
extern asn_TYPE_member_t asn_MBR_LCB_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _LCB_H_ */
#include <asn_internal.h>
