/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_RCBOptFlds_H_
#define	_RCBOptFlds_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RCBOptFlds {
	RCBOptFlds_reserved	= 0,
	RCBOptFlds_sequence_number	= 1,
	RCBOptFlds_report_time_stamp	= 2,
	RCBOptFlds_reason_for_inclusion	= 3,
	RCBOptFlds_data_set_name	= 4,
	RCBOptFlds_data_reference	= 5,
	RCBOptFlds_buffer_overflow	= 6,
	RCBOptFlds_entryID	= 7,
	RCBOptFlds_conf_revision	= 8,
	RCBOptFlds_segmentation	= 9
} e_RCBOptFlds;

/* RCBOptFlds */
typedef BIT_STRING_t	 RCBOptFlds_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RCBOptFlds_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RCBOptFlds;
asn_struct_free_f RCBOptFlds_free;
asn_struct_print_f RCBOptFlds_print;
asn_constr_check_f RCBOptFlds_constraint;
xer_type_decoder_f RCBOptFlds_decode_xer;
xer_type_encoder_f RCBOptFlds_encode_xer;
per_type_decoder_f RCBOptFlds_decode_aper;
per_type_encoder_f RCBOptFlds_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RCBOptFlds_H_ */
#include <asn_internal.h>
