/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_ServiceError_H_
#define	_ServiceError_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ServiceError {
	ServiceError_no_error	= 0,
	ServiceError_instance_not_available	= 1,
	ServiceError_instance_in_use	= 2,
	ServiceError_access_violation	= 3,
	ServiceError_access_not_allowed_in_current_state	= 4,
	ServiceError_parameter_value_inappropriate	= 5,
	ServiceError_parameter_value_inconsistent	= 6,
	ServiceError_class_not_supported	= 7,
	ServiceError_instance_locked_by_other_client	= 8,
	ServiceError_control_must_be_selected	= 9,
	ServiceError_type_conflict	= 10,
	ServiceError_failed_due_to_communications_constraint	= 11,
	ServiceError_failed_due_to_server_constraint	= 12
} e_ServiceError;

/* ServiceError */
typedef long	 ServiceError_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ServiceError_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ServiceError;
asn_struct_free_f ServiceError_free;
asn_struct_print_f ServiceError_print;
asn_constr_check_f ServiceError_constraint;
xer_type_decoder_f ServiceError_decode_xer;
xer_type_encoder_f ServiceError_encode_xer;
per_type_decoder_f ServiceError_decode_aper;
per_type_encoder_f ServiceError_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ServiceError_H_ */
#include <asn_internal.h>
