/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#include "SetDataSetValuesRequestPDU.h"

static asn_TYPE_member_t asn_MBR_value_4[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_Data,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_value_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_value_specs_4 = {
	sizeof(struct SetDataSetValuesRequestPDU__value),
	offsetof(struct SetDataSetValuesRequestPDU__value, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_value_4 = {
	"value",
	"value",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_value_tags_4,
	sizeof(asn_DEF_value_tags_4)
		/sizeof(asn_DEF_value_tags_4[0]) - 1, /* 1 */
	asn_DEF_value_tags_4,	/* Same as above */
	sizeof(asn_DEF_value_tags_4)
		/sizeof(asn_DEF_value_tags_4[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_value_4,
	1,	/* Single element */
	&asn_SPC_value_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SetDataSetValuesRequestPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SetDataSetValuesRequestPDU, datasetReference),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObjectReference,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"datasetReference"
		},
	{ ATF_POINTER, 1, offsetof(struct SetDataSetValuesRequestPDU, referenceAfter),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObjectReference,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"referenceAfter"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SetDataSetValuesRequestPDU, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_value_4,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"value"
		},
};
static const int asn_MAP_SetDataSetValuesRequestPDU_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_SetDataSetValuesRequestPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SetDataSetValuesRequestPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* datasetReference */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* referenceAfter */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
static asn_SEQUENCE_specifics_t asn_SPC_SetDataSetValuesRequestPDU_specs_1 = {
	sizeof(struct SetDataSetValuesRequestPDU),
	offsetof(struct SetDataSetValuesRequestPDU, _asn_ctx),
	asn_MAP_SetDataSetValuesRequestPDU_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_SetDataSetValuesRequestPDU_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SetDataSetValuesRequestPDU = {
	"SetDataSetValuesRequestPDU",
	"SetDataSetValuesRequestPDU",
	&asn_OP_SEQUENCE,
	asn_DEF_SetDataSetValuesRequestPDU_tags_1,
	sizeof(asn_DEF_SetDataSetValuesRequestPDU_tags_1)
		/sizeof(asn_DEF_SetDataSetValuesRequestPDU_tags_1[0]), /* 1 */
	asn_DEF_SetDataSetValuesRequestPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_SetDataSetValuesRequestPDU_tags_1)
		/sizeof(asn_DEF_SetDataSetValuesRequestPDU_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SetDataSetValuesRequestPDU_1,
	3,	/* Elements count */
	&asn_SPC_SetDataSetValuesRequestPDU_specs_1	/* Additional specs */
};

