/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_SetEditSGValueRequestPDU_H_
#define	_SetEditSGValueRequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "ObjectReference.h"
#include "Data.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct SetEditSGValueRequestPDU__data__Member {
	ObjectReference_t	 reference;
	Data_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetEditSGValueRequestPDU__data__Member;

/* SetEditSGValueRequestPDU */
typedef struct SetEditSGValueRequestPDU {
	struct SetEditSGValueRequestPDU__data {
		A_SEQUENCE_OF(SetEditSGValueRequestPDU__data__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} data;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetEditSGValueRequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetEditSGValueRequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _SetEditSGValueRequestPDU_H_ */
#include <asn_internal.h>
