/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_SetFileResponsePDU_H_
#define	_SetFileResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SetFileResponsePDU */
typedef NULL_t	 SetFileResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetFileResponsePDU;
asn_struct_free_f SetFileResponsePDU_free;
asn_struct_print_f SetFileResponsePDU_print;
asn_constr_check_f SetFileResponsePDU_constraint;
xer_type_decoder_f SetFileResponsePDU_decode_xer;
xer_type_encoder_f SetFileResponsePDU_encode_xer;
per_type_decoder_f SetFileResponsePDU_decode_aper;
per_type_encoder_f SetFileResponsePDU_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SetFileResponsePDU_H_ */
#include <asn_internal.h>
