#ifndef STTMULTIMACRODISTANCESEARCHPARASDEFINE_H
#define STTMULTIMACRODISTANCESEARCHPARASDEFINE_H
#include "../SttMultiMacroParasDefine.h"

#define IMPEDANCE_FAULT_TYPE_AN                                                 0//阻抗类的故障类型定义
#define IMPEDANCE_FAULT_TYPE_BN                                                 1
#define IMPEDANCE_FAULT_TYPE_CN                                                 2
#define IMPEDANCE_FAULT_TYPE_AB                                                 3
#define IMPEDANCE_FAULT_TYPE_BC                                                 4
#define IMPEDANCE_FAULT_TYPE_CA                                                 5
#define IMPEDANCE_FAULT_TYPE_ABN                                                6
#define IMPEDANCE_FAULT_TYPE_BCN                                                7
#define IMPEDANCE_FAULT_TYPE_CAN                                                8
#define IMPEDANCE_FAULT_TYPE_ABC                                                9
#define IMPEDANCE_FAULT_TYPE_ONE                                                10

//动作时间根节点下,按故障类型进行分类创建文件夹
#define STT_MULTI_MACRO_DISTANCESEARCH_FaultType_Items_ID_AN					 "FaultType_AN"
#define STT_MULTI_MACRO_DISTANCESEARCH_FaultType_Items_ID_BN					 "FaultType_BN"
#define STT_MULTI_MACRO_DISTANCESEARCH_FaultType_Items_ID_CN					 "FaultType_CN"
#define STT_MULTI_MACRO_DISTANCESEARCH_FaultType_Items_ID_AB					 "FaultType_AB"
#define STT_MULTI_MACRO_DISTANCESEARCH_FaultType_Items_ID_BC					 "FaultType_BC"
#define STT_MULTI_MACRO_DISTANCESEARCH_FaultType_Items_ID_CA					 "FaultType_CA"
#define STT_MULTI_MACRO_DISTANCESEARCH_FaultType_Items_ID_ThreePhase			 "FaultType_ThreePhase"
#define STT_MULTI_MACRO_DISTANCESEARCH_FaultType_Items_ID_ZeroCurr				 "FaultType_ZeroCurr"
#define STT_MULTI_MACRO_DISTANCESEARCH_FaultType_Items_ID_NegCurr				 "FaultType_NegCurr"
#define STT_MULTI_MACRO_DISTANCESEARCH_FaultType_Items_ID_ThreeParallel			 "FaultType_ThreeParallel"

//DistanceSearchI_Grid.xml 表格参数
#define STT_MULTI_MACRO_DISTANCESEARCH_GRID_PARAS_ID_SELECT                 "Select"		//选择
#define STT_MULTI_MACRO_DISTANCESEARCH_GRID_PARAS_ID_STATE					"State"			//状态
#define STT_MULTI_MACRO_DISTANCESEARCH_GRID_PARAS_ID_TripZ                  "TripZ"         //实测阻抗(Ω)
#define STT_MULTI_MACRO_DISTANCESEARCH_GRID_PARAS_ID_TripZAngle				"TripZAngle"    //实测阻抗角(°)
#define STT_MULTI_MACRO_DISTANCESEARCH_GRID_PARAS_ID_TTRIP_ERRORLOGIC		"CurveErr_ErrorLogic"		//误差类型

//QActionTimeItemParaEditWidget	功能参数页面
//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_FAULTTYPE				"FaultType"			//故障类型
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_STEP					"Step"			//阻抗步长
//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_ZONETYPE				"ZoneType"		//区段
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_FAULTIF					"FaultIf"			//短路电流
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_BEGINVAL				"BeginVal"		//首端阻抗
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_FAULTVF					"FaultVf"		//短路电压
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_BEGINVALANG				"BeginValAng"		//首端阻抗角
//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_TSETTING				"TSetting"			//时间定值
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_ENDVAL					"EndVal"		//末端阻抗
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_ENDVALANG				"EndValAng"	//末端阻抗角

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_VALSETTING				"ValSetting"		//待测定值
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_VALSETTINGANG			"ValSettingAngle"	//待测阻抗角度定值

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_DATATYPE_ID_SYSTEMFAULT            "SystemFault"		//故障类型数据类型

#define STEP_MIN 0
#define STEP_MAX 100
#define FAULTIF_MIN 0
#define FAULTIF_MAX 18
#define BEGINVAL_MIN 0
#define BEGINVAL_MAX 100
#define FAULTVF_MIN 0
#define FAULTVF_MAX 999.999
#define BEGINVALANG_MIN -360
#define BEGINVALANG_MAX 360
#define FAULTTIME_MIN 0.001
#define FAULTTIME_MAX 999.999
#define ENDVAL_MIN 0
#define ENDVAL_MAX 100
#define ENDVALANG_MIN -360
#define ENDVALANG_MAX 360
#define TTRIPRELERR_MIN 0
#define TTRIPRELERR_MAX 100
#define TTRIPABSERR_MIN 0
#define TTRIPABSERR_MAX 200

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_DEFAULT			"0"			//缺省值

//QDistanceSearchCommonParasDlg	通用参数页面
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_PREFAULTTIME			"PreFaultTime"      //故障前时间
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_TIMEAFTERTRIGGER		"TimeAfterTrigger"	//保护动作后持续时间
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_ILOAD					"ILoad"             //负荷电流
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_ILOADPH					"ILoadPh"           //负荷功角
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_K0MODE					"K0Mode"            //零序补偿系数计算方式
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_KLKR					"KlKr"              //零序补偿系数RE/RL
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_ANGKX					"AngKx"             //零序补偿系数XE/XL
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_FAULTTIME				"FaultTime"			//故障时间裕度
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_ACTIONTIME              "ActionTime"		//最小动作时间
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_SEARCHMODE				"SearchMode"		//搜索方式
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_CALCUMODE				"CalcuMode"         //计算方式
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_ZSMAG					"Zs_Mag"            //系统阻抗
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_ZSANG					"Zs_Ang"            //系统阻抗角
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_ZL                      "Zl"                //线路阻抗
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_MAXANGLE                "MaxAngle"          //最大灵敏角

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_LAB_K0						"|K0|:"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_LAB_PHI_K0					"|Phi(K0)|:   "
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_LAB_RERL					"RE/RL:"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_LAB_XEXL					"XE/XL:       "
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_LAB_Z0Z1					"|Z0/Z1|:"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_LAB_PHI_Z0Z1				"|Phi(Z0/Z1)|:"

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_DATATYPE_ID_SEARCHMODE			"SearchModePnv"			//搜索方式数据类型
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_DATATYPE_ID_PTPOSITION			"PTPosition"			//TV安装位置数据类型
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_DATATYPE_ID_CTPOS              "CTPos"                 //TA正极性数据类型
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_DATATYPE_ID_CBSIMULSEL			"CBSimulSel"			//断路器模拟数据类型
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_DATATYPE_ID_FAULTANGMODE		"FaultAngMode"			//合闸角方式数据类型

//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_FIRSTSECFAULTTIME		"FirstSecFaultTime"			//Ⅰ段最大故障时间
//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_SECONDSECFAULTTIME		"SecondSecFaultTime"			//Ⅱ段最大故障时间
//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_THIRDSECFAULTTIME		"ThirdSecFaultTime"		//Ⅲ段最大故障时间
//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_FOURTHSECFAULTTIME		"FourthSecFaultTime"		//Ⅳ段最大故障时间

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_PTPOS					"PTPos"	//TV安装位置
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_CTPOS					"CTPos"			//TA正极性
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_SIMULATEBREAKERDELAY	"SimulateBreakerDelay"			//断路器模拟
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_BRKBREAKTIME			"BrkBreakTime"		//分闸时间s
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_BRKCLOSETIME			"BrkCloseTime"		//合闸时间s
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_FAULTID					"FaultId"	//是否叠加非周期分量
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_FAULTANGMODE			"FaultAngMode"			//合闸角方式
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_FAULTANG				"FaultAng"			//合闸角


#define PREFAULTTIME_MAX 100
#define PREFAULTTIME_MIN 0
#define TIMEAFTERTRIGGER_MAX 100
#define TIMEAFTERTRIGGER_MIN 0
#define ILOAD_MAX 999
#define ILOAD_MIN 0
#define ILOADPH_MAX 360
#define ILOADPH_MIN -360
#define KLKR_MAX 999
#define KLKR_MIN 0
#define ANGKX_MAX 360
#define ANGKX_MIN -360
#define FAULTTIME_MAX 999.999
#define FAULTTIME_MIN 0
#define ACTIONTIME_MAX 999.999
#define ACTIONTIME_MIN 0

#define ZSMAG_MAX 100
#define ZSMAG_MIN 0
#define ZSANG_MAX 360
#define ZSANG_MIN -360

//#define FIRSTSECFAULTTIME_MAX 999.999
//#define FIRSTSECFAULTTIME_MIN 0.001
//#define SECONDSECFAULTTIME_MAX 999.999
//#define SECONDSECFAULTTIME_MIN 0.001
//#define THIRDSECFAULTTIME_MAX 999.999
//#define THIRDSECFAULTTIME_MIN 0.001
//#define FOURTHSECFAULTTIME_MAX 999.999
//#define FOURTHSECFAULTTIME_MIN 0.001

#define BRKBREAKTIME_MAX 999999
#define BRKBREAKTIME_MIN 0
#define BRKCLOSETIME_MAX 999999
#define BRKCLOSETIME_MIN 0
#define FAULTANG_MAX 360
#define FAULTANG_MIN -360

//QDistanceSearchCommonParasDlg		开入、开出页面
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_A						"BinA"			//开入A
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_B						"BinB"			//开入B
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_C						"BinC"			//开入C
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_D						"BinD"			//开入D
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_E						"BinE"			//开入E
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_F						"BinF"			//开入F
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_G						"BinG"			//开入G
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_H						"BinH"			//开入H
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_ANDOR					"_AndOr"	//开入逻辑
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_B01						"_B01"		//开出1状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_B02						"_B02"		//开出2状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_B03						"_B03"		//开出3状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_B04						"_B04"		//开出4状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_B05						"_B05"		//开出5状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_B06						"_B06"		//开出6状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_B07						"_B07"		//开出7状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_B08						"_B08"		//开出8状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_OUTPUTSWITCHMODE		"_OutputSwitchMode"	//开出翻转控制方式
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_OUTPUTKEEPTIME			"_OutputKeepTime"		//开出保持时间
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_ID_OUTPUTDELAYTIME			"_OutputDelayTime"		//开出翻转延时

#define OUTPUTKEEPTIME_MAX 100000
#define OUTPUTKEEPTIME_MIN 0.01
#define OUTPUTDELAYTIME_MAX 100000
#define OUTPUTDELAYTIME_MIN 0.01

//QDistanceSearchBatchAddMultDlg 批量添加界面
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LNZone1_Check       "LNZone1_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LNZone2_Check       "LNZone2_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LNZone3_Check       "LNZone3_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LNZone4_Check       "LNZone4_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LNZone5_Check       "LNZone5_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LLZone1_Check       "LLZone1_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LLZone2_Check       "LLZone2_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LLZone3_Check       "LLZone3_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LLZone4_Check       "LLZone4_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LLZone5_Check       "LLZone5_Check"

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_TSetingLN_Zone1       "TSetingLN_Zone1"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_TSetingLN_Zone2       "TSetingLN_Zone2"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_TSetingLN_Zone3       "TSetingLN_Zone3"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_TSetingLN_Zone4       "TSetingLN_Zone4"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_TSetingLN_Zone5       "TSetingLN_Zone5"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_TSetingLL_Zone1       "TSetingLL_Zone1"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_TSetingLL_Zone2       "TSetingLL_Zone2"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_TSetingLL_Zone3       "TSetingLL_Zone3"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_TSetingLL_Zone4       "TSetingLL_Zone4"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_TSetingLL_Zone5       "TSetingLL_Zone5"

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN1FaultTypeAE_Check       "LN1FaultTypeAE_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN1FaultTypeBE_Check       "LN1FaultTypeBE_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN1FaultTypeCE_Check       "LN1FaultTypeCE_Check"

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN2FaultTypeAE_Check       "LN2FaultTypeAE_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN2FaultTypeBE_Check       "LN2FaultTypeBE_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN2FaultTypeCE_Check       "LN2FaultTypeCE_Check"

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN3FaultTypeAE_Check       "LN3FaultTypeAE_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN3FaultTypeBE_Check       "LN3FaultTypeBE_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN3FaultTypeCE_Check       "LN3FaultTypeCE_Check"

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN4FaultTypeAE_Check       "LN4FaultTypeAE_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN4FaultTypeBE_Check       "LN4FaultTypeBE_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN4FaultTypeCE_Check       "LN4FaultTypeCE_Check"

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN5FaultTypeAE_Check       "LN5FaultTypeAE_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN5FaultTypeBE_Check       "LN5FaultTypeBE_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LN5FaultTypeCE_Check       "LN5FaultTypeCE_Check"

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL1FaultTypeAB_Check       "LL1FaultTypeAB_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL1FaultTypeBC_Check       "LL1FaultTypeBC_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL1FaultTypeCA_Check       "LL1FaultTypeCA_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL1FaultTypeABC_Check       "LL1FaultTypeABC_Check"

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL2FaultTypeAB_Check       "LL2FaultTypeAB_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL2FaultTypeBC_Check       "LL2FaultTypeBC_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL2FaultTypeCA_Check       "LL2FaultTypeCA_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL2FaultTypeABC_Check       "LL2FaultTypeABC_Check"

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL3FaultTypeAB_Check       "LL3FaultTypeAB_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL3FaultTypeBC_Check       "LL3FaultTypeBC_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL3FaultTypeCA_Check       "LL3FaultTypeCA_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL3FaultTypeABC_Check       "LL3FaultTypeABC_Check"

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL4FaultTypeAB_Check       "LL4FaultTypeAB_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL4FaultTypeBC_Check       "LL4FaultTypeBC_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL4FaultTypeCA_Check       "LL4FaultTypeCA_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL4FaultTypeABC_Check       "LL4FaultTypeABC_Check"

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL5FaultTypeAB_Check       "LL5FaultTypeAB_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL5FaultTypeBC_Check       "LL5FaultTypeBC_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL5FaultTypeCA_Check       "LL5FaultTypeCA_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_LL5FaultTypeABC_Check       "LL5FaultTypeABC_Check"

#define SETTINGTIME_MIN 0
#define SETTINGTIME_MAX 999.999
#define RELERR_MIN 0
#define RELERR_MAX 100
#define ABSERR_MIN 0
#define ABSERR_MAX 200

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_STEP                     "Impedancestep"			//阻抗步长
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_FAULTIF					"FaultCurrent"			//短路电流
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_FAULTVF					"Faultvoltage"		//短路电压
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_CURVEERR_ABSERR			"CurveErr_AbsErr"	//绝对误差
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_CURVEERR_RELERR			"CurveErr_RelErr"	//相对误差
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_ERRORLOGIC               "CurveErr_ErrorLogic"	//误差逻辑

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_PREFAULTTIME             "PreFaultTime"      //故障前时间
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_TIMEAFTERTRIGGER         "TimeAfterTrigger"	//保护动作后持续时间
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_ILOAD					"ILoad"             //负荷电流
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_ILOADPH					"ILoadPh"           //负荷功角
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_K0MODE					"ZeroCalMode"       //零序补偿系数计算方式
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_KLKR                     "KlKr"              //零序补偿系数RE/RL
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_ANGKX					"AngKx"             //零序补偿系数XE/XL
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_FAULTTIME				"FaultTime"			//故障时间裕度
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_ACTIONTIME               "ActionTime"		//最小动作时间
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_SEARCHMODE				"SearchModePnv"		//搜索方式
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_CALCUMODE				"UIZCalMode"         //计算方式
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_ZSMAG					"systemImpedances"   //系统阻抗
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_ZSANG					"SysFaultAngle"      //系统阻抗角
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_ZL                       "Zl"                 //线路阻抗
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_MAXANGLE                 "MaxAngle"           //最大灵敏角

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_PTPOS					"PTPos"             //TV安装位置
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_CTPOS					"CTPos"             //TA正极性
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_SIMULATEBREAKERDELAY     "CBSimulation"		//断路器模拟
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_BRKBREAKTIME             "BrkBreakTime"		//分闸时间ms
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_BRKCLOSETIME             "BrkCloseTime"		//合闸时间ms
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_FAULTID					"bIPlusDC"          //是否叠加非周期分量
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_FAULTANGMODE             "FaultIncMode"		//合闸角方式
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_FAULTANG                 "FaultAngle"		//合闸角

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_A						"A"			//开入A
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_B						"B"			//开入B
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_C						"C"			//开入C
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_D						"R"			//开入D
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_E						"E"			//开入E
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_F						"F"			//开入F
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_G						"G"			//开入G
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_H						"H"			//开入H
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_ANDOR					"BinSelect"	//开入逻辑
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_B01						"_B01"		//开出1状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_B02						"_B02"		//开出2状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_B03						"_B03"		//开出3状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_B04						"_B04"		//开出4状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_B05						"_B05"		//开出5状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_B06						"_B06"		//开出6状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_B07						"_B07"		//开出7状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_B08						"_B08"		//开出8状态
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_OUTPUTSWITCHMODE         "_OutputSwitchMode"	//开出翻转控制方式
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_OUTPUTKEEPTIME			"_OutputKeepTime"		//开出保持时间
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_BATCH_MULT_ID_OUTPUTDELAYTIME			"_OutputDelayTime"		//开出翻转延时

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_FILENAME_MULT			_T("atsgen/DistanceSearch_Paras.xml")

//选择页面按键显示
//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAEDIT_BTN_ADDMULTQUICK		_T("快速添加")
//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAEDIT_BTN_ADDMULTDLG			_T("添加系列")
//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAEDIT_BTN_ADDMULTBATCH		_T("批量添加")
//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAEDIT_BTN_DELETESELITEM		_T("删除当前")
//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAEDIT_BTN_DELETEALLITEM		_T("删除全部")
//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAEDIT_BTN_CLEARSELRESULT		_T("清除当前")
//#define STT_MULTI_MACRO_DISTANCESEARCH_PARAEDIT_BTN_CLEARALLRESULT		_T("清除全部")

//QDistanceSearchAddMultDlg 添加系列-添加系列界面
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_AN          "FaultTypeAN_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_BN          "FaultTypeBN_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_CN          "FaultTypeCN_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_AB          "FaultTypeAB_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_BC          "FaultTypeBC_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_CA          "FaultTypeCA_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_ABC          "FaultTypeABC_Check"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_LN_TSetting          "LN_SettingTime"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_LL_TSetting          "LL_SettingTime"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_LLL_TSetting          "LLL_SettingTime"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_OriginImp          "OriginImpedances"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_OriginAng          "OriginAngle"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_SearchAngBegVal          "SearchAngBeginVal"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_SearchAngEndVal          "SearchAngEndVal"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_SearchLength          "SearchLength"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_AngleStep          "AngleStep"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_ZoneType          "ZoneType"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_FaultCur          "FaultCurrent"
#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_MULT_ID_FaultVolt          "Faultvoltage"

#define STT_MULTI_MACRO_DISTANCESEARCH_PARAS_DATATYPE_ID_ERRORTYPE			"RltErrorLogic_Time"		//误差类型数据类型

#endif // STTMULTIMACRODISTANCESEARCHPARASDEFINE_H
