//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Iec61850Config.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_IEC61850CONFIG_FORM         101
#define IDS_IecCfgDataTypes             101
#define IDD_SCLFILE_TREE_VIEW           102
#define IDD_IECCFG_SMVCTRL_VIEW         103
#define IDD_IECCFG_SMVCTRL_CHS_VIEW     104
#define IDD_IECCFG_GINCTRL_VIEW         105
#define IDD_IECCFG_GINCTRL_CHS_VIEW     106
#define IDD_IECCFG_GOUTCTRL_VIEW        107
#define IDD_IECCFG_GOUTCTRL_CHS_VIEW    108
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDD_SCLFILE_CTRL_VIEW           112
#define IDB_BUTTONS                     113
#define IDD_SCLFILE_CTRLCHS_VIEW        113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_Iec61850ConfigTYPE          130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_OUTPUTWND               149
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_OUTPUT_WND                  157
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_Iec61850ConfigTYPE1         167
#define IDR_SclFileTYPE                 167
#define IDR_OUTPUT_POPUP                182
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDD_DLG_SCL_FILE_HIS            310
#define IDD_DLG_SCL_READ_PROGRESS       311
#define IDB_IECCFGFILE                  312
#define IDB_BITMAP_SCLDATA              313
#define IDD_XFILEMNGRVIEW               314
#define IDD_STATETOOL_FORM              315
#define IDR_TOOLBAR_IECFGDEVICE         316
#define IDR_TOOLBAR_DEVICE              321
#define IDD_IECCFG_SMVINCTRL_CHS_VIEW   323
#define IDD_AT02D_CBS_FORM              323
#define IDD_DLG_AT02D_CFG               324
#define IDD_IECCFG_SMVINCTRL_VIEW       325
#define IDD_IECCFG_SYSPARAS_VIEW        325
#define IDD_IECCFG_FT3COMMON_SET_DLG    326
#define IDC_TREE1                       1000
#define IDC_EDIT_SMAP_RATE              1004
#define IDC_COMBO_SMV_TYPE              1006
#define IDC_COMBO_ASDU                  1011
#define IDC_LIST_SCL_HIS                1012
#define IDC_BTN_BROWSE                  1013
#define IDC_PROGRESS_READ               1014
#define IDC_STATIC_TIME                 1015
#define IDC_BTN_ADDTO                   1016
#define IDC_COMBO_IECCFG_FILE           1017
#define IDC_COMBO_IECCFG_TYPE           1018
#define IDC_COMBO_FILTER                1018
#define IDC_BTN_OVERRITE                1019
#define IDC_BTN_FILTER                  1019
#define IDC_BTN_COMPARE                 1020
#define IDC_CHECK_I                     1020
#define IDC_CHECK_U                     1021
#define IDC_BTN_ONE_KEY_CFG             1021
#define IDC_BTN_SET_ABC                 1022
#define IDC_BTN_SET_PABC                1023
#define IDC_BUTTON_DELETE               1023
#define IDC_BTN_SET_SABC                1024
#define IDC_BUTTON1                     1024
#define IDC_SMV_RATE                    1024
#define IDC_BTN_EXPORT                  1024
#define IDC_BTN_SET_TABC                1025
#define IDC_CHECK1                      1025
#define IDC_CHECK_QUALITY               1025
#define IDC_CHECK_ALL                   1025
#define IDC_BTN_SET_0                   1026
#define IDC_CHECK_DATASET               1026
#define IDC_CHECK_SECURITY              1027
#define IDC_BTN_SET_ABC5                1027
#define IDC_CHECK2                      1028
#define IDC_CHECK_USENAME               1028
#define IDC_CHECK_SMPRATE               1028
#define IDC_RADIO_UISEL_U               1029
#define IDC_STATIC_MESTYPE              1029
#define IDC_RADIO_UISEL_ALL             1030
#define IDC_STATIC_                     1030
#define IDC_STATIC_SAMPLERATE           1030
#define IDC_RADIO_UISEL_U2              1031
#define IDC_RADIO_UISEL_I               1031
#define IDC_STATIC_ASDU                 1031
#define IDC_STATIC_LOG_MSG              1032
#define IDC_CHECK_SMPRATE2              1032
#define IDC_CHECK_REFRTM                1032
#define IDC_BTN_SET_ABC6                1032
#define IDC_COMBO_MAX_FIBER_NUM         1033
#define IDC_BTN_SET_CHECK               1033
#define IDC_COMBO_PKG_SEND_TYPE         1034
#define IDC_STATIC_PKG_SEND_TYPE        1035
#define IDC_STATIC_SEC_SYN_STATE        1036
#define IDC_COMBO_SEC_SYN_STATE         1037
#define IDC_STATIC_GROUP1               1038
#define IDC_STATIC_GROUP_RATE1          1039
#define IDC_STATIC_PT_RATE1             1040
#define IDC_EDIT_PRIM_PT_RATE1          1041
#define IDC_EDIT_SECOND_PT_RATE1        1042
#define IDC_STATIC_PT1_DIV              1043
#define IDC_STATIC_GROUP_RATE2          1044
#define IDC_STATIC_PT_RATE2             1045
#define IDC_EDIT_PRIM_PT_RATE2          1046
#define IDC_STATIC_PT1_DIV2             1047
#define IDC_STATIC_CT_RATE1             1048
#define IDC_EDIT_PRIM_CT_RATE1          1049
#define IDC_STATIC_CT1_DIV              1050
#define IDC_EDIT_SECOND_CT_RATE1        1051
#define IDC_EDIT_SECOND_PT_RATE2        1052
#define IDC_STATIC_CT_RATE2             1053
#define IDC_EDIT_PRIM_CT_RATE2          1054
#define IDC_STATIC_CT1_DIV2             1055
#define IDC_EDIT_SECOND_CT_RATE2        1056
#define IDC_STATIC_GROUP_RATE3          1057
#define IDC_STATIC_PT_RATE3             1058
#define IDC_EDIT_PRIM_PT_RATE3          1059
#define IDC_STATIC_PT1_DIV3             1060
#define IDC_EDIT_SECOND_PT_RATE3        1061
#define IDC_STATIC_CT_RATE3             1062
#define IDC_EDIT_PRIM_CT_RATE3          1063
#define IDC_STATIC_CT1_DIV3             1064
#define IDC_EDIT_SECOND_CT_RATE3        1065
#define IDC_STATIC_GROUP_RATE4          1066
#define IDC_STATIC_PT_RATE4             1067
#define IDC_EDIT_PRIM_PT_RATE4          1068
#define IDC_STATIC_PT1_DIV4             1069
#define IDC_EDIT_SECOND_PT_RATE4        1070
#define IDC_STATIC_CT_RATE4             1071
#define IDC_EDIT_PRIM_CT_RATE4          1072
#define IDC_STATIC_CT1_DIV4             1073
#define IDC_EDIT_SECOND_CT_RATE4        1074
#define IDC_STATIC_GROUP_RATE5          1075
#define IDC_STATIC_PT_RATE5             1076
#define IDC_EDIT_PRIM_PT_RATE5          1077
#define IDC_STATIC_PT1_DIV5             1078
#define IDC_EDIT_SECOND_PT_RATE5        1079
#define IDC_STATIC_CT_RATE5             1080
#define IDC_EDIT_PRIM_CT_RATE5          1081
#define IDC_STATIC_CT1_DIV5             1082
#define IDC_EDIT_SECOND_CT_RATE5        1083
#define IDC_STATIC_GROUP_RATE6          1084
#define IDC_STATIC_PT_RATE6             1085
#define IDC_EDIT_PRIM_PT_RATE6          1086
#define IDC_STATIC_PT1_DIV6             1087
#define IDC_EDIT_SECOND_PT_RATE6        1088
#define IDC_STATIC_CT_RATE6             1089
#define IDC_EDIT_PRIM_CT_RATE6          1090
#define IDC_STATIC_CT1_DIV6             1091
#define IDC_EDIT_SECOND_CT_RATE6        1092
#define IDC_STATIC_GROUP2               1093
#define IDC_STATIC_GROUP3               1094
#define IDC_STATIC_GROUP_PARAS_SET      1094
#define IDC_STATIC_BCODE_LOGIC          1095
#define IDC_RADIO_POSITIVE              1096
#define IDC_RADIO_NEGATIVE              1097
#define IDC_COMBO_SMP_RATE_FT3          1097
#define IDC_STATIC_IEC1588              1098
#define IDC_STATIC_SMP_RATE_FT3         1098
#define IDC_RADIO_IEC1588_PEER          1099
#define IDC_STATIC_BAUDRATE_FT3         1099
#define IDC_EDIT_DC_VOL_CODE_VALUE      1099
#define IDC_RADIO_IEC1588_REQ_RES       1100
#define IDC_COMBO_BAUD_RATE_FT3         1100
#define IDC_STC_DC_VOL_CODE_VALUE       1100
#define IDC_STATIC_GROUP4               1101
#define IDC_STC_DC_VOL_PRIM_VALUE       1101
#define IDC_STATIC_LC_FIBER1            1102
#define IDC_EDIT_DC_VOL_PRIM_VALUE      1102
#define IDC_RADIO_100M_FIBER1           1103
#define IDC_STC_DC_CUR_CODE_VALUE       1103
#define IDC_RADIO_1000M_FIBER1          1104
#define IDC_EDIT_DC_CUR_CODE_VALUE      1104
#define IDC_STATIC_LC_FIBER2            1105
#define IDC_STC_DC_CUR_PRIM_VALUE       1105
#define IDC_RADIO_100M_FIBER2           1106
#define IDC_EDIT_DC_CUR_PRIM_VALUE      1106
#define IDC_RADIO_1000M_FIBER2          1107
#define IDC_STC_DC_NEUTRAL_VOL_CODE_VALUE 1107
#define IDC_STATIC_LC_FIBER3            1108
#define IDC_EDIT_DC_NEUTRAL_VOL_CODE_VALUE 1108
#define IDC_RADIO_100M_FIBER3           1109
#define IDC_STC_DC_NEUTRAL_VOL_PRIM_VALUE 1109
#define IDC_RADIO_1000M_FIBER3          1110
#define IDC_EDIT_DC_NEUTRAL_VOL_PRIM_VALUE 1110
#define IDC_STATIC_LC_FIBER4            1111
#define IDC_STC_AC_PROT_CUR_CODE_VALUE  1111
#define IDC_RADIO_100M_FIBER4           1112
#define IDC_EDIT_AC_PROT_CUR_CODE_VALUE 1112
#define IDC_RADIO_1000M_FIBER4          1113
#define IDC_STC_AC_PROT_CUR_PRIM_VALUE  1113
#define IDC_STATIC_GROUP5               1114
#define IDC_EDIT_AC_PROT_CUR_PRIM_VALUE 1114
#define IDC_STATIC_ST_FIBER1            1115
#define IDC_STC_AC_MEAS_CUR_CODE_VALUE  1115
#define IDC_RADIO_BCODE_FIBER1          1116
#define IDC_EDIT_AC_MEAS_CUR_CODE_VALUE 1116
#define IDC_RADIO_FT3_FIBER1            1117
#define IDC_STC_AC_MEAS_CUR_PRIM_VALUE  1117
#define IDC_STATIC_ST_FIBER2            1118
#define IDC_EDIT_AC_MEAS_CUR_PRIM_VALUE 1118
#define IDC_RADIO_BCODE_FIBER2          1119
#define IDC_STC_AC_VOL_CODE_VALUE       1119
#define IDC_RADIO_FT3_FIBER2            1120
#define IDC_EDIT_AC__VOL_CODE_VALUE     1120
#define IDC_STATIC_ST_FIBER3            1121
#define IDC_STC_AC_VOL_PRIM_VALUE       1121
#define IDC_RADIO_BCODE_FIBER3          1122
#define IDC_EDIT_AC__VOL_PRIM_VALUE     1122
#define IDC_EDIT_AC_VOL_PRIM_VALUE      1122
#define IDC_RADIO_FT3_FIBER3            1123
#define IDC_CUSTOM_IECCFG_CTRLS_GRID    1125
#define IDC_STATIC_ST_FIBER4            1133
#define IDC_RADIO_BCODE_FIBER4          1134
#define IDC_RADIO_FT3_FIBER4            1135
#define IDC_STATIC_ST_FIBER5            1136
#define IDC_RADIO_BCODE_FIBER5          1137
#define IDC_RADIO_FT3_FIBER5            1138
#define IDC_STATIC_ST_FIBER6            1139
#define IDC_RADIO_BCODE_FIBER6          1140
#define IDC_RADIO_FT3_FIBER6            1141
#define IDC_STATIC_PARAS_SET_SEL        1145
#define IDC_COMBO_PARAS_SET_SEL         1146
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_FILE_OPEN_SCL                32771
#define ID_VIEW_IECCFG_FILE_PANE        32772
#define ID_VIEW_OUTPUT                  32773
#define ID_FILE_OPEN_SCL_HIS            32774
#define ID_FILE_USE_IECCFGFILE          32775
#define ID_FILE_RUN_61850CAP            32776
#define ID_FILE_IMPORT                  32777
#define ID_FILE_STATE_TOOL              32778
#define ID_FILE_STATE_STARTTEST         32779
#define ID_FILE_STATE_STOPTEST          32780
#define ID_VIEW_IECCFG_USEDIN           32781
#define ID_IECFGDEVICE_NEW              32786
#define ID_IECFGDEVICE_DELETE           32787
#define ID_IECFGDEVICE_MOVEUP           32788
#define ID_IECFGDEVICE_MOVEDOWN         32789
#define ID_IECFGDEVICE_CLOSE            32791
#define ID_FILE_NEW_DEVICE              32792
#define ID_VIEW_IECCFG_DEVICE_PANE      32793
#define ID_IECFGDEVICE_CLONE            32794
#define ID_VIEW_IECCFG_FILEDEVICE_PANE  32795
#define ID_IECFGDEVICE_SAVE             32796
#define ID_IECFGDEVICE_OPEN             32797
#define ID_IECFGDEVICE_INSERT           32798
#define ID_TRAYICON_EXITAPP             32799
#define ID_FILE_NEW_AT02D               32800
#define ID_FILE_IMPORT_AT02D            32801
#define ID_FILE_SAVE_AT02D              32802
#define ID_FILE_SAVE_AS_AT02D           32803
#define ID_FILE_OPEN_SCL_AT02D          32804
#define ID_FILE_OPEN_SCL_HIS_AT02D      32805
#define ID_FILE_NEW_DEVICE_AT02D        32806
#define ID_EXPORT_DEVICE_MODEL          32807
#define ID_VIEW_MODEL_USE_HARM          32808
#define ID_VIEW_VERIFY_VOL_CUR          32809
#define ID_VIEW_LINK_GOUT               32810
#define ID_VIEW_AUTO_OPEN_LAST          32811
#define ID_32811                        32811
#define ID_VIEW_CH_PATH                 32812
#define ID_32813                        32813
#define ID_SEND_CONFIG                  32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        327
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           315
#endif
#endif
