#INCLUDEPATH +=$$PWD

SOURCES +=  \
    $$PWD/GuideBook/GbXMLKeys.cpp \
    $$PWD/GuideBook/GuideBookDefine.cpp \
    $$PWD/Characteristic/CharacteristicGlobal.cpp \
    $$PWD/GuideBook/Cmd.cpp \
    $$PWD/GuideBook/CommCmd.cpp \
    $$PWD/GuideBook/Cpu.cpp \
    $$PWD/GuideBook/Cpus.cpp \
    $$PWD/GuideBook/DataObj.cpp \
    $$PWD/GuideBook/DataObjValue.cpp \
    $$PWD/GuideBook/DataSet.cpp \
    $$PWD/GuideBook/Device.cpp \
    $$PWD/GuideBook/DllCall.cpp \
    $$PWD/GuideBook/GbItemBase.cpp \
    $$PWD/GuideBook/GuideBook.cpp \
    $$PWD/GuideBook/ItemContainer.cpp \
    $$PWD/GuideBook/Items.cpp \
    $$PWD/GuideBook/JobGuide.cpp \
    $$PWD/GuideBook/MacroTest.cpp \
    $$PWD/GuideBook/MacroTestPara.cpp \
    $$PWD/GuideBook/MacroTestParaData.cpp \
    $$PWD/GuideBook/MacroTestParaDatas.cpp \
    $$PWD/GuideBook/Msg.cpp \
    $$PWD/GuideBook/PpEngineDataType.cpp \
    $$PWD/GuideBook/report.cpp \
    $$PWD/GuideBook/reports.cpp \
    $$PWD/GuideBook/Safety.cpp \
    $$PWD/GuideBook/scripText.cpp \
    $$PWD/GuideBook/SysParaEdit.cpp \
    $$PWD/GuideBook/TestGlobalDatasMngr.cpp \
    $$PWD/GuideBook/TestTypeMngr.cpp \
    $$PWD/GuideBook/ReportMap/ReportMap.cpp \
    $$PWD/GuideBook/ReportMap/RptArea.cpp \
    $$PWD/GuideBook/ReportMap/RptBkmk.cpp \
    $$PWD/GuideBook/ReportMap/RptData.cpp \
    $$PWD/GuideBook/ReportMap/RptItem.cpp \
    $$PWD/GuideBook/ReportMap/RptMapBase.cpp \
    $$PWD/GuideBook/ReportMap/RptMapRepeat.cpp \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/BkmkDataProcess.cpp \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/BkmkDataProcessMngr.cpp \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/CommCmdStrcutAttr.cpp \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/CommCmdStrcutAttrs.cpp \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/ReportTemplateConfig.cpp \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/ReportTemplateConfigGlobal.cpp \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/SysRptData.cpp \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/SysRptDataMngr.cpp \
    $$PWD/GuideBook/Standard.cpp \
    $$PWD/GuideBook/GbCommCmdConfig/CommCmdConfigXMLKeys.cpp \
    $$PWD/GuideBook/GbCommCmdConfig/GbCommCmd.cpp \
    $$PWD/GuideBook/GbCommCmdConfig/GbCommCmdConfig.cpp \
    $$PWD/GuideBook/GbCommCmdConfig/GbCommCmdGlobalDefine.cpp \
    $$PWD/GuideBook/GbLogCtrls.cpp \
    $$PWD/Characteristic/CharacterArea.cpp \
    $$PWD/Characteristic/CharacterFolder.cpp \
    $$PWD/Characteristic/Characteristic.cpp \
    $$PWD/Characteristic/CharacteristicLib.cpp \
    $$PWD/Characteristic/Characteristics.cpp \
    $$PWD/Characteristic/CharacteristicTmplate.cpp \
    $$PWD/Characteristic/CharElement.cpp \
    $$PWD/Characteristic/CharElementArc.cpp \
    $$PWD/Characteristic/CharElementArcBase.cpp \
    $$PWD/Characteristic/CharElementArcd.cpp \
    $$PWD/Characteristic/CharElementArcp.cpp \
    $$PWD/Characteristic/CharElementI2T.cpp \
    $$PWD/Characteristic/CharElementIAC.cpp \
    $$PWD/Characteristic/CharElementIEC.cpp \
    $$PWD/Characteristic/CharElementIEEE.cpp \
    $$PWD/Characteristic/CharElementInverse.cpp \
    $$PWD/Characteristic/CharElementInvOwnDef.cpp \
    $$PWD/Characteristic/CharElementLens.cpp \
    $$PWD/Characteristic/CharElementLine.cpp \
    $$PWD/Characteristic/CharElementLineBase.cpp \
    $$PWD/Characteristic/CharElementLined.cpp \
    $$PWD/Characteristic/CharElementLinep.cpp \
    $$PWD/Characteristic/CharElementLiner.cpp \
    $$PWD/Characteristic/CharElementMho.cpp \
    $$PWD/Characteristic/CharElementLine.cpp \
    $$PWD/Characteristic/CharElementPoint.cpp \
    $$PWD/Characteristic/CharInterface.cpp \
    $$PWD/Characteristic/CharInterfaceVariable.cpp \
    $$PWD/Characteristic/CharTestLineDefine.cpp \
    $$PWD/TaskMngr/TestGlobalDefine.cpp \
    $$PWD/GuideBook/SysParas.cpp \
    $$PWD/GuideBook/GbParaTypeMngr.cpp \
    $$PWD/GuideBook/ItemsRsltExprScript.cpp \
    $$PWD/GuideBook/MacroCharItems.cpp \
    $$PWD/GuideBook/GuideBookTool.cpp \
    $$PWD/TestControl/TestControlBase.cpp \
    $$PWD/TCtrlCntrConfig.cpp \
    $$PWD/GuideBook/ReportMap/RptFillInterface.cpp \
    $$PWD/TestControl/SmartTestBaseApp.cpp \
    $$PWD/TCtrlCntrWorkSpace.cpp \
    $$PWD/TCtrlMsgRcvInterface.cpp \
    $$PWD/TCtrlCntrDefine.cpp \
    $$PWD/TestControl/TestControlWnd.cpp \
    $$PWD/PpDeviceRefs.cpp \
    $$PWD/SmartTestRpcEventApi.cpp \
    $$PWD/AutoTestXMLRWKeys.cpp \
    $$PWD/GuideBook/Script/GbScript_Engine.cpp \
    $$PWD/GuideBook/Script/GbScript_EngineTest.cpp \
    $$PWD/GuideBook/Script/GbScriptFunctions.cpp \
    $$PWD/GuideBook/Script/GbScriptFunctions_xvm.cpp \
    $$PWD/GuideBook/Script/GbScript_GlobalDefine.cpp \
    $$PWD/GuideBook/Script/GbScript_GuideBook.cpp \
    $$PWD/GuideBook/Script/GbScript_System.cpp \
    $$PWD/GuideBook/Script/SmartTestHostApi.cpp \
    $$PWD/GuideBook/Script/SmartTestXvm.cpp \
    $$PWD/GuideBook/Script/XScriptBase.cpp \
    $$PWD/GuideBook/Script/XScript_XVM.cpp \
    $$PWD/AutoTestGlobalDefine.cpp \
    $$PWD/GuideBook/ReportMap/WordRptFillBase.cpp \
    $$PWD/TCtrlSystemConfig.cpp \
    $$PWD/GuideBook/GbDataTypeMngr.cpp \
    $$PWD/SmartTestRpcApi.cpp \
    $$PWD/TestControl/TestControlWnd_Linux.cpp \
    $$PWD/SmartTestRpcEventApi_Linux.cpp \
    $$PWD/GuideBook/GuideBookExportTool.cpp \
    $$PWD/GuideBookExportConfig.cpp \
    $$PWD/GuideBook/DataSetGroup.cpp \
    $$PWD/GuideBook/TestMacroUiParas.cpp \
    $$PWD/GbItemsGen/GbItemsGen.cpp \
    $$PWD/GbItemsGen/GbItemsGenRuleDefMngrGlobal.cpp \
    $$PWD/GbItemsGen/GenNodeBase.cpp \
    $$PWD/GbItemsGen/ItemsGenBase.cpp \
    $$PWD/GbItemsGen/ItemsGenClass.cpp \
    $$PWD/GbItemsGen/ItemsGenData.cpp \
    $$PWD/GbItemsGen/ItemsGenDataMap.cpp \
    $$PWD/GbItemsGen/ItemsGenDefine.cpp \
    $$PWD/GbItemsGen/ItemsGenEnable.cpp \
    $$PWD/GbItemsGen/ItemsGenInst.cpp \
    $$PWD/GbItemsGen/ItemsGenInterface.cpp \
    $$PWD/GbItemsGen/ItemsGenNameAdd.cpp \
    $$PWD/GbItemsGen/ItemsGenNameItem.cpp \
    $$PWD/GbItemsGen/ItemsGenNode.cpp \
    $$PWD/GbItemsGen/ItemsGenPara.cpp \
    $$PWD/GbItemsGen/ItemsGenParaDef.cpp \
    $$PWD/GbItemsGen/ItemsGenParasMap.cpp \
    $$PWD/GbItemsGen/MacroItemsGen.cpp \
    $$PWD/GbItemsGen/ParasGenNode.cpp \
    $$PWD/GbItemsGen/ItemsGenCharItemLine.cpp \
    $$PWD/GuideBook/GuideBookStruDscTool.cpp \
    $$PWD/Characteristic/CharTestObjects.cpp \
    $$PWD/Characteristic/CharTestPoints.cpp \
    $$PWD/AtsMes/AtsMesTestDefine.cpp \
    $$PWD/SmartTestDefineInterface.cpp \
    $$PWD/GbItemsGen/ItemGenRsltExpr.cpp \
    $$PWD/GuideBook/ItemRsltExprRun.cpp \
    $$PWD/GbItemsGen/SttGuideBookGenServer.cpp \
    $$PWD/GbItemsGen/GbItemsGenTool.cpp \
    $$PWD/GbItemsGen/ItemsGenCommCmd.cpp \
    $$PWD/GbItemsGen/ItemsGenSysParaEdit.cpp \
    $$PWD/GbItemsGen/ItemsGenSafety.cpp \ 
    $$PWD/Characteristic/CharElementDCOverLoad.cpp \
    $$PWD/Characteristic/CharElementIUF.cpp \
    $$PWD/Characteristic/CharElementUIVP.cpp \
    $$PWD/GuideBook/HdResReqest.cpp \
    $$PWD/GuideBook/GbUnqualifiedItemTool.cpp \
    $$PWD/GuideBook/GbtDataInterface.cpp \
    $$PWD/GuideBook/GbtDataInterfaces.cpp \
    $$PWD/GuideBook/GbtDataScript.cpp \
    $$PWD/GuideBook/ReportMap/JsonReport/JsonRptFill.cpp \
    $$PWD/GuideBook/TestMacroCharParas.cpp \
    $$PWD/GuideBook/GbtData.cpp \
    $$PWD/GuideBook/ReportMap/RptBaseFill.cpp \
    $$PWD/GbItemsGen/MacroSelfDefGen.cpp \
    $$PWD/Characteristic/CharElementExpr.cpp \
    $$PWD/Characteristic/CharElementI2TEx.cpp \
    $$PWD/Characteristic/CharElementRICurve.cpp \
    $$PWD/Characteristic/CharElementRXIDG.cpp \
    $$PWD/Characteristic/CharElementIT.cpp \
    $$PWD/Characteristic/CharElementLablecCurve.cpp \
    $$PWD/Characteristic/CharTestLine.cpp


HEADERS += \
    $$PWD/GuideBook/GbXMLKeys.h \
    $$PWD/GuideBook/GuideBookDefine.h \
    $$PWD/Characteristic/CharacteristicGlobal.h \
    $$PWD/GuideBook/Cmd.h \
    $$PWD/GuideBook/CommCmd.h \
    $$PWD/GuideBook/Cpu.h \
    $$PWD/GuideBook/Cpus.h \
    $$PWD/GuideBook/DataObj.h \
    $$PWD/GuideBook/DataObjValue.h \
    $$PWD/GuideBook/DataSet.h \
    $$PWD/GuideBook/Device.h \
    $$PWD/GuideBook/DllCall.h \
    $$PWD/GuideBook/GbItemBase.h \
    $$PWD/GuideBook/GuideBook.h \
    $$PWD/GuideBook/ItemContainer.h \
    $$PWD/GuideBook/Items.h \
    $$PWD/GuideBook/JobGuide.h \
    $$PWD/GuideBook/MacroTest.h \
    $$PWD/GuideBook/MacroTestPara.h \
    $$PWD/GuideBook/MacroTestParaData.h \
    $$PWD/GuideBook/MacroTestParaDatas.h \
    $$PWD/GuideBook/Msg.h \
    $$PWD/GuideBook/PpEngineDataType.h \
    $$PWD/GuideBook/report.h \
    $$PWD/GuideBook/reports.h \
    $$PWD/GuideBook/Safety.h \
    $$PWD/GuideBook/scriptText.h \
    $$PWD/GuideBook/SysParaEdit.h \
    $$PWD/GuideBook/TestGlobalDatasMngr.h \
    $$PWD/GuideBook/TestTypeMngr.h \
    $$PWD/GuideBook/ReportMap/ReportMap.h \
    $$PWD/GuideBook/ReportMap/RptArea.h \
    $$PWD/GuideBook/ReportMap/RptBkmk.h \
    $$PWD/GuideBook/ReportMap/RptData.h \
    $$PWD/GuideBook/ReportMap/RptItem.h \
    $$PWD/GuideBook/ReportMap/RptMapBase.h \
    $$PWD/GuideBook/ReportMap/RptMapRepeat.h \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/BkmkDataProcess.h \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/BkmkDataProcessMngr.h \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/CommCmdStrcutAttr.h \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/CommCmdStrcutAttrs.h \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/ReportTemplateConfig.h \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/ReportTemplateConfigGlobal.h \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/SysRptData.h \
    $$PWD/GuideBook/ReportMap/ReportTemplateConfig/SysRptDataMngr.h \
    $$PWD/GuideBook/Standard.h \
    $$PWD/GuideBook/GbCommCmdConfig/CommCmdConfigXMLKeys.h \
    $$PWD/GuideBook/GbCommCmdConfig/GbCommCmd.h \
    $$PWD/GuideBook/GbCommCmdConfig/GbCommCmdConfig.h \
    $$PWD/GuideBook/GbCommCmdConfig/GbCommCmdGlobalDefine.h \
    $$PWD/GuideBook/GbLogCtrls.h \
    $$PWD/Characteristic/CharacterArea.h \
    $$PWD/Characteristic/CharacterFolder.h \
    $$PWD/Characteristic/Characteristic.h \
    $$PWD/Characteristic/CharacteristicLib.h \
    $$PWD/Characteristic/Characteristics.h \
    $$PWD/Characteristic/CharacteristicTmplate.h \
    $$PWD/Characteristic/CharElement.h \
    $$PWD/Characteristic/CharElementArc.h \
    $$PWD/Characteristic/CharElementArcBase.h \
    $$PWD/Characteristic/CharElementArcd.h \
    $$PWD/Characteristic/CharElementArcp.h \
    $$PWD/Characteristic/CharElementI2T.h \
    $$PWD/Characteristic/CharElementIAC.h \
    $$PWD/Characteristic/CharElementIEC.h \
    $$PWD/Characteristic/CharElementIEEE.h \
    $$PWD/Characteristic/CharElementInverse.h \
    $$PWD/Characteristic/CharElementInvOwnDef.h \
    $$PWD/Characteristic/CharElementLens.h \
    $$PWD/Characteristic/CharElementLine.h \
    $$PWD/Characteristic/CharElementLineBase.h \
    $$PWD/Characteristic/CharElementLined.h \
    $$PWD/Characteristic/CharElementLinep.h \
    $$PWD/Characteristic/CharElementLiner.h \
    $$PWD/Characteristic/CharElementMho.h \
    $$PWD/Characteristic/CharElementLine.h \
    $$PWD/Characteristic/CharElementPoint.h \
    $$PWD/Characteristic/CharInterface.h \
    $$PWD/Characteristic/CharInterfaceVariable.h \
    $$PWD/Characteristic/CharTestLineDefine.h \
    $$PWD/TaskMngr/ReportSNGen.h \
    $$PWD/TaskMngr/TestGlobalDefine.h \
    $$PWD/TaskMngr/TestLibraryTasks.h \
    $$PWD/TaskMngr/TestProject.h \
    $$PWD/TaskMngr/TestTask.h \
    $$PWD/TaskMngr/TestTasksMngr.h \
    $$PWD/TaskMngr/TestTasksMngrDB.h \
    $$PWD/GuideBook/SysParas.h \
    $$PWD/GuideBook/GbParaTypeMngr.h \
    $$PWD/GuideBook/ItemsRsltExprScript.h \
    $$PWD/GuideBook/MacroCharItems.h \
    $$PWD/GuideBook/GuideBookTool.h \
    $$PWD/TestControl/TestControlBase.h \
    $$PWD/TCtrlCntrConfig.h \
    $$PWD/GuideBook/ReportMap/RptFillInterface.h \
    $$PWD/TestControl/SmartTestBaseApp.h \
    $$PWD/TCtrlCntrWorkSpace.h \
    $$PWD/TCtrlMsgRcvInterface.h \
    $$PWD/TCtrlCntrDefine.h \
    $$PWD/TestControl/TestControlWnd.h \
    $$PWD/PpDeviceRefs.h \
    $$PWD/SmartTestRpcEventApi.h \
    $$PWD/AutoTestXMLRWKeys.h \
    $$PWD/GuideBook/Script/GbScript_Engine.h \
    $$PWD/GuideBook/Script/GbScriptFunctions.h \
    $$PWD/GuideBook/Script/GbScriptFunctions_xvm.h \
    $$PWD/GuideBook/Script/GbScript_GlobalDefine.h \
    $$PWD/GuideBook/Script/GbScript_GuideBook.h \
    $$PWD/GuideBook/Script/GbScript_System.h \
    $$PWD/GuideBook/Script/SmartTestHostApi.h \
    $$PWD/GuideBook/Script/SmartTestXvm.h \
    $$PWD/GuideBook/Script/XScriptBase.h \
    $$PWD/GuideBook/Script/XScript_XVM.h \
    $$PWD/AutoTestGlobalDefine.h \
    $$PWD/GuideBook/ReportMap/WordRptFillBase.h \
    $$PWD/TCtrlSystemConfig.h \
    $$PWD/GuideBook/GbDataTypeMngr.h \
    $$PWD/SmartTestRpcApi.h \
    $$PWD/TestControl/TestControlWnd_Linux.h \
    $$PWD/GuideBook/GuideBookExportTool.h \
    $$PWD/GuideBookExportConfig.h \
    $$PWD/GuideBook/DataSetGroup.h \
    $$PWD/GuideBook/TestMacroUiParas.h \
    $$PWD/GbItemsGen/GbItemsGen.h \
    $$PWD/GbItemsGen/GbItemsGenRuleDefMngrGlobal.h \
    $$PWD/GbItemsGen/GenNodeBase.h \
    $$PWD/GbItemsGen/ItemsGenBase.h \
    $$PWD/GbItemsGen/ItemsGenClass.h \
    $$PWD/GbItemsGen/ItemsGenData.h \
    $$PWD/GbItemsGen/ItemsGenDataMap.h \
    $$PWD/GbItemsGen/ItemsGenDefine.h \
    $$PWD/GbItemsGen/ItemsGenEnable.h \
    $$PWD/GbItemsGen/ItemsGenInst.h \
    $$PWD/GbItemsGen/ItemsGenInterface.h \
    $$PWD/GbItemsGen/ItemsGenNameAdd.h \
    $$PWD/GbItemsGen/ItemsGenNameItem.h \
    $$PWD/GbItemsGen/ItemsGenNode.h \
    $$PWD/GbItemsGen/ItemsGenPara.h \
    $$PWD/GbItemsGen/ItemsGenParaDef.h \
    $$PWD/GbItemsGen/ItemsGenParasMap.h \
    $$PWD/GbItemsGen/MacroItemsGen.h \
    $$PWD/GbItemsGen/ParasGenNode.h \
    $$PWD/GbItemsGen/ItemsGenCharItemLine.h \
    $$PWD/GuideBook/GuideBookStruDscTool.h \
    $$PWD/Characteristic/CharTestPoints.h \
    $$PWD/Characteristic/CharTestObjects.h \
    $$PWD/AtsMes/AtsMesTestDefine.h \
    $$PWD/SmartTestDefineInterface.h \
    $$PWD/GbItemsGen/ItemGenRsltExpr.h \
    $$PWD/GuideBook/ItemRsltExprRun.h \
    $$PWD/GbItemsGen/SttGuideBookGenServer.h \
    $$PWD/GbItemsGen/GbItemsGenTool.h \
    $$PWD/GbItemsGen/ItemsGenCommCmd.h \
    $$PWD/GbItemsGen/ItemsGenSysParaEdit.h \
    $$PWD/GbItemsGen/ItemsGenSafety.h \ 
    $$PWD/Characteristic/CharElementDCOverLoad.h \
    $$PWD/Characteristic/CharElementIUF.h \
    $$PWD/Characteristic/CharElementUIVP.h \
    $$PWD/GuideBook/HdResReqest.h \
    $$PWD/GuideBook/GbUnqualifiedItemTool.h \
    $$PWD/GuideBook/GbtDataInterface.h \
    $$PWD/GuideBook/GbtDataInterfaces.h \
    $$PWD/GuideBook/GbtDataScript.h \
    $$PWD/GuideBook/ReportMap/JsonReport/JsonRptFill.h \
    $$PWD/GuideBook/TestMacroCharParas.h \
    $$PWD/GuideBook/GbtData.h \
    $$PWD/GuideBook/ReportMap/RptBaseFill.h \
    $$PWD/GbItemsGen/MacroSelfDefGen.h \
    $$PWD/Characteristic/CharElementExpr.h \
    $$PWD/Characteristic/CharElementI2TEx.h \
    $$PWD/Characteristic/CharElementRICurve.h \
    $$PWD/Characteristic/CharElementRXIDG.h \
    $$PWD/Characteristic/CharElementIT.h \
    $$PWD/Characteristic/CharElementLabIecCurve.h \
    $$PWD/Characteristic/CharTestLine.h
