
SOURCES +=  \
$$PWD/AutoTestGlobalDefine.cpp \
$$PWD/Characteristic/CharacterArea.cpp \
$$PWD/Characteristic/CharacterDrawView.cpp \
$$PWD/Characteristic/CharacterFolder.cpp \
$$PWD/Characteristic/Characteristic.cpp \
$$PWD/Characteristic/CharacteristicGlobal.cpp \
$$PWD/Characteristic/CharacteristicLib.cpp \
$$PWD/Characteristic/Characteristics.cpp \
$$PWD/Characteristic/CharacteristicTmplate.cpp \
$$PWD/Characteristic/CharElement.cpp \
$$PWD/Characteristic/CharElementArc.cpp \
$$PWD/Characteristic/CharElementArcBase.cpp \
$$PWD/Characteristic/CharElementArcd.cpp \
$$PWD/Characteristic/CharElementArcp.cpp \
$$PWD/Characteristic/CharElementDCOverLoad.cpp \
$$PWD/Characteristic/CharElementI2T.cpp \
$$PWD/Characteristic/CharElementIAC.cpp \
$$PWD/Characteristic/CharElementIEC.cpp \
$$PWD/Characteristic/CharElementIEEE.cpp \
$$PWD/Characteristic/CharElementInverse.cpp \
$$PWD/Characteristic/CharElementInvOwnDef.cpp \
$$PWD/Characteristic/CharElementIUF.cpp \
$$PWD/Characteristic/CharElementLens.cpp \
$$PWD/Characteristic/CharElementLine.cpp \
$$PWD/Characteristic/CharElementLineBase.cpp \
$$PWD/Characteristic/CharElementLined.cpp \
$$PWD/Characteristic/CharElementLinep.cpp \
$$PWD/Characteristic/CharElementLiner.cpp \
$$PWD/Characteristic/CharElementMho.cpp \
$$PWD/Characteristic/CharTestLine.cpp \
$$PWD/Characteristic/CharTestObjects.cpp \
$$PWD/Characteristic/CharElementPoint.cpp \
$$PWD/Characteristic/CharElementUIVP.cpp \
$$PWD/Characteristic/CharInterface.cpp \
$$PWD/Characteristic/CharInterfaceVariable.cpp \
$$PWD/Characteristic/CharMacroDraw.cpp \
$$PWD/Characteristic/CharMacroDrawLine.cpp \
$$PWD/Characteristic/CharMacroDrawPoint.cpp \
$$PWD/Characteristic/CharMacroDraws.cpp \
$$PWD/Characteristic/CharTestLineDefine.cpp \
$$PWD/Characteristic/QT/SttCharacterDrawPng.cpp \
$$PWD/Characteristic/SttCharacterDrawForTest.cpp \
$$PWD/Characteristic/CharTestPoints.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/DvmContents.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbMacroGenWzd.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbSmartGenWzd.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbSmartGenWzdGlobal.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiBase.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiDO.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiKeysFunc.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiMacroPara.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiOptr.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiParasBase.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiScript.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiSwitch.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiTool.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdCommCmdAdd.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemCopy.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemEdit.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemMove.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemPaste.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemRsltExprEdit.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemsAdd.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemSetState.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemsNameLib.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdMacroTestAdd.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdSafetyAdd.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdXItemBase.cpp \
$$PWD/GbItemsGen/GbSmartGenWzd/SttCmdWzd_CmdDataset.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Cell.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Col.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_ColDef.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_ColsDef.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Data.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Enable.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Grid.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_GridDef.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Group.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_GuideBook.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Head.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Items.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_MacroCharItems.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_MacroTest.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Png.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_PngDef.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Reports.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_ReportsDef.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_ReportTemplate.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_ReportTemplateDef.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Row.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_RowDef.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_RowsDef.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Rpeort.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_RpeortDef.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_TestMacroUiRpt.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_TestMacroUiRptDef.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Text.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_TextDef.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Title.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_TitleDef.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_Value.cpp \
$$PWD/TestMacroRptTemplate/RptTemp_ValueDef.cpp \
$$PWD/TestMacroRptTemplate/TestMacroRptTemplateGlobal.cpp \
$$PWD/XrioRead/Xrio.cpp \
$$PWD/XrioRead/XrioCfgMngrGlobal.cpp \
$$PWD/XrioRead/XrioCustom.cpp \
$$PWD/XrioRead/XrioCustomBlock.cpp \
$$PWD/XrioRead/XrioCustomParameter.cpp \
$$PWD/XrioRead/XrioListCfg.cpp \
$$PWD/XrioRead/XrioObjectCfg.cpp \
$$PWD/XrioRead/XrioTextFile.cpp \
$$PWD/XrioRead/XrioRio.cpp \
$$PWD/XrioRead/RioDevice.cpp \
$$PWD/XrioRead/RioNameplate.cpp \
$$PWD/XrioRead/RioLocation.cpp \
$$PWD/XrioRead/RioNominalValues.cpp \
$$PWD/XrioRead/RioResidualFactors.cpp \
$$PWD/XrioRead/RioLimits.cpp \
$$PWD/XrioRead/RioMisc.cpp \
$$PWD/XrioRead/RioDeviceMode.cpp \
$$PWD/XrioRead/RioManufacturer.cpp \
$$PWD/XrioRead/RioDeviceType.cpp \
$$PWD/XrioRead/RioSerialnr.cpp \
$$PWD/XrioRead/RioAdditionalINF02.cpp \
$$PWD/XrioRead/RioDeviceAddress.cpp \
$$PWD/XrioRead/RioSubstation.cpp \
$$PWD/XrioRead/RioSubstatioAddress.cpp \
$$PWD/XrioRead/RioBay.cpp \
$$PWD/XrioRead/RioBayAddress.cpp \
$$PWD/XrioRead/RioProtectedObjectName.cpp \
$$PWD/XrioRead/RioPhases.cpp \
$$PWD/XrioRead/RioFNom.cpp \
$$PWD/XrioRead/RioVNom.cpp \
$$PWD/XrioRead/RioVPrimLL.cpp \
$$PWD/XrioRead/RioINom.cpp \
$$PWD/XrioRead/RioIPrim.cpp \
$$PWD/XrioRead/RioVLNVN.cpp \
$$PWD/XrioRead/RioININOM.cpp \
$$PWD/XrioRead/RioVMaxLL.cpp \
$$PWD/XrioRead/RioIMax.cpp \
$$PWD/XrioRead/RioDeBounceTime.cpp \
$$PWD/XrioRead/RioDeGlitchTime.cpp \
$$PWD/XrioRead/RioOverloadSupTime.cpp \
$$PWD/XrioRead/RioCBConfig.cpp \
$$PWD/XrioRead/RioTripTime.cpp \
$$PWD/XrioRead/RioCloseTime.cpp \
$$PWD/XrioRead/RioP52AB.cpp \
$$PWD/XrioRead/XrioToDeviceModelTool.cpp \
$$PWD/XrioRead/XDeviceModel/XDeviceModel.cpp \
$$PWD/XLanguageResourceAts.cpp \
    $$PWD/Characteristic/CharElementRXIDG.cpp \
    $$PWD/Characteristic/CharElementIT.cpp \
    $$PWD/Characteristic/CharElementLablecCurve.cpp \
    $$PWD/Characteristic/CharElementI2TEx.cpp \
    $$PWD/Characteristic/CharElementRICurve.cpp \
    $$PWD/XrioRead/RioActive.cpp \
    $$PWD/XrioRead/RioAngle.cpp \
    $$PWD/XrioRead/RioArc.cpp \
    $$PWD/XrioRead/RioAutoClose.cpp \
    $$PWD/XrioRead/RioCurvePoint.cpp \
    $$PWD/XrioRead/RioCurvePoints.cpp \
    $$PWD/XrioRead/RioCustomCurve.cpp \
    $$PWD/XrioRead/RioDiffBias.cpp \
    $$PWD/XrioRead/RioDiffPoint.cpp \
    $$PWD/XrioRead/RioDir.cpp \
    $$PWD/XrioRead/RioDistanceProtectionDevice.cpp \
    $$PWD/XrioRead/RioEndAngle.cpp \
    $$PWD/XrioRead/RioGenricShape.cpp \
    $$PWD/XrioRead/RioI2TParameterCurve.cpp \
    $$PWD/XrioRead/RioIACParameterCurve.cpp \
    $$PWD/XrioRead/RioInside.cpp \
    $$PWD/XrioRead/RioInverseParameterCurve.cpp \
    $$PWD/XrioRead/RioInverseParameterCurveName.cpp \
    $$PWD/XrioRead/RioLine.cpp \
    $$PWD/XrioRead/RioMhoOffset.cpp \
    $$PWD/XrioRead/RioMhoReach.cpp \
    $$PWD/XrioRead/RioMhoShape.cpp \
    $$PWD/XrioRead/RioOperatingCurves.cpp \
    $$PWD/XrioRead/RioOverCurrentChar.cpp \
    $$PWD/XrioRead/RioOverCurrentCharA.cpp \
    $$PWD/XrioRead/RioOverCurrentCharB.cpp \
    $$PWD/XrioRead/RioOverCurrentCharI2T.cpp \
    $$PWD/XrioRead/RioOverCurrentCharK1.cpp \
    $$PWD/XrioRead/RioOverCurrentCharK2.cpp \
    $$PWD/XrioRead/RioOverCurrentCharP.cpp \
    $$PWD/XrioRead/RioOverCurrentCharQ.cpp \
    $$PWD/XrioRead/RioOverCurrentElements.cpp \
    $$PWD/XrioRead/RioOverCurrentGroup.cpp \
    $$PWD/XrioRead/RioOverCurrentTable.cpp \
    $$PWD/XrioRead/RioOverCurrentUnit.cpp \
    $$PWD/XrioRead/RioParameterA.cpp \
    $$PWD/XrioRead/RioParameterB.cpp \
    $$PWD/XrioRead/RioParameterC.cpp \
    $$PWD/XrioRead/RioParameterD.cpp \
    $$PWD/XrioRead/RioParameterE.cpp \
    $$PWD/XrioRead/RioPointX.cpp \
    $$PWD/XrioRead/RioPointY.cpp \
    $$PWD/XrioRead/RioRadius.cpp \
    $$PWD/XrioRead/RioRefPointAngle.cpp \
    $$PWD/XrioRead/RioRefPointMag.cpp \
    $$PWD/XrioRead/RioRefPointR.cpp \
    $$PWD/XrioRead/RioRefPointX.cpp \
    $$PWD/XrioRead/RioDifferential.cpp \
    $$PWD/XrioRead/RioDistance.cpp \
    $$PWD/XrioRead/RioOverCurrent.cpp \
    $$PWD/XrioRead/RioStandardCurve.cpp \
    $$PWD/XrioRead/RioStandardCurveName.cpp \
    $$PWD/XrioRead/RioStartAngle.cpp \
    $$PWD/XrioRead/RioTimedOverCurrentElement.cpp \
    $$PWD/XrioRead/RioTimeMultiplier.cpp \
    $$PWD/XrioRead/RioTimeMultiplierNomval.cpp \
    $$PWD/XrioRead/RioTripChar.cpp \
    $$PWD/XrioRead/XrioRioConverter.cpp \
    $$PWD/XrioRead/XrioScript.cpp \
    $$PWD/XrioRead/XrioToCharacterTool.cpp \
    $$PWD/XrioRead/RioZone.cpp \
    $$PWD/XrioRead/RioZones.cpp \
    $$PWD/Characteristic/CharElementExpr.cpp \
    $$PWD/XrioRead/RioFaultLoop.cpp \
    $$PWD/XrioRead/RioIndex.cpp \
    $$PWD/XrioRead/RioTolerances.cpp \
    $$PWD/XrioRead/RioTTMIValid.cpp \
    $$PWD/XrioRead/RioTTOLMinus.cpp \
    $$PWD/XrioRead/RioTTOLPlus.cpp \
    $$PWD/XrioRead/RioTTOLRel.cpp \
    $$PWD/XrioRead/RioTTPLValid.cpp \
    $$PWD/XrioRead/RioTTRLValid.cpp \
    $$PWD/XrioRead/RioZTABValid.cpp \
    $$PWD/XrioRead/RioZTOLAbs.cpp \
    $$PWD/XrioRead/RioZTOLRel.cpp \
    $$PWD/XrioRead/RioZTRLValid.cpp \
    $$PWD/XrioRead/RioParameterF.cpp \
    $$PWD/XrioRead/RioTIndex.cpp \
    $$PWD/XrioRead/XrioTextFileToAtsCharTool.cpp \
    $$PWD/XrioRead/SettingFilesToXrioTool.cpp


HEADERS += \
$$PWD/AutoTestGlobalDefine.h \
$$PWD/Characteristic/CharacterArea.h \
$$PWD/Characteristic/CharacterDrawView.h \
$$PWD/Characteristic/CharacterFolder.h \
$$PWD/Characteristic/Characteristic.h \
$$PWD/Characteristic/CharacteristicGlobal.h \
$$PWD/Characteristic/CharacteristicLib.h \
$$PWD/Characteristic/Characteristics.h \
$$PWD/Characteristic/CharacteristicTmplate.h \
$$PWD/Characteristic/CharElement.h \
$$PWD/Characteristic/CharElementArc.h \
$$PWD/Characteristic/CharElementArcBase.h \
$$PWD/Characteristic/CharElementArcd.h \
$$PWD/Characteristic/CharElementArcp.h \
$$PWD/Characteristic/CharElementDCOverLoad.h \
$$PWD/Characteristic/CharElementI2T.h \
$$PWD/Characteristic/CharElementIAC.h \
$$PWD/Characteristic/CharElementIEC.h \
$$PWD/Characteristic/CharElementIEEE.h \
$$PWD/Characteristic/CharElementInverse.h \
$$PWD/Characteristic/CharElementInvOwnDef.h \
$$PWD/Characteristic/CharElementIUF.h \
$$PWD/Characteristic/CharElementLens.h \
$$PWD/Characteristic/CharElementLine.h \
$$PWD/Characteristic/CharElementLineBase.h \
$$PWD/Characteristic/CharElementLined.h \
$$PWD/Characteristic/CharElementLinep.h \
$$PWD/Characteristic/CharElementLiner.h \
$$PWD/Characteristic/CharElementMho.h \
$$PWD/Characteristic/CharTestLine.h \
$$PWD/Characteristic/CharTestObjects.h \
$$PWD/Characteristic/CharElementPoint.h \
$$PWD/Characteristic/CharElementUIVP.h \
$$PWD/Characteristic/CharInterface.h \
$$PWD/Characteristic/CharInterfaceVariable.h \
$$PWD/Characteristic/CharMacroDraw.h \
$$PWD/Characteristic/CharMacroDrawLine.h \
$$PWD/Characteristic/CharMacroDrawPoint.h \
$$PWD/Characteristic/CharMacroDraws.h \
$$PWD/Characteristic/CharTestLineDefine.h \
$$PWD/Characteristic/QT/SttCharacterDrawPng.h \
$$PWD/Characteristic/SttCharacterDrawForTest.h \
$$PWD/Characteristic/CharTestPoints.h \
$$PWD/GbItemsGen/GbSmartGenWzd/DvmContents.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbMacroGenWzd.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbSmartGenWzd.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbSmartGenWzdGlobal.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiBase.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiDO.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiKeysFunc.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiMacroPara.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiOptr.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiParasBase.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiScript.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiSwitch.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdAi/GbWzdAiTool.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdCommCmdAdd.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemCopy.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemEdit.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemMove.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemPaste.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemRsltExprEdit.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemsAdd.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemSetState.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdItemsNameLib.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdMacroTestAdd.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdSafetyAdd.h \
$$PWD/GbItemsGen/GbSmartGenWzd/GbWzdXItemBase.h \
$$PWD/GbItemsGen/GbSmartGenWzd/SttCmdWzd_CmdDataset.h \
$$PWD/GuideBook/GuideBookDefine.h \
$$PWD/TestMacroRptTemplate/RptTemp_Cell.h \
$$PWD/TestMacroRptTemplate/RptTemp_Col.h \
$$PWD/TestMacroRptTemplate/RptTemp_ColDef.h \
$$PWD/TestMacroRptTemplate/RptTemp_ColsDef.h \
$$PWD/TestMacroRptTemplate/RptTemp_Data.h \
$$PWD/TestMacroRptTemplate/RptTemp_Enable.h \
$$PWD/TestMacroRptTemplate/RptTemp_Grid.h \
$$PWD/TestMacroRptTemplate/RptTemp_GridDef.h \
$$PWD/TestMacroRptTemplate/RptTemp_Group.h \
$$PWD/TestMacroRptTemplate/RptTemp_GuideBook.h \
$$PWD/TestMacroRptTemplate/RptTemp_Head.h \
$$PWD/TestMacroRptTemplate/RptTemp_Items.h \
$$PWD/TestMacroRptTemplate/RptTemp_MacroCharItems.h \
$$PWD/TestMacroRptTemplate/RptTemp_MacroTest.h \
$$PWD/TestMacroRptTemplate/RptTemp_Png.h \
$$PWD/TestMacroRptTemplate/RptTemp_PngDef.h \
$$PWD/TestMacroRptTemplate/RptTemp_Reports.h \
$$PWD/TestMacroRptTemplate/RptTemp_ReportsDef.h \
$$PWD/TestMacroRptTemplate/RptTemp_ReportTemplate.h \
$$PWD/TestMacroRptTemplate/RptTemp_ReportTemplateDef.h \
$$PWD/TestMacroRptTemplate/RptTemp_Row.h \
$$PWD/TestMacroRptTemplate/RptTemp_RowDef.h \
$$PWD/TestMacroRptTemplate/RptTemp_RowsDef.h \
$$PWD/TestMacroRptTemplate/RptTemp_Rpeort.h \
$$PWD/TestMacroRptTemplate/RptTemp_RpeortDef.h \
$$PWD/TestMacroRptTemplate/RptTemp_TestMacroUiRpt.h \
$$PWD/TestMacroRptTemplate/RptTemp_TestMacroUiRptDef.h \
$$PWD/TestMacroRptTemplate/RptTemp_Text.h \
$$PWD/TestMacroRptTemplate/RptTemp_TextDef.h \
$$PWD/TestMacroRptTemplate/RptTemp_Title.h \
$$PWD/TestMacroRptTemplate/RptTemp_TitleDef.h \
$$PWD/TestMacroRptTemplate/RptTemp_Value.h \
$$PWD/TestMacroRptTemplate/RptTemp_ValueDef.h \
$$PWD/TestMacroRptTemplate/TestMacroRptTemplateGlobal.h \
$$PWD/XrioRead/Xrio.h \
$$PWD/XrioRead/XrioCfgMngrGlobal.h \
$$PWD/XrioRead/XrioCustom.h \
$$PWD/XrioRead/XrioCustomBlock.h \
$$PWD/XrioRead/XrioCustomParameter.h \
$$PWD/XrioRead/XrioListCfg.h \
$$PWD/XrioRead/XrioObjectCfg.h \
$$PWD/XrioRead/XrioTextFile.h \
$$PWD/XrioRead/XrioRio.h \
$$PWD/XrioRead/RioDevice.h \
$$PWD/XrioRead/RioNameplate.h \
$$PWD/XrioRead/RioLocation.h \
$$PWD/XrioRead/RioNominalValues.h \
$$PWD/XrioRead/RioResidualFactors.h \
$$PWD/XrioRead/RioLimits.h \
$$PWD/XrioRead/RioMisc.h \
$$PWD/XrioRead/RioDeviceMode.h \
$$PWD/XrioRead/RioManufacturer.h \
$$PWD/XrioRead/RioDeviceType.h \
$$PWD/XrioRead/RioSerialnr.h \
$$PWD/XrioRead/RioAdditionalINF02.h \
$$PWD/XrioRead/RioDeviceAddress.h \
$$PWD/XrioRead/RioSubstation.h \
$$PWD/XrioRead/RioSubstatioAddress.h \
$$PWD/XrioRead/RioBay.h \
$$PWD/XrioRead/RioBayAddress.h \
$$PWD/XrioRead/RioProtectedObjectName.h \
$$PWD/XrioRead/RioPhases.h \
$$PWD/XrioRead/RioFNom.h \
$$PWD/XrioRead/RioVNom.h \
$$PWD/XrioRead/RioVPrimLL.h \
$$PWD/XrioRead/RioINom.h \
$$PWD/XrioRead/RioIPrim.h \
$$PWD/XrioRead/RioVLNVN.h \
$$PWD/XrioRead/RioININOM.h \
$$PWD/XrioRead/RioVMaxLL.h \
$$PWD/XrioRead/RioIMax.h \
$$PWD/XrioRead/RioDeBounceTime.h \
$$PWD/XrioRead/RioDeGlitchTime.h \
$$PWD/XrioRead/RioOverloadSupTime.h \
$$PWD/XrioRead/RioCBConfig.h \
$$PWD/XrioRead/RioTripTime.h \
$$PWD/XrioRead/RioCloseTime.h \
$$PWD/XrioRead/RioP52AB.h \
$$PWD/XrioRead/XrioToDeviceModelTool.h \
$$PWD/XrioRead/XDeviceModel/XDeviceModel.h \
$$PWD/XLanguageResourceAts.h \ 
    $$PWD/Characteristic/CharElementIT.h \
    $$PWD/Characteristic/CharElementLabIecCurve.h \
    $$PWD/Characteristic/CharElementI2TEx.h \
    $$PWD/Characteristic/CharElementRICurve.h \
    $$PWD/Characteristic/CharElementRXIDG.h \
    $$PWD/XrioRead/RioActive.h \
    $$PWD/XrioRead/RioAngle.h \
    $$PWD/XrioRead/RioArc.h \
    $$PWD/XrioRead/RioAutoClose.h \
    $$PWD/XrioRead/RioCurvePoint.h \
    $$PWD/XrioRead/RioCurvePoints.h \
    $$PWD/XrioRead/RioCustomCurve.h \
    $$PWD/XrioRead/RioDiffBias.h \
    $$PWD/XrioRead/RioDiffPoint.h \
    $$PWD/XrioRead/RioDir.h \
    $$PWD/XrioRead/RioDistanceProtectionDevice.h \
    $$PWD/XrioRead/RioEndAngle.h \
    $$PWD/XrioRead/RioGenricShape.h \
    $$PWD/XrioRead/RioI2TParameterCurve.h \
    $$PWD/XrioRead/RioIACParameterCurve.h \
    $$PWD/XrioRead/RioInside.h \
    $$PWD/XrioRead/RioInverseParameterCurve.h \
    $$PWD/XrioRead/RioInverseParameterCurveName.h \
    $$PWD/XrioRead/RioLine.h \
    $$PWD/XrioRead/RioMhoOffset.h \
    $$PWD/XrioRead/RioMhoReach.h \
    $$PWD/XrioRead/RioMhoShape.h \
    $$PWD/XrioRead/RioOperatingCurves.h \
    $$PWD/XrioRead/RioOverCurrentChar.h \
    $$PWD/XrioRead/RioOverCurrentCharA.h \
    $$PWD/XrioRead/RioOverCurrentCharB.h \
    $$PWD/XrioRead/RioOverCurrentCharI2T.h \
    $$PWD/XrioRead/RioOverCurrentCharK1.h \
    $$PWD/XrioRead/RioOverCurrentCharK2.h \
    $$PWD/XrioRead/RioOverCurrentCharP.h \
    $$PWD/XrioRead/RioOverCurrentCharQ.h \
    $$PWD/XrioRead/RioOverCurrentElements.h \
    $$PWD/XrioRead/RioOverCurrentGroup.h \
    $$PWD/XrioRead/RioOverCurrentTable.h \
    $$PWD/XrioRead/RioOverCurrentUnit.h \
    $$PWD/XrioRead/RioParameterA.h \
    $$PWD/XrioRead/RioParameterB.h \
    $$PWD/XrioRead/RioParameterC.h \
    $$PWD/XrioRead/RioParameterD.h \
    $$PWD/XrioRead/RioParameterE.h \
    $$PWD/XrioRead/RioPointX.h \
    $$PWD/XrioRead/RioPointY.h \
    $$PWD/XrioRead/RioRadius.h \
    $$PWD/XrioRead/RioRefPointAngle.h \
    $$PWD/XrioRead/RioRefPointMag.h \
    $$PWD/XrioRead/RioRefPointR.h \
    $$PWD/XrioRead/RioRefPointX.h \
    $$PWD/XrioRead/RioDifferential.h \
    $$PWD/XrioRead/RioDistance.h \
    $$PWD/XrioRead/RioOverCurrent.h \
    $$PWD/XrioRead/RioStandardCurve.h \
    $$PWD/XrioRead/RioStandardCurveName.h \
    $$PWD/XrioRead/RioStartAngle.h \
    $$PWD/XrioRead/RioTimedOverCurrentElement.h \
    $$PWD/XrioRead/RioTimeMultiplier.h \
    $$PWD/XrioRead/RioTimeMultiplierNomval.h \
    $$PWD/XrioRead/RioTripChar.h \
    $$PWD/XrioRead/XrioRioConverter.h \
    $$PWD/XrioRead/XrioScript.h \
    $$PWD/XrioRead/XrioToCharacterTool.h \
    $$PWD/XrioRead/RioZone.h \
    $$PWD/XrioRead/RioZones.h \
    $$PWD/Characteristic/CharElementExpr.h \
    $$PWD/XrioRead/RioFaultLoop.h \
    $$PWD/XrioRead/RioIndex.h \
    $$PWD/XrioRead/RioTolerances.h \
    $$PWD/XrioRead/RioTTMIValid.h \
    $$PWD/XrioRead/RioTTOLMinus.h \
    $$PWD/XrioRead/RioTTOLPlus.h \
    $$PWD/XrioRead/RioTTOLRel.h \
    $$PWD/XrioRead/RioTTPLValid.h \
    $$PWD/XrioRead/RioTTRLValid.h \
    $$PWD/XrioRead/RioZTABValid.h \
    $$PWD/XrioRead/RioZTOLAbs.h \
    $$PWD/XrioRead/RioZTOLRel.h \
    $$PWD/XrioRead/RioZTRLValid.h \
    $$PWD/XrioRead/RioParameterF.h \
    $$PWD/XrioRead/RioTIndex.h \
    $$PWD/XrioRead/XrioTextFileToAtsCharTool.h \
    $$PWD/XrioRead/SettingFilesToXrioTool.h


FORMS    += \


