// EpGlobalClassIDBaseDefine.h
//////////////////////////////////////////////////////////////////////

#if !defined(_EPGLOBALCLASSIDBASEDEFINE_H__)
#define _EPGLOBALCLASSIDBASEDEFINE_H__

//基础
#define EPCLASSID_BASECLASS         (CLASSID_BASECLASS     + 0X08000000)
#define EPCLASSID_EXLISTCLASS       (CLASSID_EXLISTCLASS   + 0X08000000)

//设备
#define EPDCLASSID_BASECLASS        (EPCLASSID_BASECLASS   + 0X00010000)
#define EPDCLASSID_EXLISTCLASS      (EPCLASSID_EXLISTCLASS + 0X00010000)

//规约
#define EPPCLASSID_BASECLASS        (EPCLASSID_BASECLASS   + 0X00020000)
#define EPPCLASSID_EXLISTCLASS      (EPCLASSID_EXLISTCLASS + 0X00020000)

//通讯
#define EPCMMCLASSID_BASECLASS      (CLASSID_BASECLASS     + 0X00040000)
#define EPCMMCLASSID_EXLISTCLASS    (CLASSID_EXLISTCLASS   + 0X00040000)

#endif // !defined(_EPGLOBALCLASSIDBASEDEFINE_H__)
