#pragma once

#include "..\GuideBook\GuideBook.h"
#include "..\GuideBook\Items.h"
#include "..\GuideBook\GbItemVariableIDReplace.h"
#include "..\..\..\Module\KeyDb\XMatchToolBase.h"
#include "..\GuideBook\ReportMap\WordRptEdit.h"

#include "..\..\..\Module\MfcCtrlEx\ThreadProgrssDlg.h"

#include "GuideBookWizardDefine.h"

#define GBTWZDCLASSID_BASE                       (CLASSID_EXLISTCLASS + 0X07FF0000)
#define GBTWZDCLASSID_BATCHITEMREF               (GBTWZDCLASSID_BASE + 0X00000001)
#define GBTWZDCLASSID_BATCHITEMGROUP             (GBTWZDCLASSID_BASE + 0X00000002)
#define GBTWZDCLASSID_BATCHITEMGROUPS            (GBTWZDCLASSID_BASE + 0X00000003)
#define GBTWZDCLASSID_GBTDATASCRIPTMAP           (GBTWZDCLASSID_BASE + 0X00000004)
#define GBTWZDCLASSID_GBTDATAINTERFACEMAP        (GBTWZDCLASSID_BASE + 0X00000005)
#define GBTWZDCLASSID_GBTINSERTSTXMLFILE         (GBTWZDCLASSID_BASE + 0X00000006)
#define GBTWZDCLASSID_GBTINSERTSTXMLFILEMNGR     (GBTWZDCLASSID_BASE + 0X00000007)
#define GBTWZDCLASSID_GBTINSERTSTXMLFILETOOL     (GBTWZDCLASSID_BASE + 0X00000008)
#define GBTWZDCLASSID_GBTDATASETREF              (GBTWZDCLASSID_BASE + 0X00000009)
#define GBTWZDCLASSID_GBTDATASETREFMNGR          (GBTWZDCLASSID_BASE + 0X0000000A)
#define GBTWZDCLASSID_BATCHITEMREFVALUE          (GBTWZDCLASSID_BASE + 0X0000000B)
#define GBTWZDCLASSID_BATCHGBTDATAGROUP          (GBTWZDCLASSID_BASE + 0X0000000C)
#define GBTWZDCLASSID_BATCHGBTDATA               (GBTWZDCLASSID_BASE + 0X0000000D)
#define GBTWZDCLASSID_COMMCMDEDIT                (GBTWZDCLASSID_BASE + 0X0000000E)
#define GBTWZDCLASSID_COMMCMDEDITMNGR            (GBTWZDCLASSID_BASE + 0X0000000F)
#define GBTWZDCLASSID_COMMCMDEDITEXPAND          (GBTWZDCLASSID_BASE + 0X00000010)


#define WM_WZD_INSERT_STXML_FINISH  (WM_USER+2251)

