/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_CancelErrorPDU_H_
#define	_CancelErrorPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectReference.h"
#include "Data.h"
#include "TimeStamp.h"
#include "Originator.h"
#include "INT8U.h"
#include <BOOLEAN.h>
#include "AddCause.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CancelErrorPDU */
typedef struct CancelErrorPDU {
	ObjectReference_t	 reference;
	Data_t	 ctlVal;
	TimeStamp_t	*operTm;	/* OPTIONAL */
	Originator_t	 origin;
	INT8U_t	 ctlNum;
	TimeStamp_t	 t;
	BOOLEAN_t	 test;
	AddCause_t	 addCause;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CancelErrorPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CancelErrorPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _CancelErrorPDU_H_ */
#include <asn_internal.h>
