/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_CreateDataSetErrorPDU_H_
#define	_CreateDataSetErrorPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServiceError.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CreateDataSetErrorPDU */
typedef ServiceError_t	 CreateDataSetErrorPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CreateDataSetErrorPDU;
asn_struct_free_f CreateDataSetErrorPDU_free;
asn_struct_print_f CreateDataSetErrorPDU_print;
asn_constr_check_f CreateDataSetErrorPDU_constraint;
xer_type_decoder_f CreateDataSetErrorPDU_decode_xer;
xer_type_encoder_f CreateDataSetErrorPDU_encode_xer;
per_type_decoder_f CreateDataSetErrorPDU_decode_aper;
per_type_encoder_f CreateDataSetErrorPDU_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CreateDataSetErrorPDU_H_ */
#include <asn_internal.h>
