/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#include "GetBRCBValuesRequestPDU.h"

static asn_TYPE_member_t asn_MBR_reference_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (26 << 2)),
		0,
		&asn_DEF_ObjectReference,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_reference_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_reference_specs_2 = {
	sizeof(struct GetBRCBValuesRequestPDU__reference),
	offsetof(struct GetBRCBValuesRequestPDU__reference, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_reference_2 = {
	"reference",
	"reference",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_reference_tags_2,
	sizeof(asn_DEF_reference_tags_2)
		/sizeof(asn_DEF_reference_tags_2[0]) - 1, /* 1 */
	asn_DEF_reference_tags_2,	/* Same as above */
	sizeof(asn_DEF_reference_tags_2)
		/sizeof(asn_DEF_reference_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_reference_2,
	1,	/* Single element */
	&asn_SPC_reference_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_GetBRCBValuesRequestPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetBRCBValuesRequestPDU, reference),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_reference_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"reference"
		},
};
static const ber_tlv_tag_t asn_DEF_GetBRCBValuesRequestPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetBRCBValuesRequestPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* reference */
};
static asn_SEQUENCE_specifics_t asn_SPC_GetBRCBValuesRequestPDU_specs_1 = {
	sizeof(struct GetBRCBValuesRequestPDU),
	offsetof(struct GetBRCBValuesRequestPDU, _asn_ctx),
	asn_MAP_GetBRCBValuesRequestPDU_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GetBRCBValuesRequestPDU = {
	"GetBRCBValuesRequestPDU",
	"GetBRCBValuesRequestPDU",
	&asn_OP_SEQUENCE,
	asn_DEF_GetBRCBValuesRequestPDU_tags_1,
	sizeof(asn_DEF_GetBRCBValuesRequestPDU_tags_1)
		/sizeof(asn_DEF_GetBRCBValuesRequestPDU_tags_1[0]), /* 1 */
	asn_DEF_GetBRCBValuesRequestPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetBRCBValuesRequestPDU_tags_1)
		/sizeof(asn_DEF_GetBRCBValuesRequestPDU_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_GetBRCBValuesRequestPDU_1,
	1,	/* Elements count */
	&asn_SPC_GetBRCBValuesRequestPDU_specs_1	/* Additional specs */
};

