/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#include "GetDataDirectoryRequestPDU.h"

static asn_TYPE_member_t asn_MBR_GetDataDirectoryRequestPDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GetDataDirectoryRequestPDU, dataReference),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObjectReference,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"dataReference"
		},
	{ ATF_POINTER, 1, offsetof(struct GetDataDirectoryRequestPDU, referenceAfter),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObjectReference,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"referenceAfter"
		},
};
static const int asn_MAP_GetDataDirectoryRequestPDU_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_GetDataDirectoryRequestPDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GetDataDirectoryRequestPDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dataReference */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* referenceAfter */
};
static asn_SEQUENCE_specifics_t asn_SPC_GetDataDirectoryRequestPDU_specs_1 = {
	sizeof(struct GetDataDirectoryRequestPDU),
	offsetof(struct GetDataDirectoryRequestPDU, _asn_ctx),
	asn_MAP_GetDataDirectoryRequestPDU_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_GetDataDirectoryRequestPDU_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GetDataDirectoryRequestPDU = {
	"GetDataDirectoryRequestPDU",
	"GetDataDirectoryRequestPDU",
	&asn_OP_SEQUENCE,
	asn_DEF_GetDataDirectoryRequestPDU_tags_1,
	sizeof(asn_DEF_GetDataDirectoryRequestPDU_tags_1)
		/sizeof(asn_DEF_GetDataDirectoryRequestPDU_tags_1[0]), /* 1 */
	asn_DEF_GetDataDirectoryRequestPDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_GetDataDirectoryRequestPDU_tags_1)
		/sizeof(asn_DEF_GetDataDirectoryRequestPDU_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_GetDataDirectoryRequestPDU_1,
	2,	/* Elements count */
	&asn_SPC_GetDataDirectoryRequestPDU_specs_1	/* Additional specs */
};

