/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetDataDirectoryErrorPDU_H_
#define	_GetDataDirectoryErrorPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServiceError.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GetDataDirectoryErrorPDU */
typedef ServiceError_t	 GetDataDirectoryErrorPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetDataDirectoryErrorPDU;
asn_struct_free_f GetDataDirectoryErrorPDU_free;
asn_struct_print_f GetDataDirectoryErrorPDU_print;
asn_constr_check_f GetDataDirectoryErrorPDU_constraint;
xer_type_decoder_f GetDataDirectoryErrorPDU_decode_xer;
xer_type_encoder_f GetDataDirectoryErrorPDU_encode_xer;
per_type_decoder_f GetDataDirectoryErrorPDU_decode_aper;
per_type_encoder_f GetDataDirectoryErrorPDU_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _GetDataDirectoryErrorPDU_H_ */
#include <asn_internal.h>
