/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetGoReferenceResponsePDU_H_
#define	_GetGoReferenceResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ObjectReference.h"
#include "INT32U.h"
#include <asn_SEQUENCE_OF.h>
#include "FunctionalConstraint.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct GetGoReferenceResponsePDU__memberData__Member {
	ObjectReference_t	 reference;
	FunctionalConstraint_t	 fc;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetGoReferenceResponsePDU__memberData__Member;

/* GetGoReferenceResponsePDU */
typedef struct GetGoReferenceResponsePDU {
	ObjectReference_t	 gocbReference;
	INT32U_t	 confRev;
	ObjectReference_t	 datSet;
	struct GetGoReferenceResponsePDU__memberData {
		A_SEQUENCE_OF(GetGoReferenceResponsePDU__memberData__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} memberData;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetGoReferenceResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetGoReferenceResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetGoReferenceResponsePDU_H_ */
#include <asn_internal.h>
