/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetLCBValuesResponsePDU_H_
#define	_GetLCBValuesResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include "ServiceError.h"
#include "LCB.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetLCBValuesResponsePDU__lcb__Member_PR {
	GetLCBValuesResponsePDU__lcb__Member_PR_NOTHING,	/* No components present */
	GetLCBValuesResponsePDU__lcb__Member_PR_error,
	GetLCBValuesResponsePDU__lcb__Member_PR_value
} GetLCBValuesResponsePDU__lcb__Member_PR;

/* Forward definitions */
typedef struct GetLCBValuesResponsePDU__lcb__Member {
	GetLCBValuesResponsePDU__lcb__Member_PR present;
	union GetLCBValuesResponsePDU__lcb__Member_u {
		ServiceError_t	 error;
		LCB_t	 value;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetLCBValuesResponsePDU__lcb__Member;

/* GetLCBValuesResponsePDU */
typedef struct GetLCBValuesResponsePDU {
	struct GetLCBValuesResponsePDU__lcb {
		A_SEQUENCE_OF(GetLCBValuesResponsePDU__lcb__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} lcb;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetLCBValuesResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetLCBValuesResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetLCBValuesResponsePDU_H_ */
#include <asn_internal.h>
