/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetMSVCBValuesResponsePDU_H_
#define	_GetMSVCBValuesResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include "ServiceError.h"
#include "MSVCB.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetMSVCBValuesResponsePDU__msvcb__Member_PR {
	GetMSVCBValuesResponsePDU__msvcb__Member_PR_NOTHING,	/* No components present */
	GetMSVCBValuesResponsePDU__msvcb__Member_PR_error,
	GetMSVCBValuesResponsePDU__msvcb__Member_PR_value
} GetMSVCBValuesResponsePDU__msvcb__Member_PR;

/* Forward definitions */
typedef struct GetMSVCBValuesResponsePDU__msvcb__Member {
	GetMSVCBValuesResponsePDU__msvcb__Member_PR present;
	union GetMSVCBValuesResponsePDU__msvcb__Member_u {
		ServiceError_t	 error;
		MSVCB_t	 value;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetMSVCBValuesResponsePDU__msvcb__Member;

/* GetMSVCBValuesResponsePDU */
typedef struct GetMSVCBValuesResponsePDU {
	struct GetMSVCBValuesResponsePDU__msvcb {
		A_SEQUENCE_OF(GetMSVCBValuesResponsePDU__msvcb__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} msvcb;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetMSVCBValuesResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetMSVCBValuesResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetMSVCBValuesResponsePDU_H_ */
#include <asn_internal.h>
