/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetRpcInterfaceDirectoryResponsePDU_H_
#define	_GetRpcInterfaceDirectoryResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <VisibleString.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetRpcInterfaceDirectoryResponsePDU */
typedef struct GetRpcInterfaceDirectoryResponsePDU {
	struct GetRpcInterfaceDirectoryResponsePDU__reference {
		A_SEQUENCE_OF(VisibleString_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} reference;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetRpcInterfaceDirectoryResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetRpcInterfaceDirectoryResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetRpcInterfaceDirectoryResponsePDU_H_ */
#include <asn_internal.h>
