/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetServerDirectoryRequestPDU_H_
#define	_GetServerDirectoryRequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "ObjectReference.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GetServerDirectoryRequestPDU__objectClass {
	GetServerDirectoryRequestPDU__objectClass_reserved	= 0,
	GetServerDirectoryRequestPDU__objectClass_logical_device	= 1,
	GetServerDirectoryRequestPDU__objectClass_file_system	= 2
} e_GetServerDirectoryRequestPDU__objectClass;

/* GetServerDirectoryRequestPDU */
typedef struct GetServerDirectoryRequestPDU {
	long	 objectClass;
	ObjectReference_t	*referenceAfter;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetServerDirectoryRequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetServerDirectoryRequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _GetServerDirectoryRequestPDU_H_ */
#include <asn_internal.h>
