/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GetURCBValuesErrorPDU_H_
#define	_GetURCBValuesErrorPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServiceError.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GetURCBValuesErrorPDU */
typedef ServiceError_t	 GetURCBValuesErrorPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetURCBValuesErrorPDU;
asn_struct_free_f GetURCBValuesErrorPDU_free;
asn_struct_print_f GetURCBValuesErrorPDU_print;
asn_constr_check_f GetURCBValuesErrorPDU_constraint;
xer_type_decoder_f GetURCBValuesErrorPDU_decode_xer;
xer_type_encoder_f GetURCBValuesErrorPDU_encode_xer;
per_type_decoder_f GetURCBValuesErrorPDU_decode_aper;
per_type_encoder_f GetURCBValuesErrorPDU_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _GetURCBValuesErrorPDU_H_ */
#include <asn_internal.h>
