/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_GoCB_H_
#define	_GoCB_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include "VisibleString129.h"
#include "ObjectReference.h"
#include "INT32U.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PHYCOMADDR;

/* GoCB */
typedef struct GoCB {
	BOOLEAN_t	 goEna;
	VisibleString129_t	 goID;
	ObjectReference_t	 datSet;
	INT32U_t	 confRev;
	BOOLEAN_t	 ndsCom;
	struct PHYCOMADDR	*dstAddress;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GoCB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GoCB;
extern asn_SEQUENCE_specifics_t asn_SPC_GoCB_specs_1;
extern asn_TYPE_member_t asn_MBR_GoCB_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PHYCOMADDR.h"

#endif	/* _GoCB_H_ */
#include <asn_internal.h>
