/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_INT64_H_
#define	_INT64_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* INT64 */
typedef long	 INT64_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_INT64;
asn_struct_free_f INT64_free;
asn_struct_print_f INT64_print;
asn_constr_check_f INT64_constraint;
xer_type_decoder_f INT64_decode_xer;
xer_type_encoder_f INT64_encode_xer;
per_type_decoder_f INT64_decode_aper;
per_type_encoder_f INT64_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _INT64_H_ */
#include <asn_internal.h>
