/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_Quality_H_
#define	_Quality_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Quality */
typedef BIT_STRING_t	 Quality_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Quality_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Quality;
asn_struct_free_f Quality_free;
asn_struct_print_f Quality_print;
asn_constr_check_f Quality_constraint;
xer_type_decoder_f Quality_decode_xer;
xer_type_encoder_f Quality_encode_xer;
per_type_decoder_f Quality_decode_aper;
per_type_encoder_f Quality_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Quality_H_ */
#include <asn_internal.h>
