/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_QueryLogAfterResponsePDU_H_
#define	_QueryLogAfterResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LogEntry;

/* QueryLogAfterResponsePDU */
typedef struct QueryLogAfterResponsePDU {
	struct QueryLogAfterResponsePDU__logEntry {
		A_SEQUENCE_OF(struct LogEntry) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} logEntry;
	BOOLEAN_t	*moreFollows;	/* DEFAULT TRUE */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} QueryLogAfterResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QueryLogAfterResponsePDU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LogEntry.h"

#endif	/* _QueryLogAfterResponsePDU_H_ */
#include <asn_internal.h>
