/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#include "QueryLogByTimeResponsePDU.h"

static asn_TYPE_member_t asn_MBR_logEntry_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_LogEntry,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_logEntry_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_logEntry_specs_2 = {
	sizeof(struct QueryLogByTimeResponsePDU__logEntry),
	offsetof(struct QueryLogByTimeResponsePDU__logEntry, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_logEntry_2 = {
	"logEntry",
	"logEntry",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_logEntry_tags_2,
	sizeof(asn_DEF_logEntry_tags_2)
		/sizeof(asn_DEF_logEntry_tags_2[0]) - 1, /* 1 */
	asn_DEF_logEntry_tags_2,	/* Same as above */
	sizeof(asn_DEF_logEntry_tags_2)
		/sizeof(asn_DEF_logEntry_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_logEntry_2,
	1,	/* Single element */
	&asn_SPC_logEntry_specs_2	/* Additional specs */
};

static int asn_DFL_4_cmp_1(const void *sptr) {
	const BOOLEAN_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 1 */
	return (*st != 1);
}
static int asn_DFL_4_set_1(void **sptr) {
	BOOLEAN_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 1 */
	*st = 1;
	return 0;
}
static asn_TYPE_member_t asn_MBR_QueryLogByTimeResponsePDU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct QueryLogByTimeResponsePDU, logEntry),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_logEntry_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"logEntry"
		},
	{ ATF_POINTER, 1, offsetof(struct QueryLogByTimeResponsePDU, moreFollows),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		&asn_DFL_4_cmp_1,	/* Compare DEFAULT 1 */
		&asn_DFL_4_set_1,	/* Set DEFAULT 1 */
		"moreFollows"
		},
};
static const int asn_MAP_QueryLogByTimeResponsePDU_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_QueryLogByTimeResponsePDU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_QueryLogByTimeResponsePDU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* logEntry */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* moreFollows */
};
static asn_SEQUENCE_specifics_t asn_SPC_QueryLogByTimeResponsePDU_specs_1 = {
	sizeof(struct QueryLogByTimeResponsePDU),
	offsetof(struct QueryLogByTimeResponsePDU, _asn_ctx),
	asn_MAP_QueryLogByTimeResponsePDU_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_QueryLogByTimeResponsePDU_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_QueryLogByTimeResponsePDU = {
	"QueryLogByTimeResponsePDU",
	"QueryLogByTimeResponsePDU",
	&asn_OP_SEQUENCE,
	asn_DEF_QueryLogByTimeResponsePDU_tags_1,
	sizeof(asn_DEF_QueryLogByTimeResponsePDU_tags_1)
		/sizeof(asn_DEF_QueryLogByTimeResponsePDU_tags_1[0]), /* 1 */
	asn_DEF_QueryLogByTimeResponsePDU_tags_1,	/* Same as above */
	sizeof(asn_DEF_QueryLogByTimeResponsePDU_tags_1)
		/sizeof(asn_DEF_QueryLogByTimeResponsePDU_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_QueryLogByTimeResponsePDU_1,
	2,	/* Elements count */
	&asn_SPC_QueryLogByTimeResponsePDU_specs_1	/* Additional specs */
};

