/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_SetEditSGValueResponsePDU_H_
#define	_SetEditSGValueResponsePDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServiceError.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SetEditSGValueResponsePDU */
typedef struct SetEditSGValueResponsePDU {
	struct SetEditSGValueResponsePDU__result {
		A_SEQUENCE_OF(ServiceError_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} result;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetEditSGValueResponsePDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetEditSGValueResponsePDU;

#ifdef __cplusplus
}
#endif

#endif	/* _SetEditSGValueResponsePDU_H_ */
#include <asn_internal.h>
