/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MMS"
 * 	found in "../mms-860.asn"
 * 	`asn1c -fcompound-names -no-gen-BER -no-gen-OER -no-gen-UPER -no-gen-example -gen-autotools`
 */

#ifndef	_SetLCBValuesRequestPDU_H_
#define	_SetLCBValuesRequestPDU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "ObjectReference.h"
#include <BOOLEAN.h>
#include "TriggerConditions.h"
#include "INT32U.h"
#include "LCBOptFlds.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct SetLCBValuesRequestPDU__lcb__Member {
	ObjectReference_t	 reference;
	BOOLEAN_t	*logEna;	/* OPTIONAL */
	ObjectReference_t	*datSet;	/* OPTIONAL */
	TriggerConditions_t	*trgOps;	/* OPTIONAL */
	INT32U_t	*intgPd;	/* OPTIONAL */
	ObjectReference_t	*logRef;	/* OPTIONAL */
	LCBOptFlds_t	*optFlds;	/* OPTIONAL */
	INT32U_t	*bufTm;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetLCBValuesRequestPDU__lcb__Member;

/* SetLCBValuesRequestPDU */
typedef struct SetLCBValuesRequestPDU {
	struct SetLCBValuesRequestPDU__lcb {
		A_SEQUENCE_OF(SetLCBValuesRequestPDU__lcb__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} lcb;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetLCBValuesRequestPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetLCBValuesRequestPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _SetLCBValuesRequestPDU_H_ */
#include <asn_internal.h>
