#pragma once


#define  DMCLASSID_BASECLASS			(CLASSID_BASECLASS + 0x00008000 )
#define  DMCLASSID_LISTCLASS			(CLASSID_EXLISTCLASS + 0x00008000 )

// #define  DMCLASSID_TAGDEFINE			(DMCLASSID_LISTCLASS+1)
// #define  DMCLASSID_TAGDEFINEMNGR		(DMCLASSID_LISTCLASS+2)
// #define  DMCLASSID_DEVICENODEDATADEFINE	(DMCLASSID_LISTCLASS+3)
// #define  DMCLASSID_DEVICENODEDEFINE		(DMCLASSID_LISTCLASS+4)
// #define  DMCLASSID_DEVICEDEFINE			(DMCLASSID_LISTCLASS+5)
// #define  DMCLASSID_DEVICENODETYPE		(DMCLASSID_LISTCLASS+6)
// #define  DMCLASSID_DEVICEMODELTEMPLATE	(DMCLASSID_LISTCLASS+7)
// #define  DMCLASSID_DEVICEMODELDEFINE	(DMCLASSID_LISTCLASS+8)
// 
// #define  DMCLASSID_TAG					(DMCLASSID_BASECLASS+9)
// #define  DMCLASSID_TAGS					(DMCLASSID_LISTCLASS+10)
// #define  DMCLASSID_DEVICENODEDATA		(DMCLASSID_LISTCLASS+11)
// #define  DMCLASSID_DEVICENODE			(DMCLASSID_LISTCLASS+12)



#define  DMCLASSID_CMMNETSERVERCONFIG		(DMCLASSID_LISTCLASS+0x00010000)
#define  DMCLASSID_CMMNETCLIENTCONFIG		(DMCLASSID_LISTCLASS+0x00030000)
#define  DMCLASSID_CMM_TCP_SERVER_CONFIG					(DMCLASSID_CMMNETSERVERCONFIG+14)
#define  DMCLASSID_CMM_TCP_CLIENT_CONFIG					(DMCLASSID_CMMNETCLIENTCONFIG+15)
#define  DMCLASSID_CMM_UDP_SERVER_CONFIG		(DMCLASSID_CMMNETSERVERCONFIG+16)
#define  DMCLASSID_CMM_UDP_CLIENT_CONFIG		(DMCLASSID_CMMNETCLIENTCONFIG+17)
#define  DMCLASSID_CMM_SERIAL_CONFIG			(DMCLASSID_LISTCLASS+18)
#define  DMCLASSID_DEVICECMMCONFIG			(DMCLASSID_LISTCLASS+19)

// #define  DMCLASSID_TAG_VALUE_DEFINE			(DMCLASSID_LISTCLASS+20)
#define  DMCLASSID_NET_CONFIG			(DMCLASSID_LISTCLASS+21)
#define  DMCLASSID_CMM_ONCONNECT			(DMCLASSID_BASECLASS+22)
#define  DMCLASSID_CMM_CONFIG_BASE			(DMCLASSID_BASECLASS+23)
//#define  DMCLASSID_DEVICEMODELTEMPLATES	(DMCLASSID_LISTCLASS+24)

#define  DMCLASSID_DEVICEMODEL				(DMCLASSID_LISTCLASS+24)
#define  DMCLASSID_PPDEVICE				(DMCLASSID_LISTCLASS+25)

#define  DMCLASSID_CMM_MMS_CONFIG				(DMCLASSID_LISTCLASS+26)
