INCLUDEPATH +=$$PWD

SOURCES +=  \
    $$PWD/SttCmdToolMngr.cpp \
    $$PWD/SttSocket/SttServerSocketDataBase.cpp \
    $$PWD/SttSocket/SttSocketDataBase_File.cpp \
    $$PWD/SttAuthority/SttModuleAuthority.cpp \
    $$PWD/SttAuthority/SttModuleAuthorityMngr.cpp \
    $$PWD/SttAuthority/SttTestClientUser.cpp \
    $$PWD/SttAuthority/SttTestClientUserMngr.cpp \
    $$PWD/SttAuthority/SttTestRemoteRegister.cpp \
    $$PWD/SttCmd/SttAssistCmd.cpp \
    $$PWD/SttCmd/SttAtsCmd.cpp \
    $$PWD/SttCmd/SttCmdBase.cpp \
    $$PWD/SttCmd/SttCmdCreator.cpp \
    $$PWD/SttCmd/SttCmdDefineGlobal.cpp \
    $$PWD/SttCmd/SttDebugCmd.cpp \
    $$PWD/SttCmd/SttMacro.cpp \
    $$PWD/SttCmd/SttParas.cpp \
    $$PWD/SttCmd/SttRemoteCmd.cpp \
    $$PWD/SttCmd/SttSysState.cpp \
    $$PWD/SttCmd/SttSystemCmd.cpp \
    $$PWD/SttCmd/SttTestCmd.cpp \
    $$PWD/Engine/SttClientTestEngine.cpp \
    $$PWD/Engine/SttNativeClientTestEngine.cpp \
    $$PWD/SttAtsSvr/SttNativeTestCtrlCntr.cpp \
    $$PWD/Engine/SttNativeTestEngine.cpp \
    $$PWD/Engine/SttTestEngineBase.cpp \
    $$PWD/Engine/SttTestEngineServerBase.cpp \
    $$PWD/SttSocket/SttCmdOverTimeMngr.cpp \
    $$PWD/Engine/SttTestEngineClientData.cpp \
    $$PWD/SttSocket/TestTerminal/SttClientSocketBase.cpp \
    $$PWD/SttSocket/TestTerminal/VC/SttClientSocket.cpp \
    $$PWD/SttSocket/TestServer/SttNativeRemoteClientSocketBase.cpp \
    $$PWD/SttSocket/TestServer/SttServerClientSocketBase.cpp \
    $$PWD/SttSocket/TestServer/SttTestServerSocketBase.cpp \
    $$PWD/SttSocket/TestServer/VC/SttNativeRemoteClientSocket.cpp \
    $$PWD/SttSocket/TestServer/VC/SttServerClientSocket.cpp \
    $$PWD/SttSocket/TestServer/VC/SttTestServerSocket.cpp \
    $$PWD/SttCmd/SttCmdData.cpp \
    $$PWD/SttFileToolMngr.cpp \
    $$PWD/SttCmd/SttRptMapDatas.cpp \
    $$PWD/SttSocket/SttSocketDataBase.cpp \
    $$PWD/SttRegisterCode.cpp \
    $$PWD/SmartTestInterface/MacroTestFactory.cpp \
    $$PWD/SmartTestInterface/ProtocolEngineFactory.cpp \
    $$PWD/Engine/SttServerNativeConfig.cpp \
    $$PWD/SttCmd/SttMsg.cpp \
    $$PWD/SttCmd/SttMsgs.cpp \
    $$PWD/SttCmd/SttAdjustCmd.cpp \
    $$PWD/LiveUpdate/SttNativeConfig/SttNativeCfgHisVer.cpp \
    $$PWD/LiveUpdate/SttNativeConfig/SttNativeCfgMngr.cpp \
    $$PWD/LiveUpdate/SttNativeConfig/SttNativeCfgMngrGlobal.cpp \
    $$PWD/SttTestAppConfig/SttTestAppCfg.cpp \
    $$PWD/SttTestAppConfig/SttTestAppConfigTool.cpp \
    $$PWD/LiveUpdate/SttNativeConfig/SttNativeCfgYun.cpp \
    $$PWD/LiveUpdate/SttNativeConfig/SttNativeCfgLiveUpdate.cpp \
    $$PWD/LiveUpdate/UpdateHistory/VerUpdateHisMngrGlobal.cpp \
    $$PWD/Engine/SttRemoteClientTestEngine.cpp \
    $$PWD/Engine/SttTestEngineRemoteClientData.cpp \
    $$PWD/TestClient/SttTestClientBase.cpp \
    $$PWD/TestClient/SttTestClientSingleTimer.cpp \
    $$PWD/LiveUpdate/SttLiveUpdateApi.cpp \
    $$PWD/LiveUpdate/SttNativeConfig/SttNativeCfgMnt.cpp \
    $$PWD/MemBuffer/stt_cycle_buffer.cpp \
    $$PWD/Engine/SttQueryAtsFileTool.cpp \
    $$PWD/API/NetworkInterface.cpp \
    $$PWD/API/QT/NetworkInterface_QT.cpp \
    $$PWD/SttProtocolBufBase.cpp \
    $$PWD/SttCmd/SttChMap.cpp \
    $$PWD/SttCmd/SttChMaps.cpp \
    $$PWD/SttCmd/SttHdCh.cpp \
    $$PWD/SttCmd/SttHdChs.cpp \
    $$PWD/SttCmd/SttIotDevice.cpp \
    $$PWD/SttCmd/SttIotDevices.cpp \
    $$PWD/SttCmd/SttIotNode.cpp \
    $$PWD/SttCmd/SttIotTopo.cpp \
    $$PWD/SttTest/Common/tmt_adjust_sys_parameter.cpp \
    $$PWD/SttTestBase/SttMacroXmlKeys.cpp \
    $$PWD/SttTestBase/SttXmlSerialize.cpp \
    $$PWD/SttTest/SttTestGlobaoConfig.cpp \
    $$PWD/SttTestBase/SttXmlSerializeBase.cpp \
    $$PWD/SttTest/Common/tmt_adjust_sys_para_trans.cpp \
    $$PWD/SttTestAppConfig/SttTestAppGateWayCfg.cpp \
    $$PWD/SttCmd/GuideBook/SttCmdGuideBookTransTool.cpp \
    $$PWD/SttCmd/GuideBook/SttCommCmd.cpp \
    $$PWD/SttCmd/GuideBook/SttDataObj.cpp \
    $$PWD/SttCmd/GuideBook/SttDevice.cpp \
    $$PWD/SttCmd/GuideBook/SttGuideBook.cpp \
    $$PWD/SttCmd/GuideBook/SttItemBase.cpp \
    $$PWD/SttCmd/GuideBook/SttItems.cpp \
    $$PWD/SttCmd/GuideBook/SttJobGuide.cpp \
    $$PWD/SttCmd/GuideBook/SttMacroTest.cpp \
    $$PWD/SttCmd/GuideBook/SttReport.cpp \
    $$PWD/SttCmd/GuideBook/SttReportMap.cpp \
    $$PWD/SttCmd/GuideBook/SttReports.cpp \
    $$PWD/SttCmd/GuideBook/SttRptData.cpp \
    $$PWD/SttCmd/GuideBook/SttSafety.cpp \
    $$PWD/SttCmd/GuideBook/SttSysParaEdit.cpp \
    $$PWD/SttCmd/GuideBook/SttSysParas.cpp \
    $$PWD/SmartTestInterface/VmSttMacroTest.cpp \
    $$PWD/SmartTestInterface/SttSmartTestSvrInterface.cpp \
    $$PWD/UI/Config/MacroTestUI/SttMacroTestUI_Group.cpp \
    $$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUI.cpp \
    $$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIDB.cpp \
    $$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIMngr.cpp \
    $$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIRef.cpp \
    $$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIs.cpp \
    $$PWD/UI/Config/MacroTestUI/SttTestCtrrlMacroTestUIMngrGlobal.cpp \
    $$PWD/SttPkgDispatchInterface.cpp \
    $$PWD/Engine/SttTestEngineServerData.cpp \
    $$PWD/SttCmd/GuideBook/SttContents.cpp \
    $$PWD/SttAtsSvr/SttSmartTest.cpp \
    $$PWD/SttAtsSvr/XSttSmartTestEntry.cpp \
    $$PWD/AdjustTool/SttAdjBase.cpp \
    $$PWD/AdjustTool/SttAdjDevice.cpp \
    $$PWD/AdjustTool/SttAdjModule.cpp \
    $$PWD/AdjustTool/SttMesLocalDb.cpp \
    $$PWD/SttCmd/GuideBook/SttTestMacroUiParas.cpp \
    $$PWD/SttCmd/GuideBook/SttMacroCharItems.cpp \
    $$PWD/SmartTestInterface/PpsttEngineCreator.cpp \
    $$PWD/SmartTestInterface/PpSttIotEngine.cpp \
    $$PWD/TestClient/PpSttIotClient.cpp \
    $$PWD/SttTestAppConfig/SttTestDeviceCfg.cpp \
    $$PWD/SttCmd/SttIotCmd.cpp \
    $$PWD/SttAtsSvr/SttSmartTestWnd.cpp \
    $$PWD/SttAtsSvr/SttSmartTestWnd_Linux.cpp \
    $$PWD/UI/Module/ScrollCtrl/ScrollComboBox.cpp \
    $$PWD/UI/Module/ScrollCtrl/ScrollListView.cpp \
    $$PWD/SmartTestInterface/AtsOutInterfaceMqttClient.cpp \
    $$PWD/SmartTestInterface/PpSttCommConfig.cpp \
    $$PWD/SmartTestInterface/PpXIotEngineBase.cpp \
    $$PWD/SttCmd/GuideBook/SttItemRsltExpr.cpp \
    $$PWD/SttSystemConfig/SttDevConfig.cpp \
    $$PWD/SttSystemConfig/SttModule.cpp \
    $$PWD/SttSystemConfig/SttModuleUse.cpp \
    $$PWD/SttSystemConfig/SttSystemConfig.cpp \
    $$PWD/SttSystemConfig/SttSystemConfigGlobal.cpp \
    $$PWD/SmartTestInterface/PpMqttIotEngine.cpp \
    $$PWD/Engine/SttNativeTestEngineInterface.cpp \
    $$PWD/SmartTestInterface/VmSttRelayTest.cpp \
    $$PWD/ReplayTest/BigComtradeTransPlay.cpp \
    $$PWD/ReplayTest/BigComtradeFileRead.cpp \
    $$PWD/ReplayTest/ComtradeBufMngr.cpp \
    $$PWD/ReplayTest/ComtradeDataBuffer.cpp \
    $$PWD/ReplayTest/ComtradePlayConfig.cpp \
    $$PWD/ReplayTest/ComtradeSendSocket.cpp \
    $$PWD/ReplayTest/SttCmtrdCfgDefineGlobal.cpp \
    $$PWD/ReplayTest/SttComtradeGroup.cpp \
    $$PWD/ReplayTest/SttModuleChComtradeBind.cpp \
    $$PWD/SttTest/Common/tmt_test_paras_head.cpp \
    $$PWD/SttTest/Common/tmt_replay_test.cpp \
    $$PWD/SttGlobalDef.cpp \
    $$PWD/SttCmd/GuideBook/SttTestMacroCharParas.cpp \
    $$PWD/Engine/SttNativeTestEngine_Mqtt.cpp \
    $$PWD/SttSocket/SttXcmdChInterface.cpp \
    $$PWD/SttAtsSvr/QAxSmartTestApp.cpp \
    $$PWD/SttTestSysGlobalPara.cpp \
    $$PWD/SttTest/Common/tmt_system_config.cpp


HEADERS += \
    $$PWD/SttCmdToolMngr.h \
    $$PWD/SttGlobalDef.h \
    $$PWD/SttGlobalDef_File.h \
    $$PWD/SttSocket/SttServerSocketDataBase.h \
    $$PWD/SttSocket/SttSocketDataBase.h \
    $$PWD/SttSocket/SttSocketDataBase_File.h \
    $$PWD/SttAuthority/SttModuleAuthority.h \
    $$PWD/SttAuthority/SttModuleAuthorityMngr.h \
    $$PWD/SttAuthority/SttTestClientUser.h \
    $$PWD/SttAuthority/SttTestClientUserMngr.h \
    $$PWD/SttAuthority/SttTestRemoteRegister.h \
    $$PWD/SttCmd/SttAssistCmd.h \
    $$PWD/SttCmd/SttAtsCmd.h \
    $$PWD/SttCmd/SttCmdBase.h \
    $$PWD/SttCmd/SttCmdCreator.h \
    $$PWD/SttCmd/SttCmdDefineGlobal.h \
    $$PWD/SttCmd/SttDebugCmd.h \
    $$PWD/SttCmd/SttMacro.h \
    $$PWD/SttCmd/SttParas.h \
    $$PWD/SttCmd/SttRemoteCmd.h \
    $$PWD/SttCmd/SttSysState.h \
    $$PWD/SttCmd/SttSystemCmd.h \
    $$PWD/SttCmd/SttTestCmd.h \
    $$PWD/Engine/SttClientTestEngine.h \
    $$PWD/Engine/SttNativeClientTestEngine.h \
    $$PWD/SttAtsSvr/SttNativeTestCtrlCntr.h \
    $$PWD/Engine/SttNativeTestEngine.h \
    $$PWD/Engine/SttTestEngineBase.h \
    $$PWD/Engine/SttTestEngineServerData.h \
    $$PWD/Engine/SttTestEngineServerBase.h \
    $$PWD/SttSocket/SttCmdOverTimeMngr.h \
    $$PWD/Engine/SttTestEngineClientData.h \
    $$PWD/SttSocket/TestTerminal/SttClientSocketBase.h \
    $$PWD/SttSocket/TestTerminal/VC/SttClientSocket.h \
    $$PWD/SttSocket/TestServer/SttNativeRemoteClientSocketBase.h \
    $$PWD/SttSocket/TestServer/SttServerClientSocketBase.h \
    $$PWD/SttSocket/TestServer/SttTestServerSocketBase.h \
    $$PWD/SttSocket/TestServer/VC/SttNativeRemoteClientSocket.h \
    $$PWD/SttSocket/TestServer/VC/SttServerClientSocket.h \
    $$PWD/SttSocket/TestServer/VC/SttTestServerSocket.h \
    $$PWD/SttCmd/SttCmdData.h \
    $$PWD/SttFileToolMngr.h \
    $$PWD/SttCmd/SttRptMapDatas.h \
    $$PWD/SttRegisterCode.h \
    $$PWD/SmartTestInterface/MacroTestFactory.h \
    $$PWD/SmartTestInterface/MacroTestInterface.h \
    $$PWD/SmartTestInterface/PpEngine_Stt.h \
    $$PWD/SmartTestInterface/ProtocolEngineFactory.h \
    $$PWD/SmartTestInterface/ProtocolEngineInterface.h \
    $$PWD/SmartTestInterface/SttBaseInterface.h \
    $$PWD/Engine/SttServerNativeConfig.h \
    $$PWD/SttCmd/SttMsg.h \
    $$PWD/SttCmd/SttMsgs.h \
    $$PWD/SmartTestInterface/SttMacroTestMsgRcvInterface.h \
    $$PWD/SmartTestInterface/SttMacroTestMsgRcvInterface_Linux.h \
    $$PWD/SttCmd/SttAdjustCmd.h \
    $$PWD/LiveUpdate/SttNativeConfig/SttNativeCfgHisVer.h \
    $$PWD/LiveUpdate/SttNativeConfig/SttNativeCfgMngr.h \
    $$PWD/LiveUpdate/SttNativeConfig/SttNativeCfgMngrGlobal.h \
    $$PWD/SttTestAppConfig/SttTestAppCfg.h \
    $$PWD/SttTestAppConfig/SttTestAppConfigTool.h \
    $$PWD/LiveUpdate/SttNativeConfig/SttNativeCfgYun.h \
    $$PWD/LiveUpdate/SttNativeConfig/SttNativeCfgLiveUpdate.h \
    $$PWD/LiveUpdate/UpdateHistory/VerUpdateHisMngrGlobal.h \
    $$PWD/Engine/SttRemoteClientTestEngine.h \
    $$PWD/Engine/SttTestEngineRemoteClientData.h \
    $$PWD/TestClient/SttTestClientBase.h \
    $$PWD/TestClient/SttTestClientSingleTimer.h \
    $$PWD/LiveUpdate/SttLiveUpdateApi.h \
    $$PWD/LiveUpdate/SttNativeConfig/SttNativeCfgMnt.h \
    $$PWD/MemBuffer/stt_cycle_buffer.h \
    $$PWD/Engine/SttQueryAtsFileTool.h \
    $$PWD/API/NetworkInterface.h \
    $$PWD/SttProtocolBufBase.h \
    $$PWD/SttCmd/SttChMap.h \
    $$PWD/SttCmd/SttChMaps.h \
    $$PWD/SttCmd/SttHdCh.h \
    $$PWD/SttCmd/SttHdChs.h \
    $$PWD/SttCmd/SttIotDevice.h \
    $$PWD/SttCmd/SttIotDevices.h \
    $$PWD/SttCmd/SttIotNode.h \
    $$PWD/SttCmd/SttIotTopo.h \
    $$PWD/SttTest/Common/tmt_adjust_sys_parameter.h \
    $$PWD/SttTestBase/SttMacroXmlKeys.h \
    $$PWD/SttTestBase/SttXmlSerialize.h \
    $$PWD/SttTest/SttTestGlobaoConfig.h \
    $$PWD/SttTestBase/SttXmlSerializeBase.h \
    $$PWD/SttTest/Common/tmt_adjust_sys_para_trans.h \
    $$PWD/SttTestAppConfig/SttTestAppGateWayCfg.h \
    $$PWD/SttCmd/GuideBook/SttCmdGuideBookTransTool.h \
    $$PWD/SttCmd/GuideBook/SttCommCmd.h \
    $$PWD/SttCmd/GuideBook/SttDataObj.h \
    $$PWD/SttCmd/GuideBook/SttDevice.h \
    $$PWD/SttCmd/GuideBook/SttGuideBook.h \
    $$PWD/SttCmd/GuideBook/SttItemBase.h \
    $$PWD/SttCmd/GuideBook/SttItems.h \
    $$PWD/SttCmd/GuideBook/SttJobGuide.h \
    $$PWD/SttCmd/GuideBook/SttMacroTest.h \
    $$PWD/SttCmd/GuideBook/SttReport.h \
    $$PWD/SttCmd/GuideBook/SttReportMap.h \
    $$PWD/SttCmd/GuideBook/SttReports.h \
    $$PWD/SttCmd/GuideBook/SttRptData.h \
    $$PWD/SttCmd/GuideBook/SttSafety.h \
    $$PWD/SttCmd/GuideBook/SttSysParaEdit.h \
    $$PWD/SttCmd/GuideBook/SttSysParas.h \
    $$PWD/SmartTestInterface/VmSttMacroTest.h \
    $$PWD/SmartTestInterface/SttSmartTestSvrInterface.h \
    $$PWD/UI/Config/MacroTestUI/SttMacroTestUI_Group.h \
    $$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUI.h \
    $$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIDB.h \
    $$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIMngr.h \
    $$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIRef.h \
    $$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIs.h \
    $$PWD/UI/Config/MacroTestUI/SttTestCtrrlMacroTestUIMngrGlobal.h \
    $$PWD/SttPkgDispatchInterface.h \
    $$PWD/SttCmd/GuideBook/SttContents.h \
    $$PWD/SttAtsSvr/SttSmartTest.h \
    $$PWD/SttAtsSvr/XSttSmartTestEntry.h \
    $$PWD/AdjustTool/SttAdjBase.h \
    $$PWD/AdjustTool/SttAdjDevice.h \
    $$PWD/AdjustTool/SttAdjModule.h \
    $$PWD/AdjustTool/SttMesLocalDb.h \
    $$PWD/SttCmd/GuideBook/SttTestMacroUiParas.h \
    $$PWD/SttCmd/GuideBook/SttMacroCharItems.h \
    $$PWD/SmartTestInterface/PpsttEngineCreator.h \
    $$PWD/SmartTestInterface/PpSttIotEngine.h \
    $$PWD/TestClient/PpSttIotClient.h \
    $$PWD/SttTestAppConfig/SttTestDeviceCfg.h \
    $$PWD/SttCmd/SttIotCmd.h \
    $$PWD/SttAtsSvr/SttSmartTestWnd.h \
    $$PWD/SttAtsSvr/SttSmartTestWnd_Linux.h \
    $$PWD/UI/Module/ScrollCtrl/ScrollComboBox.h \
    $$PWD/UI/Module/ScrollCtrl/ScrollListView.h \
    $$PWD/UI/Module/ScrollCtrl/ScrollDef.h \
    $$PWD/SmartTestInterface/AtsOutInterfaceMqttClient.h \
    $$PWD/SmartTestInterface/PpSttCommConfig.h \
    $$PWD/SmartTestInterface/PpXIotEngineBase.h \
    $$PWD/SttCmd/GuideBook/SttItemRsltExpr.h \
    $$PWD/SttSystemConfig/SttDevConfig.h \
    $$PWD/SttSystemConfig/SttModule.h \
    $$PWD/SttSystemConfig/SttModuleUse.h \
    $$PWD/SttSystemConfig/SttSystemConfig.h \
    $$PWD/SttSystemConfig/SttSystemConfigGlobal.h \
    $$PWD/SmartTestInterface/PpMqttIotEngine.h \
    $$PWD/Engine/SttNativeTestEngineInterface.h \
    $$PWD/SmartTestInterface/VmSttRelayTest.h \
    $$PWD/ReplayTest/BigComtradeTransPlay.h \
    $$PWD/ReplayTest/BigComtradeFileRead.h \
    $$PWD/ReplayTest/ComtradeBufMngr.h \
    $$PWD/ReplayTest/ComtradeDataBuffer.h \
    $$PWD/ReplayTest/ComtradePlayConfig.h \
    $$PWD/ReplayTest/ComtradeSendSocket.h \
    $$PWD/ReplayTest/SttCmtrdCfgDefineGlobal.h \
    $$PWD/ReplayTest/SttComtradeGroup.h \
    $$PWD/ReplayTest/SttModuleChComtradeBind.h \
    $$PWD/SttTest/Common/tmt_test_paras_head.h \
    $$PWD/SttTest/Common/tmt_replay_test.h \
    $$PWD/SttCmd/GuideBook/SttTestMacroCharParas.h \
    $$PWD/Engine/SttNativeTestEngine_Mqtt.h \
    $$PWD/SttSocket/SttXcmdChInterface.h \
    $$PWD/SttAtsSvr/QAxSmartTestApp.h \
    $$PWD/SttTestSysGlobalPara.h \
    $$PWD/SttTest/Common/tmt_system_config.h




