
#include(UI/UI_Common.pri)
#include(Test_Module_T.pri)
#include(SmartTestInterface/Test_SmartTestInterface.pri)
#include(UI/CommCmdWzd/Test_CommCmdWzd.pri)
include(UI/ImportDvmFile/Test_ImportDvmFile.pri)

SOURCES +=  \
$$PWD/AdjustTool/SttAdjBase.cpp \
$$PWD/AdjustTool/SttAdjDevice.cpp \
$$PWD/AdjustTool/SttAdjModule.cpp \
$$PWD/AdjustTool/SttMesLocalDb.cpp \
$$PWD/Assist/SttAppWndAssistInterface.cpp \
$$PWD/Assist/SttAssistGlobalApi.cpp \
$$PWD/Assist/SttAssistInterface.cpp \
$$PWD/BinaryDraw/XBinaryDrawBase.cpp \
$$PWD/BinaryDraw/XBinaryDrawGlobal.cpp \
$$PWD/BinaryDraw/XBinaryDrawView.cpp \
$$PWD/Engine/PpEngineServerBase/SttPpEngineServer.cpp \
$$PWD/Engine/PpEngineServerBase/SttPpServerClientSocket.cpp \
$$PWD/Engine/PpEngineServerBase/SttPpServerSocket.cpp \
$$PWD/Engine/PpEngineServerBase/SttPxPotoEngineBase.cpp \
$$PWD/Engine/PpMeas/PpSttIotEngineDeviceBase.cpp \
$$PWD/Engine/PpMeas/PpSttIotMeasDevice.cpp \
$$PWD/Engine/PpMeas/PpSttIotMeasServer.cpp \
$$PWD/Engine/SttClientTestEngine.cpp \
$$PWD/Engine/SttPowerTestEngineBase.cpp \
$$PWD/Engine/SttRemoteClientTestEngine.cpp \
$$PWD/Engine/SttServerNativeConfig.cpp \
$$PWD/Engine/SttServerTestCtrlCntr.cpp \
$$PWD/Engine/SttTestEngineBase.cpp \
$$PWD/Engine/SttTestEngineClientData.cpp \
$$PWD/Engine/SttTestEngineRemoteClientData.cpp \
$$PWD/Engine/SttTestEngineServerBase.cpp \
$$PWD/Engine/SttTestEngineServerData.cpp \
$$PWD/Engine/SttTestServerBase.cpp \
$$PWD/HtmlReport/SttModuleHtmlRptGenBase.cpp \
$$PWD/HtmlReport/SttXHtmlRptGenFactoryBase.cpp \
$$PWD/HtmlReport/SttXHtmlRptGenInterface.cpp \
$$PWD/HtmlReport/SttXmacroHtmlRptGenBase.cpp \
$$PWD/LiveUpdate/SttLiveUpdateShell.cpp \
$$PWD/LiveUpdate/SttUpdateCfg.cpp \
$$PWD/LiveUpdate/UpdateConfig/VerUpdateCfgMngr.cpp \
$$PWD/LiveUpdate/UpdateConfig/VerUpdateCfgMngrGlobal.cpp \
$$PWD/LiveUpdate/UpdateConfig/VerUpdateCfgSys.cpp \
$$PWD/LiveUpdate/UpdateConfig/VerUpdateCfgSyses.cpp \
$$PWD/LiveUpdate/UpdateConfig/VerUpdateCfgYun.cpp \
$$PWD/Main/Module/SttWgtCmdThread.cpp \
$$PWD/Protocol/SttProtocolDatas.cpp \
$$PWD/SttAuthority/SttTestClientUser.cpp \
$$PWD/SttAuthority/SttTestClientUserMngr.cpp \
$$PWD/SttAuthority/SttTestRemoteRegister.cpp \
$$PWD/SttCmd/GuideBook/SttCommCmd.cpp \
$$PWD/SttCmd/GuideBook/SttContents.cpp \
$$PWD/SttCmd/GuideBook/SttDataObj.cpp \
$$PWD/SttCmd/GuideBook/SttDevice.cpp \
$$PWD/SttCmd/GuideBook/SttGuideBook.cpp \
$$PWD/SttCmd/GuideBook/SttItemBase.cpp \
$$PWD/SttCmd/GuideBook/SttItemRsltExpr.cpp \
$$PWD/SttCmd/GuideBook/SttItems.cpp \
$$PWD/SttCmd/GuideBook/SttItemStateObject.cpp \
$$PWD/SttCmd/GuideBook/SttJobGuide.cpp \
$$PWD/SttCmd/GuideBook/SttMacroCharItems.cpp \
$$PWD/SttCmd/GuideBook/SttMacroTest.cpp \
$$PWD/SttCmd/GuideBook/SttReport.cpp \
$$PWD/SttCmd/GuideBook/SttReportMap.cpp \
$$PWD/SttCmd/GuideBook/SttReports.cpp \
$$PWD/SttCmd/GuideBook/SttRptData.cpp \
$$PWD/SttCmd/GuideBook/SttSafety.cpp \
$$PWD/SttCmd/GuideBook/SttSysParaEdit.cpp \
$$PWD/SttCmd/GuideBook/SttSysParas.cpp \
$$PWD/SttCmd/GuideBook/SttTestMacroCharParas.cpp \
$$PWD/SttCmd/GuideBook/SttTestMacroUiParas.cpp \
$$PWD/SttCmd/SttAdjustCmd.cpp \
$$PWD/SttCmd/SttAssistCmd.cpp \
$$PWD/SttCmd/SttAtsCmd.cpp \
$$PWD/SttCmd/SttChMap.cpp \
$$PWD/SttCmd/SttChMaps.cpp \
$$PWD/SttCmd/SttCmdBase.cpp \
$$PWD/SttCmd/SttCmdCreator.cpp \
$$PWD/SttCmd/SttCmdData.cpp \
$$PWD/SttCmd/SttCmdDefineGlobal.cpp \
$$PWD/SttCmd/SttDebugCmd.cpp \
$$PWD/SttCmd/SttHdCh.cpp \
$$PWD/SttCmd/SttHdChs.cpp \
$$PWD/SttCmd/SttIotCmd.cpp \
$$PWD/SttCmd/SttIotDevice.cpp \
$$PWD/SttCmd/SttIotDevices.cpp \
$$PWD/SttCmd/SttIotNode.cpp \
$$PWD/SttCmd/SttIotTopo.cpp \
$$PWD/SttCmd/SttMacro.cpp \
$$PWD/SttCmd/SttMsg.cpp \
$$PWD/SttCmd/SttMsgs.cpp \
$$PWD/SttCmd/SttParas.cpp \
$$PWD/SttCmd/SttRemoteCmd.cpp \
$$PWD/SttCmd/SttRptMapDatas.cpp \
$$PWD/SttCmd/SttSysState.cpp \
$$PWD/SttCmd/SttSystemCmd.cpp \
$$PWD/SttCmd/SttTestCmd.cpp \
$$PWD/SttCmdToolMngr.cpp \
$$PWD/SttFileToolMngr.cpp \
$$PWD/SttProtocolBufBase.cpp \
$$PWD/SttRegisterCode.cpp \
$$PWD/SttSocket/Multicast/SttMulticastClientSocket.cpp \
$$PWD/SttSocket/Multicast/SttMulticastServerSocket.cpp \
$$PWD/SttSocket/Multicast/SttUdpSocketDataBase.cpp \
$$PWD/SttSocket/SttCmdOverTimeMngr.cpp \
$$PWD/SttSocket/SttServerSocketDataBase.cpp \
$$PWD/SttSocket/SttSocketDataBase.cpp \
$$PWD/SttSocket/SttSocketDataBase_File.cpp \
$$PWD/SttSocket/SttXcmdChInterface.cpp \
$$PWD/SttSocket/TestServer/SttServerClientSocketBase.cpp \
$$PWD/SttSocket/TestServer/SttTestServerSocketBase.cpp \
$$PWD/SttSocket/TestServer/VC/SttServerClientSocket.cpp \
$$PWD/SttSocket/TestServer/VC/SttTestServerSocket.cpp \
$$PWD/SttSocket/TestTerminal/SttClientSocketBase.cpp \
$$PWD/SttSocket/TestTerminal/VC/SttClientSocket.cpp \
$$PWD/SttSocket/TestTerminal/VC/SttRcd61850ClientSocket.cpp \
    $$PWD/SttSocket/SttXcmdChAtsLib/SttAtsLibClient.cpp \
$$PWD/SttSystemConfig/SttDevConfig.cpp \
$$PWD/SttSystemConfig/SttModule.cpp \
$$PWD/SttSystemConfig/SttModuleUse.cpp \
$$PWD/SttSystemConfig/SttSystemConfig.cpp \
$$PWD/SttSystemConfig/SttSystemConfigGlobal.cpp \
$$PWD/SttTest/Common/Abnormal/tmt_abnormal_test.cpp \
$$PWD/SttTest/Common/ActionTime/tmt_vol_inverse_time_test.cpp \
$$PWD/SttTest/Common/Gradient/tmt_fault_gradient_test.cpp \
$$PWD/SttTest/Common/Impedance/tmt_cb_operate_test.cpp \
$$PWD/SttTest/Common/Impedance/tmt_distance_test.cpp \
$$PWD/SttTest/Common/Impedance/tmt_impedance_test.cpp \
$$PWD/SttTest/Common/Impedance/tmt_manuImped_test.cpp \
$$PWD/SttTest/Common/Impedance/tmt_reclose_acc_test.cpp \
$$PWD/SttTest/Common/LineVolt/tmt_linevolt_gradient_test.cpp \
$$PWD/SttTest/Common/LineVolt/tmt_linevolt_manu_test.cpp \
$$PWD/SttTest/Common/Power/tmt_power_manu_test.cpp \
$$PWD/SttTest/Common/SearchBase/tmt_complex_search.cpp \
$$PWD/SttTest/Common/SearchBase/tmt_search_base.cpp \
$$PWD/SttTest/Common/Sequence/tmt_sequence_gradient_test.cpp \
$$PWD/SttTest/Common/Sequence/tmt_sequence_manu_test.cpp \
$$PWD/SttTest/Common/Swing/tmt_swing_test.cpp \
$$PWD/SttTest/Common/tmt_adjust_sys_para_trans.cpp \
$$PWD/SttTest/Common/tmt_adjust_sys_parameter.cpp \
$$PWD/SttTest/Common/tmt_gradient_test.cpp \
$$PWD/SttTest/Common/tmt_harm_test.cpp \
$$PWD/SttTest/Common/tmt_manu_test.cpp \
$$PWD/SttTest/Common/tmt_replay_test.cpp \
$$PWD/SttTest/Common/tmt_short_time_over_test.cpp \
$$PWD/SttTest/Common/tmt_soe_test.cpp \
$$PWD/SttTest/Common/tmt_state_test.cpp \
$$PWD/SttTest/Common/tmt_system_config.cpp \
$$PWD/SttTest/Common/tmt_test_paras_head.cpp \
$$PWD/SttTest/PTU200L/tmt_pt_test.cpp \
$$PWD/SttTest/SttTestGlobaoConfig.cpp \
$$PWD/SttTestAppConfig/SttTestAppCfg.cpp \
$$PWD/SttTestAppConfig/SttTestAppConfigTool.cpp \
$$PWD/SttTestAppConfig/SttTestDeviceCfg.cpp \
$$PWD/SttTestBase/SttComplexCalApi.cpp \
$$PWD/SttTestBase/SttComplexp.cpp \
$$PWD/SttTestBase/SttDiffCurrCalculatTool.cpp \
$$PWD/SttTestBase/SttMacroXmlKeys.cpp \
$$PWD/SttTestBase/SttXmlSerialize.cpp \
$$PWD/SttTestBase/SttXmlSerializeBase.cpp \
$$PWD/SttTestCtrl/SttArgcArgvParser.cpp \
$$PWD/SttTestCtrl/SttTestAppBase.cpp \
$$PWD/SttTestCtrl/SttTestCtrlCntrBase.cpp \
$$PWD/SttTestCtrl/SttTestCtrlCntrNative.cpp \
$$PWD/SttTestCtrl/SttTestCtrlCntrWin.cpp \
$$PWD/SttTestResourceMngr/RtDataMngr/SttGlobalRtDataMngr.cpp \
$$PWD/SttTestResourceMngr/RtDataMngr/SttMacroChannels.cpp \
$$PWD/SttTestResourceMngr/RtDataMngr/SttMacroChannelsAsync.cpp \
$$PWD/SttTestResourceMngr/SttTestResourceMngr.cpp \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_4U3I.cpp \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_6U6I.cpp \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_Async.cpp \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_Sync.cpp \
$$PWD/SttTestResourceMngr/TestResource/SttTestResourceBase.cpp \
$$PWD/SttTestSysGlobalPara.cpp \
$$PWD/TestClient/PpSttIotClient.cpp \
$$PWD/TestClient/SttAtsTestClient.cpp \
$$PWD/TestClient/SttTestClientBase.cpp \
$$PWD/XLangResource_Native.cpp \
$$PWD/XLangResource_Win.cpp \
$$PWD/SMARTTESTINTERFACE/PpSttCommConfig.cpp \
$$PWD/SMARTTESTINTERFACE/PpSttIotEngine.cpp \
$$PWD/SMARTTESTINTERFACE/PpSttIotEngineClientApp.cpp \
$$PWD/SMARTTESTINTERFACE/PpXIotEngineBase.cpp \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/ppcommconfigdlg.cpp \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommcfgtcpclientdlg.cpp \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigcmsdlg.cpp \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigmmsdlg.cpp \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigserialmode.cpp \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigtcpserverdlg.cpp \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigudpclientdlg.cpp \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigudpserver.cpp \
$$PWD/SMARTTESTINTERFACE/QT/PpSttIotEngineClientAppWnd.cpp \
$$PWD/SMARTTESTINTERFACE/QT/PpSttIotEngineClientWidget.cpp \
$$PWD/SMARTTESTINTERFACE/QT/PpSttIotEngineClientWidgetMain.cpp \
$$PWD/SMARTTESTINTERFACE/QT/qsttmmsbrcbctrlwidget.cpp \
$$PWD/SMARTTESTINTERFACE/QT/qsttzoneindexsetdlg.cpp \
$$PWD/SMARTTESTINTERFACE/QT/SttPxEngineDsEditGrid.cpp \
$$PWD/SMARTTESTINTERFACE/QT/SttPxEngineDvmTreeCtrl.cpp \
$$PWD/UI/Config/Frame/SttFrame_Button.cpp \
$$PWD/UI/Config/Frame/SttFrame_Data.cpp \
$$PWD/UI/Config/Frame/SttFrame_Font.cpp \
$$PWD/UI/Config/Frame/SttFrame_GbTree.cpp \
$$PWD/UI/Config/Frame/SttFrame_GlobalData.cpp \
$$PWD/UI/Config/Frame/SttFrame_GlobalDatas.cpp \
$$PWD/UI/Config/Frame/SttFrame_Item.cpp \
$$PWD/UI/Config/Frame/SttFrame_MacroParaView.cpp \
$$PWD/UI/Config/Frame/SttFrame_Menu.cpp \
$$PWD/UI/Config/Frame/SttFrame_Menus.cpp \
$$PWD/UI/Config/Frame/SttFrame_Panal.cpp \
$$PWD/UI/Config/Frame/SttFrame_ReportView.cpp \
$$PWD/UI/Config/Frame/SttFrame_RightPanes.cpp \
$$PWD/UI/Config/Frame/SttFrame_Size.cpp \
$$PWD/UI/Config/Frame/SttFrame_XBar.cpp \
$$PWD/UI/Config/Frame/SttFrameConfig.cpp \
$$PWD/UI/Config/Frame/SttTestCtrlFrameCfgMngrGlobal.cpp \
$$PWD/UI/Config/MacroTestUI/SttMacroTestUI_Group.cpp \
$$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUI.cpp \
$$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIDB.cpp \
$$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIMngr.cpp \
$$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIRef.cpp \
$$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIs.cpp \
$$PWD/UI/Config/MacroTestUI/SttTestCtrrlMacroTestUIMngrGlobal.cpp \
$$PWD/UI/Config/TestMacroToolUI/ClassDefMngrGlobal.cpp \
$$PWD/UI/Config/TestMacroToolUI/CommcmdRef.cpp \
$$PWD/UI/Config/TestMacroToolUI/TestMacroGroup.cpp \
$$PWD/UI/Config/TestMacroToolUI/TestMacroRef.cpp \
$$PWD/UI/Config/TestMacroToolUI/TestMacroToolBar.cpp \
$$PWD/UI/Controls/ExportWordRpt/SttExportWordReport.cpp \
$$PWD/UI/Controls/ExportWordRpt/SttGbTreeCtrl_ExportRpt.cpp \
$$PWD/UI/Controls/ExportWordRpt/SttGrid_ExportRpt.cpp \
$$PWD/UI/Controls/ExportWordRpt/SttGrid_ExportRpt_Tec.cpp \
$$PWD/UI/Controls/FileMngr/SttFileMngrChildren.cpp \
$$PWD/UI/Controls/FileMngr/SttFileMngrDlg.cpp \
$$PWD/UI/Controls/FileMngr/SttFileMoveDlg.cpp \
$$PWD/UI/Controls/FileMngr/SttFileTypeMngrGrid.cpp \
$$PWD/UI/Controls/FileMngr/SttFileViewGrid.cpp \
$$PWD/UI/Controls/FileMngr/SttXFolderButton.cpp \
$$PWD/UI/Controls/SafetyMsgCfg/SttSafetyMsg.cpp \
$$PWD/UI/Controls/SafetyMsgCfg/SttSafetyMsgCfg.cpp \
$$PWD/UI/Controls/SafetyMsgCfg/SttSafetyMsgCfgGlobal.cpp \
$$PWD/UI/Controls/SafetyMsgCfg/SttSafetyMsgCfgs.cpp \
$$PWD/UI/Controls/SttAction.cpp \
$$PWD/UI/Controls/SttAddMacroWidget.cpp \
$$PWD/UI/Controls/SttCheckBox.cpp \
$$PWD/UI/Controls/SttCustomSetDlg.cpp \
$$PWD/UI/Controls/SttCustomSetTree.cpp \
$$PWD/UI/Controls/SttDataButtons.cpp \
$$PWD/UI/Controls/SttDvmEdit.cpp \
$$PWD/UI/Controls/SttFileSaveAsDlg.cpp \
$$PWD/UI/Controls/SttGbItemsEdit.cpp \
$$PWD/UI/Controls/SttGbItemsNameSelDlg.cpp \
$$PWD/UI/Controls/SttGbSafetyEdit.cpp \
$$PWD/UI/Controls/SttGroupBox.cpp \
$$PWD/UI/Controls/SttGuideBookTreeCtrl.cpp \
$$PWD/UI/Controls/SttGuideBookTreeWidget.cpp \
$$PWD/UI/Controls/SttItemButton.cpp \
$$PWD/UI/Controls/SttLanguageCfgDialog.cpp \
$$PWD/UI/Controls/SttLineEdit.cpp \
$$PWD/UI/Controls/SttMenuBar.cpp \
$$PWD/UI/Controls/SttMenuWidget.cpp \
$$PWD/UI/Controls/SttOutPutWidget.cpp \
$$PWD/UI/Controls/SttPanelBase.cpp \
$$PWD/UI/Controls/SttReportHeadSetDlg.cpp \
$$PWD/UI/Controls/SttTabWidget.cpp \
$$PWD/UI/Controls/SttTestViewsTabWidget.cpp \
$$PWD/UI/Controls/SttToolBar.cpp \
$$PWD/UI/Controls/SttToolButton.cpp \
$$PWD/UI/Controls/SttToolButtonBase.cpp \
$$PWD/UI/Controls/TestMacroTool/TestMacroToolDlg.cpp \
$$PWD/UI/Controls/ViewRpts/SttGbRptGrid_Dataset.cpp \
$$PWD/UI/Controls/ViewRpts/SttGbRptGrid_Values.cpp \
$$PWD/UI/Controls/ViewRpts/SttGbViewRpts.cpp \
$$PWD/UI/Interface/SttHtmlReportViewInterface.cpp \
$$PWD/UI/Interface/SttHtmlViewApi.cpp \
$$PWD/UI/Interface/SttMacroParaEditInterface.cpp \
$$PWD/UI/Interface/SttMacroParaEditViewMngr.cpp \
$$PWD/UI/Interface/SttMacroParaEditViewOriginal.cpp \
$$PWD/UI/Module/AinDataMap/QAinDataMapDatesetGrid.cpp \
$$PWD/UI/Module/AinDataMap/QAinDataMapDlg.cpp \
$$PWD/UI/Module/AinDataMap/QAinDataMapGrid.cpp \
$$PWD/UI/Module/ChannelParaSet/channelharmtable.cpp \
$$PWD/UI/Module/ChannelParaSet/channelpowertable.cpp \
$$PWD/UI/Module/ChannelParaSet/channeltable.cpp \
$$PWD/UI/Module/ChannelParaSet/QBasicTestParaSet.cpp \
$$PWD/UI/Module/ChannelParaSet/QBasicTestParaSetImp.cpp \
$$PWD/UI/Module/ChannelParaSet/QParaSetBase.cpp \
$$PWD/UI/Module/ChRsMap/ChMapsGrid.cpp \
$$PWD/UI/Module/ChRsMap/QChMapsDlg.cpp \
$$PWD/UI/Module/ChRsMap/QChMapsWidget.cpp \
$$PWD/UI/Module/CommConfigurationDlg/CommCfg/QSttCommCfgMainDlg.cpp \
$$PWD/UI/Module/CommConfigurationDlg/CommCfg/SttCommCfgDeviceAttrsGrid.cpp \
$$PWD/UI/Module/CommConfigurationDlg/DevComm/QSttCommCfgDeviceDlg.cpp \
$$PWD/UI/Module/CommConfigurationDlg/DevComm/QSttCommCfgDeviceWidget.cpp \
$$PWD/UI/Module/CommConfigurationDlg/DevComm/SttDevCommTeleMeasureGrid.cpp \
$$PWD/UI/Module/CommConfigurationDlg/DevComm/SttDevCommTeleParaCommGrid.cpp \
$$PWD/UI/Module/CommConfigurationDlg/PkgMonitor/QSttCommCfgPkgMonitorDlg.cpp \
$$PWD/UI/Module/CommConfigurationDlg/PkgMonitor/QSttCommCfgPkgMonitorWidget.cpp \
$$PWD/UI/Module/CommConfigurationDlg/PkgMonitor/SttCommCfgPkgMonitorLeftGrid.cpp \
$$PWD/UI/Module/CommConfigurationDlg/PkgMonitor/SttCommCfgPkgMonitorRightGrid.cpp \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/QSttCommCfgPointTblFileEditorDlg.cpp \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/QSttCommCfgPointTblFileImportDlg.cpp \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/SttCommCfgPointTblFileImportGrid.cpp \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/SttCommCfgPointTblFileImportTreeCtrl.cpp \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/SttPointTblEdtTabIntervalSetGrid.cpp \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/SttPointTblEdtTabTeleMeasureGrid.cpp \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/SttPointTblEdtTabTeleParaCommGrid.cpp \
$$PWD/UI/Module/CommConfigurationDlg/ProtocolTempl/QSttCommCfgProtocolTemplateDlg.cpp \
$$PWD/UI/Module/CommConfigurationDlg/ProtocolTempl/SttCommCfgProtocolTemplateGrid.cpp \
$$PWD/UI/Module/CommonCtrl_QT/Draw/QSttCustomArrowLine.cpp \
$$PWD/UI/Module/CommonCtrl_QT/Draw/QSttCustomRect.cpp \
$$PWD/UI/Module/CommonCtrl_QT/QCovDoubleValidator.cpp \
$$PWD/UI/Module/CommonCtrl_QT/QDataTypeComboBox.cpp \
$$PWD/UI/Module/CommonCtrl_QT/QFloatLineEdit.cpp \
$$PWD/UI/Module/CommonCtrl_QT/QIecLineEdit.cpp \
$$PWD/UI/Module/CommonCtrl_QT/QIecWidgetDelegate.cpp \
$$PWD/UI/Module/CommonCtrl_QT/QLongLineEdit.cpp \
$$PWD/UI/Module/CommonCtrl_QT/QNumberCheckBox.cpp \
$$PWD/UI/Module/CommonCtrl_QT/QSttProgDlg.cpp \
$$PWD/UI/Module/CommonCtrl_QT/SttDiffCurrCalDlg.cpp \
$$PWD/UI/Module/CommonMethod/commonMethod.cpp \
$$PWD/UI/Module/CommonMethod/FaultCalculat.cpp \
$$PWD/UI/Module/DCOutput/QAuxDCOutputDlg.cpp \
$$PWD/UI/Module/DeviceInforDlg/DeviceAttrsGrid.cpp \
$$PWD/UI/Module/DeviceInforDlg/QDeviceInforDlg.cpp \
$$PWD/UI/Module/DeviceInforDlg/SttModuleAttrsGrid.cpp \
$$PWD/UI/Module/DeviceInforDlg/SttModulesGrid.cpp \
$$PWD/UI/Module/ExSwitchSet/exswitchset.cpp \
$$PWD/UI/Module/FT3Widget/FT3OutParaWidget.cpp \
$$PWD/UI/Module/FT3Widget/FT3OutSetDialog.cpp \
$$PWD/UI/Module/FT3Widget/FT3OutWidget.cpp \
$$PWD/UI/Module/FT3Widget/IecCfgFT3OutGrid.cpp \
$$PWD/UI/Module/GooseParaWidget/goosepubwidget.cpp \
$$PWD/UI/Module/GooseParaWidget/IecCfgGoutChsGrid.cpp \
$$PWD/UI/Module/GooseParaWidget/LineEdit.cpp \
$$PWD/UI/Module/GooseParaWidget/qgooseparawidget.cpp \
$$PWD/UI/Module/GooseParaWidget/SttIntelBoutToGinGrid.cpp \
$$PWD/UI/Module/GooseParaWidget/SttIntelBoutToGinParaWidget.cpp \
$$PWD/UI/Module/GooseParaWidget/SttIntelBoutToGinPubWidget.cpp \
$$PWD/UI/Module/GooseParaWidget/SttIntelGoutToBinGrid.cpp \
$$PWD/UI/Module/GooseParaWidget/SttIntelGoutToBinParaWidget.cpp \
$$PWD/UI/Module/GooseParaWidget/SttIntelGoutToBinPubWidget.cpp \
$$PWD/UI/Module/GooseParaWidget/WidgetDelegate.cpp \
$$PWD/UI/Module/HardwareSetDlg/QHardwareSetDlg.cpp \
$$PWD/UI/Module/infoWidget/infowidget.cpp \
$$PWD/UI/Module/LuminousPower/LuminousPowerDlg.cpp \
$$PWD/UI/Module/LuminousPower/LuminousPowerGrid.cpp \
$$PWD/UI/Module/ModuleSetDlg/QModuleSetDlg.cpp \
$$PWD/UI/Module/ModuleSetDlg/QModuleSetWidget.cpp \
$$PWD/UI/Module/OutPutDebugDlg/QOutPutDebugDlg.cpp \
$$PWD/UI/Module/PopupDialog/SttFileDlgBase.cpp \
$$PWD/UI/Module/PopupDialog/SttFileMngrTool.cpp \
$$PWD/UI/Module/PopupDialog/SttFileMngrTree.cpp \
$$PWD/UI/Module/PopupDialog/SttFileSelectGrid.cpp \
$$PWD/UI/Module/PopupDialog/SttPopupOpenDialog.cpp \
$$PWD/UI/Module/PopupDialog/SttPopupSaveAsDialog.cpp \
$$PWD/UI/Module/PowerWidget/powerdiagramwidget.cpp \
$$PWD/UI/Module/PowerWidget/QPowerDiagramWidgetImp.cpp \
$$PWD/UI/Module/QExBaseListGridBase/QExBaseListComBoxDelegBase.cpp \
$$PWD/UI/Module/QExBaseListGridBase/QExBaseListFloatEditDelegBase.cpp \
$$PWD/UI/Module/QExBaseListGridBase/QExBaseListGridBase.cpp \
$$PWD/UI/Module/QExBaseListGridBase/QGridDefine.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollComboBox.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollCtrlInterface.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollListView.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollListWidget.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollSlider.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollTableWidget.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollTextEdit.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollTreeWidget.cpp \
$$PWD/UI/Module/ScrollCtrl/ScrollWebView.cpp \
$$PWD/UI/Module/SttUIDefine.cpp \
$$PWD/UI/Module/SysParas/QSysParasDlg.cpp \
$$PWD/UI/Module/SysParas/QSysParasWidget.cpp \
$$PWD/UI/Module/SysParas/QWeakSetWidget.cpp \
$$PWD/UI/Module/SysParas/WeakSetGrid.cpp \
$$PWD/UI/Module/VectorWidget/DiagramWidget.cpp \
$$PWD/UI/Module/VectorWidget/vectorwidget.cpp \
$$PWD/UI/Module/ZKCharaCurve/QCharElementDlg.cpp \
$$PWD/UI/Module/ZKCharaCurve/QCIFeatureAddDig.cpp \
$$PWD/UI/Module/ZKCharaCurve/QZKFeatureAddDig.cpp \
$$PWD/UI/ResultExpr/ResultExprCanvas.cpp \
$$PWD/UI/ResultExpr/ResultExprDlg_Data.cpp \
$$PWD/UI/ResultExpr/ResultExprDlg_Reports.cpp \
$$PWD/UI/ResultExpr/ResultExprWidget.cpp \
$$PWD/UI/ResultExpr/ResultExprWidget_Cmp.cpp \
$$PWD/UI/ResultExpr/ResultExprWidget_Error.cpp \
$$PWD/UI/ResultExpr/ResultExprWidget_Node.cpp \
$$PWD/UI/ResultExpr/ResultExprWidget_Range.cpp \
$$PWD/UI/ResultExpr/ResultExprWidget_ValueCal.cpp \
$$PWD/UI/ResultExpr/ResultExprWidgetItem.cpp \
$$PWD/UI/QSttInfWidgetBase.cpp \
$$PWD/UI/SttTestCntrCmdDefine.cpp \
$$PWD/UI/SttTestCntrFrameBase.cpp \
$$PWD/UI/Webkit/SttMacroParaEditViewHtml.cpp \
$$PWD/UI/Webkit/SttReportViewHtml.cpp \
$$PWD/UI/Webkit/SttWebViewBase.cpp \
    $$PWD/UI/SttTestCntrFrameApi.cpp \
    $$PWD/UI/Interface/SttMacroParaEditFactory.cpp \
    $$PWD/UI/Controls/SettingCtrls/QSettingItem.cpp \
    $$PWD/UI/Controls/SettingCtrls/QSettingLineEdit.cpp \
    $$PWD/UI/Controls/SettingCtrls/QSettingGridBase.cpp \
    $$PWD/UI/Controls/SettingCtrls/SettingInterface.cpp \
    $$PWD/UI/Controls/SettingCtrls/settingselectdlg.cpp \
    $$PWD/UI/Controls/SettingCtrls/QSettingGlobal.cpp \
    $$PWD/UI/Controls/SettingCtrls/QExprEdit.cpp \
    $$PWD/UI/Controls/SettingCtrls/SttGlobalModel.cpp \
    $$PWD/UI/Module/BinReverseConfig/QBinReverseCfgDialog.cpp \
    $$PWD/UI/Module/ChRsMap/BinBoutMapsGrid.cpp \
$$PWD/UI/ReportView/SttReportView.cpp \
    $$PWD/SttGlobalDef.cpp \
    $$PWD/UI/SttTestCntrThread.cpp \
    $$PWD/UI/Controls/NetworkConfig/QModifyIPAddrDlg.cpp \
    $$PWD/UI/Controls/NetworkConfig/qnetworkconfigwidget.cpp \
    $$PWD/UI/Controls/NetworkConfig/qnetworkiptable.cpp \
    $$PWD/SttUIGlobalDef.cpp \
    $$PWD/SttTestBase/SttTestEventArray.cpp \
    $$PWD/API/QT/NetworkInterface_QT.cpp \
    $$PWD/API/NetworkInterface.cpp \
    $$PWD/MemBuffer/stt_cycle_buffer.cpp \
    $$PWD/SttTest/Common/tmt_rtdata_def.cpp \
    $$PWD/HtmlReport/IECTest/SttIecTestHtmlRptGenFactory.cpp


HEADERS += \
$$PWD/AdjustTool/SttAdjBase.h \
$$PWD/AdjustTool/SttAdjDevice.h \
$$PWD/AdjustTool/SttAdjModule.h \
$$PWD/AdjustTool/SttMesLocalDb.h \
$$PWD/API/NetworkInterface.h \
$$PWD/Assist/SttAppWndAssistInterface.h \
$$PWD/Assist/SttAssistGlobalApi.h \
$$PWD/Assist/SttAssistInterface.h \
$$PWD/BinaryDraw/XBinaryDrawBase.h \
$$PWD/BinaryDraw/XBinaryDrawGlobal.h \
$$PWD/BinaryDraw/XBinaryDrawView.h \
$$PWD/Engine/PpEngineServerBase/SttPpEngineServer.h \
$$PWD/Engine/PpEngineServerBase/SttPpServerClientSocket.h \
$$PWD/Engine/PpEngineServerBase/SttPpServerSocket.h \
$$PWD/Engine/PpEngineServerBase/SttPxPotoEngineBase.h \
$$PWD/Engine/PpMeas/PpSttIotEngineDeviceBase.h \
$$PWD/Engine/PpMeas/PpSttIotMeasDevice.h \
$$PWD/Engine/PpMeas/PpSttIotMeasServer.h \
$$PWD/Engine/SttClientTestEngine.h \
$$PWD/Engine/SttPowerTestEngineBase.h \
$$PWD/Engine/SttRemoteClientTestEngine.h \
$$PWD/Engine/SttServerNativeConfig.h \
$$PWD/Engine/SttServerTestCtrlCntr.h \
$$PWD/Engine/SttTestEngineBase.h \
$$PWD/Engine/SttTestEngineClientData.h \
$$PWD/Engine/SttTestEngineRemoteClientData.h \
$$PWD/Engine/SttTestEngineServerBase.h \
$$PWD/Engine/SttTestEngineServerData.h \
$$PWD/Engine/SttTestServerBase.h \
$$PWD/HtmlReport/SttModuleHtmlRptGenBase.h \
$$PWD/HtmlReport/SttXHtmlRptGenFactoryBase.h \
$$PWD/HtmlReport/SttXHtmlRptGenInterface.h \
$$PWD/HtmlReport/SttXmacroHtmlRptGenBase.h \
$$PWD/LiveUpdate/SttLiveUpdateDef.h \
$$PWD/LiveUpdate/SttLiveUpdateShell.h \
$$PWD/LiveUpdate/SttUpdateCfg.h \
$$PWD/LiveUpdate/UpdateConfig/VerUpdateCfgMngr.h \
$$PWD/LiveUpdate/UpdateConfig/VerUpdateCfgMngrGlobal.h \
$$PWD/LiveUpdate/UpdateConfig/VerUpdateCfgSys.h \
$$PWD/LiveUpdate/UpdateConfig/VerUpdateCfgSyses.h \
$$PWD/LiveUpdate/UpdateConfig/VerUpdateCfgYun.h \
$$PWD/Main/Module/SttWgtCmdThread.h \
$$PWD/Main/SttMainArgvDef.h \
$$PWD/Protocol/SttProtocolDatas.h \
$$PWD/SttAuthority/SttTestClientUser.h \
$$PWD/SttAuthority/SttTestClientUserMngr.h \
$$PWD/SttAuthority/SttTestRemoteRegister.h \
$$PWD/SttCmd/GuideBook/SttCommCmd.h \
$$PWD/SttCmd/GuideBook/SttContents.h \
$$PWD/SttCmd/GuideBook/SttDataObj.h \
$$PWD/SttCmd/GuideBook/SttDevice.h \
$$PWD/SttCmd/GuideBook/SttGuideBook.h \
$$PWD/SttCmd/GuideBook/SttItemBase.h \
$$PWD/SttCmd/GuideBook/SttItemRsltExpr.h \
$$PWD/SttCmd/GuideBook/SttItems.h \
$$PWD/SttCmd/GuideBook/SttItemStateObject.h \
$$PWD/SttCmd/GuideBook/SttJobGuide.h \
$$PWD/SttCmd/GuideBook/SttMacroCharItems.h \
$$PWD/SttCmd/GuideBook/SttMacroTest.h \
$$PWD/SttCmd/GuideBook/SttReport.h \
$$PWD/SttCmd/GuideBook/SttReportMap.h \
$$PWD/SttCmd/GuideBook/SttReports.h \
$$PWD/SttCmd/GuideBook/SttRptData.h \
$$PWD/SttCmd/GuideBook/SttSafety.h \
$$PWD/SttCmd/GuideBook/SttSysParaEdit.h \
$$PWD/SttCmd/GuideBook/SttSysParas.h \
$$PWD/SttCmd/GuideBook/SttTestMacroCharParas.h \
$$PWD/SttCmd/GuideBook/SttTestMacroUiParas.h \
$$PWD/SttCmd/SttAdjustCmd.h \
$$PWD/SttCmd/SttAssistCmd.h \
$$PWD/SttCmd/SttAtsCmd.h \
$$PWD/SttCmd/SttChMap.h \
$$PWD/SttCmd/SttChMaps.h \
$$PWD/SttCmd/SttCmdBase.h \
$$PWD/SttCmd/SttCmdCreator.h \
$$PWD/SttCmd/SttCmdData.h \
$$PWD/SttCmd/SttCmdDefineGlobal.h \
$$PWD/SttCmd/SttDebugCmd.h \
$$PWD/SttCmd/SttHdCh.h \
$$PWD/SttCmd/SttHdChs.h \
$$PWD/SttCmd/SttIotCmd.h \
$$PWD/SttCmd/SttIotDevice.h \
$$PWD/SttCmd/SttIotDevices.h \
$$PWD/SttCmd/SttIotNode.h \
$$PWD/SttCmd/SttIotTopo.h \
$$PWD/SttCmd/SttMacro.h \
$$PWD/SttCmd/SttMsg.h \
$$PWD/SttCmd/SttMsgs.h \
$$PWD/SttCmd/SttParas.h \
$$PWD/SttCmd/SttRemoteCmd.h \
$$PWD/SttCmd/SttRptMapDatas.h \
$$PWD/SttCmd/SttSysState.h \
$$PWD/SttCmd/SttSystemCmd.h \
$$PWD/SttCmd/SttTestCmd.h \
$$PWD/SttCmdToolMngr.h \
$$PWD/SttFileToolMngr.h \
$$PWD/SttGlobalDef.h \
$$PWD/SttGlobalDef_File.h \
$$PWD/SttProtocolBufBase.h \
$$PWD/SttRegisterCode.h \
$$PWD/SttSocket/Multicast/SttGlobalMulticastDef.h \
$$PWD/SttSocket/Multicast/SttMulticastClientSocket.h \
$$PWD/SttSocket/Multicast/SttMulticastServerSocket.h \
$$PWD/SttSocket/Multicast/SttUdpSocketDataBase.h \
$$PWD/SttSocket/SttCmdOverTimeMngr.h \
$$PWD/SttSocket/SttCmdOverTimeMsgRcv.h \
$$PWD/SttSocket/SttServerSocketDataBase.h \
$$PWD/SttSocket/SttSocketDataBase.h \
$$PWD/SttSocket/SttSocketDataBase_File.h \
$$PWD/SttSocket/SttXcmdChInterface.h \
$$PWD/SttSocket/TestServer/SttServerClientSocketBase.h \
$$PWD/SttSocket/TestServer/SttTestServerSocketBase.h \
$$PWD/SttSocket/TestServer/VC/SttServerClientSocket.h \
$$PWD/SttSocket/TestServer/VC/SttTestServerSocket.h \
$$PWD/SttSocket/TestTerminal/SttClientSocketBase.h \
$$PWD/SttSocket/TestTerminal/VC/SttClientSocket.h \
$$PWD/SttSocket/TestTerminal/VC/SttRcd61850ClientSocket.h \ 
    $$PWD/SttSocket/SttXcmdChAtsLib/SttAtsLibClient.h \
$$PWD/SttSystemConfig/SttDevConfig.h \
$$PWD/SttSystemConfig/SttModule.h \
$$PWD/SttSystemConfig/SttModuleUse.h \
$$PWD/SttSystemConfig/SttSystemConfig.h \
$$PWD/SttSystemConfig/SttSystemConfigGlobal.h \
$$PWD/SttTest/Common/Abnormal/tmt_abnormal_test.h \
$$PWD/SttTest/Common/ActionTime/tmt_vol_inverse_time_test.h \
$$PWD/SttTest/Common/Gradient/tmt_fault_gradient_test.h \
$$PWD/SttTest/Common/Impedance/tmt_cb_operate_test.h \
$$PWD/SttTest/Common/Impedance/tmt_distance_test.h \
$$PWD/SttTest/Common/Impedance/tmt_impedance_test.h \
$$PWD/SttTest/Common/Impedance/tmt_manuImped_test.h \
$$PWD/SttTest/Common/Impedance/tmt_reclose_acc_test.h \
$$PWD/SttTest/Common/LineVolt/tmt_linevolt_gradient_test.h \
$$PWD/SttTest/Common/LineVolt/tmt_linevolt_manu_test.h \
$$PWD/SttTest/Common/Power/tmt_power_manu_test.h \
$$PWD/SttTest/Common/SearchBase/tmt_complex_search.h \
$$PWD/SttTest/Common/SearchBase/tmt_search_base.h \
$$PWD/SttTest/Common/Sequence/tmt_sequence_gradient_test.h \
$$PWD/SttTest/Common/Sequence/tmt_sequence_manu_test.h \
$$PWD/SttTest/Common/Swing/tmt_swing_test.h \
$$PWD/SttTest/Common/tmt_adjust_sys_para_trans.h \
$$PWD/SttTest/Common/tmt_adjust_sys_parameter.h \
$$PWD/SttTest/Common/tmt_common_def.h \
$$PWD/SttTest/Common/tmt_gradient_test.h \
$$PWD/SttTest/Common/tmt_harm_test.h \
$$PWD/SttTest/Common/tmt_manu_test.h \
$$PWD/SttTest/Common/tmt_replay_test.h \
$$PWD/SttTest/Common/tmt_result_def.h \
$$PWD/SttTest/Common/tmt_short_time_over_test.h \
$$PWD/SttTest/Common/tmt_soe_test.h \
$$PWD/SttTest/Common/tmt_state_test.h \
$$PWD/SttTest/Common/tmt_system_config.h \
$$PWD/SttTest/Common/tmt_test_paras_head.h \
$$PWD/SttTest/PTU200L/tmt_pt_test.h \
$$PWD/SttTest/SttTestGlobaoConfig.h \
$$PWD/SttTestAppConfig/SttTestAppCfg.h \
$$PWD/SttTestAppConfig/SttTestAppConfigTool.h \
$$PWD/SttTestAppConfig/SttTestDeviceCfg.h \
$$PWD/SttTestBase/SttComplexCalApi.h \
$$PWD/SttTestBase/SttComplexp.h \
$$PWD/SttTestBase/SttDiffCurrCalculatTool.h \
$$PWD/SttTestBase/SttMacroXmlKeys.h \
$$PWD/SttTestBase/SttXmlSerialize.h \
$$PWD/SttTestBase/SttXmlSerializeBase.h \
$$PWD/SttTestCtrl/SttArgcArgvParser.h \
$$PWD/SttTestCtrl/SttTestAppBase.h \
$$PWD/SttTestCtrl/SttTestCtrlCntrBase.h \
$$PWD/SttTestCtrl/SttTestCtrlCntrNative.h \
$$PWD/SttTestCtrl/SttTestCtrlCntrWin.h \
$$PWD/SttTestResourceMngr/RtDataMngr/SttGlobalRtDataMngr.h \
$$PWD/SttTestResourceMngr/RtDataMngr/SttMacroChannels.h \
$$PWD/SttTestResourceMngr/RtDataMngr/SttMacroChannelsAsync.h \
$$PWD/SttTestResourceMngr/SttTestResourceMngr.h \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_4U3I.h \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_6U6I.h \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_Async.h \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_Sync.h \
$$PWD/SttTestResourceMngr/TestResource/SttTestResourceBase.h \
$$PWD/SttTestSysGlobalPara.h \
$$PWD/TestClient/PpSttIotClient.h \
$$PWD/TestClient/SttAtsTestClient.h \
$$PWD/TestClient/SttMacroTestInterface.h \
$$PWD/TestClient/SttTestClientBase.h \
$$PWD/XLangResource_Native.h \
$$PWD/XLangResource_Win.h \
    $$PWD/AtsLib/atslib.h \
    $$PWD/AtsLib/atslib_global.h \
$$PWD/SMARTTESTINTERFACE/PpSttCommConfig.h \
$$PWD/SMARTTESTINTERFACE/PpSttIotEngine.h \
$$PWD/SMARTTESTINTERFACE/PpSttIotEngineClientApp.h \
$$PWD/SMARTTESTINTERFACE/PpXIotEngineBase.h \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/ppcommconfigdlg.h \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommcfgtcpclientdlg.h \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigcmsdlg.h \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigmmsdlg.h \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigserialmode.h \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigtcpserverdlg.h \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigudpclientdlg.h \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigudpserver.h \
$$PWD/SMARTTESTINTERFACE/QT/PpSttIotEngineClientAppWnd.h \
$$PWD/SMARTTESTINTERFACE/QT/PpSttIotEngineClientWidget.h \
$$PWD/SMARTTESTINTERFACE/QT/PpSttIotEngineClientWidgetMain.h \
$$PWD/SMARTTESTINTERFACE/QT/qsttmmsbrcbctrlwidget.h \
$$PWD/SMARTTESTINTERFACE/QT/qsttzoneindexsetdlg.h \
$$PWD/SMARTTESTINTERFACE/QT/SttPxEngineDsEditGrid.h \
$$PWD/SMARTTESTINTERFACE/QT/SttPxEngineDvmTreeCtrl.h \
$$PWD/UI/Config/Frame/SttFrame_Button.h \
$$PWD/UI/Config/Frame/SttFrame_Data.h \
$$PWD/UI/Config/Frame/SttFrame_Font.h \
$$PWD/UI/Config/Frame/SttFrame_GbTree.h \
$$PWD/UI/Config/Frame/SttFrame_GlobalData.h \
$$PWD/UI/Config/Frame/SttFrame_GlobalDatas.h \
$$PWD/UI/Config/Frame/SttFrame_Item.h \
$$PWD/UI/Config/Frame/SttFrame_MacroParaView.h \
$$PWD/UI/Config/Frame/SttFrame_Menu.h \
$$PWD/UI/Config/Frame/SttFrame_Menus.h \
$$PWD/UI/Config/Frame/SttFrame_Panal.h \
$$PWD/UI/Config/Frame/SttFrame_ReportView.h \
$$PWD/UI/Config/Frame/SttFrame_RightPanes.h \
$$PWD/UI/Config/Frame/SttFrame_Size.h \
$$PWD/UI/Config/Frame/SttFrame_XBar.h \
$$PWD/UI/Config/Frame/SttFrameConfig.h \
$$PWD/UI/Config/Frame/SttTestCtrlFrameCfgMngrGlobal.h \
$$PWD/UI/Config/MacroTestUI/SttMacroTestUI_Group.h \
$$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUI.h \
$$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIDB.h \
$$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIMngr.h \
$$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIRef.h \
$$PWD/UI/Config/MacroTestUI/SttMacroTestUI_TestMacroUIs.h \
$$PWD/UI/Config/MacroTestUI/SttTestCtrrlMacroTestUIMngrGlobal.h \
$$PWD/UI/Config/TestMacroToolUI/ClassDefMngrGlobal.h \
$$PWD/UI/Config/TestMacroToolUI/CommcmdRef.h \
$$PWD/UI/Config/TestMacroToolUI/TestMacroGroup.h \
$$PWD/UI/Config/TestMacroToolUI/TestMacroRef.h \
$$PWD/UI/Config/TestMacroToolUI/TestMacroToolBar.h \
$$PWD/UI/Controls/ExportWordRpt/SttExportWordReport.h \
$$PWD/UI/Controls/ExportWordRpt/SttGbTreeCtrl_ExportRpt.h \
$$PWD/UI/Controls/ExportWordRpt/SttGrid_ExportRpt.h \
$$PWD/UI/Controls/ExportWordRpt/SttGrid_ExportRpt_Tec.h \
$$PWD/UI/Controls/FileMngr/SttFileMngrChildren.h \
$$PWD/UI/Controls/FileMngr/SttFileMngrDlg.h \
$$PWD/UI/Controls/FileMngr/SttFileMoveDlg.h \
$$PWD/UI/Controls/FileMngr/SttFileTypeMngrGrid.h \
$$PWD/UI/Controls/FileMngr/SttFileViewGrid.h \
$$PWD/UI/Controls/FileMngr/SttXFolderButton.h \
$$PWD/UI/Controls/SafetyMsgCfg/SttSafetyMsg.h \
$$PWD/UI/Controls/SafetyMsgCfg/SttSafetyMsgCfg.h \
$$PWD/UI/Controls/SafetyMsgCfg/SttSafetyMsgCfgGlobal.h \
$$PWD/UI/Controls/SafetyMsgCfg/SttSafetyMsgCfgs.h \
$$PWD/UI/Controls/SttAction.h \
$$PWD/UI/Controls/SttAddMacroWidget.h \
$$PWD/UI/Controls/SttCheckBox.h \
$$PWD/UI/Controls/SttCustomSetDlg.h \
$$PWD/UI/Controls/SttCustomSetTree.h \
$$PWD/UI/Controls/SttDataButtons.h \
$$PWD/UI/Controls/SttDvmEdit.h \
$$PWD/UI/Controls/SttFileSaveAsDlg.h \
$$PWD/UI/Controls/SttGbItemsEdit.h \
$$PWD/UI/Controls/SttGbItemsNameSelDlg.h \
$$PWD/UI/Controls/SttGbSafetyEdit.h \
$$PWD/UI/Controls/SttGroupBox.h \
$$PWD/UI/Controls/SttGuideBookTreeCtrl.h \
$$PWD/UI/Controls/SttGuideBookTreeWidget.h \
$$PWD/UI/Controls/SttItemButton.h \
$$PWD/UI/Controls/SttLanguageCfgDialog.h \
$$PWD/UI/Controls/SttLineEdit.h \
$$PWD/UI/Controls/SttMenuBar.h \
$$PWD/UI/Controls/SttMenuWidget.h \
$$PWD/UI/Controls/SttOutPutWidget.h \
$$PWD/UI/Controls/SttPanelBase.h \
$$PWD/UI/Controls/SttReportHeadSetDlg.h \
$$PWD/UI/Controls/SttTabWidget.h \
$$PWD/UI/Controls/SttTestViewsTabWidget.h \
$$PWD/UI/Controls/SttToolBar.h \
$$PWD/UI/Controls/SttToolButton.h \
$$PWD/UI/Controls/SttToolButtonBase.h \
$$PWD/UI/Controls/TestMacroTool/TestMacroToolDlg.h \
$$PWD/UI/Controls/ViewRpts/SttGbRptGrid_Dataset.h \
$$PWD/UI/Controls/ViewRpts/SttGbRptGrid_Values.h \
$$PWD/UI/Controls/ViewRpts/SttGbViewRpts.h \
$$PWD/UI/Interface/SttHtmlReportViewInterface.h \
$$PWD/UI/Interface/SttHtmlViewApi.h \
$$PWD/UI/Interface/SttMacroParaEditInterface.h \
$$PWD/UI/Interface/SttMacroParaEditViewMngr.h \
$$PWD/UI/Interface/SttMacroParaEditViewOriginal.h \
$$PWD/UI/Module/AinDataMap/QAinDataMapDatesetGrid.h \
$$PWD/UI/Module/AinDataMap/QAinDataMapDlg.h \
$$PWD/UI/Module/AinDataMap/QAinDataMapGrid.h \
$$PWD/UI/Module/ChannelParaSet/channelharmtable.h \
$$PWD/UI/Module/ChannelParaSet/channelpowertable.h \
$$PWD/UI/Module/ChannelParaSet/channeltable.h \
$$PWD/UI/Module/ChannelParaSet/QBasicTestParaSet.h \
$$PWD/UI/Module/ChannelParaSet/QBasicTestParaSetImp.h \
$$PWD/UI/Module/ChannelParaSet/QParaSetBase.h \
$$PWD/UI/Module/ChRsMap/ChMapsGrid.h \
$$PWD/UI/Module/ChRsMap/QChMapsDlg.h \
$$PWD/UI/Module/ChRsMap/QChMapsWidget.h \
$$PWD/UI/Module/CommConfigurationDlg/CommCfg/QSttCommCfgMainDlg.h \
$$PWD/UI/Module/CommConfigurationDlg/CommCfg/SttCommCfgDeviceAttrsGrid.h \
$$PWD/UI/Module/CommConfigurationDlg/DevComm/QSttCommCfgDeviceDlg.h \
$$PWD/UI/Module/CommConfigurationDlg/DevComm/QSttCommCfgDeviceWidget.h \
$$PWD/UI/Module/CommConfigurationDlg/DevComm/SttDevCommTeleMeasureGrid.h \
$$PWD/UI/Module/CommConfigurationDlg/DevComm/SttDevCommTeleParaCommGrid.h \
$$PWD/UI/Module/CommConfigurationDlg/PkgMonitor/QSttCommCfgPkgMonitorDlg.h \
$$PWD/UI/Module/CommConfigurationDlg/PkgMonitor/QSttCommCfgPkgMonitorWidget.h \
$$PWD/UI/Module/CommConfigurationDlg/PkgMonitor/SttCommCfgPkgMonitorLeftGrid.h \
$$PWD/UI/Module/CommConfigurationDlg/PkgMonitor/SttCommCfgPkgMonitorRightGrid.h \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/QSttCommCfgPointTblFileEditorDlg.h \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/QSttCommCfgPointTblFileImportDlg.h \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/SttCommCfgPointTblFileImportGrid.h \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/SttCommCfgPointTblFileImportTreeCtrl.h \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/SttPointTblEdtTabIntervalSetGrid.h \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/SttPointTblEdtTabTeleMeasureGrid.h \
$$PWD/UI/Module/CommConfigurationDlg/PointTblFile/SttPointTblEdtTabTeleParaCommGrid.h \
$$PWD/UI/Module/CommConfigurationDlg/ProtocolTempl/QSttCommCfgProtocolTemplateDlg.h \
$$PWD/UI/Module/CommConfigurationDlg/ProtocolTempl/SttCommCfgProtocolTemplateGrid.h \
$$PWD/UI/Module/CommonCtrl_QT/Draw/QSttCustomArrowLine.h \
$$PWD/UI/Module/CommonCtrl_QT/Draw/QSttCustomRect.h \
$$PWD/UI/Module/CommonCtrl_QT/QCovDoubleValidator.h \
$$PWD/UI/Module/CommonCtrl_QT/QDataTypeComboBox.h \
$$PWD/UI/Module/CommonCtrl_QT/QFloatLineEdit.h \
$$PWD/UI/Module/CommonCtrl_QT/QIecLineEdit.h \
$$PWD/UI/Module/CommonCtrl_QT/QIecWidgetDelegate.h \
$$PWD/UI/Module/CommonCtrl_QT/QLongLineEdit.h \
$$PWD/UI/Module/CommonCtrl_QT/QNumberCheckBox.h \
$$PWD/UI/Module/CommonCtrl_QT/QSttProgDlg.h \
$$PWD/UI/Module/CommonCtrl_QT/SttDiffCurrCalDlg.h \
$$PWD/UI/Module/CommonMethod/commonMethod.h \
$$PWD/UI/Module/CommonMethod/FaultCalculat.h \
$$PWD/UI/Module/DCOutput/QAuxDCOutputDlg.h \
$$PWD/UI/Module/DeviceInforDlg/DeviceAttrsGrid.h \
$$PWD/UI/Module/DeviceInforDlg/QDeviceInforDlg.h \
$$PWD/UI/Module/DeviceInforDlg/SttModuleAttrsGrid.h \
$$PWD/UI/Module/DeviceInforDlg/SttModulesGrid.h \
$$PWD/UI/Module/ExSwitchSet/exswitchset.h \
$$PWD/UI/Module/FT3Widget/FT3OutParaWidget.h \
$$PWD/UI/Module/FT3Widget/FT3OutSetDialog.h \
$$PWD/UI/Module/FT3Widget/FT3OutWidget.h \
$$PWD/UI/Module/FT3Widget/IecCfgFT3OutGrid.h \
$$PWD/UI/Module/GooseParaWidget/goosepubwidget.h \
$$PWD/UI/Module/GooseParaWidget/IecCfgGoutChsGrid.h \
$$PWD/UI/Module/GooseParaWidget/LineEdit.h \
$$PWD/UI/Module/GooseParaWidget/qgooseparawidget.h \
$$PWD/UI/Module/GooseParaWidget/SttIntelBoutToGinGrid.h \
$$PWD/UI/Module/GooseParaWidget/SttIntelBoutToGinParaWidget.h \
$$PWD/UI/Module/GooseParaWidget/SttIntelBoutToGinPubWidget.h \
$$PWD/UI/Module/GooseParaWidget/SttIntelGoutToBinGrid.h \
$$PWD/UI/Module/GooseParaWidget/SttIntelGoutToBinParaWidget.h \
$$PWD/UI/Module/GooseParaWidget/SttIntelGoutToBinPubWidget.h \
$$PWD/UI/Module/GooseParaWidget/WidgetDelegate.h \
$$PWD/UI/Module/HardwareSetDlg/QHardwareSetDlg.h \
$$PWD/UI/Module/infoWidget/infowidget.h \
$$PWD/UI/Module/LuminousPower/LuminousPowerDlg.h \
$$PWD/UI/Module/LuminousPower/LuminousPowerGrid.h \
$$PWD/UI/Module/ModuleSetDlg/QModuleSetDlg.h \
$$PWD/UI/Module/ModuleSetDlg/QModuleSetWidget.h \
$$PWD/UI/Module/OutPutDebugDlg/QOutPutDebugDlg.h \
$$PWD/UI/Module/PopupDialog/SttFileDlgBase.h \
$$PWD/UI/Module/PopupDialog/SttFileMngrTool.h \
$$PWD/UI/Module/PopupDialog/SttFileMngrTree.h \
$$PWD/UI/Module/PopupDialog/SttFileSelectGrid.h \
$$PWD/UI/Module/PopupDialog/SttPopupOpenDialog.h \
$$PWD/UI/Module/PopupDialog/SttPopupSaveAsDialog.h \
$$PWD/UI/Module/PowerWidget/powerdiagramwidget.h \
$$PWD/UI/Module/PowerWidget/QPowerDiagramWidgetImp.h \
$$PWD/UI/Module/QExBaseListGridBase/QExBaseListComBoxDelegBase.h \
$$PWD/UI/Module/QExBaseListGridBase/QExBaseListFloatEditDelegBase.h \
$$PWD/UI/Module/QExBaseListGridBase/QExBaseListGridBase.h \
$$PWD/UI/Module/QExBaseListGridBase/QGridDefine.h \
$$PWD/UI/Module/ScrollCtrl/ScrollComboBox.h \
$$PWD/UI/Module/ScrollCtrl/ScrollCtrlInterface.h \
$$PWD/UI/Module/ScrollCtrl/ScrollDef.h \
$$PWD/UI/Module/ScrollCtrl/ScrollListView.h \
$$PWD/UI/Module/ScrollCtrl/ScrollListWidget.h \
$$PWD/UI/Module/ScrollCtrl/ScrollSlider.h \
$$PWD/UI/Module/ScrollCtrl/ScrollTableWidget.h \
$$PWD/UI/Module/ScrollCtrl/ScrollTextEdit.h \
$$PWD/UI/Module/ScrollCtrl/ScrollTreeWidget.h \
$$PWD/UI/Module/ScrollCtrl/ScrollWebView.h \
$$PWD/UI/Module/SttUIDefine.h \
$$PWD/UI/Module/SysParas/QSysParasDlg.h \
$$PWD/UI/Module/SysParas/QSysParasWidget.h \
$$PWD/UI/Module/SysParas/QWeakSetWidget.h \
$$PWD/UI/Module/SysParas/WeakSetGrid.h \
$$PWD/UI/Module/VectorWidget/DiagramWidget.h \
$$PWD/UI/Module/VectorWidget/vectorwidget.h \
$$PWD/UI/Module/ZKCharaCurve/QCharElementDlg.h \
$$PWD/UI/Module/ZKCharaCurve/QCIFeatureAddDig.h \
$$PWD/UI/Module/ZKCharaCurve/QZKFeatureAddDig.h \
$$PWD/UI/ResultExpr/ResultExprCanvas.h \
$$PWD/UI/ResultExpr/ResultExprDlg_Data.h \
$$PWD/UI/ResultExpr/ResultExprDlg_Reports.h \
$$PWD/UI/ResultExpr/ResultExprWidget.h \
$$PWD/UI/ResultExpr/ResultExprWidget_Cmp.h \
$$PWD/UI/ResultExpr/ResultExprWidget_Error.h \
$$PWD/UI/ResultExpr/ResultExprWidget_Node.h \
$$PWD/UI/ResultExpr/ResultExprWidget_Range.h \
$$PWD/UI/ResultExpr/ResultExprWidget_ValueCal.h \
$$PWD/UI/ResultExpr/ResultExprWidgetItem.h \
$$PWD/UI/QSttInfWidgetBase.h \
$$PWD/UI/SttTestCntrCmdDefine.h \
$$PWD/UI/SttTestCntrFrameBase.h \
$$PWD/UI/Webkit/SttMacroParaEditViewHtml.h \
$$PWD/UI/Webkit/SttReportViewHtml.h \
$$PWD/UI/Webkit/SttWebViewBase.h \
    $$PWD/UI/SttTestCntrFrameApi.h \
    $$PWD/UI/Interface/SttMacroParaEditFactory.h \
    $$PWD/UI/Controls/SettingCtrls/QSettingItem.h \
    $$PWD/UI/Controls/SettingCtrls/QSettingLineEdit.h \
    $$PWD/UI/Controls/SettingCtrls/QSettingGridBase.h \
    $$PWD/UI/Controls/SettingCtrls/SettingInterface.h \
    $$PWD/UI/Controls/SettingCtrls/settingselectdlg.h \
    $$PWD/UI/Controls/SettingCtrls/QSettingGlobal.h \
    $$PWD/UI/Controls/SettingCtrls/QExprEdit.h \
    $$PWD/UI/Controls/SettingCtrls/SttGlobalModel.h \
    $$PWD/UI/Module/BinReverseConfig/QBinReverseCfgDialog.h \
    $$PWD/UI/Module/ChRsMap/BinBoutMapsGrid.h \
$$PWD/UI/ReportView/SttReportView.h \
    $$PWD/UI/SttTestCntrThread.h \
    $$PWD/UI/Controls/NetworkConfig/QModifyIPAddrDlg.h \
    $$PWD/UI/Controls/NetworkConfig/qnetworkconfigwidget.h \
    $$PWD/UI/Controls/NetworkConfig/qnetworkiptable.h \
    $$PWD/SttUIGlobalDef.h \
    $$PWD/SttTestBase/SttTestEventArray.h \
    $$PWD/MemBuffer/stt_cycle_buffer.h \
    $$PWD/SttTest/Common/tmt_rtdata_def.h \
    $$PWD/HtmlReport/IECTest/SttIecTestHtmlRptGenFactory.h


FORMS    += \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/ppcommconfigdlg.ui \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommcfgtcpclientdlg.ui \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigcmsdlg.ui \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigmmsdlg.ui \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigserialmode.ui \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigtcpserverdlg.ui \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigudpclientdlg.ui \
$$PWD/SMARTTESTINTERFACE/QT/CommConfigWidget/qcommconfigudpserver.ui \
$$PWD/SMARTTESTINTERFACE/QT/PpSttIotEngineClientWidget.ui \
$$PWD/SMARTTESTINTERFACE/QT/qsttmmsbrcbctrlwidget.ui \
$$PWD/SMARTTESTINTERFACE/QT/qsttzoneindexsetdlg.ui \
$$PWD/UI/Controls/ExportWordRpt/SttExportWordReport.ui \
$$PWD/UI/Controls/SttAddMacroWidget.ui \
$$PWD/UI/Controls/SttCustomSetDlg.ui \
$$PWD/UI/Controls/SttFileSaveAsDlg.ui \
$$PWD/UI/Controls/SttGbItemsEdit.ui \
$$PWD/UI/Controls/SttGbItemsNameSelDlg.ui \
$$PWD/UI/Controls/SttGbSafetyEdit.ui \
$$PWD/UI/Controls/SttOutPutWidget.ui \
$$PWD/UI/Controls/SttReportHeadSetDlg.ui \
$$PWD/UI/Controls/TestMacroTool/TestMacroToolDlg.ui \
$$PWD/UI/Controls/ViewRpts/SttGbViewRpts.ui \
$$PWD/UI/Module/AinDataMap/QAinDataMapDlg.ui \
$$PWD/UI/Module/ZKCharaCurve/QCIFeatureAddDig.ui \
$$PWD/UI/Module/ZKCharaCurve/QZKFeatureAddDig.ui \
$$PWD/UI/ResultExpr/ResultExprDlg_Data.ui \
$$PWD/UI/ResultExpr/ResultExprDlg_Reports.ui \
$$PWD/UI/ResultExpr/ResultExprWidget.ui \
$$PWD/UI/ResultExpr/ResultExprWidget_Cmp.ui \
$$PWD/UI/ResultExpr/ResultExprWidget_Error.ui \
$$PWD/UI/ResultExpr/ResultExprWidget_Node.ui \
$$PWD/UI/ResultExpr/ResultExprWidget_Range.ui \
$$PWD/UI/ResultExpr/ResultExprWidget_ValueCal.ui \
    $$PWD/UI/Controls/SettingCtrls/settingselectdlg.ui \
    $$PWD/UI/Module/BinReverseConfig/QBinReverseCfgWidget.ui \
$$PWD/UI/ReportView/SttReportView.ui \
    $$PWD/UI/Controls/NetworkConfig/qnetworkconfigwidget.ui


