
SOURCES +=  \
$$PWD/SttSystemConfig/SttDevConfig.cpp \
$$PWD/SttSystemConfig/SttModule.cpp \
$$PWD/SttSystemConfig/SttModuleUse.cpp \
$$PWD/SttSystemConfig/SttSystemConfig.cpp \
$$PWD/SttSystemConfig/SttSystemConfigGlobal.cpp \
$$PWD/SttTest/Common/Abnormal/tmt_abnormal_test.cpp \
$$PWD/SttTest/Common/ActionTime/tmt_vol_inverse_time_test.cpp \
$$PWD/SttTest/Common/FAParasSet/tmt_fa_Paras_set.cpp \
$$PWD/SttTest/Common/Gradient/tmt_fault_gradient_test.cpp \
$$PWD/SttTest/Common/Impedance/tmt_cb_operate_test.cpp \
$$PWD/SttTest/Common/Impedance/tmt_distance_test.cpp \
$$PWD/SttTest/Common/Impedance/tmt_impedance_test.cpp \
$$PWD/SttTest/Common/Impedance/tmt_manuImped_test.cpp \
$$PWD/SttTest/Common/Impedance/tmt_reclose_acc_test.cpp \
$$PWD/SttTest/Common/LineVolt/tmt_linevolt_gradient_test.cpp \
$$PWD/SttTest/Common/LineVolt/tmt_linevolt_manu_test.cpp \
$$PWD/SttTest/Common/Power/tmt_power_manu_test.cpp \
$$PWD/SttTest/Common/SearchBase/tmt_complex_search.cpp \
$$PWD/SttTest/Common/SearchBase/tmt_search_base.cpp \
$$PWD/SttTest/Common/Sequence/tmt_sequence_gradient_test.cpp \
$$PWD/SttTest/Common/Sequence/tmt_sequence_manu_test.cpp \
$$PWD/SttTest/Common/Swing/tmt_swing_test.cpp \
$$PWD/SttTest/Common/tmt_adjust_sys_para_trans.cpp \
$$PWD/SttTest/Common/tmt_adjust_sys_parameter.cpp \
$$PWD/SttTest/Common/tmt_gradient_test.cpp \
$$PWD/SttTest/Common/tmt_harm_test.cpp \
$$PWD/SttTest/Common/tmt_manu_test.cpp \
$$PWD/SttTest/Common/tmt_replay_test.cpp \
$$PWD/SttTest/Common/tmt_short_time_over_test.cpp \
$$PWD/SttTest/Common/tmt_soe_test.cpp \
$$PWD/SttTest/Common/tmt_state_test.cpp \
$$PWD/SttTest/Common/tmt_system_config.cpp \
$$PWD/SttTest/Common/tmt_test_paras_head.cpp \
$$PWD/SttTest/PTU200L/tmt_pt_test.cpp \
$$PWD/SttTest/SttTestGlobaoConfig.cpp \
$$PWD/SttTestAppConfig/SttTestAppCfg.cpp \
$$PWD/SttTestAppConfig/SttTestAppConfigTool.cpp \
$$PWD/SttTestAppConfig/SttTestDeviceCfg.cpp \
$$PWD/SttTestBase/SttComplexCalApi.cpp \
$$PWD/SttTestBase/SttComplexp.cpp \
$$PWD/SttTestBase/SttDiffCurrCalculatTool.cpp \
$$PWD/SttTestBase/SttMacroXmlKeys.cpp \
$$PWD/SttTestBase/SttXmlSerialize.cpp \
$$PWD/SttTestBase/SttXmlSerializeBase.cpp \
$$PWD/SttTestCtrl/SttArgcArgvParser.cpp \
$$PWD/SttTestCtrl/SttTestAppBase.cpp \
$$PWD/SttTestCtrl/SttTestCtrlCntrBase.cpp \
$$PWD/SttTestCtrl/SttTestCtrlCntrNative.cpp \
$$PWD/SttTestCtrl/SttTestCtrlCntrWin.cpp \
$$PWD/SttTestResourceMngr/RtDataMngr/SttGlobalRtDataMngr.cpp \
$$PWD/SttTestResourceMngr/RtDataMngr/SttMacroChannels.cpp \
$$PWD/SttTestResourceMngr/RtDataMngr/SttMacroChannelsAsync.cpp \
$$PWD/SttTestResourceMngr/SttTestResourceMngr.cpp \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_4U3I.cpp \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_6U6I.cpp \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_Async.cpp \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_Sync.cpp \
$$PWD/SttTestResourceMngr/TestResource/SttTestResourceBase.cpp \
$$PWD/SttTestSysGlobalPara.cpp \
$$PWD/TestClient/PpSttIotClient.cpp \
$$PWD/TestClient/SttAtsTestClient.cpp \
$$PWD/TestClient/SttTestClientBase.cpp \
$$PWD/XLangResource_Native.cpp \
$$PWD/XLangResource_Win.cpp 

HEADERS += \
$$PWD/SttSystemConfig/SttDevConfig.h \
$$PWD/SttSystemConfig/SttModule.h \
$$PWD/SttSystemConfig/SttModuleUse.h \
$$PWD/SttSystemConfig/SttSystemConfig.h \
$$PWD/SttSystemConfig/SttSystemConfigGlobal.h \
$$PWD/SttTest/Common/Abnormal/tmt_abnormal_test.h \
$$PWD/SttTest/Common/ActionTime/tmt_vol_inverse_time_test.h \
$$PWD/SttTest/Common/FAParasSet/tmt_fa_Paras_set.h \
$$PWD/SttTest/Common/Gradient/tmt_fault_gradient_test.h \
$$PWD/SttTest/Common/Impedance/tmt_cb_operate_test.h \
$$PWD/SttTest/Common/Impedance/tmt_distance_test.h \
$$PWD/SttTest/Common/Impedance/tmt_impedance_test.h \
$$PWD/SttTest/Common/Impedance/tmt_manuImped_test.h \
$$PWD/SttTest/Common/Impedance/tmt_reclose_acc_test.h \
$$PWD/SttTest/Common/LineVolt/tmt_linevolt_gradient_test.h \
$$PWD/SttTest/Common/LineVolt/tmt_linevolt_manu_test.h \
$$PWD/SttTest/Common/Power/tmt_power_manu_test.h \
$$PWD/SttTest/Common/SearchBase/tmt_complex_search.h \
$$PWD/SttTest/Common/SearchBase/tmt_search_base.h \
$$PWD/SttTest/Common/Sequence/tmt_sequence_gradient_test.h \
$$PWD/SttTest/Common/Sequence/tmt_sequence_manu_test.h \
$$PWD/SttTest/Common/Swing/tmt_swing_test.h \
$$PWD/SttTest/Common/tmt_adjust_sys_para_trans.h \
$$PWD/SttTest/Common/tmt_adjust_sys_parameter.h \
$$PWD/SttTest/Common/tmt_common_def.h \
$$PWD/SttTest/Common/tmt_gradient_test.h \
$$PWD/SttTest/Common/tmt_harm_test.h \
$$PWD/SttTest/Common/tmt_manu_test.h \
$$PWD/SttTest/Common/tmt_replay_test.h \
$$PWD/SttTest/Common/tmt_result_def.h \
$$PWD/SttTest/Common/tmt_short_time_over_test.h \
$$PWD/SttTest/Common/tmt_soe_test.h \
$$PWD/SttTest/Common/tmt_state_test.h \
$$PWD/SttTest/Common/tmt_system_config.h \
$$PWD/SttTest/Common/tmt_test_paras_head.h \
$$PWD/SttTest/PTU200L/tmt_pt_test.h \
$$PWD/SttTest/SttTestGlobaoConfig.h \
$$PWD/SttTestAppConfig/SttTestAppCfg.h \
$$PWD/SttTestAppConfig/SttTestAppConfigTool.h \
$$PWD/SttTestAppConfig/SttTestDeviceCfg.h \
$$PWD/SttTestBase/SttComplexCalApi.h \
$$PWD/SttTestBase/SttComplexp.h \
$$PWD/SttTestBase/SttDiffCurrCalculatTool.h \
$$PWD/SttTestBase/SttMacroXmlKeys.h \
$$PWD/SttTestBase/SttXmlSerialize.h \
$$PWD/SttTestBase/SttXmlSerializeBase.h \
$$PWD/SttTestCtrl/SttArgcArgvParser.h \
$$PWD/SttTestCtrl/SttTestAppBase.h \
$$PWD/SttTestCtrl/SttTestCtrlCntrBase.h \
$$PWD/SttTestCtrl/SttTestCtrlCntrNative.h \
$$PWD/SttTestCtrl/SttTestCtrlCntrWin.h \
$$PWD/SttTestResourceMngr/RtDataMngr/SttGlobalRtDataMngr.h \
$$PWD/SttTestResourceMngr/RtDataMngr/SttMacroChannels.h \
$$PWD/SttTestResourceMngr/RtDataMngr/SttMacroChannelsAsync.h \
$$PWD/SttTestResourceMngr/SttTestResourceMngr.h \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_4U3I.h \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_6U6I.h \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_Async.h \
$$PWD/SttTestResourceMngr/TestResource/SttTestResource_Sync.h \
$$PWD/SttTestResourceMngr/TestResource/SttTestResourceBase.h \
$$PWD/SttTestSysGlobalPara.h \
$$PWD/TestClient/PpSttIotClient.h \
$$PWD/TestClient/SttAtsTestClient.h \
$$PWD/TestClient/SttMacroTestInterface.h \
$$PWD/TestClient/SttTestClientBase.h \
$$PWD/XLangResource_Native.h \
$$PWD/XLangResource_Win.h \ 
    $$PWD/AtsLib/atslib.h \
    $$PWD/AtsLib/atslib_global.h

FORMS    += \


