
#include "stdafx.h"
#include "XLanguageResourceAts_SmartTest.h"

#ifdef _DEBUG
#undef THIS_FILE
static char THIS_FILE[]=__FILE__;
#define new DEBUG_NEW
#endif

/////////////////////////////////////////////////////////////////////////////
// CXLanguageResourceAts_AutoTest
const CString  CXLanguageResourceAts_SmartTest::g_strXLangRsAutoTestFile = _T("AutoTest");

CXLanguageResourceAts_SmartTest::CXLanguageResourceAts_SmartTest()
{
	m_pXLangRsExe = &m_oXLangRsAutoTest;    //20161015
	m_oXLangRsAutoTest.m_strID = g_strXLangRsAutoTestFile;  //20161015
	m_oXLangRsAutoTest.m_strName = g_strXLangRsAutoTestFile;   //20161015
}

CXLanguageResourceAts_SmartTest::~CXLanguageResourceAts_SmartTest()
{
	m_oXLangRsAutoTest.RemoveAll();
}

CXLangItem* CXLanguageResourceAts_SmartTest::rs_AddString(const CString &strID, CString *pstrString)
{
	CXLangItem *p = CXLanguage::AddString(strID, pstrString);

	m_oXLangRsAutoTest.AddTail(p);

	return p;
}


void CXLanguageResourceAts_SmartTest::InitLangRsByFile()
{
	CXLanguageResourceAtsBase::InitLangRsByFile();

	InitLangRsByFileEx(&m_oXLangRsAutoTest, g_strXLangRsAutoTestFile);
}

void CXLanguageResourceAts_SmartTest::RegisterLanguageResource()
{
	CXLanguageResourceAtsBase::RegisterLanguageResource();

	//rs_AddString(g_sLangID_Login, &g_sLangTxt_Login);
	rs_AddString(g_sLangID_AutoTestVTip, &g_sLangTxt_AutoTestVTip);
// 	rs_AddString(g_sLangID_FileOpen, &g_sLangTxt_FileOpen);
	rs_AddString(g_sLangID_FileOpenTip, &g_sLangTxt_FileOpenTip);
	rs_AddString(g_sLangID_Quit, &g_sLangTxt_Quit);
	rs_AddString(g_sLangID_QuitTip, &g_sLangTxt_QuitTip);
	rs_AddString(g_sLangID_RibbonRecentDocs, &g_sLangTxt_RibbonRecentDocs);
	rs_AddString(g_sLangID_Config, &g_sLangTxt_Config);
	rs_AddString(g_sLangID_AutoTestOper, &g_sLangTxt_AutoTestOper);
// 	rs_AddString(g_sLangID_UpLoad, &g_sLangTxt_UpLoad);
// 	rs_AddString(g_sLangID_DownLoad, &g_sLangTxt_DownLoad);
	rs_AddString(g_sLangID_NewTest, &g_sLangTxt_NewTest);
	rs_AddString(g_sLangID_MultiDevTest, &g_sLangTxt_MultiDevTest);
	rs_AddString(g_sLangID_SinDevMulPro, &g_sLangTxt_SinDevMulPro);
	rs_AddString(g_sLangID_SubTempTest, &g_sLangTxt_SubTempTest);
	rs_AddString(g_sLangID_SingleDevTest, &g_sLangTxt_SingleDevTest);
	rs_AddString(g_sLangID_Test, &g_sLangTxt_Test);
	rs_AddString(g_sLangID_StartTest, &g_sLangTxt_StartTest);
	rs_AddString(g_sLangID_StartReport, &g_sLangTxt_StartReport);
	rs_AddString(g_sLangID_Stop, &g_sLangTxt_Stop);
	rs_AddString(g_sLangID_Report, &g_sLangTxt_Report);
	rs_AddString(g_sLangID_ShowScale, &g_sLangTxt_ShowScale);
	rs_AddString(g_sLangID_AdReport, &g_sLangTxt_AdReport);
	rs_AddString(g_sLangID_PrintReport, &g_sLangTxt_PrintReport);
    rs_AddString(g_sLangID_Settings, &g_sLangTxt_Settings);
	rs_AddString(g_sLangID_ReConfig, &g_sLangTxt_ReConfig);
// 	rs_AddString(g_sLangID_View, &g_sLangTxt_View);
// 	rs_AddString(g_sLangID_StatusBarTip, &g_sLangTxt_StatusBarTip);
	rs_AddString(g_sLangID_OutpWind, &g_sLangTxt_OutpWind);
	rs_AddString(g_sLangID_FileManBar, &g_sLangTxt_FileManBar);
	rs_AddString(g_sLangID_TestInfBar, &g_sLangTxt_TestInfBar);
	rs_AddString(g_sLangID_TestTaskBar, &g_sLangTxt_TestTaskBar);
	rs_AddString(g_sLangID_CharCurTest, &g_sLangTxt_CharCurTest);
	rs_AddString(g_sLangID_ShowTestInf, &g_sLangTxt_ShowTestInf);
// 	rs_AddString(g_sLangID_AboutTip, &g_sLangTxt_AboutTip);
	rs_AddString(g_sLangID_ToAndCom, &g_sLangTxt_ToAndCom);
    rs_AddString(g_sLangID_SysTools, &g_sLangTxt_SysTools);
	rs_AddString(g_sLangID_SysCom, &g_sLangTxt_SysCom);
	rs_AddString(g_sLangID_TestFileMan, &g_sLangTxt_TestFileMan);
	rs_AddString(g_sLangID_TestItemField, &g_sLangTxt_TestItemField);
    rs_AddString(g_sLangID_ReportAdjSh, &g_sLangTxt_ReportAdjSh);
    rs_AddString(g_sLangID_TestChoPro, &g_sLangTxt_TestChoPro);
	rs_AddString(g_sLangID_TestInf, &g_sLangTxt_TestInf);
	rs_AddString(g_sLangID_TaskName, &g_sLangTxt_TaskName);
	rs_AddString(g_sLangID_TestType, &g_sLangTxt_TestType);
	rs_AddString(g_sLangID_ProSet, &g_sLangTxt_ProSet);
	rs_AddString(g_sLangID_PoFile, &g_sLangTxt_PoFile);
	rs_AddString(g_sLangID_ChoTest, &g_sLangTxt_ChoTest);
	rs_AddString(g_sLangID_SelPoFile, &g_sLangTxt_SelPoFile);
	rs_AddString(g_sLangID_TitleTask, &g_sLangTxt_TitleTask);
	rs_AddString(g_sLangID_NewTestWork, &g_sLangTxt_NewTestWork);
	rs_AddString(g_sLangID_NewBuilt, &g_sLangTxt_NewBuilt);
	rs_AddString(g_sLangID_TestFileName, &g_sLangTxt_TestFileName);
	rs_AddString(g_sLangID_TesTyp, &g_sLangTxt_TesTyp);
	rs_AddString(g_sLangID_ProTypeCho, &g_sLangTxt_ProTypeCho);
	rs_AddString(g_sLangID_TestTempFile, &g_sLangTxt_TestTempFile);
	rs_AddString(g_sLangID_ProTempFile, &g_sLangTxt_ProTempFile);
	rs_AddString(g_sLangID_ProHighSet, &g_sLangTxt_ProHighSet);
	rs_AddString(g_sLangID_ProTabFile, &g_sLangTxt_ProTabFile);
	rs_AddString(g_sLangID_AppTestNo, &g_sLangTxt_AppTestNo);
	rs_AddString(g_sLangID_CTestCNum, &g_sLangTxt_CTestCNum);
	rs_AddString(g_sLangID_CoeMus, &g_sLangTxt_CoeMus);
	rs_AddString(g_sLangID_AlarmMode, &g_sLangTxt_AlarmMode);
	rs_AddString(g_sLangID_ContTest, &g_sLangTxt_ContTest);
	rs_AddString(g_sLangID_LongAlarm, &g_sLangTxt_LongAlarm);
	rs_AddString(g_sLangID_ShortAlarm, &g_sLangTxt_ShortAlarm);
	rs_AddString(g_sLangID_CusRepeat, &g_sLangTxt_CusRepeat);
	rs_AddString(g_sLangID_ComFaReNu, &g_sLangTxt_ComFaReNu);
	rs_AddString(g_sLangID_RetComS, &g_sLangTxt_RetComS);
	rs_AddString(g_sLangID_TestCoDe, &g_sLangTxt_TestCoDe);
	rs_AddString(g_sLangID_CoNuShow, &g_sLangTxt_CoNuShow);
	rs_AddString(g_sLangID_TestCoRe, &g_sLangTxt_TestCoRe);
    rs_AddString(g_sLangID_ChoProTem, &g_sLangTxt_ChoProTem);
// 	rs_AddString(g_sLangID_AdjustReport, &g_sLangTxt_AdjustReport);
	rs_AddString(g_sLangID_DeNoChTe, &g_sLangTxt_DeNoChTe);
	rs_AddString(g_sLangID_RepUse, &g_sLangTxt_RepUse);
	rs_AddString(g_sLangID_AdjustSure, &g_sLangTxt_AdjustSure);
	rs_AddString(g_sLangID_AutoTestSysSet, &g_sLangTxt_AutoTestSysSet);
	rs_AddString(g_sLangID_AlarmAutoMain, &g_sLangTxt_AlarmAutoMain);
	rs_AddString(g_sLangID_StartX, &g_sLangTxt_StartX);
	rs_AddString(g_sLangID_StartY, &g_sLangTxt_StartY);
	rs_AddString(g_sLangID_NowX, &g_sLangTxt_NowX);
	rs_AddString(g_sLangID_NowY, &g_sLangTxt_NowY);
	rs_AddString(g_sLangID_EndPointX, &g_sLangTxt_EndPointX);
	rs_AddString(g_sLangID_EndPointY, &g_sLangTxt_EndPointY);
	rs_AddString(g_sLangID_TestConR, &g_sLangTxt_TestConR);
	rs_AddString(g_sLangID_WarningProTest, &g_sLangTxt_WarningProTest);
	rs_AddString(g_sLangID_StopProcess, &g_sLangTxt_StopProcess);
	rs_AddString(g_sLangID_NeedCloPro, &g_sLangTxt_NeedCloPro);
	rs_AddString(g_sLangID_SouRepPath, &g_sLangTxt_SouRepPath);
	rs_AddString(g_sLangID_ExportSet, &g_sLangTxt_ExportSet);
	rs_AddString(g_sLangID_ExportPath, &g_sLangTxt_ExportPath);
	rs_AddString(g_sLangID_ExFileName, &g_sLangTxt_ExFileName);	
	rs_AddString(g_sLangID_ChoFileModel, &g_sLangTxt_ChoFileModel);	
	rs_AddString(g_sLangID_RepViewRat, &g_sLangTxt_RepViewRat);
	rs_AddString(g_sLangID_RepViRaCho, &g_sLangTxt_RepViRaCho);
	rs_AddString(g_sLangID_TestRepViRaSet, &g_sLangTxt_TestRepViRaSet);
	rs_AddString(g_sLangID_UnquaItem, &g_sLangTxt_UnquaItem);
	rs_AddString(g_sLangID_NoChProTem, &g_sLangTxt_NoChProTem);
	rs_AddString(g_sLangID_NoChTestTem, &g_sLangTxt_NoChTestTem);
	rs_AddString(g_sLangID_ChTemplet, &g_sLangTxt_ChTemplet);
	rs_AddString(g_sLangID_ChProtocol, &g_sLangTxt_ChProtocol);
	rs_AddString(g_sLangID_SettingsChoose, &g_sLangTxt_SettingsChoose);
	rs_AddString(g_sLangID_SetMulDev, &g_sLangTxt_SetMulDev);
	rs_AddString(g_sLangID_NoChTemFile, &g_sLangTxt_NoChTemFile);
	rs_AddString(g_sLangID_RepFileNameNu, &g_sLangTxt_RepFileNameNu);
	rs_AddString(g_sLangID_NoChTestType, &g_sLangTxt_NoChTestType);
	rs_AddString(g_sLangID_CommSetInf, &g_sLangTxt_CommSetInf);
	rs_AddString(g_sLangID_TabFileNoSel, &g_sLangTxt_TabFileNoSel);
	rs_AddString(g_sLangID_AlreadyExists, &g_sLangTxt_AlreadyExists);
	rs_AddString(g_sLangID_ModelFile, &g_sLangTxt_ModelFile);
	rs_AddString(g_sLangID_NoAddDevTestRep, &g_sLangTxt_NoAddDevTestRep);
	rs_AddString(g_sLangID_OlAddOnRep, &g_sLangTxt_OlAddOnRep);
	rs_AddString(g_sLangID_ProtocoMatching, &g_sLangTxt_ProtocoMatching);
	rs_AddString(g_sLangID_ProtocoTemplate, &g_sLangTxt_ProtocoTemplate);
	rs_AddString(g_sLangID_ChRptRe, &g_sLangTxt_ChRptRe);
	rs_AddString(g_sLangID_RptData, &g_sLangTxt_RptData);
	rs_AddString(g_sLangID_RptData2, &g_sLangTxt_RptData2);
	rs_AddString(g_sLangID_AlOpen, &g_sLangTxt_AlOpen);
	rs_AddString(g_sLangID_TestTemp, &g_sLangTxt_TestTemp);
    rs_AddString(g_sLangID_TaskTotalTime, &g_sLangTxt_TaskTotalTime);
	rs_AddString(g_sLangID_RptTotalTime, &g_sLangTxt_RptTotalTime);
	rs_AddString(g_sLangID_TestingClose, &g_sLangTxt_TestingClose);
	rs_AddString(g_sLangID_FileUnExistS, &g_sLangTxt_FileUnExistS);
	rs_AddString(g_sLangID_SelOrCretFile, &g_sLangTxt_SelOrCretFile);
	rs_AddString(g_sLangID_SelFilePath, &g_sLangTxt_SelFilePath);
	rs_AddString(g_sLangID_DelTaskYOrN, &g_sLangTxt_DelTaskYOrN);
	rs_AddString(g_sLangID_SureDelAgain, &g_sLangTxt_SureDelAgain);
	rs_AddString(g_sLangID_DelFailItem, &g_sLangTxt_DelFailItem);
	rs_AddString(g_sLangID_DelItemYOrN, &g_sLangTxt_DelItemYOrN);
	rs_AddString(g_sLangID_DelFailure, &g_sLangTxt_DelFailure);
	rs_AddString(g_sLangID_StartRptYOrN, &g_sLangTxt_StartRptYOrN);
	rs_AddString(g_sLangID_NewTestClear, &g_sLangTxt_NewTestClear);
	rs_AddString(g_sLangID_SelYes, &g_sLangTxt_SelYes);
	rs_AddString(g_sLangID_SelNo, &g_sLangTxt_SelNo);
	rs_AddString(g_sLangID_SelCancel, &g_sLangTxt_SelCancel);
	rs_AddString(g_sLangID_WavCpntNotExist, &g_sLangTxt_WavCpntNotExist);
	rs_AddString(g_sLangID_UnAutoTest, &g_sLangTxt_UnAutoTest);
	rs_AddString(g_sLangID_ToolUnExitS, &g_sLangTxt_ToolUnExitS);
	rs_AddString(g_sLangID_TestTaskFnshS, &g_sLangTxt_TestTaskFnshS);
	rs_AddString(g_sLangID_StartTestS, &g_sLangTxt_StartTestS);
	rs_AddString(g_sLangID_TestTempS, &g_sLangTxt_TestTempS);
	rs_AddString(g_sLangID_ReportFileS, &g_sLangTxt_ReportFileS);
	rs_AddString(g_sLangID_ModelFileS, &g_sLangTxt_ModelFileS);
	rs_AddString(g_sLangID_PrtcTemS, &g_sLangTxt_PrtcTemS);
	rs_AddString(g_sLangID_AutoTestContrl, &g_sLangTxt_AutoTestContrl);
	rs_AddString(g_sLangID_SGroupS, &g_sLangTxt_SGroupS);
	rs_AddString(g_sLangID_RightBuy, &g_sLangTxt_RightBuy);
    rs_AddString(g_sLangID_MainView2, &g_sLangTxt_MainView2);
    rs_AddString(g_sLangID_GroupReport, &g_sLangTxt_GroupReport);
	rs_AddString(g_sLangID_ProcessStop, &g_sLangTxt_ProcessStop);
    rs_AddString(g_sLangID_SelObjPath, &g_sLangTxt_SelObjPath);
	rs_AddString(g_sLangID_FileNameIncl, &g_sLangTxt_FileNameIncl);
	rs_AddString(g_sLangID_ReportEptFinsh, &g_sLangTxt_ReportEptFinsh);
	rs_AddString(g_sLangID_ReportTestTempt, &g_sLangTxt_ReportTestTempt);
	rs_AddString(g_sLangID_SureToDele, &g_sLangTxt_SureToDele);
	rs_AddString(g_sLangID_UnQualifadS, &g_sLangTxt_UnQualifadS);
	rs_AddString(g_sLangID_TestOver, &g_sLangTxt_TestOver);
	rs_AddString(g_sLangID_CopyOutput, &g_sLangTxt_CopyOutput);
	rs_AddString(g_sLangID_ClearOutput, &g_sLangTxt_ClearOutput);
// 	rs_AddString(g_sLangID_Unqualified2, &g_sLangTxt_Unqualified2);
	rs_AddString(g_sLangID_NoAddTestRpt, &g_sLangTxt_NoAddTestRpt);
	rs_AddString(g_sLangID_OneTestRpt, &g_sLangTxt_OneTestRpt);
	rs_AddString(g_sLangID_NoSelPrtcTem, &g_sLangTxt_NoSelPrtcTem);
	rs_AddString(g_sLangID_NoSelFile, &g_sLangTxt_NoSelFile);
	rs_AddString(g_sLangID_NameSame, &g_sLangTxt_NameSame);
	rs_AddString(g_sLangID_PrtcSame, &g_sLangTxt_PrtcSame);
	rs_AddString(g_sLangID_IPSame, &g_sLangTxt_IPSame);
	rs_AddString(g_sLangID_ObjFileExistOvwt, &g_sLangTxt_ObjFileExistOvwt);
	rs_AddString(g_sLangID_ToolTip_32781, &g_sLangTxt_ToolTip_32781);
	rs_AddString(g_sLangID_ToolTip_32782, &g_sLangTxt_ToolTip_32782);
	rs_AddString(g_sLangID_ToolTip_32783, &g_sLangTxt_ToolTip_32783);
	rs_AddString(g_sLangID_ToolTip_32784, &g_sLangTxt_ToolTip_32784);
	rs_AddString(g_sLangID_ToolTip_32775, &g_sLangTxt_ToolTip_32775);
	rs_AddString(g_sLangID_ToolTip_32776, &g_sLangTxt_ToolTip_32776);
	rs_AddString(g_sLangID_ToolTip_32777, &g_sLangTxt_ToolTip_32777);
	rs_AddString(g_sLangID_ToolTip_32778, &g_sLangTxt_ToolTip_32778);
	rs_AddString(g_sLangID_ToolTip_32779, &g_sLangTxt_ToolTip_32779);


	rs_AddString(g_sLangID_Menu_57634,&g_sLangTxt_Menu_57634);
	rs_AddString(g_sLangID_Menu_57632,&g_sLangTxt_Menu_57632);

	rs_AddString(g_sLangID_ToolTip_32789,&g_sLangTxt_ToolTip_32789);
	rs_AddString(g_sLangID_StitchRptFinish,&g_sLangTxt_StitchRptFinish);

	//2016-12-10
	rs_AddString(g_sLangID_ToolTip_2000,&g_sLangTxt_ToolTip_2000);
	rs_AddString(g_sLangID_ToolTip_32786,&g_sLangTxt_ToolTip_32786);
	rs_AddString(g_sLangID_ToolTip_32788,&g_sLangTxt_ToolTip_32788);
	rs_AddString(g_sLangID_ToolTip_2001,&g_sLangTxt_ToolTip_2001);
	rs_AddString(g_sLangID_ToolTip_32785,&g_sLangTxt_ToolTip_32785);
	rs_AddString(g_sLangID_ToolTip_351,&g_sLangTxt_ToolTip_351);
	rs_AddString(g_sLangID_ToolTip_314,&g_sLangTxt_ToolTip_314);
	rs_AddString(g_sLangID_ToolTip_320,&g_sLangTxt_ToolTip_320);
	rs_AddString(g_sLangID_ToolTip_330,&g_sLangTxt_ToolTip_330);
	rs_AddString(g_sLangID_ToolTip_358,&g_sLangTxt_ToolTip_358);
	rs_AddString(g_sLangID_ToolTip_347,&g_sLangTxt_ToolTip_347);
	rs_AddString(g_sLangID_ToolTip_310,&g_sLangTxt_ToolTip_310);
	rs_AddString(g_sLangID_ToolTip_348,&g_sLangTxt_ToolTip_348);
	rs_AddString(g_sLangID_ToolTip_349,&g_sLangTxt_ToolTip_349);
	rs_AddString(g_sLangID_ToolTip_350,&g_sLangTxt_ToolTip_350);
	rs_AddString(g_sLangID_ToolTip_357,&g_sLangTxt_ToolTip_357);
}

CString CXLanguageResourceAts_SmartTest::g_sLangID_Login                    = _T("sLogin");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_Login                   = _T("登录");
CString CXLanguageResourceAts_SmartTest::g_sLangID_AutoTestVTip             = _T("sAutoTestVTip");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_AutoTestVTip            = _T("智能自动测试系统V1.0");
// CString CXLanguageResourceAts_AutoTest::g_sLangID_FileOpen                 = _T("sFileOpen");
// CString CXLanguageResourceAts_AutoTest::g_sLangTxt_FileOpen                = _T("打开（&O）");
CString CXLanguageResourceAts_SmartTest::g_sLangID_FileOpenTip              = _T("sFileOpenTip");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_FileOpenTip             = _T("打开现有文档\n打开");
CString CXLanguageResourceAts_SmartTest::g_sLangID_Quit                     = _T("sQuit");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_Quit                    = _T("退出");
CString CXLanguageResourceAts_SmartTest::g_sLangID_QuitTip                  = _T("sQuitTip");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_QuitTip                 = _T("退出应用程序；提示保存文档\n退出");
CString CXLanguageResourceAts_SmartTest::g_sLangID_RibbonRecentDocs         = _T("sRibbonRecentDocs");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_RibbonRecentDocs        = _T("最近使用的文档");
CString CXLanguageResourceAts_SmartTest::g_sLangID_Config                   = _T("sConfig");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_Config                  = _T("系统配置");
CString CXLanguageResourceAts_SmartTest::g_sLangID_AutoTestOper             = _T("sAutoTestOper");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_AutoTestOper            = _T("自动测试操作");
// CString CXLanguageResourceAts_AutoTest::g_sLangID_UpLoad                   = _T("sUpLoad");
// CString CXLanguageResourceAts_AutoTest::g_sLangTxt_UpLoad                  = _T("上传");
// CString CXLanguageResourceAts_AutoTest::g_sLangID_DownLoad                 = _T("sDownLoad");
// CString CXLanguageResourceAts_AutoTest::g_sLangTxt_DownLoad                = _T("下载");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NewTest                  = _T("sNewTest");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NewTest                 = _T("新建测试");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NewTestWork              = _T("sNewTestWork");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NewTestWork             = _T("新建测试任务");
CString CXLanguageResourceAts_SmartTest::g_sLangID_MultiDevTest             = _T("sMultiDevTest");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_MultiDevTest            = _T("多装置测试");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SinDevMulPro             = _T("sSinDevMulPro");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SinDevMulPro            = _T("单装置多规约");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SubTempTest              = _T("sSubTempTest");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SubTempTest             = _T("子模板测试");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SingleDevTest            = _T("sSingleDevTest");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SingleDevTest           = _T("单装置测试");
CString CXLanguageResourceAts_SmartTest::g_sLangID_Test                     = _T("sTest");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_Test                    = _T("测试");
CString CXLanguageResourceAts_SmartTest::g_sLangID_StartTest                = _T("sStartTest");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_StartTest               = _T("开始测试");
CString CXLanguageResourceAts_SmartTest::g_sLangID_StartReport              = _T("sStartReport");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_StartReport             = _T("开始报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_Stop                     = _T("sStop");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_Stop                    = _T("停止");
CString CXLanguageResourceAts_SmartTest::g_sLangID_Report                   = _T("sReport");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_Report                  = _T("报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ShowScale                = _T("sShowScale");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ShowScale               = _T("显示比例");
CString CXLanguageResourceAts_SmartTest::g_sLangID_AdReport                 = _T("sAdReport");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_AdReport                = _T("调整报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_PrintReport              = _T("sPrintReport");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_PrintReport             = _T("打印报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_Settings                 = _T("sSettings");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_Settings                = _T("配置");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ReConfig                 = _T("sReConfig");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ReConfig                = _T("录波配置");
// CString CXLanguageResourceAts_AutoTest::g_sLangID_View                     = _T("sView");
// CString CXLanguageResourceAts_AutoTest::g_sLangTxt_View                    = _T("视图");
// CString CXLanguageResourceAts_AutoTest::g_sLangID_StatusBarTip             = _T("sStatusBarTip");
// CString CXLanguageResourceAts_AutoTest::g_sLangTxt_StatusBarTip            = _T("显示或隐藏状态栏\n切换状态栏");
CString CXLanguageResourceAts_SmartTest::g_sLangID_OutpWind                 = _T("sOutpWind");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_OutpWind                = _T("输出窗口");
CString CXLanguageResourceAts_SmartTest::g_sLangID_FileManBar               = _T("sFileManBar");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_FileManBar              = _T("文件管理栏");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestInfBar               = _T("sTestInfBar");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestInfBar              = _T("测试信息栏");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestTaskBar              = _T("sTestTaskBar");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestTaskBar             = _T("测试任务栏");
CString CXLanguageResourceAts_SmartTest::g_sLangID_CharCurTest              = _T("sCharCurTest");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_CharCurTest             = _T("特性曲线测试");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ShowTestInf              = _T("sShowTestInf");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ShowTestInf             = _T("显示测试信息");
// CString CXLanguageResourceAts_AutoTest::g_sLangID_AboutTip                 = _T("sAboutTip");
// CString CXLanguageResourceAts_AutoTest::g_sLangTxt_AboutTip                = _T("显示程序信息、版本号和版权\n关于");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToAndCom                 = _T("sToAndCom");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToAndCom                = _T("工具和命令");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SysTools                 = _T("sSysTools");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SysTools                = _T("系统工具");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SysCom                   = _T("sSysCom");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SysCom                  = _T("系统命令");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestFileMan              = _T("sTestFileMan");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestFileMan             = _T("测试文件管理");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestItemField            = _T("sTestItemField");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestItemField           = _T("测试项目栏");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ReportAdjSh              = _T("sReportAdjSh");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ReportAdjSh             = _T("报告调整提示");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestChoPro               = _T("sTestChoPro");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestChoPro              = _T("测试仪选择（测试仪器选择改变，需重新启动自动测试程序才能是改变生效）");
CString CXLanguageResourceAts_SmartTest::g_sLangID_AutoTestSysSet           = _T("sAutoTestSysSet");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_AutoTestSysSet          = _T("自动测试系统配置");
CString CXLanguageResourceAts_SmartTest::g_sLangID_AlarmAutoMain            = _T("sAlarmAutoMain");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_AlarmAutoMain           = _T("警告—自动测试主程序");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestInf            = _T("sTestInf");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestInf           = _T("实验信息");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TaskName           = _T("sTaskName");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TaskName          = _T("任务名称");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestType           = _T("sTestType");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestType          = _T("实验类型");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ProSet             = _T("sProSet");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ProSet            = _T("规约设置");
CString CXLanguageResourceAts_SmartTest::g_sLangID_PoFile             = _T("sPoFile");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_PoFile            = _T("点表文件");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ChoTest            = _T("sChoTest");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ChoTest           = _T("选择测试模板");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ChoProTem          = _T("sChoProTem");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ChoProTem         = _T("选择规约模板");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SelPoFile          = _T("sSelPoFile");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SelPoFile         = _T("选择点表文件");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TitleTask          = _T("sTitleTask");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TitleTask         = _T("测试任务");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NewBuilt                 = _T("sNewBuilt");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NewBuilt                = _T("新建");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestFileName             = _T("sTestFileName");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestFileName            = _T("测试文件名");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TesTyp                   = _T("sTesTyp");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TesTyp                  = _T("测试类型");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ProTypeCho               = _T("sProTypeCho");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ProTypeCho              = _T("规约种类选择");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestTempFile             = _T("sTestTempFile");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestTempFile            = _T("测试模板文件");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ProTempFile              = _T("sProTempFile");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ProTempFile             = _T("规约模板文件");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ProHighSet               = _T("sProHighSet");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ProHighSet              = _T("规约高级设置");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ProTabFile               = _T("sProTabFile");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ProTabFile              = _T("规约点表文件");
CString CXLanguageResourceAts_SmartTest::g_sLangID_RptData                  = _T("sRptData");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_RptData                 = _T("报告数据");
CString CXLanguageResourceAts_SmartTest::g_sLangID_RptData2                 = _T("sRptData2");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_RptData2                = _T("报告数据2");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestTemp                 = _T("sTestTemp");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestTemp                = _T("测试模板");
CString CXLanguageResourceAts_SmartTest::g_sLangID_AppTestNo                = _T("sAppTestNo");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_AppTestNo               = _T("出现测试不合格项目处理");
CString CXLanguageResourceAts_SmartTest::g_sLangID_CTestCNum                = _T("sCTestCNum");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_CTestCNum               = _T("重复测试项目重复次数");
CString CXLanguageResourceAts_SmartTest::g_sLangID_CoeMus                   = _T("sCoeMus");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_CoeMus                  = _T("提示音乐");
CString CXLanguageResourceAts_SmartTest::g_sLangID_AlarmMode                = _T("sAlarmMode");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_AlarmMode               = _T("告警方式");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ContTest                 = _T("sContTest");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ContTest                = _T("继续测试");
CString CXLanguageResourceAts_SmartTest::g_sLangID_LongAlarm                = _T("sLongAlarm");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_LongAlarm               = _T("长警告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ShortAlarm               = _T("sShortAlarm");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ShortAlarm              = _T("短警告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_CusRepeat                = _T("sCusRepeat");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_CusRepeat               = _T("自定义最大重复次数");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ComFaReNu                = _T("sComFaReNu");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ComFaReNu               = _T("通讯失败后重试次数");
CString CXLanguageResourceAts_SmartTest::g_sLangID_RetComS                  = _T("sRetComS");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_RetComS                 = _T("重试通讯前延时");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestCoDe                 = _T("sTestCoDe");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestCoDe                = _T("测试项目测试完成出来");
CString CXLanguageResourceAts_SmartTest::g_sLangID_CoNuShow                 = _T("sCoNuShow");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_CoNuShow                = _T("完成一级项目时进行提示");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestCoRe                 = _T("sTestCoRe");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestCoRe                = _T("测试完成，报告自动导出路径（测试模板须调用SetUploadRptFile设置导出报告文件名）");
// CString CXLanguageResourceAts_AutoTest::g_sLangID_AdjustReport             = _T("sAdjustReport");
// CString CXLanguageResourceAts_AutoTest::g_sLangTxt_AdjustReport            = _T("调整报告完成如下操作");
CString CXLanguageResourceAts_SmartTest::g_sLangID_DeNoChTe                 = _T("sDeNoChTe");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_DeNoChTe                = _T("1.删除没有选择测试的项目分类报告部分");
CString CXLanguageResourceAts_SmartTest::g_sLangID_RepUse                   = _T("sRepUse");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_RepUse                  = _T("2.对于没有测试的测试点，空白部分报告使用“——”替换");
CString CXLanguageResourceAts_SmartTest::g_sLangID_AdjustSure               = _T("sAdjustSure");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_AdjustSure              = _T("调整部分不可以回复，确定要调整吗？");
CString CXLanguageResourceAts_SmartTest::g_sLangID_StartX               = _T("sStartX");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_StartX              = _T("起点X");
CString CXLanguageResourceAts_SmartTest::g_sLangID_StartY               = _T("sStartY");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_StartY              = _T("起点Y");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NowX                 = _T("sNowX");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NowX                = _T("当前X");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NowY                 = _T("sNowY");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NowY                = _T("当前Y");
CString CXLanguageResourceAts_SmartTest::g_sLangID_EndPointX            = _T("sEndPointX");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_EndPointX           = _T("终点X");
CString CXLanguageResourceAts_SmartTest::g_sLangID_EndPointY            = _T("sEndPointY");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_EndPointY           = _T("终点Y");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestConR             = _T("sTestConR");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestConR            = _T("与测试仪控制接口程序握手，30s内握手失败，则终止进程，重新启动测试仪接口程序");
CString CXLanguageResourceAts_SmartTest::g_sLangID_WarningProTest       = _T("sWarningProTest");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_WarningProTest      = _T("程序检测到系统中有和系统相关的进程正在运行，点击“终止进程”关闭所有进程");
CString CXLanguageResourceAts_SmartTest::g_sLangID_StopProcess          = _T("sStopProcess");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_StopProcess         = _T("终止进程");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NeedCloPro           = _T("sNeedCloPro");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NeedCloPro          = _T("需要关闭的进程");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SouRepPath           = _T("sSouRepPath");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SouRepPath          = _T("源报告路径");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ExportSet            = _T("sExportSet");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ExportSet           = _T("导出设置");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ExportPath           = _T("sExportPath");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ExportPath          = _T("导出路径");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ExFileName           = _T("sExFileName");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ExFileName          = _T("导出文件名称");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ChoFileModel         = _T("sChoFileModel");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ChoFileModel        = _T("选择文件模型");
CString CXLanguageResourceAts_SmartTest::g_sLangID_RepViewRat           = _T("sRepViewRat");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_RepViewRat          = _T("报告显示比例");
CString CXLanguageResourceAts_SmartTest::g_sLangID_RepViRaCho           = _T("sRepViRaCho");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_RepViRaCho          = _T("报告显示比例选择");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestRepViRaSet       = _T("sTestRepViRaSet");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestRepViRaSet      = _T("试验报告显示比例设置");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NoChProTem          = _T("sNoChProTem");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NoChProTem         = _T("没有选择规约模板");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NoChTestTem         = _T("sNoChTestTem");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NoChTestTem        = _T("没有选择测试模板");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ChTemplet           = _T("sChTemplet");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ChTemplet          = _T("选择模板");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ChProtocol          = _T("sChProtocol");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ChProtocol         = _T("选择规约");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SettingsChoose      = _T("sSettingsChoose");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SettingsChoose     = _T("设置组选择");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SetMulDev           = _T("sSetMulDev");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SetMulDev          = _T("设置多装置");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NoChTemFile         = _T("sNoChTemFile");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NoChTemFile        = _T("没有选择模板文件");
CString CXLanguageResourceAts_SmartTest::g_sLangID_RepFileNameNu       = _T("sRepFileNameNu");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_RepFileNameNu      = _T("报告文件名为空");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NoChTestType        = _T("sNoChTestType");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NoChTestType       = _T("没有选择测试类型");
CString CXLanguageResourceAts_SmartTest::g_sLangID_CommSetInf          = _T("sCommSetInf");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_CommSetInf         = _T("通讯设置信息不全");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TabFileNoSel        = _T("sTabFileNoSel");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TabFileNoSel       = _T("点表文件没有选择");
CString CXLanguageResourceAts_SmartTest::g_sLangID_AlreadyExists       = _T("sAlreadyExists");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_AlreadyExists      = _T("%s 已经存在");
CString CXLanguageResourceAts_SmartTest::g_sLangID_UnquaItem           = _T("sUnquaItem");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_UnquaItem          = _T("不合格项目");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ModelFile           = _T("sModelFile");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ModelFile          = _T("模型文件");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NoAddDevTestRep     = _T("sNoAddDevTestRep");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NoAddDevTestRep    = _T("没有添加装置测试报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_OlAddOnRep          = _T("sOlAddOnRep");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_OlAddOnRep         = _T("只添加了一个装置测试报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ProtocoTemplate     = _T("sProtocoTemplate");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ProtocoTemplate    = _T("规约模板");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ProtocoMatching     = _T("sProtocoMatching");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ProtocoMatching    = _T("规约配型");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ChRptRe             = _T("sChRptRe");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ChRptRe            = _T("选择报告导出目标目录");
CString CXLanguageResourceAts_SmartTest::g_sLangID_AlOpen              = _T("sAlOpen");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_AlOpen             = _T("已经打开【%s】，请关闭后在创建测试报告！");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TaskTotalTime           = _T("sTaskTotalTime");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TaskTotalTime          = _T("任务总时间");
CString CXLanguageResourceAts_SmartTest::g_sLangID_RptTotalTime           = _T("sRptTotalTime");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_RptTotalTime          = _T("报告总时间");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestingClose           = _T("sTestingClose");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestingClose          = _T("正在测试中，不能关闭...");
CString CXLanguageResourceAts_SmartTest::g_sLangID_FileUnExistS           = _T("sFileUnExistS");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_FileUnExistS          = _T("文件\"%s\"不存在");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SelOrCretFile           = _T("sSelOrCretFile");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SelOrCretFile          = _T("文件夹【%s】包含有测试报告文件\n请选择或者创建一个空的文件夹");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SelFilePath           = _T("sSelFilePath");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SelFilePath          = _T("请选择报告文件存储的路径！");
CString CXLanguageResourceAts_SmartTest::g_sLangID_DelTaskYOrN           = _T("sDelTaskYOrN");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_DelTaskYOrN          = _T("是否要删除任务 %s 及其子项");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SureDelAgain           = _T("sSureDelAgain");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SureDelAgain          = _T("请再次确定删除");
CString CXLanguageResourceAts_SmartTest::g_sLangID_DelFailItem           = _T("sDelFailItem");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_DelFailItem          = _T("删除的任务中包含已经被打开的工程，删除失败");
CString CXLanguageResourceAts_SmartTest::g_sLangID_DelItemYOrN           = _T("sDelItemYOrN");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_DelItemYOrN          = _T("是否要删除工程 %s");
CString CXLanguageResourceAts_SmartTest::g_sLangID_DelFailure           = _T("sDelFailure");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_DelFailure          = _T("该工程已经被打开，删除失败");
CString CXLanguageResourceAts_SmartTest::g_sLangID_StartRptYOrN           = _T("sStartRptYOrN");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_StartRptYOrN          = _T("“开始报告”功能只测试当前打开的测试报告，\r\n你确实只要测试测试任务中的单个测试报告吗？\r\n\r\n选择“是”测试单个报告\r\n选择“否”开始任务测试\r\n选择“取消”终止操作");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NewTestClear           = _T("sNewTestClear");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NewTestClear          = _T("新建测试，清除当前报告数据吗？\r\n");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SelYes           = _T("sSelYes");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SelYes          = _T("选择“是”清除当前报告数据，新建测试\r\n");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SelNo           = _T("sSelNo");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SelNo          = _T("选择“否”，不清除当前报告数据，新建测试\r\n");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SelCancel           = _T("sSelCancel");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SelCancel          = _T("选择“取消”，不开始测试");
CString CXLanguageResourceAts_SmartTest::g_sLangID_WavCpntNotExist           = _T("sWavCpntNotExist");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_WavCpntNotExist          = _T("录波组件不存在");
CString CXLanguageResourceAts_SmartTest::g_sLangID_UnAutoTest           = _T("sUnAutoTest");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_UnAutoTest          = _T("没有启动自动测试，无法执行命令");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolUnExitS           = _T("sToolUnExitS ");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolUnExitS           = _T("工具【%s】【%s】不存在");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestTaskFnshS           = _T("sTestTaskFnshS");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestTaskFnshS          = _T("测试任务【%s】测试完成");
CString CXLanguageResourceAts_SmartTest::g_sLangID_StartTestS           = _T("sStartTestS");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_StartTestS          = _T("开始测试【%s】");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestTempS           = _T("sTestTempS");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestTempS          = _T("测试模板*******%s");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ReportFileS           = _T("sReportFileS ");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ReportFileS           = _T("报告文件*******%s");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ModelFileS           = _T("sModelFileS");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ModelFileS         = _T("模型文件********%s");
CString CXLanguageResourceAts_SmartTest::g_sLangID_PrtcTemS           = _T("sPrtcTemS");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_PrtcTemS          = _T("规约模板********%s");
CString CXLanguageResourceAts_SmartTest::g_sLangID_AutoTestContrl           = _T("sAutoTestContrl");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_AutoTestContrl          = _T("自动测试控制中心");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SGroupS           = _T("sSGroupS");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SGroupS          = _T("%s%s-组%d.%s");
CString CXLanguageResourceAts_SmartTest::g_sLangID_RightBuy           = _T("sRightBuy");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_RightBuy           = _T("Demo版本，只能使用模板【Demo-PSL-641U】，请购买正式版本！");
CString CXLanguageResourceAts_SmartTest::g_sLangID_MainView2           = _T("sMainView2");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_MainView2          = _T("主视图:");
CString CXLanguageResourceAts_SmartTest::g_sLangID_GroupReport           = _T("sGroupReport");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_GroupReport          = _T("组%d报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ProcessStop           = _T("sProcessStop");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ProcessStop          = _T("和测试相关的进程已经被终止");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SelObjPath           = _T("sSelObjPath");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SelObjPath          = _T("选择目标路径");
CString CXLanguageResourceAts_SmartTest::g_sLangID_FileNameIncl           = _T("sFileNameIncl");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_FileNameIncl          = _T("文件名称包含非法字符: %s");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ReportEptFinsh           = _T("sReportEptFinsh");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ReportEptFinsh          = _T("报告导出完成");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ObjFileExistOvwt           = _T("sObjFileExistOvwt");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ObjFileExistOvwt          = _T("目标文件已经存在,覆盖吗?");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ReportTestTempt           = _T("sReportTestTempt");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ReportTestTempt          = _T("报告【%s】对应的测试模板:【%s】");
CString CXLanguageResourceAts_SmartTest::g_sLangID_SureToDele           = _T("sSureToDele");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_SureToDele          = _T("你确实要删除【%s】吗？");
CString CXLanguageResourceAts_SmartTest::g_sLangID_UnQualifadS           = _T("sUnQualifadS");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_UnQualifadS          = _T("[%s]不合格");
CString CXLanguageResourceAts_SmartTest::g_sLangID_TestOver           = _T("sTestOver");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_TestOver          = _T("********测试结束********");
CString CXLanguageResourceAts_SmartTest::g_sLangID_CopyOutput           = _T("sCopyOutput");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_CopyOutput          = _T("复制输出");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ClearOutput           = _T("sClearOutput");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ClearOutput          = _T("清除输出");
// CString CXLanguageResourceAts_AutoTest::g_sLangID_Unqualified2           = _T("sUnqualified2");
// CString CXLanguageResourceAts_AutoTest::g_sLangTxt_Unqualified2          = _T("%s[不合格]");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NoAddTestRpt           = _T("sNoAddTestRpt");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NoAddTestRpt          = _T("没有添加测试报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_OneTestRpt           = _T("sOneTestRpt");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_OneTestRpt          = _T("只添加了一个测试报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NoSelPrtcTem           = _T("sNoSelPrtcTem");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NoSelPrtcTem          = _T("装置报告列表第【%d】没有选择规约模板");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NoSelFile           = _T("sNoSelFile");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NoSelFile          = _T("装置报告列表第【%d】没有选择点表文件");
CString CXLanguageResourceAts_SmartTest::g_sLangID_NameSame           = _T("sNameSame");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_NameSame          = _T("装置报告列表第【%d】与第【%d】名称【%s】相同");
CString CXLanguageResourceAts_SmartTest::g_sLangID_PrtcSame           = _T("sPrtcSame");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_PrtcSame          = _T("装置报告列表第【%d】与第【%d】规约模板【%s】相同");
CString CXLanguageResourceAts_SmartTest::g_sLangID_IPSame           = _T("sIPSame");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_IPSame          = _T("装置报告列表第【%d】与第【%d】IP【%s】相同");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_32781           = _T("sToolTip_32781");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_32781          = _T("打开报告\n打开报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_32782           = _T("sToolTip_32782");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_32782          = _T("关闭任务\n关闭任务");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_32783           = _T("sToolTip_32783");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_32783          = _T("恢复到未完成的状态\n恢复到未完成的状态");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_32784           = _T("sToolTip_32784");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_32784          = _T("显示报告对应的模板\n显示报告对应的模板");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_32775           = _T("sToolTip_32775");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_32775          = _T("导出任务报告\n导出任务报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_32776           = _T("sToolTip_32776");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_32776          = _T("添加报告\n添加报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_32777           = _T("sToolTip_32777");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_32777          = _T("删除报告\n删除报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_32778           = _T("sToolTip_32778");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_32778          = _T("上移报告\n上移报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_32779           = _T("sToolTip_32779");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_32779          = _T("下移报告\n下移报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_Menu_57634 = _T("sMenu_57634");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_Menu_57634 = _T("复制(&C)");
CString CXLanguageResourceAts_SmartTest::g_sLangID_Menu_57632 = _T("sMenu_57632");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_Menu_57632 = _T("清除(&C)");

CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_32789 = _T("sToolTip_32789");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_32789 = _T("拼接任务报告\n拼接任务报告");

CString CXLanguageResourceAts_SmartTest::g_sLangID_StitchRptFinish = _T("sStitchRptFinish");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_StitchRptFinish = _T("拼接任务报告完成");


//2016-12-10
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_2000 = _T("sToolTip_2000");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_2000 = _T("新建测试任务\n测试任务");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_32786 = _T("sToolTip_32786");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_32786 = _T("新建多装置测试报告\n新建多装置测试");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_32788 = _T("sToolTip_32788");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_32788 = _T("新建单装置多规约测试\n新建单装置多规约测试");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_2001 = _T("sToolTip_2001");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_2001 = _T("新建子模板测试\n新建子模板测试");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_32785 = _T("sToolTip_32785");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_32785 = _T("新建报告\n新建报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_351 = _T("sToolTip_351");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_351 = _T("开始任务测试\n开始任务");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_314 = _T("sToolTip_314");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_314 = _T("开始报告\n开始报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_320 = _T("sToolTip_320");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_320 = _T("打印报告\n打印报告");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_330 = _T("sToolTip_330");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_330 = _T("系统配置\n系统配置");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_358 = _T("sToolTip_358");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_358 = _T("测试仪选择\n测试仪选择");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_347 = _T("sToolTip_347");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_347 = _T("录波配置\n录波配置");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_310 = _T("sToolTip_310");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_310 = _T("输出窗口\n输出窗口");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_348 = _T("sToolTip_348");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_348 = _T("文件管理栏\n文件管理栏");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_349 = _T("sToolTip_349");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_349 = _T("测试信息栏\n测试信息栏");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_350 = _T("sToolTip_350");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_350 = _T("测试任务栏\n测试任务栏");
CString CXLanguageResourceAts_SmartTest::g_sLangID_ToolTip_357 = _T("sToolTip_357");
CString CXLanguageResourceAts_SmartTest::g_sLangTxt_ToolTip_357 = _T("显示测试信息\n显示测试信息");

