// EpCmmGlobalDefine.h
//////////////////////////////////////////////////////////////////////

#if !defined(_EPCMMGLOBALDEFINE_H__)
#define _EPCMMGLOBALDEFINE_H__

#include "..\EpGlobalClassIDBaseDefine.h"

//通讯通道和配置
#define EPCLASSID_CMM_CONFIG_BASE            (EPCMMCLASSID_BASECLASS + 0X07000080)
#define EPCLASSID_CMM_TCP_CLIENT_CONFIG      (EPCMMCLASSID_BASECLASS + 0X07000081)
#define EPCLASSID_NET_CONFIG                 (EPCMMCLASSID_BASECLASS + 0X07000082)
#define EPCLASSID_CMM_TCP_SERVER_CONFIG      (EPCMMCLASSID_BASECLASS + 0X07000083)
#define EPCLASSID_DEVICE_CMM_CONFIG          (EPCMMCLASSID_BASECLASS + 0X07000084)
#define EPCLASSID_CMM_UDP_CONFIG             (EPCMMCLASSID_BASECLASS + 0X07000085)
#define EPCLASSID_CMM_UDP_SERVER_CONFIG      (EPCMMCLASSID_BASECLASS + 0X07000086)
#define EPCLASSID_CMM_SERIAL_CONFIG          (EPCMMCLASSID_BASECLASS + 0X07000087)

#define  EPCMMCLASSID_NETSERVER              (EPCMMCLASSID_EXLISTCLASS+ 0X07000088)
#define  EPCMMCLASSID_TCPSERVER	             (EPCMMCLASSID_EXLISTCLASS+ 0X07000089)
#define  EPCMMCLASSID_UDPSERVER              (EPCMMCLASSID_EXLISTCLASS+ 0X0700008A)
#define  EPCMMCLASSID_SERIAL_CHANNEL         (EPCMMCLASSID_EXLISTCLASS+ 0X0700008B)
#define  EPCMMCLASSID_TCP_SERVER_CHANNEL     (EPCMMCLASSID_EXLISTCLASS+ 0X0700008C)
#define  EPCMMCLASSID_TCP_CLIENT_CHANNEL     (EPCMMCLASSID_EXLISTCLASS+ 0X0700008D)
#define  EPCMMCLASSID_UDP_SERVER_CHANNEL     (EPCMMCLASSID_EXLISTCLASS+ 0X0700008E)
#define  EPCMMCLASSID_UDP_CLIENT_CHANNEL     (EPCMMCLASSID_EXLISTCLASS+ 0X0700008F)
#define  EPCMMCLASSID_DEVICE_CMM_CHANNEL     (EPCMMCLASSID_EXLISTCLASS+ 0X07000090)
#define  EPCMMCLASSID_TCP_SERVER_CLIENT_CHANNEL  (EPCMMCLASSID_EXLISTCLASS+ 0X07000091)

// static const CString NET_CMM_MODE_BROADCAST = _T("broadcast");  //广播方式
// static const CString NET_CMM_MODE_MULTICAST = _T("multicast");  //组播方式
// static const CString NET_CMM_MODE_TOPOINT   = _T("to-point");   //点对点方式



#define ID_NET_CMM_MODE_BROADCAST   0
#define ID_NET_CMM_MODE_MULTICAST   1
#define ID_NET_CMM_MODE_TOPOINT     2


#endif // !defined(_EPCMMGLOBALDEFINE_H__)
