#ifndef STTMULTIMACRODISTANCEPARASDEFINE_H
#define STTMULTIMACRODISTANCEPARASDEFINE_H
#include "../SttMultiMacroParasDefine.h"

#define STT_MULTI_MACRO_DISTANCE_PARAS_GRID_ID_ZPhi	        "DistanceZ-Phi"
#define STT_MULTI_MACRO_DISTANCE_PARAS_GRID_ID_RX	        "DistanceR-X"

#define IMPEDANCE_FAULT_TYPE_AN                                                 0//阻抗类的故障类型定义
#define IMPEDANCE_FAULT_TYPE_BN                                                 1
#define IMPEDANCE_FAULT_TYPE_CN                                                 2
#define IMPEDANCE_FAULT_TYPE_AB                                                 3
#define IMPEDANCE_FAULT_TYPE_BC                                                 4
#define IMPEDANCE_FAULT_TYPE_CA                                                 5
#define IMPEDANCE_FAULT_TYPE_ABN                                                6
#define IMPEDANCE_FAULT_TYPE_BCN                                                7
#define IMPEDANCE_FAULT_TYPE_CAN                                                8
#define IMPEDANCE_FAULT_TYPE_ABC                                                9
#define IMPEDANCE_FAULT_TYPE_ONE                                                10

//距离跟节点下,按故障类型进行分类创建文件夹
#define STT_MULTI_MACRO_DISTANCE_FaultType_Items_ID_AN         "FaultType_AN"
#define STT_MULTI_MACRO_DISTANCE_FaultType_Items_ID_BN         "FaultType_BN"
#define STT_MULTI_MACRO_DISTANCE_FaultType_Items_ID_CN         "FaultType_CN"
#define STT_MULTI_MACRO_DISTANCE_FaultType_Items_ID_AB         "FaultType_AB"
#define STT_MULTI_MACRO_DISTANCE_FaultType_Items_ID_BC         "FaultType_BC"
#define STT_MULTI_MACRO_DISTANCE_FaultType_Items_ID_CA         "FaultType_CA"
#define STT_MULTI_MACRO_DISTANCE_FaultType_Items_ID_ABN        "FaultType_ABN"
#define STT_MULTI_MACRO_DISTANCE_FaultType_Items_ID_BCN        "FaultType_BCN"
#define STT_MULTI_MACRO_DISTANCE_FaultType_Items_ID_CAN        "FaultType_CAN"
#define STT_MULTI_MACRO_DISTANCE_FaultType_Items_ID_ABC        "FaultType_ABC"
#define STT_MULTI_MACRO_DISTANCE_FaultType_Items_ID_ONE        "FaultType_ONE"

#define STT_MULTI_MACRO_CURR_MAX	20
#define STT_MULTI_MACRO_CURR_MIN	0
#define STT_MULTI_MACRO_TSet_MAX	999.999
#define STT_MULTI_MACRO_TSet_MIN	0
#define STT_MULTI_MACRO_ZSet_MAX	999.999
#define STT_MULTI_MACRO_ZSet_MIN	0.001
#define STT_MULTI_MACRO_DISTANCE_PARAS_IMPVALUE_MAX	999.999//R、X最大值最小值
#define STT_MULTI_MACRO_DISTANCE_PARAS_IMPVALUE_MIN	-999.999
#define STT_MULTI_MACRO_ANGPLACES	2

#define STT_MULTI_MACRO_PLACES_3	3//R、X、TSet、ZSet、Curr、Abs、Rel保留3位小数
#define STT_MULTI_MACRO_PARAS_DATATYPE_ID_SystemFault			"SystemFault"//故障类型对应DataTypeId
//QDistanceResultEstimateDlg	功能参数编辑页面
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETTING			"ZSetting"			//阻抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RATE				"Rate"				//倍数
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_K0MODE			"K0Mode"			//零序补偿系数
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_KLKR				"KlKr"				//零序补偿系数K0
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ANGKX				"AngKx"				//零序补偿系数Phi(K0)
//#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_IMPREFTYPE		"ImpRefType"//		//阻抗参考方式
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTCURRENT		"FaultIf"		//短路电流20240806 luozibing 由FaultCurrent
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTDIRECTION	"FaultDirection"	//故障方向
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPE1		"FaultPermanent"	//故障性质 20240717 luozibing 测试修改
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RSETTING		"RSetting"	//电阻定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_XSETTING		"XSetting"	//电抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZsetByZAng		"ZSetByAng"	//阻抗定值对应角度、区段、故障类型


#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_DEFAULT			"0"			//缺省值

//QDistanceCommonParasDlg	通用参数页面
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_PREFAULTTIME			"PreFaultTime"		//故障前时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTIME				"FaultTime"			//故障时间裕度
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TIMEAFTERTRIGGER		"TimeAfterTrigger"	//保护动作后持续时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTRIGMODE			"FaultTrigMode"		//故障触发方式
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_PTPOS					"PTPos"				//PT安装位置
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_CTPOS					"CTPos"				//CT正极性
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ILOAD					"ILoad"				//负荷电流
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ILOADPH				"ILoadPh"			//负荷功角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_SIMULATEBREAKERDELAY	"SimulateBreakerDelay"//是否模拟断路器延时
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_BRKBREAKTIME			"BrkBreakTime"			//分闸时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_BRKCLOSETIME			"BrkCloseTime"			//断路器合闸延时
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_VZDEFINE				"VzDefine"				//抽取电压输出定义
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_VZPHDEFINE			"VzPhDefine"			//抽取电压参考项定义
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_VZPH					"VzPh"					//抽取电压相角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_MINTRIPTIME			"MinTripTime"			//最小动作时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETTINGLINE			"Zl"					//线路长度阻抗定值

//QDistanceBinarysDlg		开入、开出页面
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_BINSELECT				"_AndOr"	//开入量选择//20240809luozibing根据最新TestMacro.xml修改
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_A						"BinA"			//开入A
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_B						"BinB"			//开入B
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_C						"BinC"			//开入C
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_D						"BinD"			//开入D
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_E						"BinE"			//开入E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_F						"BinF"			//开入F
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_G						"BinG"			//开入G
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_H						"BinH"			//开入H
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B01					"_B01"		//常态开出1状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B02					"_B02"		//常态开出2状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B03					"_B03"		//常态开出3状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B04					"_B04"		//常态开出4状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B05					"_B05"		//常态开出5状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B06					"_B06"		//常态开出6状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B07					"_B07"		//常态开出7状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__B08					"_B08"		//常态开出8状态
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__OUTPUTSWITCHMODE		"_OutputSwitchMode"		//开出翻转启动方式
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__OUTPUTKEEPTIME		"_OutputKeepTime"		//开出保持时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID__OUTPUTDELAYTIME		"_OutputDelayTime"		//开出翻转时刻

typedef enum{
	IMPREFTYPE_Z_PHI = 0,//Z-Phi
	IMPREFTYPE_R_X   = 1,//R-X
}STT_MULTI_MACRO_DISTANCE_IMPREFTYPE;

//QDistanceAddSinglePhaseDlg	添加单项接地故障
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RATE_095_CHECK				"Rate_095_Check"				//倍数选择-0.95
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RATE_105_CHECK				"Rate_105_Check"				//倍数选择-1.05
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RATE_070_CHECK				"Rate_070_Check"				//倍数选择-0.70
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RATE_100_CHECK				"Rate_100_Check"				//倍数选择-1.00
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RATE_100						"Rate_100"						//倍数-自定义
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RATE_095						"Rate_095"						//倍数-0.95
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RATE_105						"Rate_105"						//倍数-1.05
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RATE_070						"Rate_070"						//倍数-0.70
// #define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RELERR						"Zone1_RelErr"					//距离动作时间相对误差限
// #define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ERRORLOGIC					"Zone1_ErrorLogic"				//距离动作时间误差逻辑判断

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ABSERR_PLUS1					"Zone1_AbsErr_p"				//I段距离动作时间绝对误差正误差
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ABSERR_MINUS1					"Zone1_AbsErr_n"			//I段距离动作时间绝对误差负误差
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RELERR1						"Zone1_RelErr"					//I段距离动作时间相对误差限
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ERRORLOGIC1					"Zone1_ErrorLogic"				//I段距离动作时间误差逻辑判断

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ABSERR_PLUS2					"Zone2_AbsErr_p"				//II段距离动作时间绝对误差正误差
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ABSERR_MINUS2					"Zone2_AbsErr_n"			//II段距离动作时间绝对误差负误差
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RELERR2						"Zone2_RelErr"					//II段距离动作时间相对误差限
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ERRORLOGIC2					"Zone2_ErrorLogic"				//II段距离动作时间误差逻辑判断

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ABSERR_PLUS3					"Zone3_AbsErr_p"				//III段距离动作时间绝对误差正误差
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ABSERR_MINUS3					"Zone3_AbsErr_n"			//III段距离动作时间绝对误差负误差
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RELERR3						"Zone3_RelErr"					//III段距离动作时间相对误差限
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ERRORLOGIC3					"Zone3_ErrorLogic"				//III段距离动作时间误差逻辑判断

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ABSERR_PLUS4					"Zone4_AbsErr_p"				//IV段距离动作时间绝对误差正误差
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ABSERR_MINUS4					"Zone4_AbsErr_n"			//IV段距离动作时间绝对误差负误差
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RELERR4						"Zone4_RelErr"					//IV段距离动作时间相对误差限
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ERRORLOGIC4					"Zone4_ErrorLogic"				//IV段距离动作时间误差逻辑判断

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ABSERR_PLUS5					"Zone5_AbsErr_p"				//V段距离动作时间绝对误差正误差
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ABSERR_MINUS5					"Zone5_AbsErr_n"			//V段距离动作时间绝对误差负误差
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RELERR5						"Zone5_RelErr"					//V段距离动作时间相对误差限
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ERRORLOGIC5					"Zone5_ErrorLogic"				//V段距离动作时间误差逻辑判断

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ABSERR_PLUS6					"ZoneLine_AbsErr_p"			//线路长度距离动作时间绝对误差正误差
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ABSERR_MINUS6					"ZoneLine_AbsErr_n"			//线路长度距离动作时间绝对误差负误差
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RELERR6						"ZoneLine_RelErr"				//线路长度距离动作时间相对误差限
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ERRORLOGIC6					"ZoneLine_ErrorLogic"			//线路长度距离动作时间误差逻辑判断

//QDistanceAddMultDlg
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_LNZONE1_CHECK				"LNZone1_Check"	//接地故障-I段选择
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_LNZONE2_CHECK				"LNZone2_Check"	//接地故障-II段选择
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_LNZONE3_CHECK				"LNZone3_Check"	//接地故障-III段选择
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_LNZONE4_CHECK				"LNZone4_Check"	//接地故障-IV段选择
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_LNZONE5_CHECK				"LNZone5_Check"	//接地故障-V段选择
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_LNZONE6_CHECK				"LNZone_Line"	//接地故障-线路长度
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_LLZONE1_CHECK				"LLZone1_Check"	//相间故障-I段选择
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_LLZONE2_CHECK				"LLZone2_Check"	//相间故障-II段选择
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_LLZONE3_CHECK				"LLZone3_Check"	//相间故障-III段选择
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_LLZONE4_CHECK				"LLZone4_Check"	//相间故障-IV段选择
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_LLZONE5_CHECK				"LLZone5_Check"	//相间故障-V段选择
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_LLZONE6_CHECK				"LLZone_Line"	//相间故障-线路长度

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_DIRECTION_RADIO_N1		"Direction_Radio_N1"//接地故障I段故障方向
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_DIRECTION_RADIO_N2		"Direction_Radio_N2"//接地故障II段故障方向
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_DIRECTION_RADIO_N3		"Direction_Radio_N3"//接地故障III段故障方向
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_DIRECTION_RADIO_N4		"Direction_Radio_N4"//接地故障IV段故障方向
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_DIRECTION_RADIO_N5		"Direction_Radio_N5"//接地故障V段故障方向
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_DIRECTION_RADIO_N6		"Direction_Radio_NLine"//接地故障线路长度故障方向
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_DIRECTION_RADIO_L1		"Direction_Radio_L1"//相间故障I段故障方向
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_DIRECTION_RADIO_L2		"Direction_Radio_L2"//相间故障II段故障方向
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_DIRECTION_RADIO_L3		"Direction_Radio_L3"//相间故障III段故障方向
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_DIRECTION_RADIO_L4		"Direction_Radio_L4"//相间故障IV段故障方向
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_DIRECTION_RADIO_L5		"Direction_Radio_L5"//相间故障V段故障方向
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_DIRECTION_RADIO_L6		"Direction_Radio_LLine"//相间故障线路长度故障方向

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEAE1_CHECK		"FaultTypeAE1_Check"//接地故障I段故障选择-A-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEBE1_CHECK		"FaultTypeBE1_Check"//接地故障I段故障选择-B-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPECE1_CHECK		"FaultTypeCE1_Check"//接地故障I段故障选择-C-E
//#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEABCE1_CHECK		"FaultTypeABCE1_Check"//接地故障I段故障选择-ABC-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEAE2_CHECK		"FaultTypeAE2_Check"//接地故障II段故障选择-A-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEBE2_CHECK		"FaultTypeBE2_Check"//接地故障II段故障选择-B-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPECE2_CHECK		"FaultTypeCE2_Check"//接地故障II段故障选择-C-E
//#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEABCE2_CHECK		"FaultTypeABCE2_Check"//接地故障II段故障选择-ABC-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEAE3_CHECK		"FaultTypeAE3_Check"//接地故障III段故障选择-A-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEBE3_CHECK		"FaultTypeBE3_Check"//接地故障III段故障选择-B-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPECE3_CHECK		"FaultTypeCE3_Check"//接地故障III段故障选择-C-E
//#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEABCE3_CHECK		"FaultTypeABCE3_Check"//接地故障III段故障选择-ABC-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEAE4_CHECK		"FaultTypeAE4_Check"//接地故障IV段故障选择-A-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEBE4_CHECK		"FaultTypeBE4_Check"//接地故障IV段故障选择-B-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPECE4_CHECK		"FaultTypeCE4_Check"//接地故障IV段故障选择-C-E
//#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEABCE4_CHECK		"FaultTypeABCE4_Check"//接地故障IV段故障选择-ABC-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEAE5_CHECK		"FaultTypeAE5_Check"//接地故障V段故障选择-A-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEBE5_CHECK		"FaultTypeBE5_Check"//接地故障V段故障选择-B-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPECE5_CHECK		"FaultTypeCE5_Check"//接地故障V段故障选择-C-E

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEAE6_CHECK		"FaultTypeAE_Line"//接地故障线路长度故障选择-A-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEBE6_CHECK		"FaultTypeBE_Line"//接地故障线路长度故障选择-B-E
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPECE6_CHECK		"FaultTypeCE_Line"//接地故障线路长度故障选择-C-E

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEAB1_CHECK		"FaultTypeAB1_Check"//相间故障I段故障选择-AB
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEBC1_CHECK		"FaultTypeBC1_Check"//相间故障I段故障选择-BC
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPECA1_CHECK		"FaultTypeCA1_Check"//相间故障I段故障选择-CA
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEABC1_CHECK		"FaultTypeABC1_Check"//相间故障I段故障选择-ABC
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEAB2_CHECK		"FaultTypeAB2_Check"//相间故障II段故障选择-AB
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEBC2_CHECK		"FaultTypeBC2_Check"//相间故障II段故障选择-BC
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPECA2_CHECK		"FaultTypeCA2_Check"//相间故障II段故障选择-CA
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEABC2_CHECK		"FaultTypeABC2_Check"//相间故障II段故障选择-ABC
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEAB3_CHECK		"FaultTypeAB3_Check"//相间故障III段故障选择-AB
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEBC3_CHECK		"FaultTypeBC3_Check"//相间故障III段故障选择-BC
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPECA3_CHECK		"FaultTypeCA3_Check"//相间故障III段故障选择-CA
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEABC3_CHECK		"FaultTypeABC3_Check"//相间故障III段故障选择-ABC
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEAB4_CHECK		"FaultTypeAB4_Check"//相间故障IV段故障选择-AB
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEBC4_CHECK		"FaultTypeBC4_Check"//相间故障IV段故障选择-BC
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPECA4_CHECK		"FaultTypeCA4_Check"//相间故障IV段故障选择-CA
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEABC4_CHECK		"FaultTypeABC4_Check"//相间故障IV段故障选择-ABC
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEAB5_CHECK		"FaultTypeAB5_Check"//相间故障V段故障选择-AB
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEBC5_CHECK		"FaultTypeBC5_Check"//相间故障V段故障选择-BC
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPECA5_CHECK		"FaultTypeCA5_Check"//相间故障V段故障选择-CA
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEABC5_CHECK		"FaultTypeABC5_Check"//相间故障V段故障选择-ABC
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEAB6_CHECK		"FaultTypeAB_Line"//相间故障线路长度故障选择-AB
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEBC6_CHECK		"FaultTypeBC_Line"//相间故障线路长度故障选择-BC
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPECA6_CHECK		"FaultTypeCA_Line"//相间故障线路长度故障选择-CA
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTTYPEABC6_CHECK		"FaultTypeABC_Line"//相间故障线路长度故障选择-ABC


#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_FAULTANGLE			"FaultAngle"//整定阻抗角

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETINGLN_ZONE1		"ZSetingLN_Zone1"//接地距离I段阻抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETINGLN_ZONE2		"ZSetingLN_Zone2"//接地距离II段阻抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETINGLN_ZONE3		"ZSetingLN_Zone3"//接地距离III段阻抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETINGLN_ZONE4		"ZSetingLN_Zone4"//接地距离IV段阻抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETINGLN_ZONE5		"ZSetingLN_Zone5"//接地距离V段阻抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETINGLN_ZONE6		"ZSetingLN_Line"//接地距离线路长度阻抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETINGLL_ZONE1		"ZSetingLL_Zone1"//相间距离I段阻抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETINGLL_ZONE2		"ZSetingLL_Zone2"//相间距离II段阻抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETINGLL_ZONE3		"ZSetingLL_Zone3"//相间距离III段阻抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETINGLL_ZONE4		"ZSetingLL_Zone4"//相间距离IV段阻抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETINGLL_ZONE5		"ZSetingLL_Zone5"//相间距离V段阻抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZSETINGLL_ZONE6		"ZSetingLL_Line"//相间距离线路长度阻抗定值

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZANGLN_ZONE1		"ZAngLN_Zone1"//接地距离I段阻抗角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZANGLN_ZONE2		"ZAngLN_Zone2"//接地距离II段阻抗角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZANGLN_ZONE3		"ZAngLN_Zone3"//接地距离III段阻抗角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZANGLN_ZONE4		"ZAngLN_Zone4"//接地距离IV段阻抗角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZANGLN_ZONE5		"ZAngLN_Zone5"//接地距离V段阻抗角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZANGLN_ZONE6		"ZAngLN_Line"//接地距离线路长度阻抗角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZANGLL_ZONE1		"ZAngLL_Zone1"//相间距离I段阻抗角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZANGLL_ZONE2		"ZAngLL_Zone2"//相间距离II段阻抗角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZANGLL_ZONE3		"ZAngLL_Zone3"//相间距离III段阻抗角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZANGLL_ZONE4		"ZAngLL_Zone4"//相间距离IV段阻抗角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZANGLL_ZONE5		"ZAngLL_Zone5"//相间距离V段阻抗角
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_ZANGLL_ZONE6		"ZAngLL_Line"//相间距离线路长度阻抗角

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TSETINGLN_ZONE1		"TSetingLN_Zone1"//接地距离I段整定动作时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TSETINGLN_ZONE2		"TSetingLN_Zone2"//接地距离II段整定动作时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TSETINGLN_ZONE3		"TSetingLN_Zone3"//接地距离III段整定动作时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TSETINGLN_ZONE4		"TSetingLN_Zone4"//接地距离IV段整定动作时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TSETINGLN_ZONE5		"TSetingLN_Zone5"//接地距离V段整定动作时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TSETINGLN_ZONE6		"TSetingLN_Line"//接地距离线路长度整定动作时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TSETINGLL_ZONE1		"TSetingLL_Zone1"//相间距离I段整定动作时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TSETINGLL_ZONE2		"TSetingLL_Zone2"//相间距离II段整定动作时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TSETINGLL_ZONE3		"TSetingLL_Zone3"//相间距离III段整定动作时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TSETINGLL_ZONE4		"TSetingLL_Zone4"//相间距离IV段整定动作时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TSETINGLL_ZONE5		"TSetingLL_Zone5"//相间距离V段整定动作时间
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_TSETINGLL_ZONE6		"TSetingLL_Line"//相间距离线路长度整定动作时间

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RSETINGLN_ZONE1		"RSetingLN_Zone1"//接地距离I段电阻定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RSETINGLN_ZONE2		"RSetingLN_Zone2"//接地距离II段电阻定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RSETINGLN_ZONE3		"RSetingLN_Zone3"//接地距离III段电阻定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RSETINGLN_ZONE4		"RSetingLN_Zone4"//接地距离IV段电阻定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RSETINGLN_ZONE5		"RSetingLN_Zone5"//接地距离V段电阻定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RSETINGLN_ZONE6		"RSetingLN_Line"//接地距离线路长度电阻定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RSETINGLL_ZONE1		"RSetingLL_Zone1"//相间距离I段电阻定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RSETINGLL_ZONE2		"RSetingLL_Zone2"//相间距离II段电阻定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RSETINGLL_ZONE3		"RSetingLL_Zone3"//相间距离III段电阻定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RSETINGLL_ZONE4		"RSetingLL_Zone4"//相间距离IV段电阻定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RSETINGLL_ZONE5		"RSetingLL_Zone5"//相间距离V段电阻定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_RSETINGLL_ZONE6		"RSetingLL_Line"//相间距离线路长度电阻定值

#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_XSETINGLN_ZONE1		"XSetingLN_Zone1"//接地距离I段电抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_XSETINGLN_ZONE2		"XSetingLN_Zone2"//接地距离II段电抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_XSETINGLN_ZONE3		"XSetingLN_Zone3"//接地距离III段电抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_XSETINGLN_ZONE4		"XSetingLN_Zone4"//接地距离IV段电抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_XSETINGLN_ZONE5		"XSetingLN_Zone5"//接地距离V段电抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_XSETINGLN_ZONE6		"XSetingLN_Line"//接地距离线路长度电抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_XSETINGLL_ZONE1		"XSetingLL_Zone1"//相间距离I段电抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_XSETINGLL_ZONE2		"XSetingLL_Zone2"//相间距离II段电抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_XSETINGLL_ZONE3		"XSetingLL_Zone3"//相间距离III段电抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_XSETINGLL_ZONE4		"XSetingLL_Zone4"//相间距离IV段电抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_XSETINGLL_ZONE5		"XSetingLL_Zone5"//相间距离V段电抗定值
#define STT_MULTI_MACRO_DISTANCE_PARAS_ID_XSETINGLL_ZONE6		"XSetingLL_Line"//相间距离线路长度电抗定值

//区段值
#define STT_MULTI_MACRO_ZONE1		2//I段
#define STT_MULTI_MACRO_ZONE2		3//II段
#define STT_MULTI_MACRO_ZONE3		4//III段
#define STT_MULTI_MACRO_ZONE4		5//IV段
#define STT_MULTI_MACRO_ZONE5		6//V段
#endif // STTMULTIMACRODISTANCEPARASDEFINE_H