
SOURCES +=  \
$$PWD/mmslite/inc/mms_string.c \
$$PWD/mmslite/src/cfg_util.c \
$$PWD/mmslite/src/genlists.c \
#$$PWD/mmslite/src/glbsem.c \
#$$PWD/mmslite/src/glbsem_w32.c \
#$$PWD/mmslite/src/glbtimer.c \
#$$PWD/mmslite/src/mem_chks.c \
$$PWD/mmslite/src/qmem.c \
#$$PWD/mmslite/src/scl_log.c \
$$PWD/mmslite/src/sclparse.c \
$$PWD/mmslite/src/sclstore.c \
$$PWD/mmslite/src/sfile.c \
$$PWD/mmslite/src/slog.c \
$$PWD/mmslite/src/slogfil.c \
$$PWD/mmslite/src/sloghex.c \
$$PWD/mmslite/src/slogipcs.c \
$$PWD/mmslite/src/slogmem.c \
$$PWD/mmslite/src/stdtime.c \
$$PWD/mmslite/src/stdtime_iccp_timestamp.c \
$$PWD/mmslite/src/stdtime_mms_btime.c \
$$PWD/mmslite/src/stdtime_mms_utctime.c \
$$PWD/mmslite/src/stdtime_quadlib.c \
$$PWD/mmslite/src/stdtime_w32.c \
$$PWD/mmslite/src/stime.c \
$$PWD/mmslite/src/str_util.c \
$$PWD/mmslite/src/sx_axs4d.c \
$$PWD/mmslite/src/sx_data.c \
#$$PWD/mmslite/src/sx_dec.c \
$$PWD/mmslite/src/sx_enc.c \
$$PWD/mmslite/src/SystemObjects.cpp \
$$PWD/mmslite/src/time_str.c \
$$PWD/Module/61850ClientConfig/61850ClientCfgMngrGlobal.cpp \
$$PWD/Module/61850ClientConfig/61850ClientConfig.cpp \
$$PWD/Module/61850ClientConfig/RemoteDev.cpp \
$$PWD/Module/61850ClientConfig/RemoteDevs.cpp \
$$PWD/Module/AT02DTool/AT02D_Tool.cpp \
$$PWD/Module/CfgDataMngr/IecCfg2MData.cpp \
$$PWD/Module/CfgDataMngr/IecCfg2MInData.cpp \
$$PWD/Module/CfgDataMngr/IecCfg6044Ch.cpp \
$$PWD/Module/CfgDataMngr/IecCfg6044Chs.cpp \
$$PWD/Module/CfgDataMngr/IecCfg6044CommonCh.cpp \
$$PWD/Module/CfgDataMngr/IecCfg6044CommonChIn.cpp \
$$PWD/Module/CfgDataMngr/IecCfg6044CommonData.cpp \
$$PWD/Module/CfgDataMngr/IecCfg6044CommonInData.cpp \
$$PWD/Module/CfgDataMngr/IecCfg6044Data.cpp \
$$PWD/Module/CfgDataMngr/IecCfg91Ch.cpp \
$$PWD/Module/CfgDataMngr/IecCfg91Chs.cpp \
$$PWD/Module/CfgDataMngr/IecCfg91Data.cpp \
$$PWD/Module/CfgDataMngr/IecCfg91StateWord.cpp \
$$PWD/Module/CfgDataMngr/IecCfg91StateWordMngr.cpp \
$$PWD/Module/CfgDataMngr/IecCfg91StatusDataSet.cpp \
$$PWD/Module/CfgDataMngr/IecCfg91StatusDataSetCh.cpp \
$$PWD/Module/CfgDataMngr/IecCfg91StcateWordBit.cpp \
$$PWD/Module/CfgDataMngr/IecCfg92Ch.cpp \
$$PWD/Module/CfgDataMngr/IecCfg92ChIn.cpp \
$$PWD/Module/CfgDataMngr/IecCfg92ChQuality.cpp \
$$PWD/Module/CfgDataMngr/IecCfg92Chs.cpp \
$$PWD/Module/CfgDataMngr/IecCfg92ChsIn.cpp \
$$PWD/Module/CfgDataMngr/IecCfg92Data.cpp \
$$PWD/Module/CfgDataMngr/IecCfg92InData.cpp \
$$PWD/Module/CfgDataMngr/IecCfgAdvanceException.cpp \
$$PWD/Module/CfgDataMngr/IecCfgChsBase.cpp \
$$PWD/Module/CfgDataMngr/IecCfgDataBase.cpp \
$$PWD/Module/CfgDataMngr/IecCfgDataChBase.cpp \
$$PWD/Module/CfgDataMngr/IecCfgDataGooseChBase.cpp \
$$PWD/Module/CfgDataMngr/IecCfgDataMngrGlobal.cpp \
$$PWD/Module/CfgDataMngr/IecCfgDatasBase.cpp \
$$PWD/Module/CfgDataMngr/IecCfgDatasMngr.cpp \
$$PWD/Module/CfgDataMngr/IecCfgDataSmvChBase.cpp \
$$PWD/Module/CfgDataMngr/IecCfgDataSmvCommon.cpp \
$$PWD/Module/CfgDataMngr/IecCfgDevice.cpp \
$$PWD/Module/CfgDataMngr/IecCfgFiberPara.cpp \
$$PWD/Module/CfgDataMngr/IecCfgFiberParas.cpp \
$$PWD/Module/CfgDataMngr/IecCfgFiberParasIn.cpp \
$$PWD/Module/CfgDataMngr/IecCfgGinAppChMap.cpp \
$$PWD/Module/CfgDataMngr/IecCfgGinAppChMaps.cpp \
$$PWD/Module/CfgDataMngr/IecCfgGinCh.cpp \
$$PWD/Module/CfgDataMngr/IecCfgGinChs.cpp \
$$PWD/Module/CfgDataMngr/IecCfgGinData.cpp \
$$PWD/Module/CfgDataMngr/IecCfgGinDatas.cpp \
$$PWD/Module/CfgDataMngr/IecCfgGooseDataBase.cpp \
$$PWD/Module/CfgDataMngr/IecCfgGoutCh.cpp \
$$PWD/Module/CfgDataMngr/IecCfgGoutChs.cpp \
$$PWD/Module/CfgDataMngr/IecCfgGoutData.cpp \
$$PWD/Module/CfgDataMngr/IecCfgGoutDatas.cpp \
$$PWD/Module/CfgDataMngr/IecCfgPrimRate.cpp \
$$PWD/Module/CfgDataMngr/IecCfgPrimRates.cpp \
$$PWD/Module/CfgDataMngr/IecCfgPrimRatesIn.cpp \
$$PWD/Module/CfgDataMngr/IecCfgSmvDataBase.cpp \
$$PWD/Module/CfgDataMngr/IecCfgSMVDatas.cpp \
$$PWD/Module/CfgDataMngr/IecCfgSmvInDatas.cpp \
$$PWD/Module/CfgDataMngr/IecCfgSmvRate.cpp \
$$PWD/Module/CfgDataMngr/IecCfgSmvRates.cpp \
$$PWD/Module/CfgDataMngr/IecCfgSysParas.cpp \
$$PWD/Module/CfgDataMngr/IecCfgSystemConfig.cpp \
$$PWD/Module/EnumType.cpp \
$$PWD/Module/GlobalDataMngr/IecFiberConfig.cpp \
$$PWD/Module/GlobalDataMngr/IecGlobalDataMngr.cpp \
$$PWD/Module/GlobalDataMngr/IecGlobalDataMngrGlobal.cpp \
$$PWD/Module/GlobalDataMngr/IecGooseChDataTypeMngr.cpp \
$$PWD/Module/GlobalDataMngr/IecSmvChDataType.cpp \
$$PWD/Module/IecCfgSclTool/SclToIecCfgTool.cpp \
$$PWD/Module/MMS_STACK_CFG/MMS_STACK_CFG.cpp \
$$PWD/Module/MMS_STACK_CFG/MMS_STACK_CFGGlobal.cpp \
$$PWD/Module/MMS_STACK_CFG/StkCfg_LocalAddress.cpp \
$$PWD/Module/MMS_STACK_CFG/StkCfg_LocalAddressList.cpp \
$$PWD/Module/MMS_STACK_CFG/StkCfg_MMS.cpp \
$$PWD/Module/MMS_STACK_CFG/StkCfg_NetAddr.cpp \
$$PWD/Module/MMS_STACK_CFG/StkCfg_NetworkAddressing.cpp \
$$PWD/Module/MMS_STACK_CFG/StkCfg_RemoteAddress.cpp \
$$PWD/Module/MMS_STACK_CFG/StkCfg_RemoteAddressList.cpp \
$$PWD/Module/MMS_STACK_CFG/StkCfg_Transport.cpp \
$$PWD/Module/MMS_STACK_CFG/StkCfg_TransportTcp.cpp \
$$PWD/Module/SCL/CcdFileRead.cpp \
$$PWD/Module/SCL/SclFileMngr/SclFileMngrGlobal.cpp \
$$PWD/Module/SCL/SclFileMngr/XSclFileMngr.cpp \
$$PWD/Module/SCL/SclFileMngr/XSclFileObj.cpp \
$$PWD/Module/SCL/SclFileRead.cpp \
$$PWD/Module/SCL/SclIecCfgDatas.cpp \
$$PWD/Module/SCL_Qt/QScdFileRWDlg.cpp \
$$PWD/Module/SCL_Qt/QSclFileRead.cpp \
$$PWD/Module/SclToModel/ModelWriteXml.cpp \
$$PWD/Module/XLanguageResourceIec.cpp \
$$PWD/Module/XLanguageResourcePp_Mms.cpp 


HEADERS += \
$$PWD/mmslite/inc/mms_def2.h \
$$PWD/mmslite/inc/mms_string.h \
$$PWD/mmslite/inc/SCL.H \
$$PWD/mmslite/inc/sx_defs.h \
$$PWD/Module/61850ClientConfig/61850ClientCfgMngrGlobal.h \
$$PWD/Module/61850ClientConfig/61850ClientConfig.h \
$$PWD/Module/61850ClientConfig/RemoteDev.h \
$$PWD/Module/61850ClientConfig/RemoteDevs.h \
$$PWD/Module/AT02DTool/AT02D_Tool.h \
$$PWD/Module/CfgDataMngr/IecCfg2MData.h \
$$PWD/Module/CfgDataMngr/IecCfg2MInData.h \
$$PWD/Module/CfgDataMngr/IecCfg6044Ch.h \
$$PWD/Module/CfgDataMngr/IecCfg6044Chs.h \
$$PWD/Module/CfgDataMngr/IecCfg6044CommonCh.h \
$$PWD/Module/CfgDataMngr/IecCfg6044CommonChIn.h \
$$PWD/Module/CfgDataMngr/IecCfg6044CommonData.h \
$$PWD/Module/CfgDataMngr/IecCfg6044CommonInData.h \
$$PWD/Module/CfgDataMngr/IecCfg6044Data.h \
$$PWD/Module/CfgDataMngr/IecCfg91Ch.h \
$$PWD/Module/CfgDataMngr/IecCfg91Chs.h \
$$PWD/Module/CfgDataMngr/IecCfg91Data.h \
$$PWD/Module/CfgDataMngr/IecCfg91StateWord.h \
$$PWD/Module/CfgDataMngr/IecCfg91StateWordBit.h \
$$PWD/Module/CfgDataMngr/IecCfg91StateWordMngr.h \
$$PWD/Module/CfgDataMngr/IecCfg91StatusDataSet.h \
$$PWD/Module/CfgDataMngr/IecCfg91StatusDataSetCh.h \
$$PWD/Module/CfgDataMngr/IecCfg92Ch.h \
$$PWD/Module/CfgDataMngr/IecCfg92ChIn.h \
$$PWD/Module/CfgDataMngr/IecCfg92ChQuality.h \
$$PWD/Module/CfgDataMngr/IecCfg92Chs.h \
$$PWD/Module/CfgDataMngr/IecCfg92ChsIn.h \
$$PWD/Module/CfgDataMngr/IecCfg92Data.h \
$$PWD/Module/CfgDataMngr/IecCfg92InData.h \
$$PWD/Module/CfgDataMngr/IecCfgAdvanceException.h \
$$PWD/Module/CfgDataMngr/IecCfgChsBase.h \
$$PWD/Module/CfgDataMngr/IecCfgDataBase.h \
$$PWD/Module/CfgDataMngr/IecCfgDataChBase.h \
$$PWD/Module/CfgDataMngr/IecCfgDataGooseChBase.h \
$$PWD/Module/CfgDataMngr/IecCfgDataMngrGlobal.h \
$$PWD/Module/CfgDataMngr/IecCfgDatasBase.h \
$$PWD/Module/CfgDataMngr/IecCfgDatasMngr.h \
$$PWD/Module/CfgDataMngr/IecCfgDataSmvChBase.h \
$$PWD/Module/CfgDataMngr/IecCfgDataSmvCommon.h \
$$PWD/Module/CfgDataMngr/IecCfgDevice.h \
$$PWD/Module/CfgDataMngr/IecCfgFiberPara.h \
$$PWD/Module/CfgDataMngr/IecCfgFiberParas.h \
$$PWD/Module/CfgDataMngr/IecCfgFiberParasIn.h \
$$PWD/Module/CfgDataMngr/IecCfgGinAppChMap.h \
$$PWD/Module/CfgDataMngr/IecCfgGinAppChMaps.h \
$$PWD/Module/CfgDataMngr/IecCfgGinCh.h \
$$PWD/Module/CfgDataMngr/IecCfgGinChs.h \
$$PWD/Module/CfgDataMngr/IecCfgGinData.h \
$$PWD/Module/CfgDataMngr/IecCfgGinDatas.h \
$$PWD/Module/CfgDataMngr/IecCfgGooseDataBase.h \
$$PWD/Module/CfgDataMngr/IecCfgGoutCh.h \
$$PWD/Module/CfgDataMngr/IecCfgGoutChs.h \
$$PWD/Module/CfgDataMngr/IecCfgGoutData.h \
$$PWD/Module/CfgDataMngr/IecCfgGoutDatas.h \
$$PWD/Module/CfgDataMngr/IecCfgPrimRate.h \
$$PWD/Module/CfgDataMngr/IecCfgPrimRates.h \
$$PWD/Module/CfgDataMngr/IecCfgPrimRatesIn.h \
$$PWD/Module/CfgDataMngr/IecCfgSmvDataBase.h \
$$PWD/Module/CfgDataMngr/IecCfgSMVDatas.h \
$$PWD/Module/CfgDataMngr/IecCfgSmvInDatas.h \
$$PWD/Module/CfgDataMngr/IecCfgSmvRate.h \
$$PWD/Module/CfgDataMngr/IecCfgSmvRates.h \
$$PWD/Module/CfgDataMngr/IecCfgSysParas.h \
$$PWD/Module/CfgDataMngr/IecCfgSystemConfig.h \
$$PWD/Module/EnumType.h \
$$PWD/Module/GlobalDataMngr/IecFiberConfig.h \
$$PWD/Module/GlobalDataMngr/IecGlobalDataMngr.h \
$$PWD/Module/GlobalDataMngr/IecGlobalDataMngrGlobal.h \
$$PWD/Module/GlobalDataMngr/IecGooseChDataTypeMngr.h \
$$PWD/Module/GlobalDataMngr/IecSmvChDataType.h \
$$PWD/Module/IecCfgSclTool/SclToIecCfgTool.h \
$$PWD/Module/MMS_STACK_CFG/MMS_STACK_CFG.h \
$$PWD/Module/MMS_STACK_CFG/MMS_STACK_CFGGlobal.h \
$$PWD/Module/MMS_STACK_CFG/StkCfg_LocalAddress.h \
$$PWD/Module/MMS_STACK_CFG/StkCfg_LocalAddressList.h \
$$PWD/Module/MMS_STACK_CFG/StkCfg_MMS.h \
$$PWD/Module/MMS_STACK_CFG/StkCfg_NetAddr.h \
$$PWD/Module/MMS_STACK_CFG/StkCfg_NetworkAddressing.h \
$$PWD/Module/MMS_STACK_CFG/StkCfg_RemoteAddress.h \
$$PWD/Module/MMS_STACK_CFG/StkCfg_RemoteAddressList.h \
$$PWD/Module/MMS_STACK_CFG/StkCfg_Transport.h \
$$PWD/Module/MMS_STACK_CFG/StkCfg_TransportTcp.h \
$$PWD/Module/SCL/CcdFileRead.h \
$$PWD/Module/SCL/SclFileMngr/SclFileMngrGlobal.h \
$$PWD/Module/SCL/SclFileMngr/XSclFileMngr.h \
$$PWD/Module/SCL/SclFileMngr/XSclFileObj.h \
$$PWD/Module/SCL/SclFileRead.h \
$$PWD/Module/SCL/SclIecCfgDatas.h \
$$PWD/Module/SCL_Qt/QScdFileRWDlg.h \
$$PWD/Module/SCL_Qt/QSclFileRead.h \
$$PWD/Module/SclToModel/ModelWriteXml.h \
$$PWD/Module/XLanguageResourceIec.h \
$$PWD/Module/XLanguageResourcePp_Mms.h 


FORMS    += \


