#-------------------------------------------------
#
# Project created by QtCreator 2022-01-09T11:03:48
#
#-------------------------------------------------

#QT       += core gui webkit network xml webkitwidgets
QT       += core gui widgets webkit network xml webkitwidgets

DEFINES +=_PSX_IDE_QT_  _QT_IN_LINUX_ OS_QT_LINUX _PSX_QT_LINUX_ #USE_Custom_CDateTime
DEFINES += XML_USE_PUGIXML   NO_XDbBaseLib _CHAR_LIB_DEV_ # USE_IN_Astra_LINUX
DEFINES +=CURLINUX NOT_USE_GB_SCRIPT _PSX_OS_CENTOS_ _NOT_USE_GOOGLE_PINYIN_ NOT_USE_XLANGUAGE
DEFINES +=DEBUG_MODE _PSX_QT_SRCFILE_GBK_
DEFINES +=_USE_SMARTTEST_INTERFACE_STT_ _USE_SMARTTEST_INTERFACE_ENGINE_STT_ _STT_NOT_IN_TEST_SERVER_
DEFINES +=STT_CMD_PARAS_HAS_GUIDEBOOK
DEFINES +=_SCRIPT_USE_XVM JSON_USE_ _not_use_CTCtrlCntrConfig
DEFINES += MMS_LITE
#DEFINES += _USE_IN_IED_QT5

INCLUDEPATH += ../../../Module/BaseClass
INCLUDEPATH += ../../../Module/OSInterface
INCLUDEPATH += ../../../Module/OSInterface/QT
INCLUDEPATH += ../../../61850/mmslite/inc

#INCLUDEPATH += /usr/local/qwt-6.1.2/include
#LIBS += -L "/usr/local/qwt-6.1.2/lib/" -lqwt
LIBS += -lX11

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = SttNativeMain
TEMPLATE = app


SOURCES += main.cpp\
    ../../../61850/Module/CfgDataMngr/IecCfgDatasMngr.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgGoutDatas.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgGoutData.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgGoutChs.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgGoutCh.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgGooseDataBase.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgGinDatas.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgGinData.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgGinChs.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgGinCh.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgDatasBase.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgDataMngrGlobal.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgDataGooseChBase.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgDataChBase.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgDataBase.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgChsBase.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg92Data.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg92ChsIn.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg92Chs.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgSMVDatas.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgSmvDataBase.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgGinAppChMaps.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgGinAppChMap.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg92ChQuality.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg92ChIn.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg92Ch.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg6044Ch.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg6044Chs.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg6044Data.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgDataSmvCommon.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg91Ch.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg91Chs.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg91Data.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgSmvRate.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgSmvRates.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgAdvanceException.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgDataSmvChBase.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg91StatusDataSet.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg91StatusDataSetCh.cpp \
    ../../../61850/Module/GlobalDataMngr/IecFiberConfig.cpp \
    ../../../61850/Module/GlobalDataMngr/IecGlobalDataMngr.cpp \
    ../../../61850/Module/GlobalDataMngr/IecGlobalDataMngrGlobal.cpp \
    ../../../61850/Module/GlobalDataMngr/IecGooseChDataTypeMngr.cpp \
    ../../../61850/Module/GlobalDataMngr/IecSmvChDataType.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgSysParas.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg6044CommonCh.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg6044CommonData.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg91StateWord.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg91StateWordMngr.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg91StcateWordBit.cpp \
#    ../../../61850/Module/CfgDataMngr/IecCfg92InputData.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgFiberPara.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgFiberParas.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgPrimRate.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgPrimRates.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgSystemConfig.cpp \
    ../../../61850/Module/XLanguageResourceIec.cpp \
    ../../../Module/OSInterface/QT/XGlobalDefine_QT.cpp \
    ../../../Module/OSInterface/QT/CFile_QT.cpp \
    ../../../Module/OSInterface/QT/CString_QT.cpp \
    ../../../Module/OSInterface/QT/CTime_QT.cpp \
    ../../../Module/OSInterface/QT/CXArray_QT.cpp \
    ../../../Module/OSInterface/QT/CXCtrl_QT.cpp \
    ../../../Module/OSInterface/QT/CXCtrl_QT_CWinApp.cpp \
    ../../../Module/OSInterface/QT/CXCtrl_QT_CWnd.cpp \
    ../../../Module/OSInterface/QT/XMsgCycleBuffer.cpp \
    ../../../Module/OSInterface/QT/std_api_linux.cpp \
    ../../../Module/OSInterface/QT/CXDrawTypes_QT.cpp \
    ../../../Module/OSInterface/QT/CWinThread_QT.cpp \
    ../../../Module/MemBuffer/BufferBase.cpp \
    ../../../Module/MemBuffer/FormatTextBuffer.cpp \
    ../../../Module/MemBuffer/EquationBuffer.cpp \
    ../../../Module/MemBuffer/EquationKey.cpp \
    ../../../Module/MemBuffer/CycleMemBuffer.cpp \
    ../../../Module/MemBuffer/StringToSystimeBuffer.cpp \
    ../../../Module/MemBuffer/XMemBufferBse.cpp \
    ../../../Module/MemBuffer/ExpandMemBuf.cpp \
    ../../../Module/MemBuffer/CycleMemBufferMngr.cpp \
    ../../../Module/MemBuffer/TCycleMemBuffer.cpp \
    ../../../Module/BaseClass/WSerializeBuff.cpp \
    ../../../Module/BaseClass/SerializeBufferBase.cpp \
    ../../../Module/BaseClass/XObjectRefBase.cpp \
    ../../../Module/BaseClass/ComplexNumber.cpp \
    ../../../Module/BaseClass/BaseList.cpp \
    ../../../Module/BaseClass/StringSerializeBuffer.cpp \
    ../../../Module/BaseClass/BaseObject.cpp \
    ../../../Module/BaseClass/BinarySerialBuffer.cpp \
    ../../../Module/BaseClass/ExBaseList.cpp \
    ../../../Module/BaseClass/ExBaseObject.cpp \
    ../../../Module/API/StringApi.cpp \
    ../../../Module/Log/LogPrint.cpp \
    ../../../Module/API/GlobalConfigApi.cpp \
    ../../../Module/API/FileApi.cpp \
    ../../../Module/API/GlobalApi.cpp \
    ../../../Module/DataMngr/DataGroup.cpp \
    ../../../Module/DataMngr/DataMngrGlobal.cpp \
    ../../../Module/DataMngr/DataType.cpp \
    ../../../Module/DataMngr/DataTypes.cpp \
    ../../../Module/DataMngr/DataTypeValue.cpp \
    ../../../Module/DataMngr/DvmData.cpp \
    ../../../Module/DataMngr/DvmDataset.cpp \
    ../../../Module/DataMngr/DvmDevice.cpp \
    ../../../Module/DataMngr/DvmDevices.cpp \
    ../../../Module/DataMngr/DvmLog.cpp \
    ../../../Module/DataMngr/DvmLogicDevice.cpp \
    ../../../Module/DataMngr/DvmLogs.cpp \
    ../../../Module/DataMngr/DvmValue.cpp \
    ../../../Module/DataMngr/LogCtrl.cpp \
    ../../../Module/DataMngr/LogCtrls.cpp \
    ../../../Module/DataMngr/LongData.cpp \
    ../../../Module/DataMngr/LongDatas.cpp \
    ../../../Module/DataMngr/RptCtrl.cpp \
    ../../../Module/DataMngr/RptCtrls.cpp \
    ../../../Module/DataMngr/ShortData.cpp \
    ../../../Module/DataMngr/ShortDatas.cpp \
    ../../../Module/DataMngr/Value.cpp \
    ../../../Module/DataMngr/Values.cpp \
    ../../../Module/System/TickCount32.cpp \
    ../../../Module/System/StringTokenizer.cpp \
    ../../../Module/GpsPcTime/GpsPcTime.cpp \
    ../../../Module/xml/XmlRWBase.cpp \
    ../../../Module/xml/XmlRWFactory.cpp \
    ../../../Module/xml/XmlRW_Pugi.cpp \
    ../../../Module/xml/PugiXML/pugixml.cpp \
    ../../../Module/XLanguage/XLangItem.cpp \
    ../../../Module/XLanguage/XLanguage.cpp \
    ../../../Module/XLanguage/XLanguageGlobal.cpp \
    ../../../Module/XLanguage/XLanguageMngr.cpp \
    ../../../Module/XLanguage/XLanguageNameParser.cpp \
    ../../../Module/XLanguage/XLanguageResource.cpp \
    ../../../Module/API/HexTransApi.cpp \
    ../../../Module/Expression/EpExpression.cpp \
    ../../../Module/Expression/EpExpressionTool.cpp \
    ../../../Module/DataMngr/DataMngrTrans.cpp \
    ../../../Module/Encrypt/XDes2.cpp \
    ../../../Module/XDrawBase/XDrawArc.cpp \
    ../../../Module/XDrawBase/XDrawBase.cpp \
    ../../../Module/XDrawBase/XDrawCircle.cpp \
    ../../../Module/XDrawBase/XDrawDataDef.cpp \
    ../../../Module/XDrawBase/XDrawElement.cpp \
    ../../../Module/XDrawBase/XDrawElements.cpp \
    ../../../Module/XDrawBase/XDrawGlobal.cpp \
    ../../../Module/XDrawBase/XDrawLine.cpp \
    ../../../Module/XDrawBase/XDrawList.cpp \
    ../../../Module/XDrawBase/XDrawMngr.cpp \
    ../../../Module/XDrawBase/XDrawMngrDescartes.cpp \
    ../../../Module/XDrawBase/XDrawMngrLogarithm.cpp \
    ../../../Module/XDrawBase/XDrawPoint.cpp \
    ../../../Module/XDrawBase/XDrawPolyline.cpp \
    ../../../Module/XDrawBase/XDrawViewBase.cpp \
    ../../../Module/Axis/AxisInterface.cpp \
    ../../../Module/Axis/DescartesAxis.cpp \
    ../../../Module/Axis/LogarithmAxis.cpp \
    ../../../Module/Axis/PolarAxis.cpp \
    ../../../Module/StringCmp/StringCmp.cpp \
    ../../../Module/StringCmp/StringCmpBlock.cpp \
    ../../../Module/StringCmp/StringCmpBlocks.cpp \
    ../../../Module/API/MathApi.cpp \
    ../../../Module/DataMngr/DvmDatasetGroup.cpp \
    ../../../Module/System/StringTokenizerU.cpp \
    ../../../Module/XfileMngrBase/XFileFindEx.cpp \
    ../../../Module/XfileMngrBase/QT/XFileFindExImp.cpp \
    ../../../Module/FilterText/FilterText.cpp \
    ../../../Module/FilterText/FilterTextGlobal.cpp \
    ../../../Module/FilterText/FilterTextMngr.cpp \
    ../../../Module/Expression/ExprParse.cpp \
    ../../../Module/XDrawBase/XDrawLineEx.cpp \
    ../../../Module/XDrawBase/XDrawPointEx.cpp \
    ../../../Module/XDrawBase/XDrawText.cpp \
    ../../../Module/API/GloblaDrawFunctions.cpp \
    ../../../Module/XLanguage/QT/XLanguageAPI_QT.cpp \
    ../../../Module/xml/JsonRW.cpp \
    ../../../Module/xml/JSON/CJSON.c \
    ../../../Module/API/StringConvert/String_Utf8_To_Gbk.cpp \
    ../../../Module/API/StringConvert/String_Gbk_To_Utf8.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgSmvInDatas.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg2MData.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg2MInData.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg6044CommonChIn.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg6044CommonInData.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgPrimRatesIn.cpp \
    ../../../61850/Module/SCL/SclFileMngr/SclFileMngrGlobal.cpp \
    ../../../61850/Module/SCL/SclFileMngr/XSclFileMngr.cpp \
    ../../../61850/Module/SCL/SclFileMngr/XSclFileObj.cpp \
    ../../../61850/Module/SCL_Qt/QScdFileRWDlg.cpp \
    ../../../61850/Module/SCL_Qt/QSclFileRead.cpp \
    ../../../61850/Module/SCL/SclIecCfgDatas.cpp \
    ../../../Module/XfileMngrBase/XFile.cpp \
    ../../../Module/XfileMngrBase/XFileMngr.cpp \
    ../../../Module/XfileMngrBase/XFileType.cpp \
    ../../../Module/XfileMngrBase/XFileTypes.cpp \
    ../../../Module/XfileMngrBase/XFolder.cpp \
    ../../../Module/BaseClass/QT/ExBaseListTreeCtrl.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfg92InData.cpp \
    ../../../Module/BaseClass/ThreadProgressInterface.cpp \
    ../../../Module/OSInterface/QT/CXDraw_QT.cpp \
    ../../../Module/API/StringConvertApi.cpp \
    ../../../AutoTest/Module/XLanguageResourceAts.cpp \
    ../../../61850/Module/XLanguageResourcePp_Mms.cpp \
    ../../../61850/Module/CfgDataMngr/IecCfgFiberParasIn.cpp \
    ../../../Module/DataMngr/DvmCmp/DvmCmpKeyDataTypes.cpp \
    ../../../Module/Expression/XExprNode.cpp \
    ../../../Module/Expression/XExprBase.cpp \
    ../../../Module/Expression/XExprGlobal.cpp \
    ../../../Module/Expression/XExprCal.cpp \
    ../../../Module/Expression/XExprCmp.cpp \
    ../../../Module/Expression/XExprError.cpp \
    ../../../Module/Expression/XExprErrorEx.cpp \
    ../../../Module/Expression/XExprErrorCombined.cpp \
    ../../../Module/Expression/XExprRange.cpp \
    ../../../Module/Expression/XExprValue.cpp \
    ../../../Module/Expression/XExprValueCal.cpp \
    ../../../Module/Expression/XExprValueCalEx.cpp \
    ../../../Module/Expression/XExprValue_Ex.cpp \
    ../../../Module/DataMngr/DvmValues.cpp \
    ../../../Module/BaseClass/XTimer.cpp \
    ../../../Module/Socket/XPing.cpp \
    ../../../Module/Socket/WinBaseSocket.cpp \
    ../../../Module/Socket/WinTcpSocket.cpp \
    ../../../Module/Socket/WinTcpSocketClient.cpp \
    ../../../Module/Socket/WinTcpSocketServer.cpp \
    ../../../Module/Socket/WinUdpScoket.cpp \
    ../../../Module/xml/XPugiXML/xpugixml.cpp \
    ../../Module/XLangResource_Native.cpp \
    XLangResource_SttNativeMain.cpp \
    ../../Module/Main/Ctrls/SttWgtButton.cpp \
    ../../Module/Main/Ctrls/SttWgtButtonGroup.cpp \
    ../../Module/Main/Ctrls/SttWgtFileMngrGrid.cpp \
    ../../Module/Main/Ctrls/SttWgtNativeMainLinux.cpp \
    ../../Module/Main/Ctrls/SttWgtStyle.cpp \
    ../../Module/Main/Ctrls/SttWgtTabCtrl.cpp \
    ../../Module/Main/Ctrls/SttWgtText.cpp \
    ../../Module/Main/Module/SttWgtBase.cpp \
    ../../Module/Main/Module/SttWgtBaseList.cpp \
    ../../Module/Main/Module/SttWgtCmdExecTool.cpp \
    ../../Module/Main/Module/SttWgtCmdThread.cpp \
    ../../Module/Main/Module/SttWgtFactory.cpp \
    ../../Module/Main/SttXuiData/SttXMainConfigGlobal.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataBase.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataBtnsGroup.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataButton.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataCmd.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataFileMngrGrid.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataFileType.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataFileTypes.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataFont.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataGlobal.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataMainConfig.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataTab.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataTabs.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataTestBtnsGroup.cpp \
    ../../Module/Main/SttXuiData/SttXuiDataText.cpp \
    ../../Module/UI/SCL/QSttSelSclFileWidget.cpp \
    ../../Module/UI/SCL/QSttSelSclIedWidget.cpp \
    ../../Module/UI/SCL/SttSelSclFileGrid.cpp \
    ../../Module/UI/SCL/SttSelSclIedGrid.cpp \
    ../../Module/LiveUpdate/SttLiveUpdateShell.cpp \
    ../../Module/LiveUpdate/SttUpdateCfg.cpp \
    ../../Module/UI/Module/QExBaseListGridBase/QExBaseListComBoxDelegBase.cpp \
    ../../Module/UI/Module/QExBaseListGridBase/QExBaseListGridBase.cpp \
    ../../Module/UI/Module/QExBaseListGridBase/QGridDefine.cpp \
    ../../Module/UI/Module/PopupDialog/SttFileDlgBase.cpp \
    ../../Module/UI/Module/PopupDialog/SttFileMngrTool.cpp \
    ../../Module/UI/Module/PopupDialog/SttFileMngrTree.cpp \
    ../../Module/UI/Module/PopupDialog/SttPopupOpenDialog.cpp \
    ../../Module/UI/Module/ScrollCtrl/ScrollComboBox.cpp \
    ../../Module/UI/Module/ScrollCtrl/ScrollCtrlInterface.cpp \
    ../../Module/UI/Module/ScrollCtrl/ScrollListView.cpp \
    ../../Module/UI/Module/ScrollCtrl/ScrollTreeWidget.cpp \
    ../../Module/UI/Module/ScrollCtrl/ScrollTableWidget.cpp \
    ../../Module/UI/Controls/SttCheckBox.cpp \
    SttNativeMainApplication.cpp \
    ../../Module/Main/SttXMainAppBase.cpp \
    SttNativeMainFrameLinux.cpp \
    ../../Module/Main/SttXMainFrameBase.cpp \
    ../../Module/SttTestBase/SttComplexCalApi.cpp \
    ../../Module/SttTestBase/SttComplexp.cpp \
    ../../Module/SttTestBase/SttMacroXmlKeys.cpp \
    ../../Module/SttTestBase/SttXmlSerialize.cpp \
    ../../Module/SttTestBase/SttXmlSerializeBase.cpp \
    ../../Module/SttSocket/SttCmdOverTimeMngr.cpp \
    ../../Module/SttSocket/SttServerSocketDataBase.cpp \
    ../../Module/SttSocket/SttSocketDataBase.cpp \
    ../../Module/SttSocket/SttSocketDataBase_File.cpp \
    ../../Module/SttCmd/SttAdjustCmd.cpp \
    ../../Module/SttCmd/SttAssistCmd.cpp \
    ../../Module/SttCmd/SttAtsCmd.cpp \
    ../../Module/SttCmd/SttChMap.cpp \
    ../../Module/SttCmd/SttChMaps.cpp \
    ../../Module/SttCmd/SttCmdBase.cpp \
    ../../Module/SttCmd/SttCmdCreator.cpp \
    ../../Module/SttCmd/SttCmdData.cpp \
    ../../Module/SttCmd/SttCmdDefineGlobal.cpp \
    ../../Module/SttCmd/SttDebugCmd.cpp \
    ../../Module/SttCmd/SttHdCh.cpp \
    ../../Module/SttCmd/SttHdChs.cpp \
    ../../Module/SttCmd/SttIotCmd.cpp \
    ../../Module/SttCmd/SttIotDevice.cpp \
    ../../Module/SttCmd/SttIotDevices.cpp \
    ../../Module/SttCmd/SttIotNode.cpp \
    ../../Module/SttCmd/SttIotTopo.cpp \
    ../../Module/SttCmd/SttMacro.cpp \
    ../../Module/SttCmd/SttMsg.cpp \
    ../../Module/SttCmd/SttMsgs.cpp \
    ../../Module/SttCmd/SttParas.cpp \
    ../../Module/SttCmd/SttRemoteCmd.cpp \
    ../../Module/SttCmd/SttRptMapDatas.cpp \
    ../../Module/SttCmd/SttSysState.cpp \
    ../../Module/SttCmd/SttSystemCmd.cpp \
    ../../Module/SttCmd/SttTestCmd.cpp \
    ../../Module/TestClient/SttTestClientBase.cpp \
    ../../Module/Engine/SttClientTestEngine.cpp \
    ../../Module/Engine/SttRemoteClientTestEngine.cpp \
    ../../Module/Engine/SttServerNativeConfig.cpp \
    ../../Module/Engine/SttServerTestCtrlCntr.cpp \
    ../../Module/Engine/SttTestEngineBase.cpp \
    ../../Module/Engine/SttTestEngineClientData.cpp \
    ../../Module/Engine/SttTestEngineRemoteClientData.cpp \
    ../../Module/Engine/SttTestEngineServerBase.cpp \
    ../../Module/Engine/SttTestEngineServerData.cpp \
    ../../Module/SttTestAppConfig/SttTestAppCfg.cpp \
    ../../Module/SttTestAppConfig/SttTestAppConfigTool.cpp \
    ../../Module/SttProtocolBufBase.cpp \
    ../../Module/SttAuthority/SttTestClientUser.cpp \
    ../../Module/SttAuthority/SttTestClientUserMngr.cpp \
    ../../Module/SttAuthority/SttTestRemoteRegister.cpp \
    ../../Module/SttFileToolMngr.cpp \
    ../../Module/SttCmd/GuideBook/SttCommCmd.cpp \
    ../../Module/SttCmd/GuideBook/SttContents.cpp \
    ../../Module/SttCmd/GuideBook/SttDataObj.cpp \
    ../../Module/SttCmd/GuideBook/SttDevice.cpp \
    ../../Module/SttCmd/GuideBook/SttGuideBook.cpp \
    ../../Module/SttCmd/GuideBook/SttItemBase.cpp \
    ../../Module/SttCmd/GuideBook/SttItemRsltExpr.cpp \
    ../../Module/SttCmd/GuideBook/SttItems.cpp \
    ../../Module/SttCmd/GuideBook/SttItemStateObject.cpp \
    ../../Module/SttCmd/GuideBook/SttJobGuide.cpp \
    ../../Module/SttCmd/GuideBook/SttMacroCharItems.cpp \
    ../../Module/SttCmd/GuideBook/SttMacroTest.cpp \
    ../../Module/SttCmd/GuideBook/SttReport.cpp \
    ../../Module/SttCmd/GuideBook/SttReportMap.cpp \
    ../../Module/SttCmd/GuideBook/SttReports.cpp \
    ../../Module/SttCmd/GuideBook/SttRptData.cpp \
    ../../Module/SttCmd/GuideBook/SttSafety.cpp \
    ../../Module/SttCmd/GuideBook/SttSysParaEdit.cpp \
    ../../Module/SttCmd/GuideBook/SttSysParas.cpp \
    ../../Module/SttCmd/GuideBook/SttTestMacroCharParas.cpp \
    ../../Module/SttCmd/GuideBook/SttTestMacroUiParas.cpp \
    ../../Module/SttSocket/TestTerminal/SttClientSocketBase.cpp \
    ../../Module/SttSocket/TestTerminal/VC/SttClientSocket.cpp \
    ../../Module/SttRegisterCode.cpp \
    ../../Module/SttSocket/TestServer/SttTestServerSocketBase.cpp \
    ../../Module/SttSocket/TestServer/QT/SttServerClientSocket.cpp \
    ../../Module/API/NetworkInterface.cpp \
    ../../Module/SttTest/Common/tmt_adjust_sys_parameter.cpp \
    ../../Module/SttTest/Common/tmt_adjust_sys_para_trans.cpp \
    ../../Module/SttTest/SttTestGlobaoConfig.cpp \
    ../../Module/SttSocket/TestServer/SttServerClientSocketBase.cpp \
    ../../../61850/Module/SCL/CcdFileRead.cpp \
    ../../../Module/Expression/XExprRangeEx.cpp
    
HEADERS  += \
    ../../../61850/Module/CfgDataMngr/IecCfgDatasMngr.h \
    ../../../61850/Module/CfgDataMngr/IecCfgGoutDatas.h \
    ../../../61850/Module/CfgDataMngr/IecCfgGoutData.h \
    ../../../61850/Module/CfgDataMngr/IecCfgGoutChs.h \
    ../../../61850/Module/CfgDataMngr/IecCfgGoutCh.h \
    ../../../61850/Module/CfgDataMngr/IecCfgGooseDataBase.h \
    ../../../61850/Module/CfgDataMngr/IecCfgGinDatas.h \
    ../../../61850/Module/CfgDataMngr/IecCfgGinData.h \
    ../../../61850/Module/CfgDataMngr/IecCfgGinChs.h \
    ../../../61850/Module/CfgDataMngr/IecCfgGinCh.h \
    ../../../61850/Module/CfgDataMngr/IecCfgDatasBase.h \
    ../../../61850/Module/CfgDataMngr/IecCfgDataMngrGlobal.h \
    ../../../61850/Module/CfgDataMngr/IecCfgDataGooseChBase.h \
    ../../../61850/Module/CfgDataMngr/IecCfgDataChBase.h \
    ../../../61850/Module/CfgDataMngr/IecCfgDataBase.h \
    ../../../61850/Module/CfgDataMngr/IecCfgChsBase.h \
    ../../../61850/Module/CfgDataMngr/IecCfg92Data.h \
    ../../../61850/Module/CfgDataMngr/IecCfg92ChsIn.h \
    ../../../61850/Module/CfgDataMngr/IecCfg92Chs.h \
    ../../../61850/Module/CfgDataMngr/IecCfgSMVDatas.h \
    ../../../61850/Module/CfgDataMngr/IecCfgSmvDataBase.h \
    ../../../61850/Module/CfgDataMngr/IecCfgGinAppChMaps.h \
    ../../../61850/Module/CfgDataMngr/IecCfgGinAppChMap.h \
    ../../../61850/Module/CfgDataMngr/IecCfg92ChQuality.h \
    ../../../61850/Module/CfgDataMngr/IecCfg92ChIn.h \
    ../../../61850/Module/CfgDataMngr/IecCfg92Ch.h \
    ../../../61850/Module/CfgDataMngr/IecCfg6044Ch.h \
    ../../../61850/Module/CfgDataMngr/IecCfg6044Chs.h \
    ../../../61850/Module/CfgDataMngr/IecCfg6044Data.h \
    ../../../61850/Module/CfgDataMngr/IecCfgDataSmvCommon.h \
    ../../../61850/Module/CfgDataMngr/IecCfg91Ch.h \
    ../../../61850/Module/CfgDataMngr/IecCfg91Chs.h \
    ../../../61850/Module/CfgDataMngr/IecCfg91Data.h \
    ../../../61850/Module/CfgDataMngr/IecCfgSmvRate.h \
    ../../../61850/Module/CfgDataMngr/IecCfgSmvRates.h \
    ../../../61850/Module/CfgDataMngr/IecCfgAdvanceException.h \
    ../../../61850/Module/CfgDataMngr/IecCfgDataSmvChBase.h \
    ../../../61850/Module/CfgDataMngr/IecCfg91StatusDataSet.h \
    ../../../61850/Module/CfgDataMngr/IecCfg91StatusDataSetCh.h \
    ../../../61850/Module/GlobalDataMngr/IecFiberConfig.h \
    ../../../61850/Module/GlobalDataMngr/IecGlobalDataMngr.h \
    ../../../61850/Module/GlobalDataMngr/IecGlobalDataMngrGlobal.h \
    ../../../61850/Module/GlobalDataMngr/IecGooseChDataTypeMngr.h \
    ../../../61850/Module/GlobalDataMngr/IecSmvChDataType.h \
    ../../../61850/Module/XLanguageResourceIec.h \
    ../../../61850/Module/CfgDataMngr/IecCfgSysParas.h \
    ../../../61850/Module/CfgDataMngr/IecCfg6044CommonCh.h \
    ../../../61850/Module/CfgDataMngr/IecCfg6044CommonData.h \
    ../../../61850/Module/CfgDataMngr/IecCfg91StateWord.h \
    ../../../61850/Module/CfgDataMngr/IecCfg91StateWordBit.h \
    ../../../61850/Module/CfgDataMngr/IecCfg91StateWordMngr.h \
   # ../../../61850/Module/CfgDataMngr/IecCfg92InputData.h \
    ../../../61850/Module/CfgDataMngr/IecCfgFiberPara.h \
    ../../../61850/Module/CfgDataMngr/IecCfgFiberParas.h \
    ../../../61850/Module/CfgDataMngr/IecCfgPrimRate.h \
    ../../../61850/Module/CfgDataMngr/IecCfgPrimRates.h \
    ../../../61850/Module/CfgDataMngr/IecCfgSystemConfig.h \
    ../../../Module/OSInterface/QT/stdafx.h \
    ../../../Module/OSInterface/QT/XGlobalDefine_QT.h \
    ../../../Module/OSInterface/QT/CFile_QT.h \
    ../../../Module/OSInterface/QT/CString_QT.h \
    ../../../Module/OSInterface/QT/CTime_QT.h \
    ../../../Module/OSInterface/QT/CXArray_QT.h \
    ../../../Module/OSInterface/QT/CXCtrl_QT.h \
    ../../../Module/OSInterface/QT/CWinThread_QT.h \
    ../../../Module/OSInterface/QT/CXDraw_QT_NOGUI.h \
    ../../../Module/OSInterface/OSInterface.h \
    ../../../Module/OSInterface/QT/std_api_linux.h \
    ../../../Module/OSInterface/QT/CXCtrl_QT_CWinApp.h \
    ../../../Module/OSInterface/QT/CXCtrl_QT_CWnd.h \
    ../../../Module/OSInterface/QT/XMsgCycleBuffer.h \
    ../../../Module/MemBuffer/BufferBase.h \
    ../../../Module/MemBuffer/FormatTextBuffer.h \
    ../../../Module/MemBuffer/CycleMemBufferMngr.h \
    ../../../Module/MemBuffer/TCycleMemBuffer.h \
    ../../../Module/MemBuffer/ExpandMemBuf.h \
    ../../../Module/MemBuffer/StringToSystimeBuffer.h \
    ../../../Module/MemBuffer/CycleMemBuffer.h \
    ../../../Module/MemBuffer/EquationBuffer.h \
    ../../../Module/MemBuffer/EquationKey.h \
    ../../../Module/MemBuffer/XMemBufferBse.h \
    ../../../Module/BaseClass/TLinkList.h \
    ../../../Module/BaseClass/WSerializeBuff.h \
    ../../../Module/BaseClass/SerializeBufferBase.h \
    ../../../Module/BaseClass/BaseObject.h \
    ../../../Module/BaseClass/BinarySerialBuffer.h \
    ../../../Module/BaseClass/BinarySerialInterface.h \
    ../../../Module/BaseClass/ExBaseList.h \
    ../../../Module/BaseClass/ExBaseObject.h \
    ../../../Module/BaseClass/BaseList.h \
    ../../../Module/BaseClass/ComplexNumber.h \
    ../../../Module/BaseClass/StringSerializeBuffer.h \
    ../../../Module/BaseClass/TLinkList_DW.h \
    ../../../Module/BaseClass/XObjectRefBase.h \
    ../../../Module/API/StringApi.h \
    ../../../Module/Log/LogPrint.h \
    ../../../Module/API/GlobalConfigApi.h \
    ../../../Module/API/FileApi.h \
    ../../../Module/API/GlobalApi.h \
    ../../../Module/DataMngr/DataGroup.h \
    ../../../Module/DataMngr/DataMngrGlobal.h \
    ../../../Module/DataMngr/DataType.h \
    ../../../Module/DataMngr/DataTypes.h \
    ../../../Module/DataMngr/DataTypeValue.h \
    ../../../Module/DataMngr/DvmData.h \
    ../../../Module/DataMngr/DvmDataset.h \
    ../../../Module/DataMngr/DvmDevice.h \
    ../../../Module/DataMngr/DvmDevices.h \
    ../../../Module/DataMngr/DvmLog.h \
    ../../../Module/DataMngr/DvmLogicDevice.h \
    ../../../Module/DataMngr/DvmLogs.h \
    ../../../Module/DataMngr/DvmValue.h \
    ../../../Module/DataMngr/LogCtrl.h \
    ../../../Module/DataMngr/LogCtrls.h \
    ../../../Module/DataMngr/LongData.h \
    ../../../Module/DataMngr/LongDatas.h \
    ../../../Module/DataMngr/RptCtrl.h \
    ../../../Module/DataMngr/RptCtrls.h \
    ../../../Module/DataMngr/ShortData.h \
    ../../../Module/DataMngr/ShortDatas.h \
    ../../../Module/DataMngr/Value.h \
    ../../../Module/DataMngr/Values.h \
    ../../../Module/System/TickCount32.h \
    ../../../Module/System/StringTokenizer.h \
    ../../../Module/GpsPcTime/GpsPcTime.h \
    ../../../Module/xml/XmlRWBase.h \
    ../../../Module/xml/XmlRWFactory.h \
    ../../../Module/xml/XmlRW_Pugi.h \
    ../../../Module/xml/PugiXML/pugiconfig.hpp \
    ../../../Module/xml/PugiXML/pugixml.hpp \
    ../../../Module/XLanguage/XLangItem.h \
    ../../../Module/XLanguage/XLanguage.h \
    ../../../Module/XLanguage/XLanguageGlobal.h \
    ../../../Module/XLanguage/XLanguageMngr.h \
    ../../../Module/XLanguage/XLanguageNameParser.h \
    ../../../Module/XLanguage/XLanguageResource.h \
    ../../../Module/API/HexTransApi.h \
    ../../../Module/Expression/EpExpression.h \
    ../../../Module/Expression/EpExpressionGlobal.h \
    ../../../Module/Expression/EpExpressionTool.h \
    ../../../Module/DataMngr/DataMngrTrans.h \
    ../../../Module/Encrypt/XDes2.h \
    ../../../Module/XDrawBase/XDrawArc.h \
    ../../../Module/XDrawBase/XDrawBase.h \
    ../../../Module/XDrawBase/XDrawCircle.h \
    ../../../Module/XDrawBase/XDrawDataDef.h \
    ../../../Module/XDrawBase/XDrawElement.h \
    ../../../Module/XDrawBase/XDrawElements.h \
    ../../../Module/XDrawBase/XDrawGlobal.h \
    ../../../Module/XDrawBase/XDrawLine.h \
    ../../../Module/XDrawBase/XDrawList.h \
    ../../../Module/XDrawBase/XDrawMngr.h \
    ../../../Module/XDrawBase/XDrawMngrDescartes.h \
    ../../../Module/XDrawBase/XDrawMngrLogarithm.h \
    ../../../Module/XDrawBase/XDrawPoint.h \
    ../../../Module/XDrawBase/XDrawPolyline.h \
    ../../../Module/XDrawBase/XDrawViewBase.h \
    ../../../Module/Axis/AxisInterface.h \
    ../../../Module/Axis/DescartesAxis.h \
    ../../../Module/Axis/LogarithmAxis.h \
    ../../../Module/Axis/PolarAxis.h \
    ../../../Module/API/GloblaDrawFunctions.h \
    ../../../Module/StringCmp/StringCmp.h \
    ../../../Module/StringCmp/StringCmpBlock.h \
    ../../../Module/StringCmp/StringCmpBlocks.h \
    ../../../Module/API/MathApi.h \
    ../../../Module/DataMngr/DvmDatasetGroup.h \
    ../../../Module/System/StringTokenizerU.h \
    ../../../Module/Socket/XPing.h \
    ../../../Module/XfileMngrBase/XFileFindEx.h \
    ../../../Module/XfileMngrBase/QT/XFileFindExImp.h \
    ../../../Module/FilterText/FilterText.h \
    ../../../Module/FilterText/FilterTextGlobal.h \
    ../../../Module/FilterText/FilterTextMngr.h \
    ../../../Module/Expression/ExprParse.h \
    ../../../Module/XDrawBase/XDrawLineEx.h \
    ../../../Module/XDrawBase/XDrawPointEx.h \
    ../../../Module/XDrawBase/XDrawText.h \
    ../../../Module/XLanguage/QT/XLanguageAPI_QT.h \
    ../../../Module/xml/JsonRW.h \
    ../../../Module/xml/XmlRWInterface.h \
    ../../../Module/xml/JSON/CJSON.h \
    ../../../Module/API/StringConvert/String_Utf8_To_Gbk.h \
    ../../../Module/API/StringConvert/String_Gbk_To_Utf8.h \
    ../../../61850/Module/CfgDataMngr/IecCfgSmvInDatas.h \
    ../../../61850/Module/CfgDataMngr/IecCfg2MData.h \
    ../../../61850/Module/CfgDataMngr/IecCfg2MInData.h \
    ../../../61850/Module/CfgDataMngr/IecCfg6044CommonChIn.h \
    ../../../61850/Module/CfgDataMngr/IecCfg6044CommonInData.h \
    ../../../61850/Module/CfgDataMngr/IecCfgPrimRatesIn.h \
    ../../../61850/Module/SCL/SclFileMngr/SclFileMngrGlobal.h \
    ../../../61850/Module/SCL/SclFileMngr/XSclFileMngr.h \
    ../../../61850/Module/SCL/SclFileMngr/XSclFileObj.h \
    ../../../61850/Module/SCL_Qt/QScdFileRWDlg.h \
    ../../../61850/Module/SCL_Qt/QSclFileRead.h \
    ../../../61850/Module/SCL/SclIecCfgDatas.h \
    ../../../Module/XfileMngrBase/XFile.h \
    ../../../Module/XfileMngrBase/XFileMngr.h \
    ../../../Module/XfileMngrBase/XFileType.h \
    ../../../Module/XfileMngrBase/XFileTypes.h \
    ../../../Module/XfileMngrBase/XFolder.h \
    ../../../Module/BaseClass/QT/ExBaseListTreeCtrl.h \
    ../../../Module/BaseClass/ThreadProgressInterface.h \
    ../../../Module/OSInterface/QT/CXDraw_QT.h \
    ../../../Module/API/StringConvertApi.h \
    ../../../AutoTest/Module/XLanguageResourceAts.h \
    ../../../61850/Module/XLanguageResourcePp_Mms.h \
    ../../../Module/DataMngr/DvmCmp/DvmCmpKeyDataTypes.h \
    ../../../Module/Expression/XExprNode.h \
    ../../../Module/Expression/XExprBase.h \
    ../../../Module/Expression/XExprGlobal.h \
    ../../../Module/Expression/XExprCal.h \
    ../../../Module/Expression/XExprCmp.h \
    ../../../Module/Expression/XExprError.h \
    ../../../Module/Expression/XExprErrorEx.h \
    ../../../Module/Expression/XExprErrorCombined.h \
    ../../../Module/Expression/XExprRange.h \
    ../../../Module/Expression/XExprValue.h \
    ../../../Module/Expression/XExprValueCal.h \
    ../../../Module/Expression/XExprValueCalEx.h \
    ../../../Module/Expression/XExprValue_Ex.h \
    ../../../Module/DataMngr/DvmValues.h \
    ../../../Module/BaseClass/XTimer.h \
    ../../../Module/Socket/WinBaseSocket.h \
    ../../../Module/Socket/WinTcpSocket.h \
    ../../../Module/Socket/WinTcpSocketClient.h \
    ../../../Module/Socket/WinTcpSocketServer.h \
    ../../../Module/Socket/WinUdpScoket.h \
    ../../../Module/xml/XPugiXML/xpugiconfig.hpp \
    ../../../Module/xml/XPugiXML/xpugixml.hpp \
    ../../Module/XLangResource_Native.h \
    XLangResource_SttNativeMain.h \
    ../../Module/Main/Ctrls/SttWgtButton.h \
    ../../Module/Main/Ctrls/SttWgtButtonGroup.h \
    ../../Module/Main/Ctrls/SttWgtFileMngrGrid.h \
    ../../Module/Main/Ctrls/SttWgtNativeMainLinux.h \
    ../../Module/Main/Ctrls/SttWgtStyle.h \
    ../../Module/Main/Ctrls/SttWgtTabCtrl.h \
    ../../Module/Main/Ctrls/SttWgtText.h \
    ../../Module/Main/Module/SttWgtBase.h \
    ../../Module/Main/Module/SttWgtBaseList.h \
    ../../Module/Main/Module/SttWgtCmdExecTool.h \
    ../../Module/Main/Module/SttWgtCmdThread.h \
    ../../Module/Main/Module/SttWgtFactory.h \
    ../../Module/Main/SttXuiData/SttXMainConfigGlobal.h \
    ../../Module/Main/SttXuiData/SttXuiDataBase.h \
    ../../Module/Main/SttXuiData/SttXuiDataBtnsGroup.h \
    ../../Module/Main/SttXuiData/SttXuiDataButton.h \
    ../../Module/Main/SttXuiData/SttXuiDataCmd.h \
    ../../Module/Main/SttXuiData/SttXuiDataFileMngrGrid.h \
    ../../Module/Main/SttXuiData/SttXuiDataFileType.h \
    ../../Module/Main/SttXuiData/SttXuiDataFileTypes.h \
    ../../Module/Main/SttXuiData/SttXuiDataFont.h \
    ../../Module/Main/SttXuiData/SttXuiDataGlobal.h \
    ../../Module/Main/SttXuiData/SttXuiDataMainConfig.h \
    ../../Module/Main/SttXuiData/SttXuiDataTab.h \
    ../../Module/Main/SttXuiData/SttXuiDataTabs.h \
    ../../Module/Main/SttXuiData/SttXuiDataTestBtnsGroup.h \
    ../../Module/Main/SttXuiData/SttXuiDataText.h \
    ../../Module/UI/SCL/QSttSelSclFileWidget.h \
    ../../Module/UI/SCL/QSttSelSclIedWidget.h \
    ../../Module/UI/SCL/SttSelSclFileGrid.h \
    ../../Module/UI/SCL/SttSelSclIedGrid.h \
    ../../Module/LiveUpdate/SttLiveUpdateDef.h \
    ../../Module/LiveUpdate/SttLiveUpdateShell.h \
    ../../Module/LiveUpdate/SttUpdateCfg.h \
    ../../Module/UI/Module/QExBaseListGridBase/QExBaseListComBoxDelegBase.h \
    ../../Module/UI/Module/QExBaseListGridBase/QExBaseListGridBase.h \
    ../../Module/UI/Module/QExBaseListGridBase/QGridDefine.h \
    ../../Module/UI/Module/PopupDialog/SttFileDlgBase.h \
    ../../Module/UI/Module/PopupDialog/SttFileMngrTool.h \
    ../../Module/UI/Module/PopupDialog/SttFileMngrTree.h \
    ../../Module/UI/Module/PopupDialog/SttPopupOpenDialog.h \
    ../../Module/UI/Module/ScrollCtrl/ScrollComboBox.h \
    ../../Module/UI/Module/ScrollCtrl/ScrollCtrlInterface.h \
    ../../Module/UI/Module/ScrollCtrl/ScrollListView.h \
    ../../Module/UI/Module/ScrollCtrl/ScrollTreeWidget.h \
    ../../Module/UI/Module/ScrollCtrl/ScrollTableWidget.h \
    ../../Module/UI/Controls/SttCheckBox.h \
    SttNativeMainApplication.h \
    ../../Module/Main/SttMainArgvDef.h \
    ../../Module/Main/SttXMainAppBase.h \
    SttNativeMainFrameLinux.h \
    ../../Module/Main/SttXMainFrameBase.h \
    ../../Module/SttTestBase/SttComplexCalApi.h \
    ../../Module/SttTestBase/SttComplexp.h \
    ../../Module/SttTestBase/SttMacroXmlKeys.h \
    ../../Module/SttTestBase/SttXmlSerialize.h \
    ../../Module/SttTestBase/SttXmlSerializeBase.h \
    ../../Module/SttSocket/SttCmdOverTimeMngr.h \
    ../../Module/SttSocket/SttServerSocketDataBase.h \
    ../../Module/SttSocket/SttSocketDataBase.h \
    ../../Module/SttSocket/SttSocketDataBase_File.h \
    ../../Module/SttCmd/SttAdjustCmd.h \
    ../../Module/SttCmd/SttAssistCmd.h \
    ../../Module/SttCmd/SttAtsCmd.h \
    ../../Module/SttCmd/SttChMap.h \
    ../../Module/SttCmd/SttChMaps.h \
    ../../Module/SttCmd/SttCmdBase.h \
    ../../Module/SttCmd/SttCmdCreator.h \
    ../../Module/SttCmd/SttCmdData.h \
    ../../Module/SttCmd/SttCmdDefineGlobal.h \
    ../../Module/SttCmd/SttDebugCmd.h \
    ../../Module/SttCmd/SttHdCh.h \
    ../../Module/SttCmd/SttHdChs.h \
    ../../Module/SttCmd/SttIotCmd.h \
    ../../Module/SttCmd/SttIotDevice.h \
    ../../Module/SttCmd/SttIotDevices.h \
    ../../Module/SttCmd/SttIotNode.h \
    ../../Module/SttCmd/SttIotTopo.h \
    ../../Module/SttCmd/SttMacro.h \
    ../../Module/SttCmd/SttMsg.h \
    ../../Module/SttCmd/SttMsgs.h \
    ../../Module/SttCmd/SttParas.h \
    ../../Module/SttCmd/SttRemoteCmd.h \
    ../../Module/SttCmd/SttRptMapDatas.h \
    ../../Module/SttCmd/SttSysState.h \
    ../../Module/SttCmd/SttSystemCmd.h \
    ../../Module/SttCmd/SttTestCmd.h \
    ../../Module/TestClient/SttMacroTestInterface.h \
    ../../Module/TestClient/SttTestClientBase.h \
    ../../Module/Engine/SttClientTestEngine.h \
    ../../Module/Engine/SttRemoteClientTestEngine.h \
    ../../Module/Engine/SttServerNativeConfig.h \
    ../../Module/Engine/SttServerTestCtrlCntr.h \
    ../../Module/Engine/SttTestEngineBase.h \
    ../../Module/Engine/SttTestEngineClientData.h \
    ../../Module/Engine/SttTestEngineRemoteClientData.h \
    ../../Module/Engine/SttTestEngineServerBase.h \
    ../../Module/Engine/SttTestEngineServerData.h \
    ../../Module/SttTestAppConfig/SttTestAppCfg.h \
    ../../Module/SttTestAppConfig/SttTestAppConfigTool.h \
    ../../Module/SttProtocolBufBase.h \
    ../../Module/SttAuthority/SttTestClientUser.h \
    ../../Module/SttAuthority/SttTestClientUserMngr.h \
    ../../Module/SttAuthority/SttTestRemoteRegister.h \
    ../../Module/SttFileToolMngr.h \
    ../../Module/SttCmd/GuideBook/SttCommCmd.h \
    ../../Module/SttCmd/GuideBook/SttContents.h \
    ../../Module/SttCmd/GuideBook/SttDataObj.h \
    ../../Module/SttCmd/GuideBook/SttDevice.h \
    ../../Module/SttCmd/GuideBook/SttGuideBook.h \
    ../../Module/SttCmd/GuideBook/SttItemBase.h \
    ../../Module/SttCmd/GuideBook/SttItemRsltExpr.h \
    ../../Module/SttCmd/GuideBook/SttItems.h \
    ../../Module/SttCmd/GuideBook/SttItemStateObject.h \
    ../../Module/SttCmd/GuideBook/SttJobGuide.h \
    ../../Module/SttCmd/GuideBook/SttMacroCharItems.h \
    ../../Module/SttCmd/GuideBook/SttMacroTest.h \
    ../../Module/SttCmd/GuideBook/SttReport.h \
    ../../Module/SttCmd/GuideBook/SttReportMap.h \
    ../../Module/SttCmd/GuideBook/SttReports.h \
    ../../Module/SttCmd/GuideBook/SttRptData.h \
    ../../Module/SttCmd/GuideBook/SttSafety.h \
    ../../Module/SttCmd/GuideBook/SttSysParaEdit.h \
    ../../Module/SttCmd/GuideBook/SttSysParas.h \
    ../../Module/SttCmd/GuideBook/SttTestMacroCharParas.h \
    ../../Module/SttCmd/GuideBook/SttTestMacroUiParas.h \
    ../../Module/SttSocket/TestTerminal/SttClientSocketBase.h \
    ../../Module/SttSocket/TestTerminal/VC/SttClientSocket.h \
    ../../Module/SttRegisterCode.h \
    ../../Module/SttSocket/TestServer/SttTestServerSocketBase.h \
    ../../Module/SttSocket/TestServer/QT/SttServerClientSocket.h \
    ../../Module/API/NetworkInterface.h \
    ../../Module/SttTest/Common/tmt_adjust_sys_parameter.h \
    ../../Module/SttTest/Common/tmt_adjust_sys_para_trans.h \
    ../../Module/SttTest/Common/tmt_common_def.h \
    ../../Module/SttTest/SttTestGlobaoConfig.h \
    ../../Module/SttSocket/TestServer/SttServerClientSocketBase.h \
    ../../../61850/Module/SCL/CcdFileRead.h \
    ../../../Module/Expression/XExprRangeEx.h

FORMS += 

RESOURCES += \
    SttNativeMain.qrc
