#include "stdafx.h"
#include "XLangResource_Native.h"

const CString CXLangResource_Native::g_strXLangRs_Test = _T("Lang_NativeTest");

CXLangResource_Native::CXLangResource_Native()
{
    m_pXLangRsExe = &m_oXLangRs_Test;
    m_oXLangRs_Test.m_strID = g_strXLangRs_Test;
    m_oXLangRs_Test.m_strName = g_strXLangRs_Test;
}

CXLangResource_Native::~CXLangResource_Native()
{
    m_oXLangRs_Test.RemoveAll();
}


CXLangItem* CXLangResource_Native::rs_AddString(const CString &strID, CString *pstrString)
{
    CXLangItem *p = CXLanguage::AddString(strID, pstrString);

    m_oXLangRs_Test.AddTail(p);

    return p;
}


void CXLangResource_Native::InitLangRsByFile()
{
    CXLanguageResourceBase::InitLangRsByFile();

    InitLangRsByFileEx(&m_oXLangRs_Test, g_strXLangRs_Test);
}


void CXLangResource_Native::RegisterLanguageResource()
{
    CXLanguageResourceBase::RegisterLanguageResource();
	rs_AddString(g_sLangID_Native_Amplitude, &g_sLangTxt_Native_Amplitude);
	rs_AddString(g_sLangID_Native_Phase, &g_sLangTxt_Native_Phase);
	rs_AddString(g_sLangID_Native_Freq, &g_sLangTxt_Native_Freq);
	rs_AddString(g_sLangID_Native_Channel, &g_sLangTxt_Native_Channel);
	rs_AddString(g_sLangID_Native_DC, &g_sLangTxt_Native_DC);
	rs_AddString(g_sLangID_Native_Fundamental, &g_sLangTxt_Native_Fundamental);
	rs_AddString(g_sLangID_Harm_Set, &g_sLangTxt_Harm_Set);
	rs_AddString(g_sLangID_Harm_Content, &g_sLangTxt_Harm_Content);
	rs_AddString(g_sLangID_Harm_Enable, &g_sLangTxt_Harm_Enable);
	rs_AddString(g_sLangID_Harm_UChannel, &g_sLangTxt_Harm_UChannel);
	rs_AddString(g_sLangID_Harm_IChannel, &g_sLangTxt_Harm_IChannel);
	rs_AddString(g_sLangID_Harm_Reset, &g_sLangTxt_Harm_Reset);
	rs_AddString(g_sLangID_Harm_FundFreq, &g_sLangTxt_Harm_FundFreq);
	rs_AddString(g_sLangID_Harm_Times, &g_sLangTxt_Harm_Times);
	rs_AddString(g_sLangID_Native_OK, &g_sLangTxt_Native_OK);
	rs_AddString(g_sLangID_Native_Cancel, &g_sLangTxt_Native_Cancel);
	rs_AddString(g_sLangID_Native_GndA, &g_sLangTxt_Native_GndA);
	rs_AddString(g_sLangID_Native_GndB, &g_sLangTxt_Native_GndB);
	rs_AddString(g_sLangID_Native_GndC, &g_sLangTxt_Native_GndC);
	rs_AddString(g_sLangID_Native_ShortAB, &g_sLangTxt_Native_ShortAB);
	rs_AddString(g_sLangID_Native_ShortBC, &g_sLangTxt_Native_ShortBC);
	rs_AddString(g_sLangID_Native_ShortCA, &g_sLangTxt_Native_ShortCA);
	rs_AddString(g_sLangID_Native_GndShortAB, &g_sLangTxt_Native_GndShortAB);
	rs_AddString(g_sLangID_Native_GndShortBC, &g_sLangTxt_Native_GndShortBC);
	rs_AddString(g_sLangID_Native_GndShortCA, &g_sLangTxt_Native_GndShortCA);
	rs_AddString(g_sLangID_Native_ShortABC, &g_sLangTxt_Native_ShortABC);
	rs_AddString(g_sLangID_Native_SinglePhase, &g_sLangTxt_Native_SinglePhase);
	rs_AddString(g_sLangID_Native_INotChange, &g_sLangTxt_Native_INotChange);
	rs_AddString(g_sLangID_Native_UNotChange, &g_sLangTxt_Native_UNotChange);
	rs_AddString(g_sLangID_Native_ZNotChange, &g_sLangTxt_Native_ZNotChange);	
	rs_AddString(g_sLangID_Native_UZoomOut, &g_sLangTxt_Native_UZoomOut);
	rs_AddString(g_sLangID_Native_UZoomIn, &g_sLangTxt_Native_UZoomIn);
	rs_AddString(g_sLangID_Native_IZoomOut, &g_sLangTxt_Native_IZoomOut);
	rs_AddString(g_sLangID_Native_IZoomIn, &g_sLangTxt_Native_IZoomIn);
	rs_AddString(g_sLangID_Native_PhaseA, &g_sLangTxt_Native_PhaseA);
	rs_AddString(g_sLangID_Native_PhaseB, &g_sLangTxt_Native_PhaseB);
	rs_AddString(g_sLangID_Native_PhaseC, &g_sLangTxt_Native_PhaseC);
	rs_AddString(g_sLangID_Native_PhaseO, &g_sLangTxt_Native_PhaseO);
	rs_AddString(g_sLangID_Native_Relay, &g_sLangTxt_Native_Relay);
	rs_AddString(g_sLangID_Native_Measure, &g_sLangTxt_Native_Measure);
	rs_AddString(g_sLangID_Native_Current, &g_sLangTxt_Native_Current);
	rs_AddString(g_sLangID_Native_Voltage, &g_sLangTxt_Native_Voltage);
	rs_AddString(g_sLangID_Native_EDPhaseV, &g_sLangTxt_Native_EDPhaseV);
	rs_AddString(g_sLangID_Native_EDCurrent, &g_sLangTxt_Native_EDCurrent);
	rs_AddString(g_sLangID_Native_EqualAmp, &g_sLangTxt_Native_EqualAmp);
	rs_AddString(g_sLangID_Native_EqualFreq, &g_sLangTxt_Native_EqualFreq);
	rs_AddString(g_sLangID_Native_PositiveSeq, &g_sLangTxt_Native_PositiveSeq);
	rs_AddString(g_sLangID_Native_NegativeSeq, &g_sLangTxt_Native_NegativeSeq);
	rs_AddString(g_sLangID_Native_ZeroSeq, &g_sLangTxt_Native_ZeroSeq);
	rs_AddString(g_sLangID_Native_Zero, &g_sLangTxt_Native_Zero);
	rs_AddString(g_sLangID_Native_AllGroup, &g_sLangTxt_Native_AllGroup);
	rs_AddString(g_sLangID_Native_CurGroup, &g_sLangTxt_Native_CurGroup);
	rs_AddString(g_sLangID_Native_LastGroup, &g_sLangTxt_Natve_LastGroup);
	rs_AddString(g_sLangID_Native_NextGroup, &g_sLangTxt_Natve_NextGroup);
	rs_AddString(g_sLangID_Native_ExBinSet, &g_sLangTxt_Native_ExBinSet);
	rs_AddString(g_sLangID_Native_ExBoutSet, &g_sLangTxt_Native_ExBoutSet);
	rs_AddString(g_sLangID_Native_GooseDataSet, &g_sLangTxt_Native_GooseDataSet);
	rs_AddString(g_sLangID_Native_Bin, &g_sLangTxt_Native_Bin);
	rs_AddString(g_sLangID_Native_Bout, &g_sLangTxt_Native_Bout);
	rs_AddString(g_sLangID_Native_BinEx, &g_sLangTxt_Native_BinEx);
	rs_AddString(g_sLangID_Native_BoutEx, &g_sLangTxt_Native_BoutEx);
	rs_AddString(g_sLangID_Native_Time, &g_sLangTxt_Native_Time);
	rs_AddString(g_sLangID_Native_Index, &g_sLangTxt_Native_Index);
	rs_AddString(g_sLangID_Native_ActType, &g_sLangTxt_Native_ActType);
	rs_AddString(g_sLangID_Native_ActionTime, &g_sLangTxt_Native_ActionTime);
	rs_AddString(g_sLangID_Native_ReturnVal, &g_sLangTxt_Native_ReturnVal);
	rs_AddString(g_sLangID_Native_ReturnCoeff, &g_sLangTxt_Native_ReturnCoeff);
	rs_AddString(g_sLangID_Native_CurTypeIdx, &g_sLangTxt_Native_CurTypeIdx);
	rs_AddString(g_sLangID_Native_Group, &g_sLangTxt_Native_Group);
	rs_AddString(g_sLangID_Native_LangSetting, &g_sLangTxt_Native_LangSetting);
	rs_AddString(g_sLangID_Native_LangTip, &g_sLangTxt_Native_LangTip);
	rs_AddString(g_sLangID_Native_LangTipContext, &g_sLangTxt_Native_LangTipContext);
	rs_AddString(g_sLangID_Native_SelectAll, &g_sLangTxt_Native_SelectAll);
	rs_AddString(g_sLangID_Native_Reverse, &g_sLangTxt_Native_Reverse);
	rs_AddString(g_sLangID_Native_Repair, &g_sLangTxt_Native_Repair);
	rs_AddString(g_sLangID_Native_IEDName, &g_sLangTxt_Native_IEDName);
	rs_AddString(g_sLangID_Native_APPID, &g_sLangTxt_Native_APPID);
	rs_AddString(g_sLangID_Native_CommonPara,&g_sLangTxt_Native_CommonPara);
	rs_AddString(g_sLangID_Native_Type,&g_sLangTxt_Native_Type);
	rs_AddString(g_sLangID_Native_LogicOr, &g_sLangTxt_Native_LogicOr);
	rs_AddString(g_sLangID_Native_LogicAnd, &g_sLangTxt_Native_LogicAnd);
	rs_AddString(g_sLangID_Native_Delete, &g_sLangTxt_Native_Delete);
	rs_AddString(g_sLangID_Native_Enter, &g_sLangTxt_Native_Enter);	
	rs_AddString(g_sLangID_Native_Esc, &g_sLangTxt_Native_Esc);	
	rs_AddString(g_sLangID_Native_State, &g_sLangTxt_Native_State);
	rs_AddString(g_sLangID_Native_Group, &g_sLangTxt_Native_Group);
	rs_AddString(g_sLangID_Native_Caps, &g_sLangTxt_Native_Caps);
	rs_AddString(g_sLangID_Native_Space, &g_sLangTxt_Native_Space);

	rs_AddString(g_sLangID_Manual_IV, &g_sLangTxt_Manual_IV);
	rs_AddString(g_sLangID_Manual_OtherParam, &g_sLangTxt_Manual_OtherParam);
	rs_AddString(g_sLangID_Manual_Changing, &g_sLangTxt_Manual_Changing);
	rs_AddString(g_sLangID_Manual_InitVal, &g_sLangTxt_Manual_InitVal);
	rs_AddString(g_sLangID_Manual_ChangeType, &g_sLangTxt_Manual_ChangeType);
	rs_AddString(g_sLangID_Manual_Channel, &g_sLangTxt_Manual_Channel);
	rs_AddString(g_sLangID_Manual_FinishVal, &g_sLangTxt_Manual_FinishVal);
	rs_AddString(g_sLangID_Manual_Step, &g_sLangTxt_Manual_Step);
	rs_AddString(g_sLangID_Manual_Timer, &g_sLangTxt_Manual_Timer);
	rs_AddString(g_sLangID_Manual_Old, &g_sLangTxt_Manual_Old);
	rs_AddString(g_sLangID_Manual_Auto, &g_sLangTxt_Manual_Auto);
	rs_AddString(g_sLangID_Manual_Delayed, &g_sLangTxt_Manual_Delayed);
	rs_AddString(g_sLangID_Manual_OutSetting, &g_sLangTxt_Manual_OutSetting);
	rs_AddString(g_sLangID_Manual_Out1, &g_sLangTxt_Manual_Out1);
	rs_AddString(g_sLangID_Manual_Out2, &g_sLangTxt_Manual_Out2);
	rs_AddString(g_sLangID_Manual_Out3, &g_sLangTxt_Manual_Out3);
	rs_AddString(g_sLangID_Manual_Out4, &g_sLangTxt_Manual_Out4);
	rs_AddString(g_sLangID_Manual_Out5, &g_sLangTxt_Manual_Out5);
	rs_AddString(g_sLangID_Manual_Out6, &g_sLangTxt_Manual_Out6);
	rs_AddString(g_sLangID_Manual_Out7, &g_sLangTxt_Manual_Out7);
	rs_AddString(g_sLangID_Manual_Out8, &g_sLangTxt_Manual_Out8);
	rs_AddString(g_sLangID_Manual_InSetting, &g_sLangTxt_Manual_InSetting);
	rs_AddString(g_sLangID_Manual_InA, &g_sLangTxt_Manual_InA);
	rs_AddString(g_sLangID_Manual_InB, &g_sLangTxt_Manual_InB);
	rs_AddString(g_sLangID_Manual_InC, &g_sLangTxt_Manual_InC);
	rs_AddString(g_sLangID_Manual_InD, &g_sLangTxt_Manual_InD);
	rs_AddString(g_sLangID_Manual_InE, &g_sLangTxt_Manual_InE);
	rs_AddString(g_sLangID_Manual_InF, &g_sLangTxt_Manual_InF);
	rs_AddString(g_sLangID_Manual_InG, &g_sLangTxt_Manual_InG);
	rs_AddString(g_sLangID_Manual_InH, &g_sLangTxt_Manual_InH);
	rs_AddString(g_sLangID_Manual_Lock, &g_sLangTxt_Manual_Lock);
	rs_AddString(g_sLangID_Manual_UnLock, &g_sLangTxt_Manual_UnLock);
	rs_AddString(g_sLangID_Native_Action, &g_sLangTxt_Native_Action);
	rs_AddString(g_sLangID_Manual_ActionTime, &g_sLangTxt_Manual_ActionTime);
	rs_AddString(g_sLangID_Manual_ReturnTime, &g_sLangTxt_Manual_ReturnTime);
	rs_AddString(g_sLangID_Manual_S_E, &g_sLangTxt_Manual_S_E);
	rs_AddString(g_sLangID_Manual_S_E_S, &g_sLangTxt_Manual_S_E_S);

	rs_AddString(g_sLangID_State_TrigerSetup, &g_sLangTxt_State_TrigerSetup);
	rs_AddString(g_sLangID_State_TrigerCondition, &g_sLangTxt_State_TrigerCondition);
	rs_AddString(g_sLangID_State_OutTime, &g_sLangTxt_State_OutTime);
	rs_AddString(g_sLangID_State_TrigerTime, &g_sLangTxt_State_TrigerTime);
	rs_AddString(g_sLangID_State_Hour, &g_sLangTxt_State_Hour);
	rs_AddString(g_sLangID_State_Minute, &g_sLangTxt_State_Minute);
	rs_AddString(g_sLangID_State_Second, &g_sLangTxt_State_Second);
	rs_AddString(g_sLangID_State_TrigerHoldTime, &g_sLangTxt_State_TrigerHoldTime);
	rs_AddString(g_sLangID_State_HoldTime, &g_sLangTxt_State_HoldTime);
	rs_AddString(g_sLangID_State_ShortCalc, &g_sLangTxt_State_ShortCalc);
	rs_AddString(g_sLangID_State_GradientSet, &g_sLangTxt_State_GradientSet);
	rs_AddString(g_sLangID_State_PasteStateBf, &g_sLangTxt_State_PasteStateBf);
	rs_AddString(g_sLangID_State_InsertStateBf, &g_sLangTxt_State_InsertStateBf);
	rs_AddString(g_sLangID_State_InsertStateAf, &g_sLangTxt_State_InsertStateAf);
	rs_AddString(g_sLangID_State_PasteStateAf, &g_sLangTxt_State_PasteStateAf);
	rs_AddString(g_sLangID_State_CopyCurState, &g_sLangTxt_State_CopyCurState);
	rs_AddString(g_sLangID_State_DeleteCurState, &g_sLangTxt_State_DeleteCurState);
	rs_AddString(g_sLangID_State_UISet, &g_sLangTxt_State_UISet);
	rs_AddString(g_sLangID_State_StateParaSet, &g_sLangTxt_State_StateParaSet);
	rs_AddString(g_sLangID_State_HarmSet, &g_sLangTxt_State_HarmSet);
	rs_AddString(g_sLangID_State_JudgeCondition, &g_sLangTxt_State_JudgeCondition);
	rs_AddString(g_sLangID_State_DCOffSet, &g_sLangTxt_State_DCOffSet);
	rs_AddString(g_sLangID_State_Tou, &g_sLangTxt_State_Tou);
	rs_AddString(g_sLangID_State_RepeatTimes, &g_sLangTxt_State_RepeatTimes);
	rs_AddString(g_sLangID_State_ChGroup, &g_sLangTxt_State_ChGroup);
	rs_AddString(g_sLangID_State_FaultType, &g_sLangTxt_State_FaultType);
	rs_AddString(g_sLangID_State_CalcMode, &g_sLangTxt_State_CalcMode);
	rs_AddString(g_sLangID_State_ShortI, &g_sLangTxt_State_ShortI);
	rs_AddString(g_sLangID_State_ShortU, &g_sLangTxt_State_ShortU);
	rs_AddString(g_sLangID_State_ZeroCoeff, &g_sLangTxt_State_ZeroCoeff);
	rs_AddString(g_sLangID_State_CalcType, &g_sLangTxt_State_CalcType);
	rs_AddString(g_sLangID_State_Amp, &g_sLangTxt_State_Amp);
	rs_AddString(g_sLangID_State_Angle, &g_sLangTxt_State_Angle);
	rs_AddString(g_sLangID_LoadI, &g_sLangTxt_LoadI);
	rs_AddString(g_sLangID_State_LoadAngle, &g_sLangTxt_State_LoadAngle);
	rs_AddString(g_sLangID_State_Trigger_Time, &g_sLangTxt_State_Trigger_Time);
	rs_AddString(g_sLangID_State_Trigger_TimeAndBin, &g_sLangTxt_State_Trigger_TimeAndBin);
	rs_AddString(g_sLangID_State_Trigger_Bin, &g_sLangTxt_State_Trigger_Bin);
	rs_AddString(g_sLangID_State_Trigger_Manu, &g_sLangTxt_State_Trigger_Manu);
	rs_AddString(g_sLangID_State_Trigger_GPSB, &g_sLangTxt_State_Trigger_GPSB);
	rs_AddString(g_sLangID_State_LinearChange, &g_sLangTxt_State_LinearChange);
	rs_AddString(g_sLangID_State_StepChange, &g_sLangTxt_State_StepChange);
	rs_AddString(g_sLangID_State_StepTime, &g_sLangTxt_State_StepTime);
	rs_AddString(g_sLangID_State_SelectChannel, &g_sLangTxt_State_SelectChannel);
	rs_AddString(g_sLangID_State_BeginVal, &g_sLangTxt_State_BeginVal);
	rs_AddString(g_sLangID_State_EndVal, &g_sLangTxt_State_EndVal);
	rs_AddString(g_sLangID_State_Step, &g_sLangTxt_State_Step);
	rs_AddString(g_sLangID_State_AmpGradient, &g_sLangTxt_State_AmpGradient);
	rs_AddString(g_sLangID_State_FreqGradient, &g_sLangTxt_State_FreqGradient);
	rs_AddString(g_sLangID_State_LastState, &g_sLangTxt_State_LastState);
	rs_AddString(g_sLangID_State_FirstState, &g_sLangTxt_State_FirstState);
	rs_AddString(g_sLangID_State_No, &g_sLangTxt_State_No);
	rs_AddString(g_sLangID_State_Yes, &g_sLangTxt_State_Yes);
	rs_AddString(g_sLangID_State_HarmCount, &g_sLangTxt_State_HarmCount);
	rs_AddString(g_sLangID_Gradient_Var, &g_sLangTxt_Gradient_Var);
	rs_AddString(g_sLangID_Gradient_VarType, &g_sLangTxt_Gradient_VarType);
	rs_AddString(g_sLangID_Gradient_Phase, &g_sLangTxt_Gradient_Phase);
	rs_AddString(g_sLangID_Gradient_Init, &g_sLangTxt_Gradient_Init);
	rs_AddString(g_sLangID_Gradient_Finish, &g_sLangTxt_Gradient_Finish);
	rs_AddString(g_sLangID_Gradient_Step, &g_sLangTxt_Gradient_Step);
	rs_AddString(g_sLangID_Gradient_Time, &g_sLangTxt_Gradient_Time);
	rs_AddString(g_sLangID_Gradient_Direction, &g_sLangTxt_Gradient_Direction);
	rs_AddString(g_sLangID_Gradient_MaxAngle, &g_sLangTxt_Gradient_MaxAngle);
	rs_AddString(g_sLangID_Gradient_Clockwise, &g_sLangTxt_Gradient_Clockwise);    
	rs_AddString(g_sLangID_Gradient_Anticlockwise, &g_sLangTxt_Gradient_Anticlockwise);
	rs_AddString(g_sLangID_Gradient_AllFreq, &g_sLangTxt_Gradient_AllFreq);
	rs_AddString(g_sLangID_Gradient_TimeBeforeChange, &g_sLangTxt_Gradient_TimeBeforeChange);
	rs_AddString(g_sLangID_Gradient_TimeBeforeFail, &g_sLangTxt_Gradient_TimeBeforeFail);
	rs_AddString(g_sLangID_Gradient_CurBeforeChange, &g_sLangTxt_Gradient_CurBeforeChange);
	rs_AddString(g_sLangID_Gradient_Normal, &g_sLangTxt_Gradient_Normal);
	rs_AddString(g_sLangID_Gradient_Failure, &g_sLangTxt_Gradient_Failure);

	rs_AddString(g_sLangID_Report_TestChoose, &g_sLangTxt_Report_TestChoose);
	rs_AddString(g_sLangID_Report_TestObjInf, &g_sLangTxt_Report_TestObjInf);
	rs_AddString(g_sLangID_Report_SubInfo, &g_sLangTxt_Report_SubInfo);
	rs_AddString(g_sLangID_Report_SubName, &g_sLangTxt_Report_SubName);
	rs_AddString(g_sLangID_Report_SubAdd, &g_sLangTxt_Report_SubAdd);
	rs_AddString(g_sLangID_Report_ReturnName, &g_sLangTxt_Report_ReturnName);
	rs_AddString(g_sLangID_Report_ReturnAdd, &g_sLangTxt_Report_ReturnAdd);
	rs_AddString(g_sLangID_Report_Tester, &g_sLangTxt_Report_Tester);
	rs_AddString(g_sLangID_Report_ReportTitle, &g_sLangTxt_Report_ReportTitle);
	rs_AddString(g_sLangID_Report_DeviceName, &g_sLangTxt_Report_DeviceName);
	rs_AddString(g_sLangID_Report_DeviceInfo, &g_sLangTxt_Report_DeviceInfo);
	rs_AddString(g_sLangID_Report_DeviceType, &g_sLangTxt_Report_DeviceType);
	rs_AddString(g_sLangID_Report_DevAddress, &g_sLangTxt_Report_DevAddress);
	rs_AddString(g_sLangID_Report_Manufacturer, &g_sLangTxt_Report_Manufacturer);
	rs_AddString(g_sLangID_Report_SeniorNum, &g_sLangTxt_Report_SeniorNum);
	rs_AddString(g_sLangID_Report_CusOrdNum, &g_sLangTxt_Report_CusOrdNum);
	rs_AddString(g_sLangID_Report_AdditionalInfo, &g_sLangTxt_Report_AdditionalInfo);
	rs_AddString(g_sLangID_Report_RatedValue, &g_sLangTxt_Report_RatedValue);
	rs_AddString(g_sLangID_Report_TestEquInfo, &g_sLangTxt_Report_TestEquInfo);
	rs_AddString(g_sLangID_Report_DUTs, &g_sLangTxt_Report_DUTs);
	rs_AddString(g_sLangID_Report_Title, &g_sLangTxt_Report_Title);
}

CString CXLangResource_Native::g_sLangID_Native_LangSetting                 = _T("Native_LangSetting");
CString CXLangResource_Native::g_sLangTxt_Native_LangSetting                = _T("语言设置");
CString CXLangResource_Native::g_sLangID_Native_LangTip                 = _T("Native_LangTip");
CString CXLangResource_Native::g_sLangTxt_Native_LangTip                = _T("提示");
CString CXLangResource_Native::g_sLangID_Native_LangTipContext                 = _T("Native_LangTipContext");
CString CXLangResource_Native::g_sLangTxt_Native_LangTipContext                = _T("语言设置重启后生效");

CString CXLangResource_Native::g_sLangID_Native_Amplitude                 = _T("Native_Amplitude");		
CString CXLangResource_Native::g_sLangTxt_Native_Amplitude                 = _T("幅值");
CString CXLangResource_Native::g_sLangID_Native_Phase                 = _T("Native_Angle");
CString CXLangResource_Native::g_sLangTxt_Native_Phase                 = _T("相位");
CString CXLangResource_Native::g_sLangID_Native_Freq                 = _T("Native_Freq");
CString CXLangResource_Native::g_sLangTxt_Native_Freq                 = _T("频率");
CString CXLangResource_Native::g_sLangID_Native_Channel                = _T("Native_Channel");
CString CXLangResource_Native::g_sLangTxt_Native_Channel                 = _T("通道");
CString CXLangResource_Native::g_sLangID_Native_DC                 = _T("Native_DC");
CString CXLangResource_Native::g_sLangTxt_Native_DC                 = _T("直流");
CString CXLangResource_Native::g_sLangID_Native_Fundamental             = _T("Native_Fundamental");
CString CXLangResource_Native::g_sLangTxt_Native_Fundamental            = _T("基波");

CString CXLangResource_Native::g_sLangID_Harm_Set                = _T("Harm_Set");
CString CXLangResource_Native::g_sLangTxt_Harm_Set                 = _T("谐波设置");
CString CXLangResource_Native::g_sLangID_Harm_Content               = _T("Harm_Content");
CString CXLangResource_Native::g_sLangTxt_Harm_Content                 = _T("谐波含有率");
CString CXLangResource_Native::g_sLangID_Harm_Enable                    = _T("Harm_Enable");
CString CXLangResource_Native::g_sLangTxt_Harm_Enable                      = _T("使能");
CString CXLangResource_Native::g_sLangID_Harm_UChannel                    = _T("Harm_UChannel");
CString CXLangResource_Native::g_sLangTxt_Harm_UChannel                      = _T("电压通道");
CString CXLangResource_Native::g_sLangID_Harm_IChannel                    = _T("Harm_IChannel");
CString CXLangResource_Native::g_sLangTxt_Harm_IChannel                      = _T("电流通道");
CString CXLangResource_Native::g_sLangID_Harm_Reset                    = _T("Harm_Reset");
CString CXLangResource_Native::g_sLangTxt_Harm_Reset                      = _T("谐波清零");
CString CXLangResource_Native::g_sLangID_Harm_FundFreq                    = _T("Harm_FundFreq");
CString CXLangResource_Native::g_sLangTxt_Harm_FundFreq                     = _T("基波频率");
CString CXLangResource_Native::g_sLangID_Harm_Times                   = _T("Harm_Times");
CString CXLangResource_Native::g_sLangTxt_Harm_Times                     = _T("次");

CString CXLangResource_Native::g_sLangID_Native_PhaseA	= _T("Native_PhaseA");
CString CXLangResource_Native::g_sLangTxt_Native_PhaseA	= _T("A相");
CString CXLangResource_Native::g_sLangID_Native_PhaseB	= _T("Native_PhaseB");
CString CXLangResource_Native::g_sLangTxt_Native_PhaseB	= _T("B相");
CString CXLangResource_Native::g_sLangID_Native_PhaseC	= _T("Native_PhaseC");
CString CXLangResource_Native::g_sLangTxt_Native_PhaseC	= _T("C相");
CString CXLangResource_Native::g_sLangID_Native_PhaseO	= _T("Native_PhaseO");
CString CXLangResource_Native::g_sLangTxt_Native_PhaseO	= _T("0相");
CString CXLangResource_Native::g_sLangID_Native_Relay	= _T("Native_Relay");
CString CXLangResource_Native::g_sLangTxt_Native_Relay	= _T("保护");
CString CXLangResource_Native::g_sLangID_Native_Measure	= _T("Native_Measure");
CString CXLangResource_Native::g_sLangTxt_Native_Measure= _T("测量");
CString CXLangResource_Native::g_sLangID_Native_Current	= _T("Native_Current");
CString CXLangResource_Native::g_sLangTxt_Native_Current= _T("电流");
CString CXLangResource_Native::g_sLangID_Native_Voltage	= _T("Native_Voltage");
CString CXLangResource_Native::g_sLangTxt_Native_Voltage= _T("电压");
CString CXLangResource_Native::g_sLangID_Native_OK			=_T("Native_OK");
CString CXLangResource_Native::g_sLangTxt_Native_OK			=_T("确定");
CString CXLangResource_Native::g_sLangID_Native_Cancel			=_T("Native_Cancel");
CString CXLangResource_Native::g_sLangTxt_Native_Cancel			=_T("取消");
CString CXLangResource_Native::g_sLangID_Native_GndA	= _T("Native_GndA");
CString CXLangResource_Native::g_sLangTxt_Native_GndA	= _T("A相接地");
CString CXLangResource_Native::g_sLangID_Native_GndB	= _T("Native_GndB");
CString CXLangResource_Native::g_sLangTxt_Native_GndB	= _T("B相接地");
CString CXLangResource_Native::g_sLangID_Native_GndC	= _T("Native_GndC");
CString CXLangResource_Native::g_sLangTxt_Native_GndC	= _T("C相接地");
CString CXLangResource_Native::g_sLangID_Native_ShortAB	= _T("Native_ShortAB");
CString CXLangResource_Native::g_sLangTxt_Native_ShortAB	= _T("AB短路");
CString CXLangResource_Native::g_sLangID_Native_ShortBC	= _T("Native_ShortBC");
CString CXLangResource_Native::g_sLangTxt_Native_ShortBC	= _T("BC短路");
CString CXLangResource_Native::g_sLangID_Native_ShortCA	= _T("Native_ShortCA");
CString CXLangResource_Native::g_sLangTxt_Native_ShortCA= _T("CA短路");
CString CXLangResource_Native::g_sLangID_Native_GndShortAB	= _T("Native_GndShortAB");
CString CXLangResource_Native::g_sLangTxt_Native_GndShortAB	= _T("AB接地短路");
CString CXLangResource_Native::g_sLangID_Native_GndShortBC	= _T("Native_GndShortBC");
CString CXLangResource_Native::g_sLangTxt_Native_GndShortBC	= _T("BC接地短路");
CString CXLangResource_Native::g_sLangID_Native_GndShortCA	= _T("Native_GndShortCA");
CString CXLangResource_Native::g_sLangTxt_Native_GndShortCA	= _T("CA接地短路");
CString CXLangResource_Native::g_sLangID_Native_ShortABC	= _T("Native_ShortABC");
CString CXLangResource_Native::g_sLangTxt_Native_ShortABC	= _T("三相短路");
CString CXLangResource_Native::g_sLangID_Native_SinglePhase	= _T("Native_SinglePhase");
CString CXLangResource_Native::g_sLangTxt_Native_SinglePhase	= _T("单相系统");
CString CXLangResource_Native::g_sLangID_Native_INotChange	= _T("Native_INotChange");
CString CXLangResource_Native::g_sLangTxt_Native_INotChange	= _T("电流不变");
CString CXLangResource_Native::g_sLangID_Native_UNotChange	= _T("Native_UNotChange");
CString CXLangResource_Native::g_sLangTxt_Native_UNotChange	= _T("电压不变");
CString CXLangResource_Native::g_sLangID_Native_ZNotChange	= _T("Native_ZNotChange");
CString CXLangResource_Native::g_sLangTxt_Native_ZNotChange	= _T("系统阻抗不变");
CString CXLangResource_Native::g_sLangID_Native_UZoomOut	= _T("Native_UZoomOut");
CString CXLangResource_Native::g_sLangTxt_Native_UZoomOut	= _T("电压放大");
CString CXLangResource_Native::g_sLangID_Native_UZoomIn	= _T("Native_UDZoomIn");
CString CXLangResource_Native::g_sLangTxt_Native_UZoomIn	= _T("电压缩小");
CString CXLangResource_Native::g_sLangID_Native_IZoomOut	= _T("Native_IZoomOut");
CString CXLangResource_Native::g_sLangTxt_Native_IZoomOut	= _T("电流放大");
CString CXLangResource_Native::g_sLangID_Native_IZoomIn	= _T("Native_IZoomIn");
CString CXLangResource_Native::g_sLangTxt_Native_IZoomIn	= _T("电流缩小");
CString CXLangResource_Native::g_sLangID_Native_EDPhaseV = _T("Native_EDPhaseV");
CString CXLangResource_Native::g_sLangTxt_Native_EDPhaseV = _T("额定相电压");
CString CXLangResource_Native::g_sLangID_Native_EDCurrent = _T("Native_EDCurrent");
CString CXLangResource_Native::g_sLangTxt_Native_EDCurrent = _T("额定电流");
CString CXLangResource_Native::g_sLangID_Native_EqualAmp = _T("Native_EqualAmp");
CString CXLangResource_Native::g_sLangTxt_Native_EqualAmp = _T("等幅值");
CString CXLangResource_Native::g_sLangID_Native_EqualFreq = _T("Native_EqualFreq");
CString CXLangResource_Native::g_sLangTxt_Native_EqualFreq = _T("等频率");
CString CXLangResource_Native::g_sLangID_Native_PositiveSeq = _T("Native_PositiveSeq");
CString CXLangResource_Native::g_sLangTxt_Native_PositiveSeq = _T("正序");
CString CXLangResource_Native::g_sLangID_Native_NegativeSeq = _T("Native_NegativeSeq");
CString CXLangResource_Native::g_sLangTxt_Native_NegativeSeq = _T("负序");
CString CXLangResource_Native::g_sLangID_Native_ZeroSeq = _T("Native_ZeroSeq");
CString CXLangResource_Native::g_sLangTxt_Native_ZeroSeq = _T("零序");
CString CXLangResource_Native::g_sLangID_Native_Zero = _T("Native_Zero");
CString CXLangResource_Native::g_sLangTxt_Native_Zero = _T("零");
CString CXLangResource_Native::g_sLangID_Native_AllGroup = _T("Native_AllGroup");
CString CXLangResource_Native::g_sLangTxt_Native_AllGroup = _T("总组数:");
CString CXLangResource_Native::g_sLangID_Native_CurGroup = _T("Native_CurGroup");
CString CXLangResource_Native::g_sLangTxt_Native_CurGroup = _T("当前组:");
CString CXLangResource_Native::g_sLangID_Native_LastGroup = _T("Native_LastGroup");
CString CXLangResource_Native::g_sLangTxt_Natve_LastGroup = _T("上一组");
CString CXLangResource_Native::g_sLangID_Native_NextGroup = _T("Native_NextGroup");
CString CXLangResource_Native::g_sLangTxt_Natve_NextGroup = _T("下一组");
CString CXLangResource_Native::g_sLangID_Native_ExBinSet       = _T("Native_ExBinSet");
CString CXLangResource_Native::g_sLangTxt_Native_ExBinSet      = _T("扩展开入设置");
CString CXLangResource_Native::g_sLangID_Native_ExBoutSet      = _T("Native_ExBoutSet");
CString CXLangResource_Native::g_sLangTxt_Native_ExBoutSet     = _T("扩展开出设置");
CString CXLangResource_Native::g_sLangID_Native_GooseDataSet   = _T("Native_GooseDataSet");
CString CXLangResource_Native::g_sLangTxt_Native_GooseDataSet  = _T("Goose数据发送");
CString CXLangResource_Native::g_sLangID_Native_Bin                 = _T("Native_Bin");
CString CXLangResource_Native::g_sLangTxt_Native_Bin                 = _T("开入量");
CString CXLangResource_Native::g_sLangID_Native_Bout                 = _T("Native_Bout");
CString CXLangResource_Native::g_sLangTxt_Native_Bout                 = _T("开出量");
CString CXLangResource_Native::g_sLangID_Native_BinEx                 = _T("Native_BinEx");
CString CXLangResource_Native::g_sLangTxt_Native_BinEx                 = _T("扩展开入");
CString CXLangResource_Native::g_sLangID_Native_BoutEx                 = _T("Native_BoutEx");
CString CXLangResource_Native::g_sLangTxt_Native_BoutEx                 = _T("扩展开出");
CString CXLangResource_Native::g_sLangID_Native_Time				= _T("Native_Time");
CString CXLangResource_Native::g_sLangTxt_Native_Time				= _T("时间");
CString CXLangResource_Native::g_sLangID_Native_Index				= _T("Native_Index");
CString CXLangResource_Native::g_sLangTxt_Native_Index				= _T("序号");
CString CXLangResource_Native::g_sLangID_Native_ActType			= _T("Native_ActType");
CString CXLangResource_Native::g_sLangTxt_Native_ActType		= _T("动作类型");
CString CXLangResource_Native::g_sLangID_Native_ActionTime		= _T("Native_ActionTime");
CString CXLangResource_Native::g_sLangTxt_Native_ActionTime		= _T("动作时间(s)");
CString CXLangResource_Native::g_sLangID_Native_CurTypeIdx		= _T("Native_CurTypeIdx");
CString CXLangResource_Native::g_sLangTxt_Native_CurTypeIdx		= _T("当前状态号");
CString CXLangResource_Native::g_sLangID_Native_Group			= _T("Native_Group");
CString CXLangResource_Native::g_sLangTxt_Native_Group			= _T("组");
CString CXLangResource_Native::g_sLangID_Native_SelectAll		= _T("Native_SelectAll");
CString CXLangResource_Native::g_sLangTxt_Native_SelectAll		= _T("全选");
CString CXLangResource_Native::g_sLangID_Native_Reverse			= _T("Native_Reverse");
CString CXLangResource_Native::g_sLangTxt_Native_Reverse		= _T("取反");
CString CXLangResource_Native::g_sLangID_Native_Repair			= _T("Native_Repair");
CString CXLangResource_Native::g_sLangTxt_Native_Repair			= _T("置检修");
CString CXLangResource_Native::g_sLangID_Native_IEDName			= _T("Native_IEDName");
CString CXLangResource_Native::g_sLangTxt_Native_IEDName		= _T("IED名称");
CString CXLangResource_Native::g_sLangID_Native_APPID			= _T("Native_APPID");
CString CXLangResource_Native::g_sLangTxt_Native_APPID			= _T("应用标识(APPID)    0x");
CString CXLangResource_Native::g_sLangID_Native_CommonPara		= _T("Native_CommonPara");
CString CXLangResource_Native::g_sLangTxt_Native_CommonPara		= _T("通用参数");
CString CXLangResource_Native::g_sLangID_Native_Type			= _T("Native_Type");
CString CXLangResource_Native::g_sLangTxt_Native_Type			= _T("类型:");
CString CXLangResource_Native::g_sLangID_Native_Action                 = _T("Native_Action");
CString CXLangResource_Native::g_sLangTxt_Native_Action                 = _T("动作值(V):");
CString CXLangResource_Native::g_sLangID_Native_ReturnVal                 = _T("Native_ReturnVal");
CString CXLangResource_Native::g_sLangTxt_Native_ReturnVal                 = _T("返回值(V):");
CString CXLangResource_Native::g_sLangID_Native_ReturnCoeff                = _T("Native_ReturnCoeff");
CString CXLangResource_Native::g_sLangTxt_Native_ReturnCoeff                 = _T("返回系数");
CString CXLangResource_Native::g_sLangID_Native_LogicOr                 = _T("Native_LogicOr");
CString CXLangResource_Native::g_sLangTxt_Native_LogicOr                 = _T("逻辑或");
CString CXLangResource_Native::g_sLangID_Native_LogicAnd                 = _T("Native_LogicAnd");
CString CXLangResource_Native::g_sLangTxt_Native_LogicAnd                 = _T("逻辑与");
CString CXLangResource_Native::g_sLangID_Native_Delete	= _T("Native_Delete");
CString CXLangResource_Native::g_sLangTxt_Native_Delete	= _T("删除");
CString CXLangResource_Native::g_sLangID_Native_Enter	= _T("Native_Enter");
CString CXLangResource_Native::g_sLangTxt_Native_Enter	= _T("完成");
CString CXLangResource_Native::g_sLangID_Native_Esc	= _T("Native_Esc");
CString CXLangResource_Native::g_sLangTxt_Native_Esc	= _T("关闭");
CString CXLangResource_Native::g_sLangID_Native_Caps	= _T("Native_Caps");
CString CXLangResource_Native::g_sLangTxt_Native_Caps	= _T("大小写");
CString CXLangResource_Native::g_sLangID_Native_Space	= _T("Native_Space");
CString CXLangResource_Native::g_sLangTxt_Native_Space	= _T("空格");
CString CXLangResource_Native::g_sLangID_Native_State = _T("Native_State");
CString CXLangResource_Native::g_sLangTxt_Native_State = _T("状态");
CString CXLangResource_Native::g_sLangID_Manual_IV                 = _T("Manual_IV");
CString CXLangResource_Native::g_sLangTxt_Manual_IV                 = _T("电流电压");
CString CXLangResource_Native::g_sLangID_Manual_OtherParam                 = _T("Manual_OtherParam");
CString CXLangResource_Native::g_sLangTxt_Manual_OtherParam                 = _T("其它参数设置");
CString CXLangResource_Native::g_sLangID_Manual_Changing                 = _T("Manual_Changing");
CString CXLangResource_Native::g_sLangTxt_Manual_Changing                 = _T("递变");
CString CXLangResource_Native::g_sLangID_Manual_InitVal                 = _T("Manual_InitVal");
CString CXLangResource_Native::g_sLangTxt_Manual_InitVal                 = _T("始值(V):");
CString CXLangResource_Native::g_sLangID_Manual_ChangeType                 = _T("Manual_ChangeType");
CString CXLangResource_Native::g_sLangTxt_Manual_ChangeType                 = _T("变化方式:");
CString CXLangResource_Native::g_sLangID_Manual_Channel                 = _T("Manual_Channel");
CString CXLangResource_Native::g_sLangTxt_Manual_Channel                 = _T("通道选择:");
CString CXLangResource_Native::g_sLangID_Manual_FinishVal                 = _T("Manual_FinishVal");
CString CXLangResource_Native::g_sLangTxt_Manual_FinishVal                 = _T("终值(V):");
CString CXLangResource_Native::g_sLangID_Manual_Step                 = _T("Manual_Step");
CString CXLangResource_Native::g_sLangTxt_Manual_Step                 = _T("步长(V):");
CString CXLangResource_Native::g_sLangID_Manual_Timer                 = _T("Manual_Timer");
CString CXLangResource_Native::g_sLangTxt_Manual_Timer                 = _T("时间(s):");
CString CXLangResource_Native::g_sLangID_Manual_Old                 = _T("Manual_Old");
CString CXLangResource_Native::g_sLangTxt_Manual_Old                 = _T("老化");
CString CXLangResource_Native::g_sLangID_Manual_Auto                 = _T("Manual_Auto");
CString CXLangResource_Native::g_sLangTxt_Manual_Auto                 = _T("自动");

CString CXLangResource_Native::g_sLangID_Manual_Delayed                 = _T("Manual_Delayed");
CString CXLangResource_Native::g_sLangTxt_Manual_Delayed                 = _T("触发后延时(s):");
CString CXLangResource_Native::g_sLangID_Manual_OutSetting                 = _T("Manual_OutSetting");
CString CXLangResource_Native::g_sLangTxt_Manual_OutSetting                 = _T("开出设置");
CString CXLangResource_Native::g_sLangID_Manual_Out1                 = _T("Manual_Out1");
CString CXLangResource_Native::g_sLangTxt_Manual_Out1                 = _T("开出1");
CString CXLangResource_Native::g_sLangID_Manual_Out2                 = _T("Manual_Out2");
CString CXLangResource_Native::g_sLangTxt_Manual_Out2                 = _T("开出2");
CString CXLangResource_Native::g_sLangID_Manual_Out3                 = _T("Manual_Out3");
CString CXLangResource_Native::g_sLangTxt_Manual_Out3                 = _T("开出3");
CString CXLangResource_Native::g_sLangID_Manual_Out4                 = _T("Manual_Out4");
CString CXLangResource_Native::g_sLangTxt_Manual_Out4                 = _T("开出4");
CString CXLangResource_Native::g_sLangID_Manual_Out5                 = _T("Manual_Out5");
CString CXLangResource_Native::g_sLangTxt_Manual_Out5                 = _T("开出5");
CString CXLangResource_Native::g_sLangID_Manual_Out6                 = _T("Manual_Out6");
CString CXLangResource_Native::g_sLangTxt_Manual_Out6                 = _T("开出6");
CString CXLangResource_Native::g_sLangID_Manual_Out7                 = _T("Manual_Out7");
CString CXLangResource_Native::g_sLangTxt_Manual_Out7                 = _T("开出7");
CString CXLangResource_Native::g_sLangID_Manual_Out8                 = _T("Manual_Out8");
CString CXLangResource_Native::g_sLangTxt_Manual_Out8                 = _T("开出8");
CString CXLangResource_Native::g_sLangID_Manual_InSetting                 = _T("Manual_InSetting");
CString CXLangResource_Native::g_sLangTxt_Manual_InSetting                 = _T("开入设置");
CString CXLangResource_Native::g_sLangID_Manual_InA                 = _T("Manual_InA");
CString CXLangResource_Native::g_sLangTxt_Manual_InA                 = _T("开入A");
CString CXLangResource_Native::g_sLangID_Manual_InB                 = _T("Manual_InB");
CString CXLangResource_Native::g_sLangTxt_Manual_InB                 = _T("开入B");
CString CXLangResource_Native::g_sLangID_Manual_InC                 = _T("Manual_InC");
CString CXLangResource_Native::g_sLangTxt_Manual_InC                 = _T("开入C");
CString CXLangResource_Native::g_sLangID_Manual_InD                 = _T("Manual_InD");
CString CXLangResource_Native::g_sLangTxt_Manual_InD                 = _T("开入D");
CString CXLangResource_Native::g_sLangID_Manual_InE                 = _T("Manual_InE");
CString CXLangResource_Native::g_sLangTxt_Manual_InE                 = _T("开入E");
CString CXLangResource_Native::g_sLangID_Manual_InF                 = _T("Manual_InF");
CString CXLangResource_Native::g_sLangTxt_Manual_InF                 = _T("开入F");
CString CXLangResource_Native::g_sLangID_Manual_InG                 = _T("Manual_InG");
CString CXLangResource_Native::g_sLangTxt_Manual_InG                 = _T("开入G");
CString CXLangResource_Native::g_sLangID_Manual_InH                 = _T("Manual_InH");
CString CXLangResource_Native::g_sLangTxt_Manual_InH                 = _T("开入H");
CString CXLangResource_Native::g_sLangID_Manual_Lock                 = _T("Manual_Lock");
CString CXLangResource_Native::g_sLangTxt_Manual_Lock                 = _T("锁");
CString CXLangResource_Native::g_sLangID_Manual_UnLock                 = _T("Manual_UnLock");
CString CXLangResource_Native::g_sLangTxt_Manual_UnLock                 = _T("解锁");
CString CXLangResource_Native::g_sLangID_Manual_ActionTime                 = _T("Manual_ActionTime");
CString CXLangResource_Native::g_sLangTxt_Manual_ActionTime                 = _T("动作时间(s):");
CString CXLangResource_Native::g_sLangID_Manual_ReturnTime                 = _T("Manual_ReturnTime");
CString CXLangResource_Native::g_sLangTxt_Manual_ReturnTime                 = _T("返回时间(s):");
CString CXLangResource_Native::g_sLangID_Manual_S_E                 = _T("Manual_S_E");
CString CXLangResource_Native::g_sLangTxt_Manual_S_E                 = _T("始-终");
CString CXLangResource_Native::g_sLangID_Manual_S_E_S                 = _T("Manual_S_E_S");
CString CXLangResource_Native::g_sLangTxt_Manual_S_E_S                 = _T("始-终-始");

CString CXLangResource_Native::g_sLangID_State_TrigerSetup                 = _T("State_TrigerSetup");
CString CXLangResource_Native::g_sLangTxt_State_TrigerSetup                 = _T("触发设置");
CString CXLangResource_Native::g_sLangID_State_TrigerCondition                 = _T("State_TrigerCondition");
CString CXLangResource_Native::g_sLangTxt_State_TrigerCondition                 = _T("触发条件:");
CString CXLangResource_Native::g_sLangID_State_OutTime                 = _T("State_OutTime");
CString CXLangResource_Native::g_sLangTxt_State_OutTime                 = _T("输出时间(s):");
CString CXLangResource_Native::g_sLangID_State_TrigerTime                 = _T("State_TrigerTime");
CString CXLangResource_Native::g_sLangTxt_State_TrigerTime                 = _T("触发时刻");
CString CXLangResource_Native::g_sLangID_State_Hour                 = _T("State_Hour");
CString CXLangResource_Native::g_sLangTxt_State_Hour                 = _T("时");
CString CXLangResource_Native::g_sLangID_State_Minute                 = _T("State_Minute");
CString CXLangResource_Native::g_sLangTxt_State_Minute                 = _T("分");
CString CXLangResource_Native::g_sLangID_State_Second                 = _T("State_Second");
CString CXLangResource_Native::g_sLangTxt_State_Second                 = _T("秒");
CString CXLangResource_Native::g_sLangID_State_TrigerHoldTime                 = _T("State_TrigerHoldTime");
CString CXLangResource_Native::g_sLangTxt_State_TrigerHoldTime                 = _T("触发后保持时间(s):");
CString CXLangResource_Native::g_sLangID_State_HoldTime                 = _T("State_HoldTime");
CString CXLangResource_Native::g_sLangTxt_State_HoldTime                 = _T("保持时间(s):");
CString CXLangResource_Native::g_sLangID_State_ShortCalc                 = _T("State_ShortCalc");
CString CXLangResource_Native::g_sLangTxt_State_ShortCalc                 = _T("短路计算");
CString CXLangResource_Native::g_sLangID_State_GradientSet                 = _T("State_GradientSet");
CString CXLangResource_Native::g_sLangTxt_State_GradientSet                 = _T("递变设置");
CString CXLangResource_Native::g_sLangID_State_PasteStateBf                 = _T("State_PasteStateBf");
CString CXLangResource_Native::g_sLangTxt_State_PasteStateBf                 = _T("粘贴状态—前");
CString CXLangResource_Native::g_sLangID_State_InsertStateBf                 = _T("State_InsertStateBf");
CString CXLangResource_Native::g_sLangTxt_State_InsertStateBf                 = _T("插入状态—前");
CString CXLangResource_Native::g_sLangID_State_InsertStateAf                 = _T("State_InsertStateAf");
CString CXLangResource_Native::g_sLangTxt_State_InsertStateAf                 = _T("插入状态—后");
CString CXLangResource_Native::g_sLangID_State_PasteStateAf                 = _T("State_PasteStateAf");
CString CXLangResource_Native::g_sLangTxt_State_PasteStateAf                 = _T("粘贴状态—后");
CString CXLangResource_Native::g_sLangID_State_CopyCurState                 = _T("State_CopyCurState");
CString CXLangResource_Native::g_sLangTxt_State_CopyCurState                 = _T("拷贝当前状态");
CString CXLangResource_Native::g_sLangID_State_DeleteCurState                 = _T("State_DeleteCurState");
CString CXLangResource_Native::g_sLangTxt_State_DeleteCurState                 = _T("删除当前状态");
CString CXLangResource_Native::g_sLangID_State_UISet					= _T("State_UISet");
CString CXLangResource_Native::g_sLangTxt_State_UISet					= _T("电压电流设置");
CString CXLangResource_Native::g_sLangID_State_StateParaSet                 = _T("State_StateParaSet");
CString CXLangResource_Native::g_sLangTxt_State_StateParaSet                 = _T("状态参数设置");
CString CXLangResource_Native::g_sLangID_State_HarmSet                 = _T("State_HarmSet");
CString CXLangResource_Native::g_sLangTxt_State_HarmSet                 = _T("谐波设置");
CString CXLangResource_Native::g_sLangID_State_JudgeCondition			=_T("State_JudgeCondition");
CString CXLangResource_Native::g_sLangTxt_State_JudgeCondition			=_T("开入翻转参考状态");
CString CXLangResource_Native::g_sLangID_State_DCOffSet			=_T("State_DCOffSet");
CString CXLangResource_Native::g_sLangTxt_State_DCOffSet			=_T("叠加衰减直流分量");
CString CXLangResource_Native::g_sLangID_State_Tou			=_T("State_Tou");
CString CXLangResource_Native::g_sLangTxt_State_Tou			=_T("衰减时间常数");
CString CXLangResource_Native::g_sLangID_State_RepeatTimes			=_T("State_RepeatTimes");
CString CXLangResource_Native::g_sLangTxt_State_RepeatTimes			=_T("循环次数");
CString CXLangResource_Native::g_sLangID_State_ChGroup			=_T("State_ChGroup");
CString CXLangResource_Native::g_sLangTxt_State_ChGroup			=_T("组号:");
CString CXLangResource_Native::g_sLangID_State_FaultType			=_T("State_FaultType");
CString CXLangResource_Native::g_sLangTxt_State_FaultType			=_T("故障类型:");
CString CXLangResource_Native::g_sLangID_State_CalcMode			=_T("State_CalcMode");
CString CXLangResource_Native::g_sLangTxt_State_CalcMode			=_T("计算模型:");
CString CXLangResource_Native::g_sLangID_State_ShortI			=_T("State_ShortI");
CString CXLangResource_Native::g_sLangTxt_State_ShortI			=_T("短路电流(A):");
CString CXLangResource_Native::g_sLangID_State_ShortU			=_T("State_ShortU");
CString CXLangResource_Native::g_sLangTxt_State_ShortU			=_T("短路电压(V):");
CString CXLangResource_Native::g_sLangID_State_ZeroCoeff			=_T("State_ZeroCoeff");
CString CXLangResource_Native::g_sLangTxt_State_ZeroCoeff			=_T("零序补偿系数");
CString CXLangResource_Native::g_sLangID_State_CalcType			=_T("State_CalcType");
CString CXLangResource_Native::g_sLangTxt_State_CalcType			=_T("计算方式:");
CString CXLangResource_Native::g_sLangID_State_Amp			=_T("State_Amp");
CString CXLangResource_Native::g_sLangTxt_State_Amp			=_T("幅值:");
CString CXLangResource_Native::g_sLangID_State_Angle			=_T("State_Angle");
CString CXLangResource_Native::g_sLangTxt_State_Angle			=_T("相角:");
CString CXLangResource_Native::g_sLangID_LoadI			=_T("State_LoadI");
CString CXLangResource_Native::g_sLangTxt_LoadI			=_T("负荷电流(A):");
CString CXLangResource_Native::g_sLangID_State_LoadAngle			=_T("State_LoadAngle");
CString CXLangResource_Native::g_sLangTxt_State_LoadAngle			=_T("负荷功角(°):");
CString CXLangResource_Native::g_sLangID_State_Trigger_Time		= _T("State_Trigger_Time");
CString CXLangResource_Native::g_sLangTxt_State_Trigger_Time	= _T("时间触发");
CString CXLangResource_Native::g_sLangID_State_Trigger_TimeAndBin	= _T("State_Trigger_TimeAndBin");
CString CXLangResource_Native::g_sLangTxt_State_Trigger_TimeAndBin	= _T("时间+开入量触发");
CString CXLangResource_Native::g_sLangID_State_Trigger_Bin		= _T("State_Trigger_Bin");
CString CXLangResource_Native::g_sLangTxt_State_Trigger_Bin		= _T("开入量触发");
CString CXLangResource_Native::g_sLangID_State_Trigger_Manu		= _T("State_Trigger_Manu");
CString CXLangResource_Native::g_sLangTxt_State_Trigger_Manu	= _T("手动触发");
CString CXLangResource_Native::g_sLangID_State_Trigger_GPSB		= _T("State_Trigger_GPSB");
CString CXLangResource_Native::g_sLangTxt_State_Trigger_GPSB	= _T("GPS/B码触发");
CString CXLangResource_Native::g_sLangID_State_LinearChange  =  _T("State_LinearChange");
CString CXLangResource_Native::g_sLangTxt_State_LinearChange	= _T("线性变化");
CString CXLangResource_Native::g_sLangID_State_StepChange	= _T("State_StepChange");
CString CXLangResource_Native::g_sLangTxt_State_StepChange	= _T("阶梯变化");
CString CXLangResource_Native::g_sLangID_State_StepTime = _T("State_StepTime");
CString CXLangResource_Native::g_sLangTxt_State_StepTime  = _T("步长时间(s)");
CString CXLangResource_Native::g_sLangID_State_SelectChannel = _T("State_SelectChannel");
CString CXLangResource_Native::g_sLangTxt_State_SelectChannel = _T("选择");
CString CXLangResource_Native::g_sLangID_State_BeginVal = _T("State_BeginVal");
CString CXLangResource_Native::g_sLangTxt_State_BeginVal = _T("始值");
CString CXLangResource_Native::g_sLangID_State_EndVal = _T("State_EndVal");
CString CXLangResource_Native::g_sLangTxt_State_EndVal = _T("终值");
CString CXLangResource_Native::g_sLangID_State_Step = _T("State_Step");
CString CXLangResource_Native::g_sLangTxt_State_Step = _T("步长");
CString CXLangResource_Native::g_sLangID_State_AmpGradient = _T("State_AmpGradient");
CString CXLangResource_Native::g_sLangTxt_State_AmpGradient = _T("幅值递变");
CString CXLangResource_Native::g_sLangID_State_FreqGradient = _T("State_FreqGradient");
CString CXLangResource_Native::g_sLangTxt_State_FreqGradient = _T("频率递变");
CString CXLangResource_Native::g_sLangID_State_LastState =	_T("State_LastState");
CString CXLangResource_Native::g_sLangTxt_State_LastState = _T("上一个状态");
CString CXLangResource_Native::g_sLangID_State_FirstState = _T("State_FirstState");
CString CXLangResource_Native::g_sLangTxt_State_FirstState = _T("第一个状态");
CString CXLangResource_Native::g_sLangID_State_No = _T("State_No");
CString CXLangResource_Native::g_sLangTxt_State_No = _T("否");
CString CXLangResource_Native::g_sLangID_State_Yes = _T("State_Yes");
CString CXLangResource_Native::g_sLangTxt_State_Yes = _T("是");
CString CXLangResource_Native::g_sLangID_State_HarmCount = _T("State_HarmCount");
CString CXLangResource_Native::g_sLangTxt_State_HarmCount = _T("次谐波");

CString CXLangResource_Native::g_sLangID_Gradient_Var		= _T("Gradient_Var");
CString CXLangResource_Native::g_sLangTxt_Gradient_Var		= _T("变量");
CString CXLangResource_Native::g_sLangID_Gradient_VarType		= _T("Gradient_VarType");
CString CXLangResource_Native::g_sLangTxt_Gradient_VarType		= _T("变量类型");
CString CXLangResource_Native::g_sLangID_Gradient_Phase		= _T("Gradient_Phase");
CString CXLangResource_Native::g_sLangTxt_Gradient_Phase		= _T("电流相差");
CString CXLangResource_Native::g_sLangID_Gradient_Init		= _T("Gradient_Init");
CString CXLangResource_Native::g_sLangTxt_Gradient_Init		= _T("变化始值");
CString CXLangResource_Native::g_sLangID_Gradient_Finish		= _T("Gradient_Finish");
CString CXLangResource_Native::g_sLangTxt_Gradient_Finish		= _T("变化终值");
CString CXLangResource_Native::g_sLangID_Gradient_Step		= _T("Gradient_Step");
CString CXLangResource_Native::g_sLangTxt_Gradient_Step		= _T("变化步长");
CString CXLangResource_Native::g_sLangID_Gradient_Time		= _T("Gradient_Time");
CString CXLangResource_Native::g_sLangTxt_Gradient_Time		= _T("故障时间");
CString CXLangResource_Native::g_sLangID_Gradient_Direction		= _T("Gradient_Direction");
CString CXLangResource_Native::g_sLangTxt_Gradient_Direction		= _T("递变方向");
CString CXLangResource_Native::g_sLangID_Gradient_MaxAngle                 = _T("Gradient_MaxAngle");
CString CXLangResource_Native::g_sLangTxt_Gradient_MaxAngle                 = _T("最大灵敏角");
CString CXLangResource_Native::g_sLangID_Gradient_Clockwise                 = _T("Gradient_Clockwise");
CString CXLangResource_Native::g_sLangTxt_Gradient_Clockwise                 = _T("顺时针");
CString CXLangResource_Native::g_sLangID_Gradient_Anticlockwise                 = _T("Gradient_Anticlockwise");
CString CXLangResource_Native::g_sLangTxt_Gradient_Anticlockwise                 = _T("逆时针");
CString CXLangResource_Native::g_sLangID_Gradient_AllFreq                 = _T("Gradient_AllFreq");
CString CXLangResource_Native::g_sLangTxt_Gradient_AllFreq                 = _T("全部频率");
CString CXLangResource_Native::g_sLangID_Gradient_TimeBeforeChange			 = _T("Gradient_TimeBeforeChange"); 
CString CXLangResource_Native::g_sLangTxt_Gradient_TimeBeforeChange			 = _T("变化前时间"); 
CString CXLangResource_Native::g_sLangID_Gradient_TimeBeforeFail			 = _T("Gradient_TimeBeforeFail"); 
CString CXLangResource_Native::g_sLangTxt_Gradient_TimeBeforeFail			 = _T("故障前时间"); 
CString CXLangResource_Native::g_sLangID_Gradient_CurBeforeChange			 = _T("Gradient_CurBeforeChange");  
CString CXLangResource_Native::g_sLangTxt_Gradient_CurBeforeChange			 = _T("变化前电流"); 
CString CXLangResource_Native::g_sLangID_Gradient_Normal			 = _T("Gradient_Normal"); 
CString CXLangResource_Native::g_sLangTxt_Gradient_Normal			 = _T("正常态"); 
CString CXLangResource_Native::g_sLangID_Gradient_Failure			 = _T("Gradient_Failure"); 
CString CXLangResource_Native::g_sLangTxt_Gradient_Failure			 = _T("故障态"); 

CString CXLangResource_Native::g_sLangID_Report_TestChoose			 = _T("Report_TestChoose"); 
CString CXLangResource_Native::g_sLangTxt_Report_TestChoose			 = _T("内容选择"); 
CString CXLangResource_Native::g_sLangID_Report_TestObjInf			 = _T("Report_TestObjInf"); 
CString CXLangResource_Native::g_sLangTxt_Report_TestObjInf			 = _T("测试对象信息"); 
CString CXLangResource_Native::g_sLangID_Report_SubInfo				 = _T("Report_SubInfo"); 
CString CXLangResource_Native::g_sLangTxt_Report_SubInfo			 = _T("变电站信息");
CString CXLangResource_Native::g_sLangID_Report_SubName				 = _T("Report_SubName"); 
CString CXLangResource_Native::g_sLangTxt_Report_SubName			 = _T("变电站名称");
CString CXLangResource_Native::g_sLangID_Report_SubAdd				 = _T("Report_SubAdd"); 
CString CXLangResource_Native::g_sLangTxt_Report_SubAdd				 = _T("变电站地址");
CString CXLangResource_Native::g_sLangID_Report_ReturnName			 = _T("Report_ReturnName"); 
CString CXLangResource_Native::g_sLangTxt_Report_ReturnName			 = _T("回路名称");
CString CXLangResource_Native::g_sLangID_Report_ReturnAdd			 = _T("Report_ReturnAdd"); 
CString CXLangResource_Native::g_sLangTxt_Report_ReturnAdd			 = _T("回路地址");
CString CXLangResource_Native::g_sLangID_Report_Tester				 = _T("Report_Tester"); 
CString CXLangResource_Native::g_sLangTxt_Report_Tester				 = _T("测试人员");
CString CXLangResource_Native::g_sLangID_Report_ReportTitle			 = _T("Report_ReportTitle"); 
CString CXLangResource_Native::g_sLangTxt_Report_ReportTitle		 = _T("报告标题");
CString CXLangResource_Native::g_sLangID_Report_DeviceInfo			 = _T("Report_DeviceInfo"); 
CString CXLangResource_Native::g_sLangTxt_Report_DeviceInfo			 = _T("装置信息");
CString CXLangResource_Native::g_sLangID_Report_DeviceName			 = _T("Report_DeviceName"); 
CString CXLangResource_Native::g_sLangTxt_Report_DeviceName			 = _T("装置名称");
CString CXLangResource_Native::g_sLangID_Report_DeviceType			 = _T("Report_DeviceType"); 
CString CXLangResource_Native::g_sLangTxt_Report_DeviceType			 = _T("装置型号");
CString CXLangResource_Native::g_sLangID_Report_DevAddress			 = _T("Report_DevAddress"); 
CString CXLangResource_Native::g_sLangTxt_Report_DevAddress			 = _T("装置地址");
CString CXLangResource_Native::g_sLangID_Report_Manufacturer		 = _T("Report_Manufacturer"); 
CString CXLangResource_Native::g_sLangTxt_Report_Manufacturer		 = _T("生产厂家");
CString CXLangResource_Native::g_sLangID_Report_SeniorNum			 = _T("Report_SeniorNum"); 
CString CXLangResource_Native::g_sLangTxt_Report_SeniorNum		     = _T("序列号");
CString CXLangResource_Native::g_sLangID_Report_CusOrdNum			 = _T("Report_CusOrdNum"); 
CString CXLangResource_Native::g_sLangTxt_Report_CusOrdNum		     = _T("定制单编号");
CString CXLangResource_Native::g_sLangID_Report_AdditionalInfo		 = _T("Report_AdditionalInfo"); 
CString CXLangResource_Native::g_sLangTxt_Report_AdditionalInfo		 = _T("附加信息");
CString CXLangResource_Native::g_sLangID_Report_RatedValue			 = _T("Report_RatedValue"); 
CString CXLangResource_Native::g_sLangTxt_Report_RatedValue			 = _T("额定值");
CString CXLangResource_Native::g_sLangID_Report_TestEquInfo			 = _T("Report_TestEquInfo"); 
CString CXLangResource_Native::g_sLangTxt_Report_TestEquInfo		 = _T("测试设备信息");
CString CXLangResource_Native::g_sLangID_Report_DUTs				 = _T("Report_DUTs"); 
CString CXLangResource_Native::g_sLangTxt_Report_DUTs				 = _T("被测装置");
CString CXLangResource_Native::g_sLangID_Report_Title				 = _T("Report_Title"); 
CString CXLangResource_Native::g_sLangTxt_Report_Title				 = _T("报告内容与格式");