//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CharLibDev.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_CHARLIBDEV_FORM             101
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_CharLibDevTYPE              130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define IDD_DIALOG_ARC                  132
#define ID_VIEW_FILEVIEW                133
#define IDD_DIALOG_ARCD                 133
#define ID_VIEW_CLASSVIEW               134
#define IDD_DIALOG_ARCP                 134
#define ID_PROPERTIES                   135
#define IDD_DIALOG_LINE                 135
#define ID_OPEN                         136
#define IDD_DIALOG_LINED                136
#define ID_OPEN_WITH                    137
#define IDD_DIALOG_LINER                137
#define ID_DUMMY_COMPILE                138
#define IDD_DIALOG_LENS                 138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define IDD_DIALOG_MHO                  139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_CHAR                 310
#define IDD_DIALOG_CHARDOLDER           311
#define IDD_DIALOG_CHAR_ELEMENT         312
#define IDD_DIALOG_INV_I2T              313
#define IDD_DIALOG_INV_IAC              314
#define IDD_DIALOG_INV_IEC              315
#define IDD_DIALOG_INV_IEEE             316
#define IDD_DIALOG_IMPORT_FROM_RIO_FILE 317
#define IDD_DIALOG_POLYLINE             318
#define IDD_DIALOG_POLYLINE1            319
#define IDD_DIALOG_INV_BASE             319
#define IDD_DIALOG_INV_OWNDEF           320
#define IDD_IOWNDEF_ADDPOINT            321
#define IDB_PNG1                        322
#define IDC_EDIT_NAME                   1001
#define IDC_EDIT_ID                     1002
#define IDC_RADIO_DECARTES              1003
#define IDC_RADIO_POLOR                 1004
#define IDC_RADIO_LOG                   1005
#define IDC_TREE_FOLDER                 1006
#define IDC_RADIO_SL_PLUMB              1007
#define IDC_RADIO_SL_VERT               1008
#define IDC_BTN_NEW_VARIABLE            1009
#define IDC_RADIO_LOG2                  1009
#define IDC_RADIO_SL_HORZ               1009
#define IDC_BTN_DELETE_VARIABLE         1010
#define IDC_EDIT_XMIN                   1010
#define IDC_BTN_NEW_ELEMENT             1011
#define IDC_EDIT_YMIN                   1011
#define IDC_BTN_DELETE__ELEMENT         1012
#define IDC_EDIT_XMIN2                  1012
#define IDC_EDIT_XMAX                   1012
#define IDC_BTN_MOVEUP                  1013
#define IDC_EDIT_YMAX                   1013
#define IDC_BTN_MOVE_DOWN               1014
#define IDC_DRAW_CHARTEMP               1015
#define IDC_GRID_CHARINTERFACE          1016
#define IDC_GRID_CHARELEMENT            1017
#define IDC_EDIT_XB                     1017
#define IDC_GRID_MACROTEST              1018
#define IDC_EDIT_YB                     1018
#define IDC_EDIT_XE                     1019
#define IDC_EDIT_YE                     1020
#define IDC_FRAME_ELEMENT               1021
#define IDC_CMB_ELEMENTTYPE             1022
#define IDC_EDIT_ERROR_LEN              1023
#define IDC_EDIT_TESTPOINTS             1024
#define IDC_EDIT_FORWARDREACH           1024
#define IDC_EDIT_ANGLE                  1025
#define IDC_EDIT_OFFSET                 1026
#define IDC_EDIT_LENGTHUSE              1026
#define IDC_EDIT_WIDTH                  1027
#define IDC_IEEE_P                      1027
#define IDC_IAC_C                       1027
#define IDC_STATIC_CHARNAME             1028
#define IDC_IEEE_Q                      1028
#define IDC_IAC_E                       1028
#define IDC_EDIT1                       1029
#define IDC_STATIC_ALTYPE               1029
#define IDC_IEEE_K1                     1029
#define IDC_IAC_D                       1029
#define IDC_EDIT2                       1030
#define IDC_STATIC_FOLDERNAME           1030
#define IDC_IEEE_K2                     1030
#define IDC_IAC_BETA                    1030
#define IDC_EDIT3                       1031
#define IDC_STATIC_ERRORLENGTH          1031
#define IDC_EDIT4                       1032
#define IDC_STATIC_EDGETESTPOINT        1032
#define IDC_EDIT5                       1033
#define IDC_STATIC_CHAR                 1033
#define IDC_STATIC_CHARMARKING          1033
#define IDC_COMBO1                      1034
#define IDC_STATIC_CHARCOORDIN          1034
#define IDC_EDIT_ARC_X                  1035
#define IDC_STATIC_CHARSEARMODE         1035
#define IDC_EDIT_ARC_Y                  1036
#define IDC_STATIC_CHARSEARMODE2        1036
#define IDC_EDIT_TP                     1036
#define IDC_EDIT_ARC_RADIUS             1037
#define IDC_EDIT_A                      1037
#define IDC_EDIT_ARC_STARTANGLE         1038
#define IDC_TREE1                       1038
#define IDC_TREE_XRIO                   1038
#define IDC_TREE_RIO_FILE               1038
#define IDC_EDIT_ARC_ENDANGLE           1039
#define IDC_EDIT_X                      1039
#define IDC_COMBO_DIR                   1040
#define IDC_EDIT_Y                      1041
#define IDC_EDIT_ARC_Z                  1041
#define IDC_EDIT_ARC_PH                 1042
#define IDC_BUTTON_BROWSE               1043
#define IDC_EDIT_RIO_FILE               1044
#define IDC_COMBO_CLOCKWISE             1045
#define IDC_IEEE_TP                     1045
#define IDC_IEEE_A                      1046
#define IDC_IEEE_B                      1047
#define IDC_IOWNDEF_XMAX                1048
#define IDC_IOWNDEF_TMAX                1049
#define IDC_IEC_TP                      1050
#define IDC_IEC_K                       1051
#define IDC_IEC_ALPHA                   1052
#define IDC_IAC_TP                      1053
#define IDC_IAC_A                       1054
#define IDC_IAC_B                       1055
#define IDC_INVOWNDEF_GRID              1056
#define IDC_INVOWNDEF_ADDPOINT          1057
#define IDC_INVOWNDEF_DELPOINT          1058
#define IDC_IOWNDEF_X_EDIT              1058
#define IDC_IOWNDEF_Y_EDIT              1059
#define IDC_IEEE_PIC                    1059
#define IDC_IAC_PIC                     1060
#define IDC_INVOWNDEF_DELALLPOINT       1061
#define IDC_INVOWNDEF_ADDPOINTHEAD      1062
#define IDC_INVOWNDEF_ADDPOINTPREV      1063
#define IDC_BUTTON4                     1064
#define IDC_INVOWNDEF_ADDPOINTAFTER     1064
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_CHAROPTR_NEWCHAR             32771
#define ID_CHAROPTR_SAVE                32772
#define ID_CHAROPTR_SAVEAS              32773
#define ID_CHAROPTR_DELETE              32774
#define ID_CHAROPTR_EXPORT              32775
#define ID_VIEW_OUTPUTWND32776          32776
#define ID_VIEW_CHARPANE                32777
#define ID_CHAROPTR_EDIT                32778
#define ID_EDIT_FOLDER                  32779
#define ID_DELETE_FOLDER                32780
#define ID_CHAROPTR_IMPORTFROMRIOFILE   32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        323
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           318
#endif
#endif
