#pragma once

// #include "Analog.h"
// #include "Analogs.h"
// #include "Binary.h"
// #include "BinaryIns.h"
// #include "BinaryOuts.h"
// #include "Binarys.h"
#include "CommCmd.h"
#include "Cpu.h"
#include "Cpus.h"
// #include "CtrlWords.h"
#include "Device.h"
#include "GuideBook.h"
#include "GuideBookDefine.h"
#include "ItemContainer.h"
#include "Items.h"
#include "JobGuide.h"
#include "MacroTest.h"
#include "MacroTestPara.h"
#include "MacroCharItems.h"
#include "Msg.h"
#include "report.h"
#include "reports.h"
#include "Safety.h"
#include "scriptText.h"
// #include "Set.h"
// #include "Sets.h"
// #include "Soe.h"
// #include "Soes.h"
// #include "SoftSwitchs.h"
#include "Standard.h"
#include "SysParaEdit.h"
#include "SysParas.h"
#include "ValParas.h"
#include "GbDataTypeMngr.h"
#include "MacroTestParaDatas.h"
#include "MacroTestParaData.h"
